import numpy as np

# =============================================================================
# S.py
# Service category product assignments — letter S
# Generated by: product-service-mapper skill
# =============================================================================

Seeking_Second_Opinion = np.array([
    {"catid": 52, "prodcode": 37234, "descr": ""},
    {"catid": 52, "prodcode": 37244, "descr": ""},
    {"catid": 52, "prodcode": 37245, "descr": ""},
    {"catid": 52, "prodcode": 37661, "descr": ""},
    {"catid": 52, "prodcode": 37662, "descr": ""},
    {"catid": 52, "prodcode": 37664, "descr": ""},
    {"catid": 52, "prodcode": 37665, "descr": ""},
    {"catid": 52, "prodcode": 37666, "descr": ""},
    {"catid": 52, "prodcode": 37668, "descr": ""},
    {"catid": 52, "prodcode": 38717, "descr": ""},
    {"catid": 52, "prodcode": 38718, "descr": ""},
    {"catid": 52, "prodcode": 38719, "descr": ""},
    {"catid": 52, "prodcode": 38722, "descr": ""},
    {"catid": 52, "prodcode": 39226, "descr": ""},
    {"catid": 52, "prodcode": 39227, "descr": ""},
    {"catid": 52, "prodcode": 39230, "descr": ""},
    {"catid": 52, "prodcode": 39286, "descr": ""},
    {"catid": 52, "prodcode": 39602, "descr": ""},
    {"catid": 52, "prodcode": 39603, "descr": ""},
])

Seminal_Fluid_Analysis_SFA = np.array([
    {"catid": 332, "prodcode": 36619, "descr": ""},
    {"catid": 332, "prodcode": 37682, "descr": ""},
    {"catid": 332, "prodcode": 37683, "descr": ""},
    {"catid": 332, "prodcode": 39829, "descr": ""},
    {"catid": 332, "prodcode": 39831, "descr": ""},
    {"catid": 332, "prodcode": 39834, "descr": ""},
    {"catid": 332, "prodcode": 39837, "descr": ""},
    {"catid": 332, "prodcode": 39838, "descr": ""},
    {"catid": 332, "prodcode": 39868, "descr": ""},
])

Serum_Acid_Phosphate = np.array([
    {"catid": 154, "prodcode": 38450, "descr": ""},
    {"catid": 154, "prodcode": 38451, "descr": ""},
])

Serum_Bilirubin_Total_and_Direct = np.array([
    {"catid": 156, "prodcode": 39845, "descr": ""},
])

Serum_Chloride = np.array([
    {"catid": 161, "prodcode": 39848, "descr": ""},
    {"catid": 161, "prodcode": 39850, "descr": ""},
])

Serum_Inorganic_Phosphate = np.array([
    {"catid": 155, "prodcode": 36572, "descr": ""},
    {"catid": 155, "prodcode": 36573, "descr": ""},
    {"catid": 155, "prodcode": 36574, "descr": ""},
    {"catid": 155, "prodcode": 37496, "descr": ""},
    {"catid": 155, "prodcode": 37985, "descr": ""},
    {"catid": 155, "prodcode": 38415, "descr": ""},
    {"catid": 155, "prodcode": 39821, "descr": ""},
])

Serum_Iron = np.array([
    {"catid": 323, "prodcode": 39852, "descr": ""},
])

Serum_Lactate_Dehydrogenase = np.array([
    {"catid": 163, "prodcode": 39857, "descr": ""},
])

Serum_Lithium = np.array([
    {"catid": 160, "prodcode": 36572, "descr": ""},
    {"catid": 160, "prodcode": 36573, "descr": ""},
    {"catid": 160, "prodcode": 36574, "descr": ""},
    {"catid": 160, "prodcode": 39552, "descr": ""},
])

Serum_Magnesium = np.array([
    {"catid": 158, "prodcode": 36377, "descr": ""},
    {"catid": 158, "prodcode": 36533, "descr": ""},
    {"catid": 158, "prodcode": 39560, "descr": ""},
    {"catid": 158, "prodcode": 39561, "descr": ""},
])

Serum_Potasium = np.array([
    {"catid": 159, "prodcode": 38428, "descr": ""},
    {"catid": 159, "prodcode": 39848, "descr": ""},
    {"catid": 159, "prodcode": 39850, "descr": ""},
])

Serum_Sodium = np.array([
    {"catid": 145, "prodcode": 39861, "descr": ""},
])

Sinus_X_rays = np.array([
    {"catid": 130, "prodcode": 37686, "descr": ""},
    {"catid": 130, "prodcode": 37688, "descr": ""},
])

Skin_Scraping_for_Fungi = np.array([
    {"catid": 229, "prodcode": 36586, "descr": ""},
    {"catid": 229, "prodcode": 39822, "descr": ""},
    {"catid": 229, "prodcode": 39823, "descr": ""},
])

Skin_Snip_for_Microfilaria = np.array([
    {"catid": 228, "prodcode": 36577, "descr": ""},
    {"catid": 228, "prodcode": 36583, "descr": ""},
])

Skull_X_rays = np.array([
    {"catid": 133, "prodcode": 37569, "descr": ""},
    {"catid": 133, "prodcode": 37580, "descr": ""},
    {"catid": 133, "prodcode": 37587, "descr": ""},
    {"catid": 133, "prodcode": 37589, "descr": ""},
    {"catid": 133, "prodcode": 37616, "descr": ""},
    {"catid": 133, "prodcode": 37623, "descr": ""},
    {"catid": 133, "prodcode": 38578, "descr": ""},
    {"catid": 133, "prodcode": 39269, "descr": ""},
])

Special_Care_baby_Unit = np.array([
    {"catid": 307, "prodcode": 37175, "descr": ""},
    {"catid": 307, "prodcode": 37176, "descr": ""},
    {"catid": 307, "prodcode": 37177, "descr": ""},
    {"catid": 307, "prodcode": 37178, "descr": ""},
    {"catid": 307, "prodcode": 37179, "descr": ""},
    {"catid": 307, "prodcode": 38417, "descr": ""},
    {"catid": 307, "prodcode": 38497, "descr": ""},
    {"catid": 307, "prodcode": 38510, "descr": ""},
    {"catid": 307, "prodcode": 38511, "descr": ""},
    {"catid": 307, "prodcode": 38513, "descr": ""},
    {"catid": 307, "prodcode": 38514, "descr": ""},
    {"catid": 307, "prodcode": 39047, "descr": ""},
])

Specialist_Consultation = np.array([
    {"catid": 26, "prodcode": 39226, "descr": ""},
    {"catid": 26, "prodcode": 39227, "descr": ""},
])

Specialist_Opthalmologist_Consultation = np.array([
    {"catid": 181, "prodcode": 37234, "descr": ""},
    {"catid": 181, "prodcode": 37235, "descr": ""},
    {"catid": 181, "prodcode": 39050, "descr": ""},
])

Sputum_Acid_Fast_Bacilli_AFB_Test = np.array([
    {"catid": 336, "prodcode": 38709, "descr": ""},
    {"catid": 336, "prodcode": 38710, "descr": ""},
])

Stool_Occult_Blood = np.array([
    {"catid": 249, "prodcode": 37484, "descr": ""},
])

Stress_Management = np.array([
    {"catid": 87, "prodcode": 38477, "descr": ""},
])

Surgeries_All_Inclusive = np.array([
    {"catid": 46, "prodcode": 36648, "descr": ""},
    {"catid": 46, "prodcode": 36664, "descr": ""},
    {"catid": 46, "prodcode": 36665, "descr": ""},
    {"catid": 46, "prodcode": 36714, "descr": ""},
    {"catid": 46, "prodcode": 37201, "descr": ""},
    {"catid": 46, "prodcode": 37218, "descr": ""},
    {"catid": 46, "prodcode": 37577, "descr": ""},
    {"catid": 46, "prodcode": 37585, "descr": ""},
    {"catid": 46, "prodcode": 37598, "descr": ""},
    {"catid": 46, "prodcode": 37599, "descr": ""},
    {"catid": 46, "prodcode": 37600, "descr": ""},
    {"catid": 46, "prodcode": 37601, "descr": ""},
    {"catid": 46, "prodcode": 39092, "descr": ""},
    {"catid": 46, "prodcode": 39093, "descr": ""},
    {"catid": 46, "prodcode": 39101, "descr": ""},
    {"catid": 46, "prodcode": 39286, "descr": ""},
])

Surgical_Cancer_Care = np.array([
    {"catid": 141, "prodcode": 36684, "descr": ""},
    {"catid": 141, "prodcode": 36685, "descr": ""},
    {"catid": 141, "prodcode": 37598, "descr": ""},
    {"catid": 141, "prodcode": 37599, "descr": ""},
    {"catid": 141, "prodcode": 37600, "descr": ""},
    {"catid": 141, "prodcode": 37601, "descr": ""},
    {"catid": 141, "prodcode": 38561, "descr": ""},
    {"catid": 141, "prodcode": 38562, "descr": ""},
    {"catid": 141, "prodcode": 39055, "descr": ""},
    {"catid": 141, "prodcode": 39196, "descr": ""},
])

Surgical_extraction = np.array([
    {"catid": 172, "prodcode": 39286, "descr": ""},
])

# =============================================================================
# SUMMARY — S.py
# =============================================================================
# Categories in this file : 41
# Total product entries    : 117
# Duplicate entries removed: 0
#
# Breakdown by category:
#   Scaling_and_Polishing (catid=168): (no products — variable omitted)
#   Seeking_Second_Opinion (catid=52): 19 products
#   Semen_M_C_S (catid=322): (no products — variable omitted)
#   Semi_Private_Room (catid=341): (no products — variable omitted)
#   Seminal_Fluid_Analysis_SFA (catid=332): 9 products
#   Serum_Acid_Phosphate (catid=154): 2 products
#   Serum_Albumin (catid=157): (no products — variable omitted)
#   Serum_Alkaline_Phosphate (catid=153): (no products — variable omitted)
#   Serum_Bicarbonate (catid=162): (no products — variable omitted)
#   Serum_Bilirubin_Total_and_Direct (catid=156): 1 products
#   Serum_Calcium (catid=148): (no products — variable omitted)
#   Serum_Chloride (catid=161): 2 products
#   Serum_Cholesterol (catid=289): (no products — variable omitted)
#   Serum_Gamma_Glutamyl_Transferase (catid=164): (no products — variable omitted)
#   Serum_Inorganic_Phosphate (catid=155): 7 products
#   Serum_Iron (catid=323): 1 products
#   Serum_Lactate_Dehydrogenase (catid=163): 1 products
#   Serum_Lithium (catid=160): 4 products
#   Serum_Magnesium (catid=158): 4 products
#   Serum_Potasium (catid=159): 3 products
#   Serum_Sodium (catid=145): 1 products
#   Serum_Uric_Acid (catid=315): (no products — variable omitted)
#   Sigmoidoscopy (catid=101): (no products — variable omitted)
#   Sinus_X_rays (catid=130): 2 products
#   Skin_Scraping_for_Fungi (catid=229): 3 products
#   Skin_Snip_for_Microfilaria (catid=228): 2 products
#   Skull_X_rays (catid=133): 8 products
#   Special_Care_baby_Unit (catid=307): 12 products
#   Specialist_Consultation (catid=26): 2 products
#   Specialist_Drug_Therapy (catid=211): (no products — variable omitted)
#   Specialist_Opthalmologist_Consultation (catid=181): 3 products
#   Sputum_Acid_Fast_Bacilli_AFB_Test (catid=336): 2 products
#   Sputum_M_C_S (catid=242): (no products — variable omitted)
#   Standard_Room (catid=340): (no products — variable omitted)
#   Stool_M_C_S (catid=244): (no products — variable omitted)
#   Stool_Occult_Blood (catid=249): 1 products
#   Stress_Management (catid=87): 1 products
#   Surgeries_All_Inclusive (catid=46): 16 products
#   Surgical_Cancer_Care (catid=141): 10 products
#   Surgical_extraction (catid=172): 1 products
#   Syphilis_Screening (catid=320): (no products — variable omitted)
# =============================================================================
