import numpy as np

# =============================================================================
# F.py
# Service category product assignments — letter F
# Generated by: product-service-mapper skill
# =============================================================================

Facials = np.array([
    {"catid": 194, "prodcode": 38518, "descr": ""},
    {"catid": 194, "prodcode": 38624, "descr": ""},
    {"catid": 194, "prodcode": 39286, "descr": ""},
])

Family_Planning_Out_Patient_Limit = np.array([
    {"catid": 43, "prodcode": 36131, "descr": ""},
    {"catid": 43, "prodcode": 37374, "descr": ""},
    {"catid": 43, "prodcode": 37478, "descr": ""},
    {"catid": 43, "prodcode": 38390, "descr": ""},
])

Fasting_Blood_Sugar = np.array([
    {"catid": 149, "prodcode": 39041, "descr": ""},
])

Fertility_Investigations = np.array([
    {"catid": 227, "prodcode": 36544, "descr": ""},
    {"catid": 227, "prodcode": 36573, "descr": ""},
    {"catid": 227, "prodcode": 37487, "descr": ""},
    {"catid": 227, "prodcode": 37502, "descr": ""},
    {"catid": 227, "prodcode": 37685, "descr": ""},
    {"catid": 227, "prodcode": 38238, "descr": ""},
    {"catid": 227, "prodcode": 38240, "descr": ""},
    {"catid": 227, "prodcode": 38441, "descr": ""},
    {"catid": 227, "prodcode": 38444, "descr": ""},
    {"catid": 227, "prodcode": 38446, "descr": ""},
    {"catid": 227, "prodcode": 38447, "descr": ""},
    {"catid": 227, "prodcode": 38448, "descr": ""},
    {"catid": 227, "prodcode": 38449, "descr": ""},
    {"catid": 227, "prodcode": 38730, "descr": ""},
    {"catid": 227, "prodcode": 38733, "descr": ""},
    {"catid": 227, "prodcode": 39252, "descr": ""},
    {"catid": 227, "prodcode": 39829, "descr": ""},
    {"catid": 227, "prodcode": 39830, "descr": ""},
    {"catid": 227, "prodcode": 39831, "descr": ""},
    {"catid": 227, "prodcode": 39834, "descr": ""},
    {"catid": 227, "prodcode": 39837, "descr": ""},
    {"catid": 227, "prodcode": 39838, "descr": ""},
    {"catid": 227, "prodcode": 39841, "descr": ""},
    {"catid": 227, "prodcode": 39866, "descr": ""},
    {"catid": 227, "prodcode": 39867, "descr": ""},
])

Fertility_Specialist_Consultation_and_Counselling = np.array([
    {"catid": 226, "prodcode": 37502, "descr": ""},
    {"catid": 226, "prodcode": 39050, "descr": ""},
])

Full_Blood_Count_and_differentials_FBC = np.array([
    {"catid": 196, "prodcode": 38423, "descr": ""},
])

# =============================================================================
# SUMMARY — F.py
# =============================================================================
# Categories in this file : 7
# Total product entries    : 36
# Duplicate entries removed: 0
#
# Breakdown by category:
#   Facials (catid=194): 3 products
#   Family_Physician (catid=282): (no products — variable omitted)
#   Family_Planning_Out_Patient_Limit (catid=43): 4 products
#   Fasting_Blood_Sugar (catid=149): 1 products
#   Fertility_Investigations (catid=227): 25 products
#   Fertility_Specialist_Consultation_and_Counselling (catid=226): 2 products
#   Full_Blood_Count_and_differentials_FBC (catid=196): 1 products
# =============================================================================
