import numpy as np

# =============================================================================
# T.py
# Service category product assignments — letter T
# Generated by: product-service-mapper skill
# =============================================================================

Therapeutic_Abortion_Manual_Vacuum_Aspiration = np.array([
    {"catid": 255, "prodcode": 36648, "descr": ""},
    {"catid": 255, "prodcode": 36677, "descr": ""},
    {"catid": 255, "prodcode": 38430, "descr": ""},
    {"catid": 255, "prodcode": 38431, "descr": ""},
    {"catid": 255, "prodcode": 38433, "descr": ""},
    {"catid": 255, "prodcode": 38434, "descr": ""},
    {"catid": 255, "prodcode": 38435, "descr": ""},
    {"catid": 255, "prodcode": 38436, "descr": ""},
    {"catid": 255, "prodcode": 38501, "descr": ""},
    {"catid": 255, "prodcode": 39092, "descr": ""},
    {"catid": 255, "prodcode": 39093, "descr": ""},
    {"catid": 255, "prodcode": 39101, "descr": ""},
    {"catid": 255, "prodcode": 39245, "descr": ""},
])

Thoracic_Inlet_X_rays = np.array([
    {"catid": 125, "prodcode": 36721, "descr": ""},
    {"catid": 125, "prodcode": 39125, "descr": ""},
])

Thoraco_Lumbar_X_rays = np.array([
    {"catid": 126, "prodcode": 36721, "descr": ""},
])

Thoracoscopy = np.array([
    {"catid": 112, "prodcode": 36648, "descr": ""},
    {"catid": 112, "prodcode": 39050, "descr": ""},
    {"catid": 112, "prodcode": 39092, "descr": ""},
    {"catid": 112, "prodcode": 39093, "descr": ""},
    {"catid": 112, "prodcode": 39101, "descr": ""},
])

Thyroid_Function_Tests = np.array([
    {"catid": 314, "prodcode": 38418, "descr": ""},
])

Toxoplasma_Screening = np.array([
    {"catid": 232, "prodcode": 38430, "descr": ""},
    {"catid": 232, "prodcode": 38431, "descr": ""},
    {"catid": 232, "prodcode": 38433, "descr": ""},
    {"catid": 232, "prodcode": 38434, "descr": ""},
    {"catid": 232, "prodcode": 38435, "descr": ""},
    {"catid": 232, "prodcode": 38436, "descr": ""},
])

Treatment_of_basic_outpatient_and_in_patient_cases = np.array([
    {"catid": 58, "prodcode": 39286, "descr": ""},
])

# =============================================================================
# SUMMARY — T.py
# =============================================================================
# Categories in this file : 9
# Total product entries    : 29
# Duplicate entries removed: 0
#
# Breakdown by category:
#   Therapeutic_Abortion_Manual_Vacuum_Aspiration (catid=255): 13 products
#   Thoracic_Inlet_X_rays (catid=125): 2 products
#   Thoraco_Lumbar_X_rays (catid=126): 1 products
#   Thoracoscopy (catid=112): 5 products
#   Throat_Swab_M_C_S (catid=238): (no products — variable omitted)
#   Thyroid_Function_Tests (catid=314): 1 products
#   Toxoplasma_Screening (catid=232): 6 products
#   Treatment_of_basic_outpatient_and_in_patient_cases (catid=58): 1 products
#   Trypanosomes_Screening (catid=231): (no products — variable omitted)
# =============================================================================
