import numpy as np

# =============================================================================
# D.py
# Service category product assignments — letter D
# Generated by: product-service-mapper skill
# =============================================================================

D_Dimer = np.array([
    {"catid": 335, "prodcode": 27738, "descr": ""},
])

Delivery_Multiple = np.array([
    {"catid": 253, "prodcode": 25296, "descr": ""},
    {"catid": 253, "prodcode": 26322, "descr": ""},
    {"catid": 253, "prodcode": 27005, "descr": ""},
    {"catid": 253, "prodcode": 27751, "descr": ""},
])

Delivery_SVD_or_Normal_and_Complicated = np.array([
    {"catid": 252, "prodcode": 25276, "descr": ""},
    {"catid": 252, "prodcode": 25384, "descr": ""},
    {"catid": 252, "prodcode": 25411, "descr": ""},
    {"catid": 252, "prodcode": 25663, "descr": ""},
    {"catid": 252, "prodcode": 25664, "descr": ""},
    {"catid": 252, "prodcode": 25668, "descr": ""},
    {"catid": 252, "prodcode": 25685, "descr": ""},
    {"catid": 252, "prodcode": 25779, "descr": ""},
    {"catid": 252, "prodcode": 25780, "descr": ""},
    {"catid": 252, "prodcode": 25781, "descr": ""},
    {"catid": 252, "prodcode": 26096, "descr": ""},
    {"catid": 252, "prodcode": 26099, "descr": ""},
    {"catid": 252, "prodcode": 26132, "descr": ""},
    {"catid": 252, "prodcode": 26228, "descr": ""},
    {"catid": 252, "prodcode": 26230, "descr": ""},
    {"catid": 252, "prodcode": 26265, "descr": ""},
    {"catid": 252, "prodcode": 26316, "descr": ""},
    {"catid": 252, "prodcode": 26317, "descr": ""},
    {"catid": 252, "prodcode": 26318, "descr": ""},
    {"catid": 252, "prodcode": 26319, "descr": ""},
    {"catid": 252, "prodcode": 26320, "descr": ""},
    {"catid": 252, "prodcode": 26321, "descr": ""},
    {"catid": 252, "prodcode": 26333, "descr": ""},
    {"catid": 252, "prodcode": 26387, "descr": ""},
    {"catid": 252, "prodcode": 26389, "descr": ""},
    {"catid": 252, "prodcode": 26393, "descr": ""},
    {"catid": 252, "prodcode": 26396, "descr": ""},
    {"catid": 252, "prodcode": 26397, "descr": ""},
    {"catid": 252, "prodcode": 26398, "descr": ""},
    {"catid": 252, "prodcode": 26399, "descr": ""},
    {"catid": 252, "prodcode": 26400, "descr": ""},
    {"catid": 252, "prodcode": 26401, "descr": ""},
    {"catid": 252, "prodcode": 26403, "descr": ""},
])

Dental_Care = np.array([
    {"catid": 36, "prodcode": 25261, "descr": ""},
    {"catid": 36, "prodcode": 25277, "descr": ""},
    {"catid": 36, "prodcode": 25292, "descr": ""},
    {"catid": 36, "prodcode": 25331, "descr": ""},
    {"catid": 36, "prodcode": 25342, "descr": ""},
    {"catid": 36, "prodcode": 25343, "descr": ""},
    {"catid": 36, "prodcode": 25344, "descr": ""},
    {"catid": 36, "prodcode": 25345, "descr": ""},
    {"catid": 36, "prodcode": 25346, "descr": ""},
    {"catid": 36, "prodcode": 25350, "descr": ""},
    {"catid": 36, "prodcode": 25657, "descr": ""},
    {"catid": 36, "prodcode": 25675, "descr": ""},
    {"catid": 36, "prodcode": 25689, "descr": ""},
    {"catid": 36, "prodcode": 25705, "descr": ""},
    {"catid": 36, "prodcode": 25721, "descr": ""},
    {"catid": 36, "prodcode": 25722, "descr": ""},
    {"catid": 36, "prodcode": 25724, "descr": ""},
    {"catid": 36, "prodcode": 25732, "descr": ""},
    {"catid": 36, "prodcode": 25737, "descr": ""},
    {"catid": 36, "prodcode": 25738, "descr": ""},
    {"catid": 36, "prodcode": 25739, "descr": ""},
    {"catid": 36, "prodcode": 26247, "descr": ""},
    {"catid": 36, "prodcode": 26337, "descr": ""},
    {"catid": 36, "prodcode": 26341, "descr": ""},
    {"catid": 36, "prodcode": 26352, "descr": ""},
    {"catid": 36, "prodcode": 26353, "descr": ""},
    {"catid": 36, "prodcode": 26354, "descr": ""},
    {"catid": 36, "prodcode": 26363, "descr": ""},
    {"catid": 36, "prodcode": 26364, "descr": ""},
    {"catid": 36, "prodcode": 26365, "descr": ""},
    {"catid": 36, "prodcode": 26368, "descr": ""},
    {"catid": 36, "prodcode": 26369, "descr": ""},
    {"catid": 36, "prodcode": 26370, "descr": ""},
    {"catid": 36, "prodcode": 26396, "descr": ""},
    {"catid": 36, "prodcode": 26397, "descr": ""},
    {"catid": 36, "prodcode": 26398, "descr": ""},
    {"catid": 36, "prodcode": 26399, "descr": ""},
    {"catid": 36, "prodcode": 26400, "descr": ""},
    {"catid": 36, "prodcode": 27003, "descr": ""},
    {"catid": 36, "prodcode": 27020, "descr": ""},
    {"catid": 36, "prodcode": 27021, "descr": ""},
    {"catid": 36, "prodcode": 27032, "descr": ""},
    {"catid": 36, "prodcode": 27462, "descr": ""},
    {"catid": 36, "prodcode": 27530, "descr": ""},
    {"catid": 36, "prodcode": 27532, "descr": ""},
    {"catid": 36, "prodcode": 27693, "descr": ""},
    {"catid": 36, "prodcode": 27758, "descr": ""},
])

Dental_consultation = np.array([
    {"catid": 338, "prodcode": 25239, "descr": ""},
])

Dental_pain_therapy = np.array([
    {"catid": 171, "prodcode": 25292, "descr": ""},
    {"catid": 171, "prodcode": 25650, "descr": ""},
    {"catid": 171, "prodcode": 25651, "descr": ""},
    {"catid": 171, "prodcode": 27003, "descr": ""},
    {"catid": 171, "prodcode": 27289, "descr": ""},
    {"catid": 171, "prodcode": 27548, "descr": ""},
    {"catid": 171, "prodcode": 28438, "descr": ""},
])

Diagnosis_Confirmation_From_Secondary_And_Tertiary_Care_Centres = np.array([
    {"catid": 259, "prodcode": 26255, "descr": ""},
    {"catid": 259, "prodcode": 26256, "descr": ""},
    {"catid": 259, "prodcode": 26257, "descr": ""},
    {"catid": 259, "prodcode": 26258, "descr": ""},
])

Dialysis_And_All_Related_Care = np.array([
    {"catid": 257, "prodcode": 25285, "descr": ""},
    {"catid": 257, "prodcode": 26096, "descr": ""},
    {"catid": 257, "prodcode": 26218, "descr": ""},
    {"catid": 257, "prodcode": 27174, "descr": ""},
])

Dietician_or_Nutritionist = np.array([
    {"catid": 270, "prodcode": 26865, "descr": ""},
])

# =============================================================================
# SUMMARY — D.py
# =============================================================================
# Categories in this file : 11
# Total product entries    : 102
# Duplicate entries removed: 0
#
# Breakdown by category:
#   D_Dimer (catid=335): 1 products
#   Delivery_Multiple (catid=253): 4 products
#   Delivery_SVD_or_Normal_and_Complicated (catid=252): 33 products
#   Dental_Care (catid=36): 47 products
#   Dental_consultation (catid=338): 1 products
#   Dental_pain_therapy (catid=171): 7 products
#   Dermatologist (catid=281): (no products — variable omitted)
#   Diagnosis_Confirmation_From_Secondary_And_Tertiary_Care_Centres (catid=259): 4 products
#   Dialysis_And_All_Related_Care (catid=257): 4 products
#   Dietician_or_Nutritionist (catid=270): 1 products
#   Dpt (catid=84): (no products — variable omitted)
# =============================================================================
