import numpy as np

# =============================================================================
# E.py
# Service category product assignments — letter E
# Generated by: product-service-mapper skill
# =============================================================================

Echocardiography = np.array([
    {"catid": 99, "prodcode": 26403, "descr": ""},
    {"catid": 99, "prodcode": 26902, "descr": ""},
])

Electrolytes_Urea_and_Creatinine = np.array([
    {"catid": 167, "prodcode": 26156, "descr": ""},
    {"catid": 167, "prodcode": 26902, "descr": ""},
    {"catid": 167, "prodcode": 27090, "descr": ""},
    {"catid": 167, "prodcode": 27096, "descr": ""},
    {"catid": 167, "prodcode": 27097, "descr": ""},
    {"catid": 167, "prodcode": 27098, "descr": ""},
])

Emergency_Transportation = np.array([
    {"catid": 90, "prodcode": 25285, "descr": ""},
    {"catid": 90, "prodcode": 26965, "descr": ""},
    {"catid": 90, "prodcode": 26966, "descr": ""},
    {"catid": 90, "prodcode": 26967, "descr": ""},
    {"catid": 90, "prodcode": 27533, "descr": ""},
    {"catid": 90, "prodcode": 27534, "descr": ""},
])

Endocrinologist = np.array([
    {"catid": 275, "prodcode": 26440, "descr": ""},
])

Endoscopic_retrograde_cholangiopancreatography_ERCP = np.array([
    {"catid": 103, "prodcode": 25321, "descr": ""},
    {"catid": 103, "prodcode": 26359, "descr": ""},
    {"catid": 103, "prodcode": 26960, "descr": ""},
])

Enteroscopy = np.array([
    {"catid": 114, "prodcode": 25071, "descr": ""},
    {"catid": 114, "prodcode": 25160, "descr": ""},
    {"catid": 114, "prodcode": 25321, "descr": ""},
    {"catid": 114, "prodcode": 25706, "descr": ""},
    {"catid": 114, "prodcode": 25735, "descr": ""},
    {"catid": 114, "prodcode": 25736, "descr": ""},
    {"catid": 114, "prodcode": 26092, "descr": ""},
    {"catid": 114, "prodcode": 26359, "descr": ""},
    {"catid": 114, "prodcode": 26719, "descr": ""},
    {"catid": 114, "prodcode": 27497, "descr": ""},
    {"catid": 114, "prodcode": 27498, "descr": ""},
])

Eye_Swab_M_C_S = np.array([
    {"catid": 241, "prodcode": 26372, "descr": ""},
])

Eye_Optical_Care = np.array([
    {"catid": 35, "prodcode": 24740, "descr": ""},
    {"catid": 35, "prodcode": 24856, "descr": ""},
    {"catid": 35, "prodcode": 24857, "descr": ""},
    {"catid": 35, "prodcode": 25986, "descr": ""},
    {"catid": 35, "prodcode": 25987, "descr": ""},
    {"catid": 35, "prodcode": 26014, "descr": ""},
    {"catid": 35, "prodcode": 26555, "descr": ""},
    {"catid": 35, "prodcode": 26658, "descr": ""},
    {"catid": 35, "prodcode": 26659, "descr": ""},
    {"catid": 35, "prodcode": 26688, "descr": ""},
    {"catid": 35, "prodcode": 26690, "descr": ""},
    {"catid": 35, "prodcode": 26695, "descr": ""},
    {"catid": 35, "prodcode": 26730, "descr": ""},
    {"catid": 35, "prodcode": 26789, "descr": ""},
    {"catid": 35, "prodcode": 26833, "descr": ""},
    {"catid": 35, "prodcode": 27292, "descr": ""},
    {"catid": 35, "prodcode": 27293, "descr": ""},
    {"catid": 35, "prodcode": 27294, "descr": ""},
    {"catid": 35, "prodcode": 27364, "descr": ""},
    {"catid": 35, "prodcode": 27365, "descr": ""},
    {"catid": 35, "prodcode": 27378, "descr": ""},
    {"catid": 35, "prodcode": 27563, "descr": ""},
    {"catid": 35, "prodcode": 27566, "descr": ""},
    {"catid": 35, "prodcode": 27610, "descr": ""},
    {"catid": 35, "prodcode": 27869, "descr": ""},
    {"catid": 35, "prodcode": 27870, "descr": ""},
    {"catid": 35, "prodcode": 27899, "descr": ""},
    {"catid": 35, "prodcode": 27972, "descr": ""},
    {"catid": 35, "prodcode": 27977, "descr": ""},
    {"catid": 35, "prodcode": 27978, "descr": ""},
    {"catid": 35, "prodcode": 27979, "descr": ""},
    {"catid": 35, "prodcode": 28420, "descr": ""},
    {"catid": 35, "prodcode": 28441, "descr": ""},
    {"catid": 35, "prodcode": 28442, "descr": ""},
    {"catid": 35, "prodcode": 28445, "descr": ""},
    {"catid": 35, "prodcode": 28446, "descr": ""},
    {"catid": 35, "prodcode": 28460, "descr": ""},
])

# =============================================================================
# SUMMARY — E.py
# =============================================================================
# Categories in this file : 14
# Total product entries    : 67
# Duplicate entries removed: 0
#
# Breakdown by category:
#   Ear_Swab_M_C_S (catid=239): (no products — variable omitted)
#   ECG_PRE_AND_POST_EXERCISE (catid=115): (no products — variable omitted)
#   Echocardiography (catid=99): 2 products
#   Electrolytes_Urea_and_Creatinine (catid=167): 6 products
#   Emergency_Room_Care (catid=88): (no products — variable omitted)
#   Emergency_Transportation (catid=90): 6 products
#   Endocervical_Swab_ECS_M_or_C_or_S (catid=235): (no products — variable omitted)
#   Endocrinologist (catid=275): 1 products
#   Endoscopic_retrograde_cholangiopancreatography_ERCP (catid=103): 3 products
#   ENT_Surgeon_Otorhinolaryngologist (catid=261): (no products — variable omitted)
#   Enteroscopy (catid=114): 11 products
#   Erythrocyte_Sedimentation_Rate_ESR (catid=209): (no products — variable omitted)
#   Eye_Swab_M_C_S (catid=241): 1 products
#   Eye_Optical_Care (catid=35): 37 products
# =============================================================================
