import numpy as np

# =============================================================================
# H.py
# Service category product assignments — letter H
# Generated by: product-service-mapper skill
# =============================================================================

Hemoglobin_HB = np.array([
    {"catid": 200, "prodcode": 25229, "descr": ""},
    {"catid": 200, "prodcode": 25230, "descr": ""},
])

Hepatitis_B = np.array([
    {"catid": 83, "prodcode": 27177, "descr": ""},
    {"catid": 83, "prodcode": 27468, "descr": ""},
])

Hepatitis_B_Screening = np.array([
    {"catid": 318, "prodcode": 25628, "descr": ""},
])

Hepatitis_B_Surface_Antigen_HBSAg = np.array([
    {"catid": 310, "prodcode": 27177, "descr": ""},
    {"catid": 310, "prodcode": 27468, "descr": ""},
])

HIV_Screening = np.array([
    {"catid": 311, "prodcode": 25608, "descr": ""},
    {"catid": 311, "prodcode": 26896, "descr": ""},
])

Hysteroscopy = np.array([
    {"catid": 113, "prodcode": 25735, "descr": ""},
    {"catid": 113, "prodcode": 25736, "descr": ""},
    {"catid": 113, "prodcode": 26098, "descr": ""},
    {"catid": 113, "prodcode": 27000, "descr": ""},
    {"catid": 113, "prodcode": 27001, "descr": ""},
    {"catid": 113, "prodcode": 27160, "descr": ""},
    {"catid": 113, "prodcode": 28432, "descr": ""},
])

# =============================================================================
# SUMMARY — H.py
# =============================================================================
# Categories in this file : 14
# Total product entries    : 16
# Duplicate entries removed: 0
#
# Breakdown by category:
#   H_Pylori (catid=246): (no products — variable omitted)
#   HBA1C (catid=316): (no products — variable omitted)
#   Hematological_Test (catid=31): (no products — variable omitted)
#   Hematologist (catid=272): (no products — variable omitted)
#   Hemoglobin_HB (catid=200): 2 products
#   Hepatitis_B (catid=83): 2 products
#   Hepatitis_B_Screening (catid=318): 1 products
#   Hepatitis_B_Surface_Antigen_HBSAg (catid=310): 2 products
#   Hepatitis_C_Screening (catid=317): (no products — variable omitted)
#   High_Vaginal_Swab_HVS_M_or_C_or_S (catid=236): (no products — variable omitted)
#   Hiv_Care_And_Treatment_At_Designated_Sites (catid=51): (no products — variable omitted)
#   HIV_Confirmatory_Test (catid=312): (no products — variable omitted)
#   HIV_Screening (catid=311): 2 products
#   Hysteroscopy (catid=113): 7 products
# =============================================================================
