import numpy as np

# =============================================================================
# I.py
# Service category product assignments — letter I
# Generated by: product-service-mapper skill
# =============================================================================

In_Patient_Care_Limit = np.array([
    {"catid": 28, "prodcode": 25706, "descr": ""},
    {"catid": 28, "prodcode": 27694, "descr": ""},
    {"catid": 28, "prodcode": 27695, "descr": ""},
])

Incision_and_Drainage = np.array([
    {"catid": 180, "prodcode": 25277, "descr": ""},
    {"catid": 180, "prodcode": 25334, "descr": ""},
    {"catid": 180, "prodcode": 26099, "descr": ""},
    {"catid": 180, "prodcode": 26132, "descr": ""},
    {"catid": 180, "prodcode": 26228, "descr": ""},
    {"catid": 180, "prodcode": 26230, "descr": ""},
    {"catid": 180, "prodcode": 26247, "descr": ""},
    {"catid": 180, "prodcode": 26333, "descr": ""},
    {"catid": 180, "prodcode": 26387, "descr": ""},
    {"catid": 180, "prodcode": 26389, "descr": ""},
    {"catid": 180, "prodcode": 26393, "descr": ""},
    {"catid": 180, "prodcode": 26396, "descr": ""},
    {"catid": 180, "prodcode": 26397, "descr": ""},
    {"catid": 180, "prodcode": 26398, "descr": ""},
    {"catid": 180, "prodcode": 26399, "descr": ""},
    {"catid": 180, "prodcode": 26400, "descr": ""},
    {"catid": 180, "prodcode": 26401, "descr": ""},
    {"catid": 180, "prodcode": 26403, "descr": ""},
])

Injectibles = np.array([
    {"catid": 216, "prodcode": 25110, "descr": ""},
    {"catid": 216, "prodcode": 26490, "descr": ""},
])

Intensive_Care_Unit = np.array([
    {"catid": 91, "prodcode": 26049, "descr": ""},
])

Intermediate_Surgeries = np.array([
    {"catid": 286, "prodcode": 25264, "descr": ""},
    {"catid": 286, "prodcode": 25268, "descr": ""},
    {"catid": 286, "prodcode": 25320, "descr": ""},
    {"catid": 286, "prodcode": 25351, "descr": ""},
    {"catid": 286, "prodcode": 25375, "descr": ""},
    {"catid": 286, "prodcode": 25644, "descr": ""},
    {"catid": 286, "prodcode": 25646, "descr": ""},
    {"catid": 286, "prodcode": 25648, "descr": ""},
    {"catid": 286, "prodcode": 25650, "descr": ""},
    {"catid": 286, "prodcode": 25651, "descr": ""},
    {"catid": 286, "prodcode": 25654, "descr": ""},
    {"catid": 286, "prodcode": 25655, "descr": ""},
    {"catid": 286, "prodcode": 25656, "descr": ""},
    {"catid": 286, "prodcode": 25658, "descr": ""},
    {"catid": 286, "prodcode": 25659, "descr": ""},
    {"catid": 286, "prodcode": 25660, "descr": ""},
    {"catid": 286, "prodcode": 25661, "descr": ""},
    {"catid": 286, "prodcode": 25662, "descr": ""},
    {"catid": 286, "prodcode": 25666, "descr": ""},
    {"catid": 286, "prodcode": 25674, "descr": ""},
    {"catid": 286, "prodcode": 25677, "descr": ""},
    {"catid": 286, "prodcode": 25685, "descr": ""},
    {"catid": 286, "prodcode": 25686, "descr": ""},
    {"catid": 286, "prodcode": 25693, "descr": ""},
    {"catid": 286, "prodcode": 25696, "descr": ""},
    {"catid": 286, "prodcode": 25709, "descr": ""},
    {"catid": 286, "prodcode": 25719, "descr": ""},
    {"catid": 286, "prodcode": 25720, "descr": ""},
    {"catid": 286, "prodcode": 26217, "descr": ""},
    {"catid": 286, "prodcode": 26264, "descr": ""},
    {"catid": 286, "prodcode": 26266, "descr": ""},
    {"catid": 286, "prodcode": 26273, "descr": ""},
    {"catid": 286, "prodcode": 26277, "descr": ""},
    {"catid": 286, "prodcode": 26281, "descr": ""},
    {"catid": 286, "prodcode": 26292, "descr": ""},
    {"catid": 286, "prodcode": 26293, "descr": ""},
    {"catid": 286, "prodcode": 26294, "descr": ""},
    {"catid": 286, "prodcode": 26302, "descr": ""},
    {"catid": 286, "prodcode": 26310, "descr": ""},
    {"catid": 286, "prodcode": 26323, "descr": ""},
    {"catid": 286, "prodcode": 26348, "descr": ""},
    {"catid": 286, "prodcode": 26350, "descr": ""},
    {"catid": 286, "prodcode": 26379, "descr": ""},
    {"catid": 286, "prodcode": 26404, "descr": ""},
    {"catid": 286, "prodcode": 26406, "descr": ""},
    {"catid": 286, "prodcode": 26963, "descr": ""},
    {"catid": 286, "prodcode": 26964, "descr": ""},
    {"catid": 286, "prodcode": 26979, "descr": ""},
    {"catid": 286, "prodcode": 26980, "descr": ""},
    {"catid": 286, "prodcode": 26981, "descr": ""},
    {"catid": 286, "prodcode": 26986, "descr": ""},
    {"catid": 286, "prodcode": 26987, "descr": ""},
    {"catid": 286, "prodcode": 26999, "descr": ""},
    {"catid": 286, "prodcode": 27004, "descr": ""},
    {"catid": 286, "prodcode": 27023, "descr": ""},
    {"catid": 286, "prodcode": 27024, "descr": ""},
    {"catid": 286, "prodcode": 27025, "descr": ""},
    {"catid": 286, "prodcode": 27031, "descr": ""},
    {"catid": 286, "prodcode": 27037, "descr": ""},
    {"catid": 286, "prodcode": 27040, "descr": ""},
    {"catid": 286, "prodcode": 27132, "descr": ""},
    {"catid": 286, "prodcode": 27133, "descr": ""},
    {"catid": 286, "prodcode": 27134, "descr": ""},
    {"catid": 286, "prodcode": 27143, "descr": ""},
    {"catid": 286, "prodcode": 27144, "descr": ""},
    {"catid": 286, "prodcode": 27161, "descr": ""},
    {"catid": 286, "prodcode": 27166, "descr": ""},
    {"catid": 286, "prodcode": 27445, "descr": ""},
    {"catid": 286, "prodcode": 27446, "descr": ""},
    {"catid": 286, "prodcode": 27447, "descr": ""},
    {"catid": 286, "prodcode": 27452, "descr": ""},
    {"catid": 286, "prodcode": 27539, "descr": ""},
    {"catid": 286, "prodcode": 27548, "descr": ""},
    {"catid": 286, "prodcode": 27550, "descr": ""},
    {"catid": 286, "prodcode": 27551, "descr": ""},
    {"catid": 286, "prodcode": 27553, "descr": ""},
    {"catid": 286, "prodcode": 27556, "descr": ""},
])

# =============================================================================
# SUMMARY — I.py
# =============================================================================
# Categories in this file : 8
# Total product entries    : 101
# Duplicate entries removed: 0
#
# Breakdown by category:
#   Implanon (catid=188): (no products — variable omitted)
#   In_Patient_Care_Limit (catid=28): 3 products
#   Incision_and_Drainage (catid=180): 18 products
#   Incubator_Care (catid=217): (no products — variable omitted)
#   Infertility_Care (catid=39): (no products — variable omitted)
#   Injectibles (catid=216): 2 products
#   Intensive_Care_Unit (catid=91): 1 products
#   Intermediate_Surgeries (catid=286): 77 products
# =============================================================================
