import numpy as np

# =============================================================================
# N.py
# Service category product assignments — letter N
# Generated by: product-service-mapper skill
# =============================================================================

Neck_X_rays = np.array([
    {"catid": 122, "prodcode": 25311, "descr": ""},
    {"catid": 122, "prodcode": 25726, "descr": ""},
    {"catid": 122, "prodcode": 25799, "descr": ""},
    {"catid": 122, "prodcode": 26098, "descr": ""},
    {"catid": 122, "prodcode": 26253, "descr": ""},
    {"catid": 122, "prodcode": 27692, "descr": ""},
])

Neonatologist = np.array([
    {"catid": 280, "prodcode": 25255, "descr": ""},
    {"catid": 280, "prodcode": 25256, "descr": ""},
    {"catid": 280, "prodcode": 25257, "descr": ""},
    {"catid": 280, "prodcode": 25258, "descr": ""},
    {"catid": 280, "prodcode": 25259, "descr": ""},
    {"catid": 280, "prodcode": 25260, "descr": ""},
    {"catid": 280, "prodcode": 25319, "descr": ""},
    {"catid": 280, "prodcode": 25320, "descr": ""},
    {"catid": 280, "prodcode": 26049, "descr": ""},
    {"catid": 280, "prodcode": 26951, "descr": ""},
    {"catid": 280, "prodcode": 26965, "descr": ""},
    {"catid": 280, "prodcode": 26966, "descr": ""},
])

Nephrologist = np.array([
    {"catid": 278, "prodcode": 26156, "descr": ""},
])

Neurosurgeon = np.array([
    {"catid": 268, "prodcode": 25315, "descr": ""},
    {"catid": 268, "prodcode": 26099, "descr": ""},
    {"catid": 268, "prodcode": 26132, "descr": ""},
    {"catid": 268, "prodcode": 26228, "descr": ""},
    {"catid": 268, "prodcode": 26230, "descr": ""},
    {"catid": 268, "prodcode": 26333, "descr": ""},
    {"catid": 268, "prodcode": 26387, "descr": ""},
    {"catid": 268, "prodcode": 26389, "descr": ""},
    {"catid": 268, "prodcode": 26393, "descr": ""},
    {"catid": 268, "prodcode": 26396, "descr": ""},
    {"catid": 268, "prodcode": 26397, "descr": ""},
    {"catid": 268, "prodcode": 26398, "descr": ""},
    {"catid": 268, "prodcode": 26399, "descr": ""},
    {"catid": 268, "prodcode": 26400, "descr": ""},
    {"catid": 268, "prodcode": 26401, "descr": ""},
    {"catid": 268, "prodcode": 26403, "descr": ""},
])

Non_surgical_extraction = np.array([
    {"catid": 173, "prodcode": 25650, "descr": ""},
    {"catid": 173, "prodcode": 25651, "descr": ""},
    {"catid": 173, "prodcode": 26099, "descr": ""},
    {"catid": 173, "prodcode": 26132, "descr": ""},
    {"catid": 173, "prodcode": 26228, "descr": ""},
    {"catid": 173, "prodcode": 26230, "descr": ""},
    {"catid": 173, "prodcode": 26333, "descr": ""},
    {"catid": 173, "prodcode": 26352, "descr": ""},
    {"catid": 173, "prodcode": 26353, "descr": ""},
    {"catid": 173, "prodcode": 26354, "descr": ""},
    {"catid": 173, "prodcode": 26387, "descr": ""},
    {"catid": 173, "prodcode": 26389, "descr": ""},
    {"catid": 173, "prodcode": 26393, "descr": ""},
    {"catid": 173, "prodcode": 26396, "descr": ""},
    {"catid": 173, "prodcode": 26397, "descr": ""},
    {"catid": 173, "prodcode": 26398, "descr": ""},
    {"catid": 173, "prodcode": 26399, "descr": ""},
    {"catid": 173, "prodcode": 26400, "descr": ""},
    {"catid": 173, "prodcode": 26401, "descr": ""},
    {"catid": 173, "prodcode": 26403, "descr": ""},
    {"catid": 173, "prodcode": 27548, "descr": ""},
])

Norplant = np.array([
    {"catid": 191, "prodcode": 25071, "descr": ""},
    {"catid": 191, "prodcode": 26092, "descr": ""},
    {"catid": 191, "prodcode": 26719, "descr": ""},
    {"catid": 191, "prodcode": 27497, "descr": ""},
    {"catid": 191, "prodcode": 27498, "descr": ""},
])

Npi_Immunization_0_5_Years = np.array([
    {"catid": 40, "prodcode": 26041, "descr": ""},
    {"catid": 40, "prodcode": 26366, "descr": ""},
    {"catid": 40, "prodcode": 26839, "descr": ""},
    {"catid": 40, "prodcode": 26848, "descr": ""},
    {"catid": 40, "prodcode": 27586, "descr": ""},
])

Number_of_Sessions_Covered = np.array([
    {"catid": 223, "prodcode": 25281, "descr": ""},
    {"catid": 223, "prodcode": 25282, "descr": ""},
    {"catid": 223, "prodcode": 25316, "descr": ""},
])

Nursing_Care_and_Consumables = np.array([
    {"catid": 214, "prodcode": 25158, "descr": ""},
    {"catid": 214, "prodcode": 25242, "descr": ""},
    {"catid": 214, "prodcode": 25243, "descr": ""},
    {"catid": 214, "prodcode": 25245, "descr": ""},
    {"catid": 214, "prodcode": 25246, "descr": ""},
    {"catid": 214, "prodcode": 25248, "descr": ""},
    {"catid": 214, "prodcode": 25250, "descr": ""},
    {"catid": 214, "prodcode": 25267, "descr": ""},
    {"catid": 214, "prodcode": 25593, "descr": ""},
    {"catid": 214, "prodcode": 25594, "descr": ""},
    {"catid": 214, "prodcode": 26133, "descr": ""},
    {"catid": 214, "prodcode": 26134, "descr": ""},
    {"catid": 214, "prodcode": 26135, "descr": ""},
    {"catid": 214, "prodcode": 26136, "descr": ""},
    {"catid": 214, "prodcode": 26216, "descr": ""},
    {"catid": 214, "prodcode": 26219, "descr": ""},
    {"catid": 214, "prodcode": 26220, "descr": ""},
    {"catid": 214, "prodcode": 26221, "descr": ""},
    {"catid": 214, "prodcode": 26224, "descr": ""},
    {"catid": 214, "prodcode": 26225, "descr": ""},
    {"catid": 214, "prodcode": 26226, "descr": ""},
    {"catid": 214, "prodcode": 26241, "descr": ""},
    {"catid": 214, "prodcode": 26279, "descr": ""},
    {"catid": 214, "prodcode": 26283, "descr": ""},
    {"catid": 214, "prodcode": 26284, "descr": ""},
    {"catid": 214, "prodcode": 26309, "descr": ""},
    {"catid": 214, "prodcode": 26344, "descr": ""},
    {"catid": 214, "prodcode": 27130, "descr": ""},
    {"catid": 214, "prodcode": 27135, "descr": ""},
    {"catid": 214, "prodcode": 27136, "descr": ""},
    {"catid": 214, "prodcode": 27409, "descr": ""},
    {"catid": 214, "prodcode": 27410, "descr": ""},
    {"catid": 214, "prodcode": 27411, "descr": ""},
    {"catid": 214, "prodcode": 27412, "descr": ""},
    {"catid": 214, "prodcode": 27413, "descr": ""},
    {"catid": 214, "prodcode": 27543, "descr": ""},
    {"catid": 214, "prodcode": 27546, "descr": ""},
    {"catid": 214, "prodcode": 27557, "descr": ""},
    {"catid": 214, "prodcode": 27558, "descr": ""},
    {"catid": 214, "prodcode": 27694, "descr": ""},
    {"catid": 214, "prodcode": 27695, "descr": ""},
    {"catid": 214, "prodcode": 28495, "descr": ""},
])

# =============================================================================
# SUMMARY — N.py
# =============================================================================
# Categories in this file : 10
# Total product entries    : 111
# Duplicate entries removed: 0
#
# Breakdown by category:
#   Neck_X_rays (catid=122): 6 products
#   Neonatologist (catid=280): 12 products
#   Nephrologist (catid=278): 1 products
#   Neurologist (catid=277): (no products — variable omitted)
#   Neurosurgeon (catid=268): 16 products
#   Non_surgical_extraction (catid=173): 21 products
#   Norplant (catid=191): 5 products
#   Npi_Immunization_0_5_Years (catid=40): 5 products
#   Number_of_Sessions_Covered (catid=223): 3 products
#   Nursing_Care_and_Consumables (catid=214): 42 products
# =============================================================================
