import numpy as np

# =============================================================================
# U.py
# Service category product assignments — letter U
# Generated by: product-service-mapper skill
# =============================================================================

Upper_GI_Endoscopy = np.array([
    {"catid": 102, "prodcode": 25160, "descr": ""},
    {"catid": 102, "prodcode": 25706, "descr": ""},
    {"catid": 102, "prodcode": 25735, "descr": ""},
    {"catid": 102, "prodcode": 25736, "descr": ""},
])

Urethral_Swab_M_C_S = np.array([
    {"catid": 237, "prodcode": 25306, "descr": ""},
    {"catid": 237, "prodcode": 26960, "descr": ""},
    {"catid": 237, "prodcode": 27102, "descr": ""},
    {"catid": 237, "prodcode": 27103, "descr": ""},
    {"catid": 237, "prodcode": 27149, "descr": ""},
])

Urinalysis = np.array([
    {"catid": 300, "prodcode": 25160, "descr": ""},
    {"catid": 300, "prodcode": 25229, "descr": ""},
    {"catid": 300, "prodcode": 25230, "descr": ""},
    {"catid": 300, "prodcode": 25706, "descr": ""},
    {"catid": 300, "prodcode": 27061, "descr": ""},
])

Urine_M_C_S = np.array([
    {"catid": 234, "prodcode": 25806, "descr": ""},
    {"catid": 234, "prodcode": 25810, "descr": ""},
    {"catid": 234, "prodcode": 25811, "descr": ""},
    {"catid": 234, "prodcode": 25812, "descr": ""},
    {"catid": 234, "prodcode": 26176, "descr": ""},
    {"catid": 234, "prodcode": 27059, "descr": ""},
    {"catid": 234, "prodcode": 27114, "descr": ""},
    {"catid": 234, "prodcode": 27289, "descr": ""},
    {"catid": 234, "prodcode": 28438, "descr": ""},
])

Urine_Pregnancy_Test = np.array([
    {"catid": 166, "prodcode": 25201, "descr": ""},
    {"catid": 166, "prodcode": 25202, "descr": ""},
    {"catid": 166, "prodcode": 25203, "descr": ""},
    {"catid": 166, "prodcode": 25204, "descr": ""},
    {"catid": 166, "prodcode": 25595, "descr": ""},
    {"catid": 166, "prodcode": 25610, "descr": ""},
    {"catid": 166, "prodcode": 26244, "descr": ""},
    {"catid": 166, "prodcode": 26245, "descr": ""},
    {"catid": 166, "prodcode": 27119, "descr": ""},
    {"catid": 166, "prodcode": 27120, "descr": ""},
    {"catid": 166, "prodcode": 27763, "descr": ""},
])

Urologist = np.array([
    {"catid": 262, "prodcode": 25214, "descr": ""},
    {"catid": 262, "prodcode": 25235, "descr": ""},
    {"catid": 262, "prodcode": 26378, "descr": ""},
    {"catid": 262, "prodcode": 27001, "descr": ""},
    {"catid": 262, "prodcode": 27046, "descr": ""},
    {"catid": 262, "prodcode": 27047, "descr": ""},
    {"catid": 262, "prodcode": 27158, "descr": ""},
    {"catid": 262, "prodcode": 27159, "descr": ""},
])

# =============================================================================
# SUMMARY — U.py
# =============================================================================
# Categories in this file : 6
# Total product entries    : 42
# Duplicate entries removed: 0
#
# Breakdown by category:
#   Upper_GI_Endoscopy (catid=102): 4 products
#   Urethral_Swab_M_C_S (catid=237): 5 products
#   Urinalysis (catid=300): 5 products
#   Urine_M_C_S (catid=234): 9 products
#   Urine_Pregnancy_Test (catid=166): 11 products
#   Urologist (catid=262): 8 products
# =============================================================================
