import numpy as np

# =============================================================================
# V.py
# Service category product assignments — letter V
# Generated by: product-service-mapper skill
# =============================================================================

Vitamin_A = np.array([
    {"catid": 78, "prodcode": 25512, "descr": ""},
    {"catid": 78, "prodcode": 26041, "descr": ""},
    {"catid": 78, "prodcode": 26366, "descr": ""},
    {"catid": 78, "prodcode": 26839, "descr": ""},
    {"catid": 78, "prodcode": 26848, "descr": ""},
    {"catid": 78, "prodcode": 26902, "descr": ""},
    {"catid": 78, "prodcode": 27325, "descr": ""},
    {"catid": 78, "prodcode": 27361, "descr": ""},
    {"catid": 78, "prodcode": 27362, "descr": ""},
    {"catid": 78, "prodcode": 27394, "descr": ""},
    {"catid": 78, "prodcode": 27586, "descr": ""},
])

# =============================================================================
# SUMMARY — V.py
# =============================================================================
# Categories in this file : 2
# Total product entries    : 11
# Duplicate entries removed: 0
#
# Breakdown by category:
#   VDRL_Veneral_Disease_Research_Laboratory_Test_unless_where_disallowed_by_diagnosis (catid=245): (no products — variable omitted)
#   Vitamin_A (catid=78): 11 products
# =============================================================================
