import numpy as np

# =============================================================================
# X.py
# Service category product assignments — letter X
# Generated by: product-service-mapper skill
# =============================================================================

X_rays_of_All_Body_Joints = np.array([
    {"catid": 129, "prodcode": 25315, "descr": ""},
    {"catid": 129, "prodcode": 25411, "descr": ""},
    {"catid": 129, "prodcode": 25595, "descr": ""},
    {"catid": 129, "prodcode": 25596, "descr": ""},
    {"catid": 129, "prodcode": 25779, "descr": ""},
    {"catid": 129, "prodcode": 25780, "descr": ""},
    {"catid": 129, "prodcode": 25781, "descr": ""},
    {"catid": 129, "prodcode": 26265, "descr": ""},
    {"catid": 129, "prodcode": 27018, "descr": ""},
])

# =============================================================================
# SUMMARY — X.py
# =============================================================================
# Categories in this file : 1
# Total product entries    : 9
# Duplicate entries removed: 0
#
# Breakdown by category:
#   X_rays_of_All_Body_Joints (catid=129): 9 products
# =============================================================================
