import numpy as np

# =============================================================================
# A.py
# Service category product assignments — letter A
# Generated by: product-service-mapper skill
# =============================================================================

Abdominal_X_Rays = np.array([
    {"catid": 121, "prodcode": 6436, "descr": ""},
    {"catid": 121, "prodcode": 6446, "descr": ""},
    {"catid": 121, "prodcode": 6447, "descr": ""},
    {"catid": 121, "prodcode": 6448, "descr": ""},
    {"catid": 121, "prodcode": 6449, "descr": ""},
])

Accident_And_Emergency_Care_Out_Patient = np.array([
    {"catid": 27, "prodcode": 5295, "descr": ""},
    {"catid": 27, "prodcode": 5301, "descr": ""},
])

Additional_Immunization_0_5_Years = np.array([
    {"catid": 41, "prodcode": 6115, "descr": ""},
    {"catid": 41, "prodcode": 7213, "descr": ""},
])

Additional_Immunization_6_Years_And_Above = np.array([
    {"catid": 42, "prodcode": 5625, "descr": ""},
    {"catid": 42, "prodcode": 6112, "descr": ""},
    {"catid": 42, "prodcode": 6113, "descr": ""},
    {"catid": 42, "prodcode": 6114, "descr": ""},
    {"catid": 42, "prodcode": 6120, "descr": ""},
    {"catid": 42, "prodcode": 6121, "descr": ""},
    {"catid": 42, "prodcode": 6122, "descr": ""},
    {"catid": 42, "prodcode": 6212, "descr": ""},
    {"catid": 42, "prodcode": 6213, "descr": ""},
    {"catid": 42, "prodcode": 6394, "descr": ""},
    {"catid": 42, "prodcode": 6396, "descr": ""},
    {"catid": 42, "prodcode": 7214, "descr": ""},
    {"catid": 42, "prodcode": 7605, "descr": ""},
])

Admission = np.array([
    {"catid": 215, "prodcode": 5301, "descr": ""},
])

Advanced_Diagnostic_Imaging = np.array([
    {"catid": 30, "prodcode": 5249, "descr": ""},
    {"catid": 30, "prodcode": 5282, "descr": ""},
    {"catid": 30, "prodcode": 6221, "descr": ""},
    {"catid": 30, "prodcode": 6579, "descr": ""},
    {"catid": 30, "prodcode": 6594, "descr": ""},
    {"catid": 30, "prodcode": 6880, "descr": ""},
    {"catid": 30, "prodcode": 6893, "descr": ""},
    {"catid": 30, "prodcode": 6894, "descr": ""},
    {"catid": 30, "prodcode": 6895, "descr": ""},
    {"catid": 30, "prodcode": 6896, "descr": ""},
    {"catid": 30, "prodcode": 6897, "descr": ""},
    {"catid": 30, "prodcode": 6898, "descr": ""},
    {"catid": 30, "prodcode": 6899, "descr": ""},
    {"catid": 30, "prodcode": 6900, "descr": ""},
    {"catid": 30, "prodcode": 6901, "descr": ""},
    {"catid": 30, "prodcode": 6902, "descr": ""},
    {"catid": 30, "prodcode": 6903, "descr": ""},
    {"catid": 30, "prodcode": 6904, "descr": ""},
    {"catid": 30, "prodcode": 6905, "descr": ""},
    {"catid": 30, "prodcode": 6906, "descr": ""},
    {"catid": 30, "prodcode": 6907, "descr": ""},
    {"catid": 30, "prodcode": 6908, "descr": ""},
    {"catid": 30, "prodcode": 6909, "descr": ""},
    {"catid": 30, "prodcode": 6910, "descr": ""},
    {"catid": 30, "prodcode": 6911, "descr": ""},
    {"catid": 30, "prodcode": 6912, "descr": ""},
    {"catid": 30, "prodcode": 6913, "descr": ""},
    {"catid": 30, "prodcode": 6914, "descr": ""},
    {"catid": 30, "prodcode": 6915, "descr": ""},
    {"catid": 30, "prodcode": 6916, "descr": ""},
    {"catid": 30, "prodcode": 6917, "descr": ""},
    {"catid": 30, "prodcode": 6918, "descr": ""},
    {"catid": 30, "prodcode": 6919, "descr": ""},
    {"catid": 30, "prodcode": 6920, "descr": ""},
    {"catid": 30, "prodcode": 6921, "descr": ""},
    {"catid": 30, "prodcode": 6922, "descr": ""},
    {"catid": 30, "prodcode": 6923, "descr": ""},
    {"catid": 30, "prodcode": 6924, "descr": ""},
    {"catid": 30, "prodcode": 6925, "descr": ""},
    {"catid": 30, "prodcode": 6926, "descr": ""},
    {"catid": 30, "prodcode": 6927, "descr": ""},
    {"catid": 30, "prodcode": 6928, "descr": ""},
    {"catid": 30, "prodcode": 6929, "descr": ""},
    {"catid": 30, "prodcode": 6930, "descr": ""},
    {"catid": 30, "prodcode": 7301, "descr": ""},
    {"catid": 30, "prodcode": 7437, "descr": ""},
    {"catid": 30, "prodcode": 7704, "descr": ""},
    {"catid": 30, "prodcode": 7714, "descr": ""},
    {"catid": 30, "prodcode": 7738, "descr": ""},
])

Advanced_Laboratory_Investigations_Pathology = np.array([
    {"catid": 34, "prodcode": 5248, "descr": ""},
    {"catid": 34, "prodcode": 5252, "descr": ""},
    {"catid": 34, "prodcode": 5253, "descr": ""},
    {"catid": 34, "prodcode": 5254, "descr": ""},
    {"catid": 34, "prodcode": 5257, "descr": ""},
    {"catid": 34, "prodcode": 5266, "descr": ""},
    {"catid": 34, "prodcode": 5267, "descr": ""},
    {"catid": 34, "prodcode": 5556, "descr": ""},
    {"catid": 34, "prodcode": 5557, "descr": ""},
    {"catid": 34, "prodcode": 5558, "descr": ""},
    {"catid": 34, "prodcode": 5559, "descr": ""},
    {"catid": 34, "prodcode": 5560, "descr": ""},
    {"catid": 34, "prodcode": 5561, "descr": ""},
    {"catid": 34, "prodcode": 5563, "descr": ""},
    {"catid": 34, "prodcode": 5564, "descr": ""},
    {"catid": 34, "prodcode": 5575, "descr": ""},
    {"catid": 34, "prodcode": 5582, "descr": ""},
    {"catid": 34, "prodcode": 5798, "descr": ""},
    {"catid": 34, "prodcode": 5799, "descr": ""},
    {"catid": 34, "prodcode": 5801, "descr": ""},
    {"catid": 34, "prodcode": 5804, "descr": ""},
    {"catid": 34, "prodcode": 5806, "descr": ""},
    {"catid": 34, "prodcode": 5807, "descr": ""},
    {"catid": 34, "prodcode": 5808, "descr": ""},
    {"catid": 34, "prodcode": 5812, "descr": ""},
    {"catid": 34, "prodcode": 5829, "descr": ""},
    {"catid": 34, "prodcode": 5985, "descr": ""},
    {"catid": 34, "prodcode": 5993, "descr": ""},
    {"catid": 34, "prodcode": 6007, "descr": ""},
    {"catid": 34, "prodcode": 6008, "descr": ""},
    {"catid": 34, "prodcode": 6024, "descr": ""},
    {"catid": 34, "prodcode": 6025, "descr": ""},
    {"catid": 34, "prodcode": 6026, "descr": ""},
    {"catid": 34, "prodcode": 6027, "descr": ""},
    {"catid": 34, "prodcode": 6055, "descr": ""},
    {"catid": 34, "prodcode": 6056, "descr": ""},
    {"catid": 34, "prodcode": 6057, "descr": ""},
    {"catid": 34, "prodcode": 6059, "descr": ""},
    {"catid": 34, "prodcode": 6060, "descr": ""},
    {"catid": 34, "prodcode": 6061, "descr": ""},
    {"catid": 34, "prodcode": 6065, "descr": ""},
    {"catid": 34, "prodcode": 6066, "descr": ""},
    {"catid": 34, "prodcode": 6067, "descr": ""},
    {"catid": 34, "prodcode": 6068, "descr": ""},
    {"catid": 34, "prodcode": 6069, "descr": ""},
    {"catid": 34, "prodcode": 6070, "descr": ""},
    {"catid": 34, "prodcode": 6071, "descr": ""},
    {"catid": 34, "prodcode": 6072, "descr": ""},
    {"catid": 34, "prodcode": 6096, "descr": ""},
    {"catid": 34, "prodcode": 6098, "descr": ""},
    {"catid": 34, "prodcode": 6099, "descr": ""},
    {"catid": 34, "prodcode": 6101, "descr": ""},
    {"catid": 34, "prodcode": 6102, "descr": ""},
    {"catid": 34, "prodcode": 6103, "descr": ""},
    {"catid": 34, "prodcode": 6104, "descr": ""},
    {"catid": 34, "prodcode": 6343, "descr": ""},
    {"catid": 34, "prodcode": 6344, "descr": ""},
    {"catid": 34, "prodcode": 6346, "descr": ""},
    {"catid": 34, "prodcode": 6347, "descr": ""},
    {"catid": 34, "prodcode": 6348, "descr": ""},
    {"catid": 34, "prodcode": 6349, "descr": ""},
    {"catid": 34, "prodcode": 6350, "descr": ""},
    {"catid": 34, "prodcode": 6351, "descr": ""},
    {"catid": 34, "prodcode": 6352, "descr": ""},
    {"catid": 34, "prodcode": 6358, "descr": ""},
    {"catid": 34, "prodcode": 6359, "descr": ""},
    {"catid": 34, "prodcode": 6360, "descr": ""},
    {"catid": 34, "prodcode": 6366, "descr": ""},
    {"catid": 34, "prodcode": 6464, "descr": ""},
    {"catid": 34, "prodcode": 6465, "descr": ""},
    {"catid": 34, "prodcode": 6466, "descr": ""},
    {"catid": 34, "prodcode": 6547, "descr": ""},
    {"catid": 34, "prodcode": 6548, "descr": ""},
    {"catid": 34, "prodcode": 6549, "descr": ""},
    {"catid": 34, "prodcode": 6743, "descr": ""},
    {"catid": 34, "prodcode": 6749, "descr": ""},
    {"catid": 34, "prodcode": 6750, "descr": ""},
    {"catid": 34, "prodcode": 6757, "descr": ""},
    {"catid": 34, "prodcode": 6758, "descr": ""},
    {"catid": 34, "prodcode": 6759, "descr": ""},
    {"catid": 34, "prodcode": 6768, "descr": ""},
    {"catid": 34, "prodcode": 6777, "descr": ""},
    {"catid": 34, "prodcode": 6805, "descr": ""},
    {"catid": 34, "prodcode": 6814, "descr": ""},
    {"catid": 34, "prodcode": 7137, "descr": ""},
    {"catid": 34, "prodcode": 7144, "descr": ""},
    {"catid": 34, "prodcode": 7146, "descr": ""},
    {"catid": 34, "prodcode": 7147, "descr": ""},
    {"catid": 34, "prodcode": 7148, "descr": ""},
    {"catid": 34, "prodcode": 7149, "descr": ""},
    {"catid": 34, "prodcode": 7150, "descr": ""},
    {"catid": 34, "prodcode": 7161, "descr": ""},
    {"catid": 34, "prodcode": 7162, "descr": ""},
    {"catid": 34, "prodcode": 7165, "descr": ""},
    {"catid": 34, "prodcode": 7166, "descr": ""},
    {"catid": 34, "prodcode": 7167, "descr": ""},
    {"catid": 34, "prodcode": 7169, "descr": ""},
    {"catid": 34, "prodcode": 7170, "descr": ""},
    {"catid": 34, "prodcode": 7406, "descr": ""},
    {"catid": 34, "prodcode": 7407, "descr": ""},
    {"catid": 34, "prodcode": 7408, "descr": ""},
    {"catid": 34, "prodcode": 7409, "descr": ""},
    {"catid": 34, "prodcode": 7583, "descr": ""},
    {"catid": 34, "prodcode": 7588, "descr": ""},
])

Advanced_Ocular_tests = np.array([
    {"catid": 184, "prodcode": 5368, "descr": ""},
    {"catid": 184, "prodcode": 5640, "descr": ""},
    {"catid": 184, "prodcode": 6805, "descr": ""},
    {"catid": 184, "prodcode": 6814, "descr": ""},
    {"catid": 184, "prodcode": 6919, "descr": ""},
    {"catid": 184, "prodcode": 7301, "descr": ""},
    {"catid": 184, "prodcode": 7704, "descr": ""},
    {"catid": 184, "prodcode": 7714, "descr": ""},
    {"catid": 184, "prodcode": 7718, "descr": ""},
    {"catid": 184, "prodcode": 7721, "descr": ""},
    {"catid": 184, "prodcode": 7736, "descr": ""},
])

Amalgam_Filling = np.array([
    {"catid": 179, "prodcode": 5551, "descr": ""},
    {"catid": 179, "prodcode": 5552, "descr": ""},
    {"catid": 179, "prodcode": 5982, "descr": ""},
    {"catid": 179, "prodcode": 6091, "descr": ""},
    {"catid": 179, "prodcode": 6253, "descr": ""},
    {"catid": 179, "prodcode": 6254, "descr": ""},
    {"catid": 179, "prodcode": 6365, "descr": ""},
])

Antenatal_Care_Including_all_specialist_care_and_anc_drugs = np.array([
    {"catid": 251, "prodcode": 5297, "descr": ""},
    {"catid": 251, "prodcode": 5298, "descr": ""},
    {"catid": 251, "prodcode": 5640, "descr": ""},
    {"catid": 251, "prodcode": 5828, "descr": ""},
    {"catid": 251, "prodcode": 5891, "descr": ""},
    {"catid": 251, "prodcode": 6803, "descr": ""},
    {"catid": 251, "prodcode": 7159, "descr": ""},
    {"catid": 251, "prodcode": 7531, "descr": ""},
    {"catid": 251, "prodcode": 7718, "descr": ""},
    {"catid": 251, "prodcode": 7721, "descr": ""},
    {"catid": 251, "prodcode": 7736, "descr": ""},
])

Aspirates_M_C_S = np.array([
    {"catid": 243, "prodcode": 6435, "descr": ""},
])

Assisted_Delivery = np.array([
    {"catid": 254, "prodcode": 5659, "descr": ""},
    {"catid": 254, "prodcode": 7176, "descr": ""},
    {"catid": 254, "prodcode": 7279, "descr": ""},
    {"catid": 254, "prodcode": 7280, "descr": ""},
    {"catid": 254, "prodcode": 7283, "descr": ""},
    {"catid": 254, "prodcode": 7464, "descr": ""},
    {"catid": 254, "prodcode": 7465, "descr": ""},
    {"catid": 254, "prodcode": 7467, "descr": ""},
])

# =============================================================================
# SUMMARY — A.py
# =============================================================================
# Categories in this file : 15
# Total product entries    : 213
#
# Breakdown by category:
#   Abdominal_X_Rays (catid=121): 5 products
#   Access_to_prescribed_drugs (catid=222): (no products — variable omitted)
#   Accident_And_Emergency_Care_Out_Patient (catid=27): 2 products
#   Additional_Immunization_0_5_Years (catid=41): 2 products
#   Additional_Immunization_6_Years_And_Above (catid=42): 13 products
#   Admission (catid=215): 1 products
#   Advanced_Diagnostic_Imaging (catid=30): 48 products
#   Advanced_Laboratory_Investigations_Pathology (catid=34): 104 products
#   Advanced_Ocular_tests (catid=184): 11 products
#   After_Demise_Compensation (catid=250): (no products — variable omitted)
#   Amalgam_Filling (catid=179): 7 products
#   Annual_Visual_Acuity_Check_Using_Snellen_Chart (catid=290): (no products — variable omitted)
#   Antenatal_Care_Including_all_specialist_care_and_anc_drugs (catid=251): 11 products
#   Aspirates_M_C_S (catid=243): 1 products
#   Assisted_Delivery (catid=254): 8 products
# =============================================================================
