import numpy as np

# =============================================================================
# D.py
# Service category product assignments — letter D
# Generated by: product-service-mapper skill
# =============================================================================

D_Dimer = np.array([
    {"catid": 335, "prodcode": 5579, "descr": ""},
])

Delivery_Multiple = np.array([
    {"catid": 253, "prodcode": 5301, "descr": ""},
    {"catid": 253, "prodcode": 5659, "descr": ""},
    {"catid": 253, "prodcode": 6226, "descr": ""},
    {"catid": 253, "prodcode": 7217, "descr": ""},
    {"catid": 253, "prodcode": 7279, "descr": ""},
    {"catid": 253, "prodcode": 7280, "descr": ""},
    {"catid": 253, "prodcode": 7281, "descr": ""},
    {"catid": 253, "prodcode": 7282, "descr": ""},
    {"catid": 253, "prodcode": 7283, "descr": ""},
    {"catid": 253, "prodcode": 7464, "descr": ""},
    {"catid": 253, "prodcode": 7465, "descr": ""},
    {"catid": 253, "prodcode": 7467, "descr": ""},
])

Delivery_SVD_or_Normal_and_Complicated = np.array([
    {"catid": 252, "prodcode": 5298, "descr": ""},
    {"catid": 252, "prodcode": 5329, "descr": ""},
    {"catid": 252, "prodcode": 5659, "descr": ""},
    {"catid": 252, "prodcode": 6180, "descr": ""},
    {"catid": 252, "prodcode": 6443, "descr": ""},
    {"catid": 252, "prodcode": 6570, "descr": ""},
    {"catid": 252, "prodcode": 6898, "descr": ""},
    {"catid": 252, "prodcode": 6925, "descr": ""},
    {"catid": 252, "prodcode": 7231, "descr": ""},
    {"catid": 252, "prodcode": 7233, "descr": ""},
    {"catid": 252, "prodcode": 7238, "descr": ""},
    {"catid": 252, "prodcode": 7239, "descr": ""},
    {"catid": 252, "prodcode": 7279, "descr": ""},
    {"catid": 252, "prodcode": 7280, "descr": ""},
    {"catid": 252, "prodcode": 7283, "descr": ""},
    {"catid": 252, "prodcode": 7464, "descr": ""},
    {"catid": 252, "prodcode": 7465, "descr": ""},
    {"catid": 252, "prodcode": 7467, "descr": ""},
    {"catid": 252, "prodcode": 7643, "descr": ""},
])

Dental_Care = np.array([
    {"catid": 36, "prodcode": 5389, "descr": ""},
    {"catid": 36, "prodcode": 5402, "descr": ""},
    {"catid": 36, "prodcode": 5403, "descr": ""},
    {"catid": 36, "prodcode": 5670, "descr": ""},
    {"catid": 36, "prodcode": 5700, "descr": ""},
    {"catid": 36, "prodcode": 5701, "descr": ""},
    {"catid": 36, "prodcode": 5702, "descr": ""},
    {"catid": 36, "prodcode": 6217, "descr": ""},
    {"catid": 36, "prodcode": 6453, "descr": ""},
    {"catid": 36, "prodcode": 6667, "descr": ""},
    {"catid": 36, "prodcode": 6863, "descr": ""},
    {"catid": 36, "prodcode": 6864, "descr": ""},
    {"catid": 36, "prodcode": 7159, "descr": ""},
    {"catid": 36, "prodcode": 7690, "descr": ""},
    {"catid": 36, "prodcode": 7691, "descr": ""},
    {"catid": 36, "prodcode": 7692, "descr": ""},
    {"catid": 36, "prodcode": 7694, "descr": ""},
    {"catid": 36, "prodcode": 7695, "descr": ""},
    {"catid": 36, "prodcode": 7696, "descr": ""},
    {"catid": 36, "prodcode": 7697, "descr": ""},
    {"catid": 36, "prodcode": 7698, "descr": ""},
    {"catid": 36, "prodcode": 7699, "descr": ""},
    {"catid": 36, "prodcode": 7700, "descr": ""},
    {"catid": 36, "prodcode": 7701, "descr": ""},
])

Dental_consultation = np.array([
    {"catid": 338, "prodcode": 6805, "descr": ""},
    {"catid": 338, "prodcode": 6814, "descr": ""},
])

Dental_pain_therapy = np.array([
    {"catid": 171, "prodcode": 5321, "descr": ""},
    {"catid": 171, "prodcode": 5322, "descr": ""},
    {"catid": 171, "prodcode": 5332, "descr": ""},
    {"catid": 171, "prodcode": 5333, "descr": ""},
    {"catid": 171, "prodcode": 6329, "descr": ""},
    {"catid": 171, "prodcode": 7227, "descr": ""},
    {"catid": 171, "prodcode": 7268, "descr": ""},
])

Dermatologist = np.array([
    {"catid": 281, "prodcode": 5355, "descr": ""},
    {"catid": 281, "prodcode": 6153, "descr": ""},
])

Diagnosis_Confirmation_From_Secondary_And_Tertiary_Care_Centres = np.array([
    {"catid": 259, "prodcode": 5301, "descr": ""},
    {"catid": 259, "prodcode": 7204, "descr": ""},
])

Dialysis_And_All_Related_Care = np.array([
    {"catid": 257, "prodcode": 5300, "descr": ""},
    {"catid": 257, "prodcode": 5616, "descr": ""},
    {"catid": 257, "prodcode": 6183, "descr": ""},
    {"catid": 257, "prodcode": 6435, "descr": ""},
    {"catid": 257, "prodcode": 6559, "descr": ""},
    {"catid": 257, "prodcode": 7276, "descr": ""},
])

# =============================================================================
# SUMMARY — D.py
# =============================================================================
# Categories in this file : 11
# Total product entries    : 75
#
# Breakdown by category:
#   D_Dimer (catid=335): 1 products
#   Delivery_Multiple (catid=253): 12 products
#   Delivery_SVD_or_Normal_and_Complicated (catid=252): 19 products
#   Dental_Care (catid=36): 24 products
#   Dental_consultation (catid=338): 2 products
#   Dental_pain_therapy (catid=171): 7 products
#   Dermatologist (catid=281): 2 products
#   Diagnosis_Confirmation_From_Secondary_And_Tertiary_Care_Centres (catid=259): 2 products
#   Dialysis_And_All_Related_Care (catid=257): 6 products
#   Dietician_or_Nutritionist (catid=270): (no products — variable omitted)
#   Dpt (catid=84): (no products — variable omitted)
# =============================================================================
