import numpy as np

# =============================================================================
# N.py
# Service category product assignments — letter N
# Generated by: product-service-mapper skill
# =============================================================================

Neck_X_rays = np.array([
    {"catid": 122, "prodcode": 5244, "descr": ""},
    {"catid": 122, "prodcode": 5245, "descr": ""},
    {"catid": 122, "prodcode": 5666, "descr": ""},
    {"catid": 122, "prodcode": 5667, "descr": ""},
    {"catid": 122, "prodcode": 6064, "descr": ""},
    {"catid": 122, "prodcode": 6180, "descr": ""},
    {"catid": 122, "prodcode": 6443, "descr": ""},
    {"catid": 122, "prodcode": 6446, "descr": ""},
    {"catid": 122, "prodcode": 6447, "descr": ""},
    {"catid": 122, "prodcode": 6448, "descr": ""},
    {"catid": 122, "prodcode": 6902, "descr": ""},
    {"catid": 122, "prodcode": 6934, "descr": ""},
    {"catid": 122, "prodcode": 7231, "descr": ""},
    {"catid": 122, "prodcode": 7278, "descr": ""},
    {"catid": 122, "prodcode": 7637, "descr": ""},
    {"catid": 122, "prodcode": 7638, "descr": ""},
])

Neonatologist = np.array([
    {"catid": 280, "prodcode": 5795, "descr": ""},
    {"catid": 280, "prodcode": 7288, "descr": ""},
    {"catid": 280, "prodcode": 7289, "descr": ""},
    {"catid": 280, "prodcode": 7570, "descr": ""},
    {"catid": 280, "prodcode": 7571, "descr": ""},
    {"catid": 280, "prodcode": 7670, "descr": ""},
    {"catid": 280, "prodcode": 7671, "descr": ""},
    {"catid": 280, "prodcode": 7672, "descr": ""},
    {"catid": 280, "prodcode": 7673, "descr": ""},
    {"catid": 280, "prodcode": 7674, "descr": ""},
    {"catid": 280, "prodcode": 7675, "descr": ""},
    {"catid": 280, "prodcode": 7703, "descr": ""},
])

Nephrologist = np.array([
    {"catid": 278, "prodcode": 5228, "descr": ""},
    {"catid": 278, "prodcode": 5234, "descr": ""},
    {"catid": 278, "prodcode": 5235, "descr": ""},
    {"catid": 278, "prodcode": 5236, "descr": ""},
    {"catid": 278, "prodcode": 5237, "descr": ""},
    {"catid": 278, "prodcode": 5238, "descr": ""},
    {"catid": 278, "prodcode": 5239, "descr": ""},
    {"catid": 278, "prodcode": 5240, "descr": ""},
    {"catid": 278, "prodcode": 5241, "descr": ""},
    {"catid": 278, "prodcode": 5242, "descr": ""},
    {"catid": 278, "prodcode": 5243, "descr": ""},
    {"catid": 278, "prodcode": 5608, "descr": ""},
    {"catid": 278, "prodcode": 5609, "descr": ""},
    {"catid": 278, "prodcode": 7290, "descr": ""},
    {"catid": 278, "prodcode": 7291, "descr": ""},
])

Neurologist = np.array([
    {"catid": 277, "prodcode": 7294, "descr": ""},
    {"catid": 277, "prodcode": 7295, "descr": ""},
])

Neurosurgeon = np.array([
    {"catid": 268, "prodcode": 5298, "descr": ""},
    {"catid": 268, "prodcode": 5368, "descr": ""},
    {"catid": 268, "prodcode": 6180, "descr": ""},
    {"catid": 268, "prodcode": 6919, "descr": ""},
    {"catid": 268, "prodcode": 7233, "descr": ""},
    {"catid": 268, "prodcode": 7296, "descr": ""},
    {"catid": 268, "prodcode": 7297, "descr": ""},
])

Non_surgical_extraction = np.array([
    {"catid": 173, "prodcode": 5298, "descr": ""},
    {"catid": 173, "prodcode": 5321, "descr": ""},
    {"catid": 173, "prodcode": 5322, "descr": ""},
    {"catid": 173, "prodcode": 5332, "descr": ""},
    {"catid": 173, "prodcode": 5333, "descr": ""},
    {"catid": 173, "prodcode": 6180, "descr": ""},
    {"catid": 173, "prodcode": 6329, "descr": ""},
    {"catid": 173, "prodcode": 6453, "descr": ""},
    {"catid": 173, "prodcode": 7227, "descr": ""},
    {"catid": 173, "prodcode": 7233, "descr": ""},
    {"catid": 173, "prodcode": 7268, "descr": ""},
])

Norplant = np.array([
    {"catid": 191, "prodcode": 5190, "descr": ""},
    {"catid": 191, "prodcode": 5191, "descr": ""},
    {"catid": 191, "prodcode": 5218, "descr": ""},
    {"catid": 191, "prodcode": 5448, "descr": ""},
    {"catid": 191, "prodcode": 5449, "descr": ""},
    {"catid": 191, "prodcode": 5455, "descr": ""},
    {"catid": 191, "prodcode": 5456, "descr": ""},
    {"catid": 191, "prodcode": 5492, "descr": ""},
    {"catid": 191, "prodcode": 5512, "descr": ""},
    {"catid": 191, "prodcode": 5513, "descr": ""},
    {"catid": 191, "prodcode": 6242, "descr": ""},
    {"catid": 191, "prodcode": 6243, "descr": ""},
    {"catid": 191, "prodcode": 6247, "descr": ""},
    {"catid": 191, "prodcode": 6309, "descr": ""},
    {"catid": 191, "prodcode": 6326, "descr": ""},
    {"catid": 191, "prodcode": 6327, "descr": ""},
    {"catid": 191, "prodcode": 6535, "descr": ""},
    {"catid": 191, "prodcode": 6673, "descr": ""},
    {"catid": 191, "prodcode": 6676, "descr": ""},
    {"catid": 191, "prodcode": 6941, "descr": ""},
    {"catid": 191, "prodcode": 7182, "descr": ""},
    {"catid": 191, "prodcode": 7189, "descr": ""},
    {"catid": 191, "prodcode": 7298, "descr": ""},
    {"catid": 191, "prodcode": 7401, "descr": ""},
])

Npi_Immunization_0_5_Years = np.array([
    {"catid": 40, "prodcode": 6115, "descr": ""},
    {"catid": 40, "prodcode": 6393, "descr": ""},
    {"catid": 40, "prodcode": 7213, "descr": ""},
])

Number_of_Sessions_Covered = np.array([
    {"catid": 223, "prodcode": 6226, "descr": ""},
    {"catid": 223, "prodcode": 7280, "descr": ""},
    {"catid": 223, "prodcode": 7435, "descr": ""},
])

Nursing_Care_and_Consumables = np.array([
    {"catid": 214, "prodcode": 5270, "descr": ""},
    {"catid": 214, "prodcode": 5301, "descr": ""},
    {"catid": 214, "prodcode": 5531, "descr": ""},
    {"catid": 214, "prodcode": 5614, "descr": ""},
    {"catid": 214, "prodcode": 5615, "descr": ""},
    {"catid": 214, "prodcode": 5623, "descr": ""},
    {"catid": 214, "prodcode": 5624, "descr": ""},
    {"catid": 214, "prodcode": 5842, "descr": ""},
    {"catid": 214, "prodcode": 5843, "descr": ""},
    {"catid": 214, "prodcode": 5844, "descr": ""},
    {"catid": 214, "prodcode": 5845, "descr": ""},
    {"catid": 214, "prodcode": 5846, "descr": ""},
    {"catid": 214, "prodcode": 5848, "descr": ""},
    {"catid": 214, "prodcode": 5852, "descr": ""},
    {"catid": 214, "prodcode": 5855, "descr": ""},
    {"catid": 214, "prodcode": 5884, "descr": ""},
    {"catid": 214, "prodcode": 5885, "descr": ""},
    {"catid": 214, "prodcode": 5886, "descr": ""},
    {"catid": 214, "prodcode": 5912, "descr": ""},
    {"catid": 214, "prodcode": 6330, "descr": ""},
    {"catid": 214, "prodcode": 6331, "descr": ""},
    {"catid": 214, "prodcode": 6332, "descr": ""},
    {"catid": 214, "prodcode": 6333, "descr": ""},
    {"catid": 214, "prodcode": 6334, "descr": ""},
    {"catid": 214, "prodcode": 6336, "descr": ""},
    {"catid": 214, "prodcode": 6375, "descr": ""},
    {"catid": 214, "prodcode": 6376, "descr": ""},
    {"catid": 214, "prodcode": 6377, "descr": ""},
    {"catid": 214, "prodcode": 6378, "descr": ""},
    {"catid": 214, "prodcode": 6379, "descr": ""},
    {"catid": 214, "prodcode": 6380, "descr": ""},
    {"catid": 214, "prodcode": 6382, "descr": ""},
    {"catid": 214, "prodcode": 6383, "descr": ""},
    {"catid": 214, "prodcode": 6384, "descr": ""},
    {"catid": 214, "prodcode": 6385, "descr": ""},
    {"catid": 214, "prodcode": 6393, "descr": ""},
    {"catid": 214, "prodcode": 6741, "descr": ""},
    {"catid": 214, "prodcode": 6742, "descr": ""},
    {"catid": 214, "prodcode": 6782, "descr": ""},
    {"catid": 214, "prodcode": 7112, "descr": ""},
    {"catid": 214, "prodcode": 7113, "descr": ""},
    {"catid": 214, "prodcode": 7114, "descr": ""},
    {"catid": 214, "prodcode": 7115, "descr": ""},
    {"catid": 214, "prodcode": 7116, "descr": ""},
    {"catid": 214, "prodcode": 7171, "descr": ""},
    {"catid": 214, "prodcode": 7172, "descr": ""},
    {"catid": 214, "prodcode": 7173, "descr": ""},
    {"catid": 214, "prodcode": 7174, "descr": ""},
    {"catid": 214, "prodcode": 7175, "descr": ""},
    {"catid": 214, "prodcode": 7198, "descr": ""},
    {"catid": 214, "prodcode": 7200, "descr": ""},
    {"catid": 214, "prodcode": 7208, "descr": ""},
    {"catid": 214, "prodcode": 7210, "descr": ""},
    {"catid": 214, "prodcode": 7228, "descr": ""},
    {"catid": 214, "prodcode": 7271, "descr": ""},
    {"catid": 214, "prodcode": 7402, "descr": ""},
    {"catid": 214, "prodcode": 7403, "descr": ""},
    {"catid": 214, "prodcode": 7410, "descr": ""},
    {"catid": 214, "prodcode": 7411, "descr": ""},
    {"catid": 214, "prodcode": 7412, "descr": ""},
    {"catid": 214, "prodcode": 7413, "descr": ""},
    {"catid": 214, "prodcode": 7419, "descr": ""},
    {"catid": 214, "prodcode": 7420, "descr": ""},
    {"catid": 214, "prodcode": 7421, "descr": ""},
    {"catid": 214, "prodcode": 7422, "descr": ""},
    {"catid": 214, "prodcode": 7429, "descr": ""},
    {"catid": 214, "prodcode": 7431, "descr": ""},
    {"catid": 214, "prodcode": 7432, "descr": ""},
    {"catid": 214, "prodcode": 7433, "descr": ""},
    {"catid": 214, "prodcode": 7434, "descr": ""},
    {"catid": 214, "prodcode": 7594, "descr": ""},
    {"catid": 214, "prodcode": 7601, "descr": ""},
    {"catid": 214, "prodcode": 7602, "descr": ""},
    {"catid": 214, "prodcode": 7603, "descr": ""},
    {"catid": 214, "prodcode": 7604, "descr": ""},
])

# =============================================================================
# SUMMARY — N.py
# =============================================================================
# Categories in this file : 10
# Total product entries    : 168
#
# Breakdown by category:
#   Neck_X_rays (catid=122): 16 products
#   Neonatologist (catid=280): 12 products
#   Nephrologist (catid=278): 15 products
#   Neurologist (catid=277): 2 products
#   Neurosurgeon (catid=268): 7 products
#   Non_surgical_extraction (catid=173): 11 products
#   Norplant (catid=191): 24 products
#   Npi_Immunization_0_5_Years (catid=40): 3 products
#   Number_of_Sessions_Covered (catid=223): 3 products
#   Nursing_Care_and_Consumables (catid=214): 75 products
# =============================================================================
