import numpy as np

# =============================================================================
# O.py
# Service category product assignments — letter O
# Generated by: product-service-mapper skill
# =============================================================================

Obstetrician = np.array([
    {"catid": 264, "prodcode": 5297, "descr": ""},
    {"catid": 264, "prodcode": 5298, "descr": ""},
    {"catid": 264, "prodcode": 5301, "descr": ""},
    {"catid": 264, "prodcode": 5659, "descr": ""},
    {"catid": 264, "prodcode": 5828, "descr": ""},
    {"catid": 264, "prodcode": 6803, "descr": ""},
    {"catid": 264, "prodcode": 7159, "descr": ""},
    {"catid": 264, "prodcode": 7279, "descr": ""},
    {"catid": 264, "prodcode": 7280, "descr": ""},
    {"catid": 264, "prodcode": 7283, "descr": ""},
    {"catid": 264, "prodcode": 7464, "descr": ""},
    {"catid": 264, "prodcode": 7465, "descr": ""},
    {"catid": 264, "prodcode": 7467, "descr": ""},
])

Obstetrics_And_Gynaecology_Care_In_Patient_Limit_Applies = np.array([
    {"catid": 38, "prodcode": 5297, "descr": ""},
    {"catid": 38, "prodcode": 5298, "descr": ""},
    {"catid": 38, "prodcode": 5301, "descr": ""},
    {"catid": 38, "prodcode": 5659, "descr": ""},
    {"catid": 38, "prodcode": 5696, "descr": ""},
    {"catid": 38, "prodcode": 5697, "descr": ""},
    {"catid": 38, "prodcode": 5698, "descr": ""},
    {"catid": 38, "prodcode": 5699, "descr": ""},
    {"catid": 38, "prodcode": 5828, "descr": ""},
    {"catid": 38, "prodcode": 6180, "descr": ""},
    {"catid": 38, "prodcode": 6803, "descr": ""},
    {"catid": 38, "prodcode": 7159, "descr": ""},
    {"catid": 38, "prodcode": 7233, "descr": ""},
    {"catid": 38, "prodcode": 7279, "descr": ""},
    {"catid": 38, "prodcode": 7280, "descr": ""},
    {"catid": 38, "prodcode": 7283, "descr": ""},
    {"catid": 38, "prodcode": 7464, "descr": ""},
    {"catid": 38, "prodcode": 7465, "descr": ""},
    {"catid": 38, "prodcode": 7467, "descr": ""},
    {"catid": 38, "prodcode": 7492, "descr": ""},
    {"catid": 38, "prodcode": 7493, "descr": ""},
    {"catid": 38, "prodcode": 7494, "descr": ""},
    {"catid": 38, "prodcode": 7607, "descr": ""},
    {"catid": 38, "prodcode": 7721, "descr": ""},
])

Oncological_Investigations = np.array([
    {"catid": 139, "prodcode": 6073, "descr": ""},
    {"catid": 139, "prodcode": 6074, "descr": ""},
    {"catid": 139, "prodcode": 6075, "descr": ""},
    {"catid": 139, "prodcode": 6076, "descr": ""},
    {"catid": 139, "prodcode": 6077, "descr": ""},
    {"catid": 139, "prodcode": 6351, "descr": ""},
    {"catid": 139, "prodcode": 6352, "descr": ""},
])

Oncologist_Or_Cancer_Specialist_Visits = np.array([
    {"catid": 138, "prodcode": 5298, "descr": ""},
    {"catid": 138, "prodcode": 5397, "descr": ""},
    {"catid": 138, "prodcode": 5398, "descr": ""},
    {"catid": 138, "prodcode": 5680, "descr": ""},
    {"catid": 138, "prodcode": 5684, "descr": ""},
    {"catid": 138, "prodcode": 5685, "descr": ""},
    {"catid": 138, "prodcode": 5686, "descr": ""},
    {"catid": 138, "prodcode": 5689, "descr": ""},
    {"catid": 138, "prodcode": 5692, "descr": ""},
    {"catid": 138, "prodcode": 5693, "descr": ""},
    {"catid": 138, "prodcode": 5698, "descr": ""},
    {"catid": 138, "prodcode": 5887, "descr": ""},
    {"catid": 138, "prodcode": 5889, "descr": ""},
    {"catid": 138, "prodcode": 6180, "descr": ""},
    {"catid": 138, "prodcode": 6212, "descr": ""},
    {"catid": 138, "prodcode": 6214, "descr": ""},
    {"catid": 138, "prodcode": 6862, "descr": ""},
    {"catid": 138, "prodcode": 6868, "descr": ""},
    {"catid": 138, "prodcode": 7233, "descr": ""},
    {"catid": 138, "prodcode": 7288, "descr": ""},
    {"catid": 138, "prodcode": 7292, "descr": ""},
    {"catid": 138, "prodcode": 7294, "descr": ""},
    {"catid": 138, "prodcode": 7296, "descr": ""},
    {"catid": 138, "prodcode": 7473, "descr": ""},
    {"catid": 138, "prodcode": 7474, "descr": ""},
    {"catid": 138, "prodcode": 7475, "descr": ""},
    {"catid": 138, "prodcode": 7478, "descr": ""},
    {"catid": 138, "prodcode": 7479, "descr": ""},
    {"catid": 138, "prodcode": 7480, "descr": ""},
    {"catid": 138, "prodcode": 7484, "descr": ""},
    {"catid": 138, "prodcode": 7674, "descr": ""},
    {"catid": 138, "prodcode": 7676, "descr": ""},
    {"catid": 138, "prodcode": 7679, "descr": ""},
    {"catid": 138, "prodcode": 7684, "descr": ""},
    {"catid": 138, "prodcode": 7686, "descr": ""},
    {"catid": 138, "prodcode": 7688, "descr": ""},
])

Operculectomy = np.array([
    {"catid": 176, "prodcode": 5303, "descr": ""},
    {"catid": 176, "prodcode": 5311, "descr": ""},
    {"catid": 176, "prodcode": 5338, "descr": ""},
    {"catid": 176, "prodcode": 5339, "descr": ""},
    {"catid": 176, "prodcode": 5340, "descr": ""},
    {"catid": 176, "prodcode": 5341, "descr": ""},
    {"catid": 176, "prodcode": 5342, "descr": ""},
    {"catid": 176, "prodcode": 5343, "descr": ""},
    {"catid": 176, "prodcode": 5344, "descr": ""},
    {"catid": 176, "prodcode": 5345, "descr": ""},
    {"catid": 176, "prodcode": 5346, "descr": ""},
    {"catid": 176, "prodcode": 5347, "descr": ""},
    {"catid": 176, "prodcode": 5348, "descr": ""},
    {"catid": 176, "prodcode": 5349, "descr": ""},
    {"catid": 176, "prodcode": 5350, "descr": ""},
    {"catid": 176, "prodcode": 5351, "descr": ""},
    {"catid": 176, "prodcode": 5352, "descr": ""},
    {"catid": 176, "prodcode": 5353, "descr": ""},
    {"catid": 176, "prodcode": 5354, "descr": ""},
    {"catid": 176, "prodcode": 5355, "descr": ""},
    {"catid": 176, "prodcode": 5356, "descr": ""},
    {"catid": 176, "prodcode": 5357, "descr": ""},
    {"catid": 176, "prodcode": 5358, "descr": ""},
    {"catid": 176, "prodcode": 5359, "descr": ""},
    {"catid": 176, "prodcode": 5360, "descr": ""},
    {"catid": 176, "prodcode": 5361, "descr": ""},
    {"catid": 176, "prodcode": 5362, "descr": ""},
    {"catid": 176, "prodcode": 5363, "descr": ""},
    {"catid": 176, "prodcode": 5364, "descr": ""},
    {"catid": 176, "prodcode": 5365, "descr": ""},
    {"catid": 176, "prodcode": 5366, "descr": ""},
    {"catid": 176, "prodcode": 5367, "descr": ""},
    {"catid": 176, "prodcode": 5368, "descr": ""},
    {"catid": 176, "prodcode": 5369, "descr": ""},
    {"catid": 176, "prodcode": 5370, "descr": ""},
    {"catid": 176, "prodcode": 5371, "descr": ""},
    {"catid": 176, "prodcode": 5372, "descr": ""},
    {"catid": 176, "prodcode": 5373, "descr": ""},
    {"catid": 176, "prodcode": 5374, "descr": ""},
    {"catid": 176, "prodcode": 5375, "descr": ""},
    {"catid": 176, "prodcode": 5376, "descr": ""},
    {"catid": 176, "prodcode": 5377, "descr": ""},
    {"catid": 176, "prodcode": 5378, "descr": ""},
    {"catid": 176, "prodcode": 5379, "descr": ""},
    {"catid": 176, "prodcode": 5380, "descr": ""},
    {"catid": 176, "prodcode": 5381, "descr": ""},
    {"catid": 176, "prodcode": 5382, "descr": ""},
    {"catid": 176, "prodcode": 5383, "descr": ""},
    {"catid": 176, "prodcode": 5384, "descr": ""},
    {"catid": 176, "prodcode": 5639, "descr": ""},
    {"catid": 176, "prodcode": 5857, "descr": ""},
    {"catid": 176, "prodcode": 5858, "descr": ""},
    {"catid": 176, "prodcode": 5859, "descr": ""},
    {"catid": 176, "prodcode": 5860, "descr": ""},
    {"catid": 176, "prodcode": 5861, "descr": ""},
    {"catid": 176, "prodcode": 5883, "descr": ""},
    {"catid": 176, "prodcode": 6123, "descr": ""},
    {"catid": 176, "prodcode": 6170, "descr": ""},
    {"catid": 176, "prodcode": 6196, "descr": ""},
    {"catid": 176, "prodcode": 6407, "descr": ""},
    {"catid": 176, "prodcode": 6420, "descr": ""},
    {"catid": 176, "prodcode": 6427, "descr": ""},
    {"catid": 176, "prodcode": 6428, "descr": ""},
    {"catid": 176, "prodcode": 6553, "descr": ""},
    {"catid": 176, "prodcode": 6554, "descr": ""},
    {"catid": 176, "prodcode": 6806, "descr": ""},
    {"catid": 176, "prodcode": 6829, "descr": ""},
    {"catid": 176, "prodcode": 6830, "descr": ""},
    {"catid": 176, "prodcode": 6849, "descr": ""},
    {"catid": 176, "prodcode": 6852, "descr": ""},
    {"catid": 176, "prodcode": 7258, "descr": ""},
    {"catid": 176, "prodcode": 7264, "descr": ""},
    {"catid": 176, "prodcode": 7488, "descr": ""},
    {"catid": 176, "prodcode": 7614, "descr": ""},
])

Opv_Or_Ipv = np.array([
    {"catid": 81, "prodcode": 6395, "descr": ""},
    {"catid": 81, "prodcode": 7435, "descr": ""},
    {"catid": 81, "prodcode": 7606, "descr": ""},
    {"catid": 81, "prodcode": 7691, "descr": ""},
])

Oral_Glucose_Tolerance_Test_OGTT = np.array([
    {"catid": 152, "prodcode": 5826, "descr": ""},
    {"catid": 152, "prodcode": 5827, "descr": ""},
    {"catid": 152, "prodcode": 5841, "descr": ""},
    {"catid": 152, "prodcode": 7578, "descr": ""},
    {"catid": 152, "prodcode": 7582, "descr": ""},
    {"catid": 152, "prodcode": 7589, "descr": ""},
    {"catid": 152, "prodcode": 7590, "descr": ""},
])

Orthopedic_Surgeon = np.array([
    {"catid": 263, "prodcode": 5300, "descr": ""},
    {"catid": 263, "prodcode": 5666, "descr": ""},
    {"catid": 263, "prodcode": 5667, "descr": ""},
    {"catid": 263, "prodcode": 6179, "descr": ""},
    {"catid": 263, "prodcode": 6180, "descr": ""},
    {"catid": 263, "prodcode": 6181, "descr": ""},
    {"catid": 263, "prodcode": 6183, "descr": ""},
    {"catid": 263, "prodcode": 6559, "descr": ""},
    {"catid": 263, "prodcode": 6827, "descr": ""},
    {"catid": 263, "prodcode": 6932, "descr": ""},
    {"catid": 263, "prodcode": 6933, "descr": ""},
    {"catid": 263, "prodcode": 7276, "descr": ""},
    {"catid": 263, "prodcode": 7278, "descr": ""},
    {"catid": 263, "prodcode": 7628, "descr": ""},
    {"catid": 263, "prodcode": 7637, "descr": ""},
    {"catid": 263, "prodcode": 7638, "descr": ""},
])

Osmotic_Fragility_Test = np.array([
    {"catid": 327, "prodcode": 5205, "descr": ""},
    {"catid": 327, "prodcode": 5206, "descr": ""},
    {"catid": 327, "prodcode": 5777, "descr": ""},
    {"catid": 327, "prodcode": 5939, "descr": ""},
    {"catid": 327, "prodcode": 5969, "descr": ""},
    {"catid": 327, "prodcode": 6091, "descr": ""},
    {"catid": 327, "prodcode": 6282, "descr": ""},
    {"catid": 327, "prodcode": 6365, "descr": ""},
    {"catid": 327, "prodcode": 7398, "descr": ""},
    {"catid": 327, "prodcode": 7591, "descr": ""},
    {"catid": 327, "prodcode": 7592, "descr": ""},
])

Out_Patient_care_Limit = np.array([
    {"catid": 57, "prodcode": 5301, "descr": ""},
    {"catid": 57, "prodcode": 5397, "descr": ""},
    {"catid": 57, "prodcode": 5398, "descr": ""},
    {"catid": 57, "prodcode": 5680, "descr": ""},
    {"catid": 57, "prodcode": 5684, "descr": ""},
    {"catid": 57, "prodcode": 5685, "descr": ""},
    {"catid": 57, "prodcode": 5686, "descr": ""},
    {"catid": 57, "prodcode": 5689, "descr": ""},
    {"catid": 57, "prodcode": 5692, "descr": ""},
    {"catid": 57, "prodcode": 5693, "descr": ""},
    {"catid": 57, "prodcode": 5698, "descr": ""},
    {"catid": 57, "prodcode": 5887, "descr": ""},
    {"catid": 57, "prodcode": 5889, "descr": ""},
    {"catid": 57, "prodcode": 6212, "descr": ""},
    {"catid": 57, "prodcode": 6214, "descr": ""},
    {"catid": 57, "prodcode": 6805, "descr": ""},
    {"catid": 57, "prodcode": 6814, "descr": ""},
    {"catid": 57, "prodcode": 6862, "descr": ""},
    {"catid": 57, "prodcode": 6868, "descr": ""},
    {"catid": 57, "prodcode": 7288, "descr": ""},
    {"catid": 57, "prodcode": 7292, "descr": ""},
    {"catid": 57, "prodcode": 7294, "descr": ""},
    {"catid": 57, "prodcode": 7296, "descr": ""},
    {"catid": 57, "prodcode": 7473, "descr": ""},
    {"catid": 57, "prodcode": 7474, "descr": ""},
    {"catid": 57, "prodcode": 7475, "descr": ""},
    {"catid": 57, "prodcode": 7478, "descr": ""},
    {"catid": 57, "prodcode": 7479, "descr": ""},
    {"catid": 57, "prodcode": 7480, "descr": ""},
    {"catid": 57, "prodcode": 7484, "descr": ""},
    {"catid": 57, "prodcode": 7674, "descr": ""},
    {"catid": 57, "prodcode": 7676, "descr": ""},
    {"catid": 57, "prodcode": 7679, "descr": ""},
    {"catid": 57, "prodcode": 7684, "descr": ""},
    {"catid": 57, "prodcode": 7686, "descr": ""},
    {"catid": 57, "prodcode": 7688, "descr": ""},
])

# =============================================================================
# SUMMARY — O.py
# =============================================================================
# Categories in this file : 12
# Total product entries    : 228
#
# Breakdown by category:
#   Obstetrician (catid=264): 13 products
#   Obstetrics_And_Gynaecology_Care_In_Patient_Limit_Applies (catid=38): 24 products
#   Oncological_Investigations (catid=139): 7 products
#   Oncologist (catid=273): (no products — variable omitted)
#   Oncologist_Or_Cancer_Specialist_Visits (catid=138): 36 products
#   Operculectomy (catid=176): 74 products
#   Opv_Or_Ipv (catid=81): 4 products
#   Oral_and_Maxillofacial_Surgeon (catid=283): (no products — variable omitted)
#   Oral_Glucose_Tolerance_Test_OGTT (catid=152): 7 products
#   Orthopedic_Surgeon (catid=263): 16 products
#   Osmotic_Fragility_Test (catid=327): 11 products
#   Out_Patient_care_Limit (catid=57): 36 products
# =============================================================================
