import numpy as np

# =============================================================================
# S.py
# Service category product assignments — letter S
# Generated by: product-service-mapper skill
# =============================================================================
Scaling_and_Polishing = np.array([
    {"catid": 168, "prodcode": 7430, "descr": ""},
])

Seeking_Second_Opinion = np.array([
    {"catid": 52, "prodcode": 5298, "descr": ""},
    {"catid": 52, "prodcode": 5397, "descr": ""},
    {"catid": 52, "prodcode": 5398, "descr": ""},
    {"catid": 52, "prodcode": 5680, "descr": ""},
    {"catid": 52, "prodcode": 5684, "descr": ""},
    {"catid": 52, "prodcode": 5685, "descr": ""},
    {"catid": 52, "prodcode": 5686, "descr": ""},
    {"catid": 52, "prodcode": 5689, "descr": ""},
    {"catid": 52, "prodcode": 5692, "descr": ""},
    {"catid": 52, "prodcode": 5693, "descr": ""},
    {"catid": 52, "prodcode": 5698, "descr": ""},
    {"catid": 52, "prodcode": 5887, "descr": ""},
    {"catid": 52, "prodcode": 5889, "descr": ""},
    {"catid": 52, "prodcode": 6074, "descr": ""},
    {"catid": 52, "prodcode": 6180, "descr": ""},
    {"catid": 52, "prodcode": 6212, "descr": ""},
    {"catid": 52, "prodcode": 6214, "descr": ""},
    {"catid": 52, "prodcode": 6862, "descr": ""},
    {"catid": 52, "prodcode": 6868, "descr": ""},
    {"catid": 52, "prodcode": 7233, "descr": ""},
    {"catid": 52, "prodcode": 7288, "descr": ""},
    {"catid": 52, "prodcode": 7292, "descr": ""},
    {"catid": 52, "prodcode": 7294, "descr": ""},
    {"catid": 52, "prodcode": 7296, "descr": ""},
    {"catid": 52, "prodcode": 7473, "descr": ""},
    {"catid": 52, "prodcode": 7474, "descr": ""},
    {"catid": 52, "prodcode": 7475, "descr": ""},
    {"catid": 52, "prodcode": 7478, "descr": ""},
    {"catid": 52, "prodcode": 7479, "descr": ""},
    {"catid": 52, "prodcode": 7480, "descr": ""},
    {"catid": 52, "prodcode": 7484, "descr": ""},
    {"catid": 52, "prodcode": 7674, "descr": ""},
    {"catid": 52, "prodcode": 7676, "descr": ""},
    {"catid": 52, "prodcode": 7679, "descr": ""},
    {"catid": 52, "prodcode": 7684, "descr": ""},
    {"catid": 52, "prodcode": 7686, "descr": ""},
    {"catid": 52, "prodcode": 7688, "descr": ""},
])

Semi_Private_Room = np.array([
    {"catid": 341, "prodcode": 5301, "descr": ""},
])

Seminal_Fluid_Analysis_SFA = np.array([
    {"catid": 332, "prodcode": 5301, "descr": ""},
    {"catid": 332, "prodcode": 6356, "descr": ""},
    {"catid": 332, "prodcode": 6357, "descr": ""},
])

Serum_Acid_Phosphate = np.array([
    {"catid": 154, "prodcode": 6921, "descr": ""},
    {"catid": 154, "prodcode": 7734, "descr": ""},
    {"catid": 154, "prodcode": 7735, "descr": ""},
    {"catid": 154, "prodcode": 7736, "descr": ""},
])

Serum_Albumin = np.array([
    {"catid": 157, "prodcode": 5796, "descr": ""},
    {"catid": 157, "prodcode": 6772, "descr": ""},
])

Serum_Bilirubin_Total_and_Direct = np.array([
    {"catid": 156, "prodcode": 6446, "descr": ""},
    {"catid": 156, "prodcode": 6447, "descr": ""},
    {"catid": 156, "prodcode": 6448, "descr": ""},
    {"catid": 156, "prodcode": 6771, "descr": ""},
])

Serum_Chloride = np.array([
    {"catid": 161, "prodcode": 5228, "descr": ""},
    {"catid": 161, "prodcode": 5234, "descr": ""},
    {"catid": 161, "prodcode": 5235, "descr": ""},
    {"catid": 161, "prodcode": 5236, "descr": ""},
    {"catid": 161, "prodcode": 5237, "descr": ""},
    {"catid": 161, "prodcode": 5238, "descr": ""},
    {"catid": 161, "prodcode": 5239, "descr": ""},
    {"catid": 161, "prodcode": 5240, "descr": ""},
    {"catid": 161, "prodcode": 5241, "descr": ""},
    {"catid": 161, "prodcode": 5242, "descr": ""},
    {"catid": 161, "prodcode": 5243, "descr": ""},
    {"catid": 161, "prodcode": 5608, "descr": ""},
    {"catid": 161, "prodcode": 5609, "descr": ""},
])

Serum_Cholesterol = np.array([
    {"catid": 289, "prodcode": 6016, "descr": ""},
    {"catid": 289, "prodcode": 6017, "descr": ""},
    {"catid": 289, "prodcode": 6755, "descr": ""},
    {"catid": 289, "prodcode": 6756, "descr": ""},
])

Serum_Gamma_Glutamyl_Transferase = np.array([
    {"catid": 164, "prodcode": 5809, "descr": ""},
    {"catid": 164, "prodcode": 5810, "descr": ""},
    {"catid": 164, "prodcode": 5811, "descr": ""},
    {"catid": 164, "prodcode": 5818, "descr": ""},
    {"catid": 164, "prodcode": 6062, "descr": ""},
])

Serum_Inorganic_Phosphate = np.array([
    {"catid": 155, "prodcode": 5802, "descr": ""},
    {"catid": 155, "prodcode": 6361, "descr": ""},
    {"catid": 155, "prodcode": 6674, "descr": ""},
    {"catid": 155, "prodcode": 6784, "descr": ""},
])

Serum_Lactate_Dehydrogenase = np.array([
    {"catid": 163, "prodcode": 6747, "descr": ""},
    {"catid": 163, "prodcode": 6751, "descr": ""},
    {"catid": 163, "prodcode": 6752, "descr": ""},
])

Serum_Lithium = np.array([
    {"catid": 160, "prodcode": 6181, "descr": ""},
    {"catid": 160, "prodcode": 6805, "descr": ""},
])

Serum_Magnesium = np.array([
    {"catid": 158, "prodcode": 6939, "descr": ""},
    {"catid": 158, "prodcode": 7064, "descr": ""},
    {"catid": 158, "prodcode": 7117, "descr": ""},
    {"catid": 158, "prodcode": 7118, "descr": ""},
    {"catid": 158, "prodcode": 7119, "descr": ""},
    {"catid": 158, "prodcode": 7120, "descr": ""},
    {"catid": 158, "prodcode": 7121, "descr": ""},
])

Serum_Potasium = np.array([
    {"catid": 159, "prodcode": 5228, "descr": ""},
    {"catid": 159, "prodcode": 5234, "descr": ""},
    {"catid": 159, "prodcode": 5235, "descr": ""},
    {"catid": 159, "prodcode": 5236, "descr": ""},
    {"catid": 159, "prodcode": 5237, "descr": ""},
    {"catid": 159, "prodcode": 5238, "descr": ""},
    {"catid": 159, "prodcode": 5239, "descr": ""},
    {"catid": 159, "prodcode": 5240, "descr": ""},
    {"catid": 159, "prodcode": 5241, "descr": ""},
    {"catid": 159, "prodcode": 5242, "descr": ""},
    {"catid": 159, "prodcode": 5243, "descr": ""},
    {"catid": 159, "prodcode": 5608, "descr": ""},
    {"catid": 159, "prodcode": 5609, "descr": ""},
])

Sigmoidoscopy = np.array([
    {"catid": 101, "prodcode": 5249, "descr": ""},
    {"catid": 101, "prodcode": 5652, "descr": ""},
    {"catid": 101, "prodcode": 5653, "descr": ""},
    {"catid": 101, "prodcode": 6129, "descr": ""},
    {"catid": 101, "prodcode": 7437, "descr": ""},
])

Sinus_X_rays = np.array([
    {"catid": 130, "prodcode": 7704, "descr": ""},
    {"catid": 130, "prodcode": 7705, "descr": ""},
    {"catid": 130, "prodcode": 7706, "descr": ""},
    {"catid": 130, "prodcode": 7707, "descr": ""},
])

Skin_Scraping_for_Fungi = np.array([
    {"catid": 229, "prodcode": 5225, "descr": ""},
    {"catid": 229, "prodcode": 5612, "descr": ""},
    {"catid": 229, "prodcode": 6111, "descr": ""},
    {"catid": 229, "prodcode": 7158, "descr": ""},
])

Skin_Snip_for_Microfilaria = np.array([
    {"catid": 228, "prodcode": 5581, "descr": ""},
    {"catid": 228, "prodcode": 7152, "descr": ""},
    {"catid": 228, "prodcode": 7153, "descr": ""},
    {"catid": 228, "prodcode": 7155, "descr": ""},
    {"catid": 228, "prodcode": 7157, "descr": ""},
])

Skull_X_rays = np.array([
    {"catid": 133, "prodcode": 5666, "descr": ""},
    {"catid": 133, "prodcode": 5667, "descr": ""},
    {"catid": 133, "prodcode": 7278, "descr": ""},
    {"catid": 133, "prodcode": 7637, "descr": ""},
    {"catid": 133, "prodcode": 7638, "descr": ""},
])

Special_Care_baby_Unit = np.array([
    {"catid": 307, "prodcode": 6211, "descr": ""},
    {"catid": 307, "prodcode": 6374, "descr": ""},
    {"catid": 307, "prodcode": 7681, "descr": ""},
])

Specialist_Drug_Therapy = np.array([
    {"catid": 211, "prodcode": 5687, "descr": ""},
    {"catid": 211, "prodcode": 5688, "descr": ""},
])

Specialist_Opthalmologist_Consultation = np.array([
    {"catid": 181, "prodcode": 5271, "descr": ""},
    {"catid": 181, "prodcode": 5272, "descr": ""},
    {"catid": 181, "prodcode": 5332, "descr": ""},
    {"catid": 181, "prodcode": 5333, "descr": ""},
    {"catid": 181, "prodcode": 5334, "descr": ""},
])

Sputum_Acid_Fast_Bacilli_AFB_Test = np.array([
    {"catid": 336, "prodcode": 5813, "descr": ""},
    {"catid": 336, "prodcode": 7164, "descr": ""},
])

Standard_Room = np.array([
    {"catid": 340, "prodcode": 5301, "descr": ""},
])

Stool_Occult_Blood = np.array([
    {"catid": 249, "prodcode": 5566, "descr": ""},
    {"catid": 249, "prodcode": 5586, "descr": ""},
    {"catid": 249, "prodcode": 7579, "descr": ""},
    {"catid": 249, "prodcode": 7580, "descr": ""},
])

Stress_Management = np.array([
    {"catid": 87, "prodcode": 5276, "descr": ""},
    {"catid": 87, "prodcode": 5277, "descr": ""},
])

Surgeries_All_Inclusive = np.array([
    {"catid": 46, "prodcode": 5274, "descr": ""},
    {"catid": 46, "prodcode": 5275, "descr": ""},
    {"catid": 46, "prodcode": 5278, "descr": ""},
    {"catid": 46, "prodcode": 5279, "descr": ""},
    {"catid": 46, "prodcode": 5280, "descr": ""},
    {"catid": 46, "prodcode": 5281, "descr": ""},
    {"catid": 46, "prodcode": 5284, "descr": ""},
    {"catid": 46, "prodcode": 5285, "descr": ""},
    {"catid": 46, "prodcode": 5286, "descr": ""},
    {"catid": 46, "prodcode": 5287, "descr": ""},
    {"catid": 46, "prodcode": 5288, "descr": ""},
    {"catid": 46, "prodcode": 5289, "descr": ""},
    {"catid": 46, "prodcode": 5290, "descr": ""},
    {"catid": 46, "prodcode": 5291, "descr": ""},
    {"catid": 46, "prodcode": 5292, "descr": ""},
    {"catid": 46, "prodcode": 5293, "descr": ""},
    {"catid": 46, "prodcode": 5294, "descr": ""},
    {"catid": 46, "prodcode": 5296, "descr": ""},
    {"catid": 46, "prodcode": 5298, "descr": ""},
    {"catid": 46, "prodcode": 5302, "descr": ""},
    {"catid": 46, "prodcode": 5306, "descr": ""},
    {"catid": 46, "prodcode": 5307, "descr": ""},
    {"catid": 46, "prodcode": 5308, "descr": ""},
    {"catid": 46, "prodcode": 5313, "descr": ""},
    {"catid": 46, "prodcode": 5314, "descr": ""},
    {"catid": 46, "prodcode": 5315, "descr": ""},
    {"catid": 46, "prodcode": 5317, "descr": ""},
    {"catid": 46, "prodcode": 5318, "descr": ""},
    {"catid": 46, "prodcode": 5319, "descr": ""},
    {"catid": 46, "prodcode": 5321, "descr": ""},
    {"catid": 46, "prodcode": 5322, "descr": ""},
    {"catid": 46, "prodcode": 5323, "descr": ""},
    {"catid": 46, "prodcode": 5324, "descr": ""},
    {"catid": 46, "prodcode": 5325, "descr": ""},
    {"catid": 46, "prodcode": 5326, "descr": ""},
    {"catid": 46, "prodcode": 5327, "descr": ""},
    {"catid": 46, "prodcode": 5328, "descr": ""},
    {"catid": 46, "prodcode": 5330, "descr": ""},
    {"catid": 46, "prodcode": 5331, "descr": ""},
    {"catid": 46, "prodcode": 5332, "descr": ""},
    {"catid": 46, "prodcode": 5333, "descr": ""},
    {"catid": 46, "prodcode": 5334, "descr": ""},
    {"catid": 46, "prodcode": 5361, "descr": ""},
    {"catid": 46, "prodcode": 5381, "descr": ""},
    {"catid": 46, "prodcode": 5384, "descr": ""},
    {"catid": 46, "prodcode": 5385, "descr": ""},
    {"catid": 46, "prodcode": 5386, "descr": ""},
    {"catid": 46, "prodcode": 5388, "descr": ""},
    {"catid": 46, "prodcode": 5392, "descr": ""},
    {"catid": 46, "prodcode": 5393, "descr": ""},
    {"catid": 46, "prodcode": 5394, "descr": ""},
    {"catid": 46, "prodcode": 5395, "descr": ""},
    {"catid": 46, "prodcode": 5629, "descr": ""},
    {"catid": 46, "prodcode": 5630, "descr": ""},
    {"catid": 46, "prodcode": 5632, "descr": ""},
    {"catid": 46, "prodcode": 5634, "descr": ""},
    {"catid": 46, "prodcode": 5636, "descr": ""},
    {"catid": 46, "prodcode": 5637, "descr": ""},
    {"catid": 46, "prodcode": 5638, "descr": ""},
    {"catid": 46, "prodcode": 5642, "descr": ""},
    {"catid": 46, "prodcode": 5643, "descr": ""},
    {"catid": 46, "prodcode": 5644, "descr": ""},
    {"catid": 46, "prodcode": 5645, "descr": ""},
    {"catid": 46, "prodcode": 5646, "descr": ""},
    {"catid": 46, "prodcode": 5647, "descr": ""},
    {"catid": 46, "prodcode": 5648, "descr": ""},
    {"catid": 46, "prodcode": 5649, "descr": ""},
    {"catid": 46, "prodcode": 5650, "descr": ""},
    {"catid": 46, "prodcode": 5651, "descr": ""},
    {"catid": 46, "prodcode": 5654, "descr": ""},
    {"catid": 46, "prodcode": 5655, "descr": ""},
    {"catid": 46, "prodcode": 5656, "descr": ""},
    {"catid": 46, "prodcode": 5661, "descr": ""},
    {"catid": 46, "prodcode": 5662, "descr": ""},
    {"catid": 46, "prodcode": 5663, "descr": ""},
    {"catid": 46, "prodcode": 5664, "descr": ""},
    {"catid": 46, "prodcode": 5665, "descr": ""},
    {"catid": 46, "prodcode": 5668, "descr": ""},
    {"catid": 46, "prodcode": 5669, "descr": ""},
    {"catid": 46, "prodcode": 5671, "descr": ""},
    {"catid": 46, "prodcode": 5672, "descr": ""},
    {"catid": 46, "prodcode": 5673, "descr": ""},
    {"catid": 46, "prodcode": 5674, "descr": ""},
    {"catid": 46, "prodcode": 5675, "descr": ""},
    {"catid": 46, "prodcode": 5676, "descr": ""},
    {"catid": 46, "prodcode": 5677, "descr": ""},
    {"catid": 46, "prodcode": 5678, "descr": ""},
    {"catid": 46, "prodcode": 5679, "descr": ""},
    {"catid": 46, "prodcode": 5861, "descr": ""},
    {"catid": 46, "prodcode": 5862, "descr": ""},
    {"catid": 46, "prodcode": 5863, "descr": ""},
    {"catid": 46, "prodcode": 5864, "descr": ""},
    {"catid": 46, "prodcode": 5866, "descr": ""},
    {"catid": 46, "prodcode": 5867, "descr": ""},
    {"catid": 46, "prodcode": 5868, "descr": ""},
    {"catid": 46, "prodcode": 5869, "descr": ""},
    {"catid": 46, "prodcode": 5870, "descr": ""},
    {"catid": 46, "prodcode": 5871, "descr": ""},
    {"catid": 46, "prodcode": 5872, "descr": ""},
    {"catid": 46, "prodcode": 5873, "descr": ""},
    {"catid": 46, "prodcode": 5874, "descr": ""},
    {"catid": 46, "prodcode": 5875, "descr": ""},
    {"catid": 46, "prodcode": 5877, "descr": ""},
    {"catid": 46, "prodcode": 5878, "descr": ""},
    {"catid": 46, "prodcode": 5880, "descr": ""},
    {"catid": 46, "prodcode": 5881, "descr": ""},
    {"catid": 46, "prodcode": 5882, "descr": ""},
    {"catid": 46, "prodcode": 6124, "descr": ""},
    {"catid": 46, "prodcode": 6126, "descr": ""},
    {"catid": 46, "prodcode": 6127, "descr": ""},
    {"catid": 46, "prodcode": 6128, "descr": ""},
    {"catid": 46, "prodcode": 6130, "descr": ""},
    {"catid": 46, "prodcode": 6131, "descr": ""},
    {"catid": 46, "prodcode": 6132, "descr": ""},
    {"catid": 46, "prodcode": 6133, "descr": ""},
    {"catid": 46, "prodcode": 6134, "descr": ""},
    {"catid": 46, "prodcode": 6135, "descr": ""},
    {"catid": 46, "prodcode": 6136, "descr": ""},
    {"catid": 46, "prodcode": 6137, "descr": ""},
    {"catid": 46, "prodcode": 6138, "descr": ""},
    {"catid": 46, "prodcode": 6139, "descr": ""},
    {"catid": 46, "prodcode": 6140, "descr": ""},
    {"catid": 46, "prodcode": 6142, "descr": ""},
    {"catid": 46, "prodcode": 6143, "descr": ""},
    {"catid": 46, "prodcode": 6144, "descr": ""},
    {"catid": 46, "prodcode": 6145, "descr": ""},
    {"catid": 46, "prodcode": 6146, "descr": ""},
    {"catid": 46, "prodcode": 6147, "descr": ""},
    {"catid": 46, "prodcode": 6148, "descr": ""},
    {"catid": 46, "prodcode": 6149, "descr": ""},
    {"catid": 46, "prodcode": 6150, "descr": ""},
    {"catid": 46, "prodcode": 6151, "descr": ""},
    {"catid": 46, "prodcode": 6152, "descr": ""},
    {"catid": 46, "prodcode": 6155, "descr": ""},
    {"catid": 46, "prodcode": 6156, "descr": ""},
    {"catid": 46, "prodcode": 6157, "descr": ""},
    {"catid": 46, "prodcode": 6158, "descr": ""},
    {"catid": 46, "prodcode": 6159, "descr": ""},
    {"catid": 46, "prodcode": 6160, "descr": ""},
    {"catid": 46, "prodcode": 6161, "descr": ""},
    {"catid": 46, "prodcode": 6162, "descr": ""},
    {"catid": 46, "prodcode": 6163, "descr": ""},
    {"catid": 46, "prodcode": 6165, "descr": ""},
    {"catid": 46, "prodcode": 6166, "descr": ""},
    {"catid": 46, "prodcode": 6167, "descr": ""},
    {"catid": 46, "prodcode": 6168, "descr": ""},
    {"catid": 46, "prodcode": 6169, "descr": ""},
    {"catid": 46, "prodcode": 6171, "descr": ""},
    {"catid": 46, "prodcode": 6172, "descr": ""},
    {"catid": 46, "prodcode": 6173, "descr": ""},
    {"catid": 46, "prodcode": 6174, "descr": ""},
    {"catid": 46, "prodcode": 6176, "descr": ""},
    {"catid": 46, "prodcode": 6177, "descr": ""},
    {"catid": 46, "prodcode": 6178, "descr": ""},
    {"catid": 46, "prodcode": 6180, "descr": ""},
    {"catid": 46, "prodcode": 6182, "descr": ""},
    {"catid": 46, "prodcode": 6184, "descr": ""},
    {"catid": 46, "prodcode": 6185, "descr": ""},
    {"catid": 46, "prodcode": 6186, "descr": ""},
    {"catid": 46, "prodcode": 6187, "descr": ""},
    {"catid": 46, "prodcode": 6188, "descr": ""},
    {"catid": 46, "prodcode": 6189, "descr": ""},
    {"catid": 46, "prodcode": 6190, "descr": ""},
    {"catid": 46, "prodcode": 6191, "descr": ""},
    {"catid": 46, "prodcode": 6192, "descr": ""},
    {"catid": 46, "prodcode": 6193, "descr": ""},
    {"catid": 46, "prodcode": 6194, "descr": ""},
    {"catid": 46, "prodcode": 6195, "descr": ""},
    {"catid": 46, "prodcode": 6197, "descr": ""},
    {"catid": 46, "prodcode": 6198, "descr": ""},
    {"catid": 46, "prodcode": 6199, "descr": ""},
    {"catid": 46, "prodcode": 6200, "descr": ""},
    {"catid": 46, "prodcode": 6201, "descr": ""},
    {"catid": 46, "prodcode": 6202, "descr": ""},
    {"catid": 46, "prodcode": 6203, "descr": ""},
    {"catid": 46, "prodcode": 6204, "descr": ""},
    {"catid": 46, "prodcode": 6205, "descr": ""},
    {"catid": 46, "prodcode": 6206, "descr": ""},
    {"catid": 46, "prodcode": 6210, "descr": ""},
    {"catid": 46, "prodcode": 6329, "descr": ""},
    {"catid": 46, "prodcode": 6390, "descr": ""},
    {"catid": 46, "prodcode": 6391, "descr": ""},
    {"catid": 46, "prodcode": 6397, "descr": ""},
    {"catid": 46, "prodcode": 6399, "descr": ""},
    {"catid": 46, "prodcode": 6400, "descr": ""},
    {"catid": 46, "prodcode": 6401, "descr": ""},
    {"catid": 46, "prodcode": 6402, "descr": ""},
    {"catid": 46, "prodcode": 6403, "descr": ""},
    {"catid": 46, "prodcode": 6404, "descr": ""},
    {"catid": 46, "prodcode": 6405, "descr": ""},
    {"catid": 46, "prodcode": 6406, "descr": ""},
    {"catid": 46, "prodcode": 6417, "descr": ""},
    {"catid": 46, "prodcode": 6421, "descr": ""},
    {"catid": 46, "prodcode": 6422, "descr": ""},
    {"catid": 46, "prodcode": 6423, "descr": ""},
    {"catid": 46, "prodcode": 6424, "descr": ""},
    {"catid": 46, "prodcode": 6425, "descr": ""},
    {"catid": 46, "prodcode": 6426, "descr": ""},
    {"catid": 46, "prodcode": 6429, "descr": ""},
    {"catid": 46, "prodcode": 6434, "descr": ""},
    {"catid": 46, "prodcode": 6440, "descr": ""},
    {"catid": 46, "prodcode": 6441, "descr": ""},
    {"catid": 46, "prodcode": 6442, "descr": ""},
    {"catid": 46, "prodcode": 6444, "descr": ""},
    {"catid": 46, "prodcode": 6445, "descr": ""},
    {"catid": 46, "prodcode": 6454, "descr": ""},
    {"catid": 46, "prodcode": 6455, "descr": ""},
    {"catid": 46, "prodcode": 6456, "descr": ""},
    {"catid": 46, "prodcode": 6457, "descr": ""},
    {"catid": 46, "prodcode": 6459, "descr": ""},
    {"catid": 46, "prodcode": 6460, "descr": ""},
    {"catid": 46, "prodcode": 6461, "descr": ""},
    {"catid": 46, "prodcode": 6462, "descr": ""},
    {"catid": 46, "prodcode": 6555, "descr": ""},
    {"catid": 46, "prodcode": 6556, "descr": ""},
    {"catid": 46, "prodcode": 6557, "descr": ""},
    {"catid": 46, "prodcode": 6558, "descr": ""},
    {"catid": 46, "prodcode": 6785, "descr": ""},
    {"catid": 46, "prodcode": 6787, "descr": ""},
    {"catid": 46, "prodcode": 6788, "descr": ""},
    {"catid": 46, "prodcode": 6790, "descr": ""},
    {"catid": 46, "prodcode": 6799, "descr": ""},
    {"catid": 46, "prodcode": 6801, "descr": ""},
    {"catid": 46, "prodcode": 6802, "descr": ""},
    {"catid": 46, "prodcode": 6804, "descr": ""},
    {"catid": 46, "prodcode": 6807, "descr": ""},
    {"catid": 46, "prodcode": 6808, "descr": ""}, 
    {"catid": 46, "prodcode": 6809, "descr": ""},
    {"catid": 46, "prodcode": 6811, "descr": ""},
    {"catid": 46, "prodcode": 6812, "descr": ""},
    {"catid": 46, "prodcode": 6813, "descr": ""},
    {"catid": 46, "prodcode": 6817, "descr": ""},
    {"catid": 46, "prodcode": 6818, "descr": ""},
    {"catid": 46, "prodcode": 6819, "descr": ""},
    {"catid": 46, "prodcode": 6820, "descr": ""},
    {"catid": 46, "prodcode": 6821, "descr": ""},
    {"catid": 46, "prodcode": 6822, "descr": ""},
    {"catid": 46, "prodcode": 6823, "descr": ""},
    {"catid": 46, "prodcode": 6824, "descr": ""},
    {"catid": 46, "prodcode": 6825, "descr": ""},
    {"catid": 46, "prodcode": 6826, "descr": ""},
    {"catid": 46, "prodcode": 6828, "descr": ""},
    {"catid": 46, "prodcode": 6832, "descr": ""},
    {"catid": 46, "prodcode": 6833, "descr": ""},
    {"catid": 46, "prodcode": 6835, "descr": ""},
    {"catid": 46, "prodcode": 6837, "descr": ""},
    {"catid": 46, "prodcode": 6838, "descr": ""},
    {"catid": 46, "prodcode": 6839, "descr": ""},
    {"catid": 46, "prodcode": 6840, "descr": ""},
    {"catid": 46, "prodcode": 6841, "descr": ""},
    {"catid": 46, "prodcode": 6842, "descr": ""},
    {"catid": 46, "prodcode": 6843, "descr": ""},
    {"catid": 46, "prodcode": 6844, "descr": ""},
    {"catid": 46, "prodcode": 6845, "descr": ""},
    {"catid": 46, "prodcode": 6846, "descr": ""},
    {"catid": 46, "prodcode": 6847, "descr": ""},
    {"catid": 46, "prodcode": 6848, "descr": ""},
    {"catid": 46, "prodcode": 6850, "descr": ""},
    {"catid": 46, "prodcode": 6851, "descr": ""},
    {"catid": 46, "prodcode": 6853, "descr": ""},
    {"catid": 46, "prodcode": 6858, "descr": ""},
    {"catid": 46, "prodcode": 7197, "descr": ""},
    {"catid": 46, "prodcode": 7199, "descr": ""},
    {"catid": 46, "prodcode": 7207, "descr": ""},
    {"catid": 46, "prodcode": 7209, "descr": ""},
    {"catid": 46, "prodcode": 7223, "descr": ""},
    {"catid": 46, "prodcode": 7224, "descr": ""},
    {"catid": 46, "prodcode": 7225, "descr": ""},
    {"catid": 46, "prodcode": 7226, "descr": ""},
    {"catid": 46, "prodcode": 7227, "descr": ""},
    {"catid": 46, "prodcode": 7229, "descr": ""},
    {"catid": 46, "prodcode": 7230, "descr": ""},
    {"catid": 46, "prodcode": 7232, "descr": ""},
    {"catid": 46, "prodcode": 7233, "descr": ""},
    {"catid": 46, "prodcode": 7234, "descr": ""},
    {"catid": 46, "prodcode": 7235, "descr": ""},
    {"catid": 46, "prodcode": 7236, "descr": ""},
    {"catid": 46, "prodcode": 7240, "descr": ""},
    {"catid": 46, "prodcode": 7241, "descr": ""},
    {"catid": 46, "prodcode": 7242, "descr": ""},
    {"catid": 46, "prodcode": 7243, "descr": ""},
    {"catid": 46, "prodcode": 7244, "descr": ""},
    {"catid": 46, "prodcode": 7246, "descr": ""},
    {"catid": 46, "prodcode": 7247, "descr": ""},
    {"catid": 46, "prodcode": 7248, "descr": ""},
    {"catid": 46, "prodcode": 7249, "descr": ""},
    {"catid": 46, "prodcode": 7250, "descr": ""},
    {"catid": 46, "prodcode": 7251, "descr": ""},
    {"catid": 46, "prodcode": 7252, "descr": ""},
    {"catid": 46, "prodcode": 7253, "descr": ""},
    {"catid": 46, "prodcode": 7254, "descr": ""},
    {"catid": 46, "prodcode": 7255, "descr": ""},
    {"catid": 46, "prodcode": 7256, "descr": ""},
    {"catid": 46, "prodcode": 7257, "descr": ""},
    {"catid": 46, "prodcode": 7259, "descr": ""},
    {"catid": 46, "prodcode": 7260, "descr": ""},
    {"catid": 46, "prodcode": 7261, "descr": ""},
    {"catid": 46, "prodcode": 7262, "descr": ""},
    {"catid": 46, "prodcode": 7263, "descr": ""},
    {"catid": 46, "prodcode": 7265, "descr": ""},
    {"catid": 46, "prodcode": 7266, "descr": ""},
    {"catid": 46, "prodcode": 7267, "descr": ""},
    {"catid": 46, "prodcode": 7268, "descr": ""},
    {"catid": 46, "prodcode": 7269, "descr": ""},
    {"catid": 46, "prodcode": 7270, "descr": ""},
    {"catid": 46, "prodcode": 7272, "descr": ""},
    {"catid": 46, "prodcode": 7273, "descr": ""},
    {"catid": 46, "prodcode": 7274, "descr": ""},
    {"catid": 46, "prodcode": 7275, "descr": ""},
    {"catid": 46, "prodcode": 7284, "descr": ""},
    {"catid": 46, "prodcode": 7285, "descr": ""},
    {"catid": 46, "prodcode": 7286, "descr": ""},
    {"catid": 46, "prodcode": 7287, "descr": ""},
    {"catid": 46, "prodcode": 7436, "descr": ""},
    {"catid": 46, "prodcode": 7438, "descr": ""},
    {"catid": 46, "prodcode": 7441, "descr": ""},
    {"catid": 46, "prodcode": 7443, "descr": ""},
    {"catid": 46, "prodcode": 7444, "descr": ""},
    {"catid": 46, "prodcode": 7445, "descr": ""},
    {"catid": 46, "prodcode": 7447, "descr": ""},
    {"catid": 46, "prodcode": 7451, "descr": ""},
    {"catid": 46, "prodcode": 7452, "descr": ""},
    {"catid": 46, "prodcode": 7453, "descr": ""},
    {"catid": 46, "prodcode": 7454, "descr": ""},
    {"catid": 46, "prodcode": 7455, "descr": ""},
    {"catid": 46, "prodcode": 7457, "descr": ""},
    {"catid": 46, "prodcode": 7458, "descr": ""},
    {"catid": 46, "prodcode": 7459, "descr": ""},
    {"catid": 46, "prodcode": 7460, "descr": ""},
    {"catid": 46, "prodcode": 7461, "descr": ""},
    {"catid": 46, "prodcode": 7462, "descr": ""},
    {"catid": 46, "prodcode": 7463, "descr": ""},
    {"catid": 46, "prodcode": 7466, "descr": ""},
    {"catid": 46, "prodcode": 7468, "descr": ""},
    {"catid": 46, "prodcode": 7469, "descr": ""},
    {"catid": 46, "prodcode": 7608, "descr": ""},
    {"catid": 46, "prodcode": 7609, "descr": ""},
    {"catid": 46, "prodcode": 7611, "descr": ""},
    {"catid": 46, "prodcode": 7612, "descr": ""},
    {"catid": 46, "prodcode": 7613, "descr": ""},
    {"catid": 46, "prodcode": 7615, "descr": ""},
    {"catid": 46, "prodcode": 7616, "descr": ""},
    {"catid": 46, "prodcode": 7617, "descr": ""},
    {"catid": 46, "prodcode": 7618, "descr": ""},
    {"catid": 46, "prodcode": 7619, "descr": ""},
    {"catid": 46, "prodcode": 7620, "descr": ""},
    {"catid": 46, "prodcode": 7621, "descr": ""},
    {"catid": 46, "prodcode": 7622, "descr": ""},
    {"catid": 46, "prodcode": 7624, "descr": ""},
    {"catid": 46, "prodcode": 7625, "descr": ""},
    {"catid": 46, "prodcode": 7626, "descr": ""},
    {"catid": 46, "prodcode": 7627, "descr": ""},
    {"catid": 46, "prodcode": 7629, "descr": ""},
    {"catid": 46, "prodcode": 7630, "descr": ""},
    {"catid": 46, "prodcode": 7631, "descr": ""},
    {"catid": 46, "prodcode": 7632, "descr": ""},
    {"catid": 46, "prodcode": 7633, "descr": ""},
    {"catid": 46, "prodcode": 7634, "descr": ""},
    {"catid": 46, "prodcode": 7635, "descr": ""},
    {"catid": 46, "prodcode": 7636, "descr": ""},
    {"catid": 46, "prodcode": 7639, "descr": ""},
    {"catid": 46, "prodcode": 7640, "descr": ""},
    {"catid": 46, "prodcode": 7641, "descr": ""},
    {"catid": 46, "prodcode": 7642, "descr": ""},
    {"catid": 46, "prodcode": 7644, "descr": ""},
    {"catid": 46, "prodcode": 7645, "descr": ""},
    {"catid": 46, "prodcode": 7646, "descr": ""},
    {"catid": 46, "prodcode": 7647, "descr": ""},
    {"catid": 46, "prodcode": 7648, "descr": ""},
    {"catid": 46, "prodcode": 7649, "descr": ""},
    {"catid": 46, "prodcode": 7650, "descr": ""},
    {"catid": 46, "prodcode": 7651, "descr": ""},
    {"catid": 46, "prodcode": 7652, "descr": ""},
    {"catid": 46, "prodcode": 7653, "descr": ""},
    {"catid": 46, "prodcode": 7654, "descr": ""},
    {"catid": 46, "prodcode": 7655, "descr": ""},
    {"catid": 46, "prodcode": 7657, "descr": ""},
    {"catid": 46, "prodcode": 7658, "descr": ""},
    {"catid": 46, "prodcode": 7659, "descr": ""},
    {"catid": 46, "prodcode": 7660, "descr": ""},
    {"catid": 46, "prodcode": 7661, "descr": ""},
    {"catid": 46, "prodcode": 7662, "descr": ""},
    {"catid": 46, "prodcode": 7663, "descr": ""},
    {"catid": 46, "prodcode": 7664, "descr": ""},
    {"catid": 46, "prodcode": 7665, "descr": ""},
    {"catid": 46, "prodcode": 7666, "descr": ""},
    {"catid": 46, "prodcode": 7667, "descr": ""},
    {"catid": 46, "prodcode": 7668, "descr": ""},
    {"catid": 46, "prodcode": 7669, "descr": ""},
])

Surgical_Cancer_Care = np.array([
    {"catid": 141, "prodcode": 5299, "descr": ""},
    {"catid": 141, "prodcode": 5390, "descr": ""},
    {"catid": 141, "prodcode": 5391, "descr": ""},
    {"catid": 141, "prodcode": 5865, "descr": ""},
    {"catid": 141, "prodcode": 6154, "descr": ""},
    {"catid": 141, "prodcode": 6427, "descr": ""},
    {"catid": 141, "prodcode": 6428, "descr": ""},
    {"catid": 141, "prodcode": 6430, "descr": ""},
    {"catid": 141, "prodcode": 6447, "descr": ""},
    {"catid": 141, "prodcode": 6448, "descr": ""},
    {"catid": 141, "prodcode": 6449, "descr": ""},
    {"catid": 141, "prodcode": 6780, "descr": ""},
    {"catid": 141, "prodcode": 6810, "descr": ""},
    {"catid": 141, "prodcode": 6831, "descr": ""},
    {"catid": 141, "prodcode": 6834, "descr": ""},
    {"catid": 141, "prodcode": 6854, "descr": ""},
    {"catid": 141, "prodcode": 6856, "descr": ""},
    {"catid": 141, "prodcode": 6857, "descr": ""},
    {"catid": 141, "prodcode": 7134, "descr": ""},
    {"catid": 141, "prodcode": 7245, "descr": ""},
])

Surgical_extraction = np.array([
    {"catid": 172, "prodcode": 6218, "descr": ""},
    {"catid": 172, "prodcode": 6219, "descr": ""},
    {"catid": 172, "prodcode": 6408, "descr": ""},
    {"catid": 172, "prodcode": 6409, "descr": ""},
    {"catid": 172, "prodcode": 6410, "descr": ""},
    {"catid": 172, "prodcode": 6411, "descr": ""},
    {"catid": 172, "prodcode": 6412, "descr": ""},
    {"catid": 172, "prodcode": 6413, "descr": ""},
    {"catid": 172, "prodcode": 6414, "descr": ""},
    {"catid": 172, "prodcode": 6415, "descr": ""},
    {"catid": 172, "prodcode": 6416, "descr": ""},
    {"catid": 172, "prodcode": 7233, "descr": ""},
])

# =============================================================================
# SUMMARY — S.py
# =============================================================================
# Categories in this file : 41
# Total product entries    : 566
#
# Breakdown by category:
#   Scaling_and_Polishing (catid=168): 1 products
#   Seeking_Second_Opinion (catid=52): 37 products
#   Semen_M_C_S (catid=322): (no products — variable omitted)
#   Semi_Private_Room (catid=341): 1 products
#   Seminal_Fluid_Analysis_SFA (catid=332): 3 products
#   Serum_Acid_Phosphate (catid=154): 4 products
#   Serum_Albumin (catid=157): 2 products
#   Serum_Alkaline_Phosphate (catid=153): (no products — variable omitted)
#   Serum_Bicarbonate (catid=162): (no products — variable omitted)
#   Serum_Bilirubin_Total_and_Direct (catid=156): 4 products
#   Serum_Calcium (catid=148): (no products — variable omitted)
#   Serum_Chloride (catid=161): 13 products
#   Serum_Cholesterol (catid=289): 4 products
#   Serum_Gamma_Glutamyl_Transferase (catid=164): 5 products
#   Serum_Inorganic_Phosphate (catid=155): 4 products
#   Serum_Iron (catid=323): (no products — variable omitted)
#   Serum_Lactate_Dehydrogenase (catid=163): 3 products
#   Serum_Lithium (catid=160): 2 products
#   Serum_Magnesium (catid=158): 7 products
#   Serum_Potasium (catid=159): 13 products
#   Serum_Sodium (catid=145): (no products — variable omitted)
#   Serum_Uric_Acid (catid=315): (no products — variable omitted)
#   Sigmoidoscopy (catid=101): 5 products
#   Sinus_X_rays (catid=130): 4 products
#   Skin_Scraping_for_Fungi (catid=229): 4 products
#   Skin_Snip_for_Microfilaria (catid=228): 5 products
#   Skull_X_rays (catid=133): 5 products
#   Special_Care_baby_Unit (catid=307): 3 products
#   Specialist_Consultation (catid=26): (no products — variable omitted)
#   Specialist_Drug_Therapy (catid=211): 2 products
#   Specialist_Opthalmologist_Consultation (catid=181): 5 products
#   Sputum_Acid_Fast_Bacilli_AFB_Test (catid=336): 2 products
#   Sputum_M_C_S (catid=242): (no products — variable omitted)
#   Standard_Room (catid=340): 1 products
#   Stool_M_C_S (catid=244): (no products — variable omitted)
#   Stool_Occult_Blood (catid=249): 4 products
#   Stress_Management (catid=87): 2 products
#   Surgeries_All_Inclusive (catid=46): 389 products
#   Surgical_Cancer_Care (catid=141): 20 products
#   Surgical_extraction (catid=172): 12 products
#   Syphilis_Screening (catid=320): (no products — variable omitted)
# =============================================================================
