import numpy as np

# =============================================================================
# V.py
# Service category product assignments — letter V
# Generated by: product-service-mapper skill
# =============================================================================

VDRL_Veneral_Disease_Research_Laboratory_Test_unless_where_disallowed_by_diagnosis = np.array([
    {"catid": 245, "prodcode": 6062, "descr": ""},
    {"catid": 245, "prodcode": 6084, "descr": ""},
    {"catid": 245, "prodcode": 6088, "descr": ""},
    {"catid": 245, "prodcode": 6089, "descr": ""},
])

Vitamin_A = np.array([
    {"catid": 78, "prodcode": 5207, "descr": ""},
    {"catid": 78, "prodcode": 6115, "descr": ""},
    {"catid": 78, "prodcode": 6784, "descr": ""},
    {"catid": 78, "prodcode": 7187, "descr": ""},
    {"catid": 78, "prodcode": 7213, "descr": ""},
])

# =============================================================================
# SUMMARY — V.py
# =============================================================================
# Categories in this file : 2
# Total product entries    : 9
#
# Breakdown by category:
#   VDRL_Veneral_Disease_Research_Laboratory_Test_unless_where_disallowed_by_diagnosis (catid=245): 4 products
#   Vitamin_A (catid=78): 5 products
# =============================================================================
