import numpy as np

# =============================================================================
# H.py
# Service category product assignments — letter H
# Generated by: product-service-mapper skill
# =============================================================================

HBA1C = np.array([
    {"catid": 316, "prodcode": 19583, "descr": ""},
])

Hematological_Test = np.array([
    {"catid": 31, "prodcode": 19455, "descr": ""},
    {"catid": 31, "prodcode": 20135, "descr": ""},
    {"catid": 31, "prodcode": 20148, "descr": ""},
])

Hepatitis_B = np.array([
    {"catid": 83, "prodcode": 17968, "descr": ""},
    {"catid": 83, "prodcode": 19420, "descr": ""},
    {"catid": 83, "prodcode": 19762, "descr": ""},
])

Hepatitis_B_Screening = np.array([
    {"catid": 318, "prodcode": 16674, "descr": ""},
    {"catid": 318, "prodcode": 19762, "descr": ""},
])

Hepatitis_B_Surface_Antigen_HBSAg = np.array([
    {"catid": 310, "prodcode": 17968, "descr": ""},
    {"catid": 310, "prodcode": 18011, "descr": ""},
    {"catid": 310, "prodcode": 19420, "descr": ""},
])

Hepatitis_C_Screening = np.array([
    {"catid": 317, "prodcode": 18029, "descr": ""},
])

Hiv_Care_And_Treatment_At_Designated_Sites = np.array([
    {"catid": 51, "prodcode": 19438, "descr": ""},
    {"catid": 51, "prodcode": 19439, "descr": ""},
    {"catid": 51, "prodcode": 19580, "descr": ""},
    {"catid": 51, "prodcode": 19581, "descr": ""},
    {"catid": 51, "prodcode": 19582, "descr": ""},
    {"catid": 51, "prodcode": 19583, "descr": ""},
    {"catid": 51, "prodcode": 19584, "descr": ""},
    {"catid": 51, "prodcode": 19585, "descr": ""},
    {"catid": 51, "prodcode": 19586, "descr": ""},
    {"catid": 51, "prodcode": 19587, "descr": ""},
    {"catid": 51, "prodcode": 19588, "descr": ""},
    {"catid": 51, "prodcode": 19589, "descr": ""},
])

HIV_Screening = np.array([
    {"catid": 311, "prodcode": 18013, "descr": ""},
    {"catid": 311, "prodcode": 19385, "descr": ""},
    {"catid": 311, "prodcode": 19387, "descr": ""},
    {"catid": 311, "prodcode": 19476, "descr": ""},
])

Hysteroscopy = np.array([
    {"catid": 113, "prodcode": 19569, "descr": ""},
    {"catid": 113, "prodcode": 19578, "descr": ""},
    {"catid": 113, "prodcode": 19659, "descr": ""},
    {"catid": 113, "prodcode": 20246, "descr": ""},
])

# =============================================================================
# SUMMARY — H.py
# =============================================================================
# Categories in this file : 14
# Total product entries    : 33
# Duplicate entries removed: 0
#
# Breakdown by category:
#   H_Pylori (catid=246): (no products — variable omitted)
#   HBA1C (catid=316): 1 products
#   Hematological_Test (catid=31): 3 products
#   Hematologist (catid=272): (no products — variable omitted)
#   Hemoglobin_HB (catid=200): (no products — variable omitted)
#   Hepatitis_B (catid=83): 3 products
#   Hepatitis_B_Screening (catid=318): 2 products
#   Hepatitis_B_Surface_Antigen_HBSAg (catid=310): 3 products
#   Hepatitis_C_Screening (catid=317): 1 products
#   High_Vaginal_Swab_HVS_M_or_C_or_S (catid=236): (no products — variable omitted)
#   Hiv_Care_And_Treatment_At_Designated_Sites (catid=51): 12 products
#   HIV_Confirmatory_Test (catid=312): (no products — variable omitted)
#   HIV_Screening (catid=311): 4 products
#   Hysteroscopy (catid=113): 4 products
# =============================================================================
