import numpy as np

# =============================================================================
# M.py
# Service category product assignments — letter M
# Generated by: product-service-mapper skill
# =============================================================================
"""
Major_Surgeries = np.array([
    {"catid": 287, "prodcode": 16618, "descr": ""},
    {"catid": 287, "prodcode": 16622, "descr": ""},
    {"catid": 287, "prodcode": 16623, "descr": ""},
    {"catid": 287, "prodcode": 16668, "descr": ""},
    {"catid": 287, "prodcode": 16738, "descr": ""},
    {"catid": 287, "prodcode": 18057, "descr": ""},
    {"catid": 287, "prodcode": 18058, "descr": ""},
    {"catid": 287, "prodcode": 18059, "descr": ""},
    {"catid": 287, "prodcode": 18060, "descr": ""},
    {"catid": 287, "prodcode": 18061, "descr": ""},
    {"catid": 287, "prodcode": 18062, "descr": ""},
    {"catid": 287, "prodcode": 18063, "descr": ""},
    {"catid": 287, "prodcode": 18066, "descr": ""},
    {"catid": 287, "prodcode": 18067, "descr": ""},
    {"catid": 287, "prodcode": 18069, "descr": ""},
    {"catid": 287, "prodcode": 18070, "descr": ""},
    {"catid": 287, "prodcode": 18071, "descr": ""},
    {"catid": 287, "prodcode": 18072, "descr": ""},
    {"catid": 287, "prodcode": 18104, "descr": ""},
    {"catid": 287, "prodcode": 18111, "descr": ""},
    {"catid": 287, "prodcode": 18115, "descr": ""},
    {"catid": 287, "prodcode": 18124, "descr": ""},
    {"catid": 287, "prodcode": 18125, "descr": ""},
    {"catid": 287, "prodcode": 18146, "descr": ""},
    {"catid": 287, "prodcode": 18147, "descr": ""},
    {"catid": 287, "prodcode": 18158, "descr": ""},
    {"catid": 287, "prodcode": 18168, "descr": ""},
    {"catid": 287, "prodcode": 18169, "descr": ""},
    {"catid": 287, "prodcode": 18246, "descr": ""},
    {"catid": 287, "prodcode": 19296, "descr": ""},
    {"catid": 287, "prodcode": 19521, "descr": ""},
    {"catid": 287, "prodcode": 19525, "descr": ""},
    {"catid": 287, "prodcode": 19528, "descr": ""},
    {"catid": 287, "prodcode": 19529, "descr": ""},
    {"catid": 287, "prodcode": 19569, "descr": ""},
    {"catid": 287, "prodcode": 19596, "descr": ""},
    {"catid": 287, "prodcode": 19606, "descr": ""},
    {"catid": 287, "prodcode": 19613, "descr": ""},
    {"catid": 287, "prodcode": 19614, "descr": ""},
    {"catid": 287, "prodcode": 19615, "descr": ""},
    {"catid": 287, "prodcode": 19616, "descr": ""},
    {"catid": 287, "prodcode": 19617, "descr": ""},
    {"catid": 287, "prodcode": 19618, "descr": ""},
    {"catid": 287, "prodcode": 19619, "descr": ""},
    {"catid": 287, "prodcode": 19631, "descr": ""},
    {"catid": 287, "prodcode": 19635, "descr": ""},
    {"catid": 287, "prodcode": 19641, "descr": ""},
    {"catid": 287, "prodcode": 19667, "descr": ""},
    {"catid": 287, "prodcode": 19668, "descr": ""},
    {"catid": 287, "prodcode": 19672, "descr": ""},
    {"catid": 287, "prodcode": 20171, "descr": ""},
    {"catid": 287, "prodcode": 20172, "descr": ""},
    {"catid": 287, "prodcode": 20173, "descr": ""},
    {"catid": 287, "prodcode": 20177, "descr": ""},
    {"catid": 287, "prodcode": 20178, "descr": ""},
    {"catid": 287, "prodcode": 20182, "descr": ""},
    {"catid": 287, "prodcode": 20215, "descr": ""},
    {"catid": 287, "prodcode": 20216, "descr": ""},
    {"catid": 287, "prodcode": 20224, "descr": ""},
])

Malaria_Parasite = np.array([
    {"catid": 230, "prodcode": 16804, "descr": ""},
    {"catid": 230, "prodcode": 19474, "descr": ""},
])

Male_Circumcision_and_Ear_piercing_within_first_6_wks = np.array([
    {"catid": 225, "prodcode": 18076, "descr": ""},
    {"catid": 225, "prodcode": 19554, "descr": ""},
    {"catid": 225, "prodcode": 19555, "descr": ""},
    {"catid": 225, "prodcode": 19556, "descr": ""},
    {"catid": 225, "prodcode": 19557, "descr": ""},
    {"catid": 225, "prodcode": 19662, "descr": ""},
    {"catid": 225, "prodcode": 19663, "descr": ""},
    {"catid": 225, "prodcode": 19664, "descr": ""},
])

Mammography_For_Women_40_Years_Of_Age = np.array([
    {"catid": 291, "prodcode": 16804, "descr": ""},
    {"catid": 291, "prodcode": 16805, "descr": ""},
    {"catid": 291, "prodcode": 16806, "descr": ""},
    {"catid": 291, "prodcode": 16807, "descr": ""},
    {"catid": 291, "prodcode": 19364, "descr": ""},
    {"catid": 291, "prodcode": 20151, "descr": ""},
    {"catid": 291, "prodcode": 20152, "descr": ""},
    {"catid": 291, "prodcode": 20210, "descr": ""},
])

Mandibles_or_Temporomandibular_Joint_X_Rays = np.array([
    {"catid": 128, "prodcode": 18034, "descr": ""},
    {"catid": 128, "prodcode": 18107, "descr": ""},
    {"catid": 128, "prodcode": 19518, "descr": ""},
    {"catid": 128, "prodcode": 19559, "descr": ""},
    {"catid": 128, "prodcode": 19565, "descr": ""},
    {"catid": 128, "prodcode": 19608, "descr": ""},
    {"catid": 128, "prodcode": 19609, "descr": ""},
    {"catid": 128, "prodcode": 19625, "descr": ""},
    {"catid": 128, "prodcode": 19626, "descr": ""},
    {"catid": 128, "prodcode": 19629, "descr": ""},
    {"catid": 128, "prodcode": 19669, "descr": ""},
])

Mantoux_Heaf_s_Test = np.array([
    {"catid": 247, "prodcode": 16804, "descr": ""},
    {"catid": 247, "prodcode": 19474, "descr": ""},
])
"""
Mastoid_X_rays = np.array([
    {"catid": 131, "prodcode": 16808, "descr": ""},
    {"catid": 131, "prodcode": 18271, "descr": ""},
    {"catid": 131, "prodcode": 18319, "descr": ""},
])

Measles = np.array([
    {"catid": 79, "prodcode": 19762, "descr": ""},
])

Meningitis = np.array([
    {"catid": 95, "prodcode": 19697, "descr": ""},
    {"catid": 95, "prodcode": 19762, "descr": ""},
])

Mental_Illness_Care_With_Certified_Psychiatrists_Outpatient_Care_Only = np.array([
    {"catid": 86, "prodcode": 18088, "descr": ""},
])

Microbiology_And_Parasitology = np.array([
    {"catid": 33, "prodcode": 17724, "descr": ""},
    {"catid": 33, "prodcode": 18042, "descr": ""},
    {"catid": 33, "prodcode": 18044, "descr": ""},
    {"catid": 33, "prodcode": 18199, "descr": ""},
    {"catid": 33, "prodcode": 19404, "descr": ""},
    {"catid": 33, "prodcode": 19458, "descr": ""},
    {"catid": 33, "prodcode": 19463, "descr": ""},
    {"catid": 33, "prodcode": 19477, "descr": ""},
    {"catid": 33, "prodcode": 19479, "descr": ""},
    {"catid": 33, "prodcode": 20127, "descr": ""},
    {"catid": 33, "prodcode": 20128, "descr": ""},
    {"catid": 33, "prodcode": 20130, "descr": ""},
    {"catid": 33, "prodcode": 20136, "descr": ""},
])

Minor_Surgeries = np.array([
    {"catid": 285, "prodcode": 16616, "descr": ""},
    {"catid": 285, "prodcode": 16619, "descr": ""},
    {"catid": 285, "prodcode": 16620, "descr": ""},
    {"catid": 285, "prodcode": 16743, "descr": ""},
    {"catid": 285, "prodcode": 16744, "descr": ""},
    {"catid": 285, "prodcode": 16763, "descr": ""},
    {"catid": 285, "prodcode": 18064, "descr": ""},
    {"catid": 285, "prodcode": 18073, "descr": ""},
    {"catid": 285, "prodcode": 18076, "descr": ""},
    {"catid": 285, "prodcode": 18078, "descr": ""},
    {"catid": 285, "prodcode": 18105, "descr": ""},
    {"catid": 285, "prodcode": 18106, "descr": ""},
    {"catid": 285, "prodcode": 18123, "descr": ""},
    {"catid": 285, "prodcode": 18156, "descr": ""},
    {"catid": 285, "prodcode": 18173, "descr": ""},
    {"catid": 285, "prodcode": 18191, "descr": ""},
    {"catid": 285, "prodcode": 18803, "descr": ""},
    {"catid": 285, "prodcode": 19517, "descr": ""},
    {"catid": 285, "prodcode": 19523, "descr": ""},
    {"catid": 285, "prodcode": 19526, "descr": ""},
    {"catid": 285, "prodcode": 19527, "descr": ""},
    {"catid": 285, "prodcode": 19540, "descr": ""},
    {"catid": 285, "prodcode": 19546, "descr": ""},
    {"catid": 285, "prodcode": 19552, "descr": ""},
    {"catid": 285, "prodcode": 19554, "descr": ""},
    {"catid": 285, "prodcode": 19555, "descr": ""},
    {"catid": 285, "prodcode": 19556, "descr": ""},
    {"catid": 285, "prodcode": 19557, "descr": ""},
    {"catid": 285, "prodcode": 19591, "descr": ""},
    {"catid": 285, "prodcode": 19597, "descr": ""},
    {"catid": 285, "prodcode": 19610, "descr": ""},
    {"catid": 285, "prodcode": 19611, "descr": ""},
    {"catid": 285, "prodcode": 19612, "descr": ""},
    {"catid": 285, "prodcode": 19627, "descr": ""},
    {"catid": 285, "prodcode": 19629, "descr": ""},
    {"catid": 285, "prodcode": 19637, "descr": ""},
    {"catid": 285, "prodcode": 19638, "descr": ""},
    {"catid": 285, "prodcode": 19639, "descr": ""},
    {"catid": 285, "prodcode": 19640, "descr": ""},
    {"catid": 285, "prodcode": 19648, "descr": ""},
    {"catid": 285, "prodcode": 19651, "descr": ""},
    {"catid": 285, "prodcode": 19662, "descr": ""},
    {"catid": 285, "prodcode": 19663, "descr": ""},
    {"catid": 285, "prodcode": 19664, "descr": ""},
    {"catid": 285, "prodcode": 19686, "descr": ""},
    {"catid": 285, "prodcode": 19687, "descr": ""},
    {"catid": 285, "prodcode": 19688, "descr": ""},
    {"catid": 285, "prodcode": 19689, "descr": ""},
    {"catid": 285, "prodcode": 20028, "descr": ""},
    {"catid": 285, "prodcode": 20181, "descr": ""},
    {"catid": 285, "prodcode": 20189, "descr": ""},
    {"catid": 285, "prodcode": 20200, "descr": ""},
    {"catid": 285, "prodcode": 20208, "descr": ""},
    {"catid": 285, "prodcode": 20209, "descr": ""},
    {"catid": 285, "prodcode": 20219, "descr": ""},
    {"catid": 285, "prodcode": 20228, "descr": ""},
    {"catid": 285, "prodcode": 20229, "descr": ""},
    {"catid": 285, "prodcode": 20233, "descr": ""},
])

Mmr = np.array([
    {"catid": 93, "prodcode": 19762, "descr": ""},
])

Mortuary_Services = np.array([
    {"catid": 53, "prodcode": 18047, "descr": ""},
    {"catid": 53, "prodcode": 18048, "descr": ""},
])

MRI = np.array([
    {"catid": 98, "prodcode": 18477, "descr": ""},
])

# =============================================================================
# SUMMARY — M.py
# =============================================================================
# Categories in this file : 18
# Total product entries    : 172
# Duplicate entries removed: 0
#
# Breakdown by category:
#   Major_Surgeries (catid=287): 59 products
#   Malaria_Parasite (catid=230): 2 products
#   Male_Circumcision_and_Ear_piercing_within_first_6_wks (catid=225): 8 products
#   Mammography_For_Women_40_Years_Of_Age (catid=291): 8 products
#   Mandibles_or_Temporomandibular_Joint_X_Rays (catid=128): 11 products
#   Mantoux_Heaf_s_Test (catid=247): 2 products
#   Mastoid_X_rays (catid=131): 3 products
#   MCH (catid=202): (no products — variable omitted)
#   MCHC (catid=210): (no products — variable omitted)
#   MCV (catid=203): (no products — variable omitted)
#   Measles (catid=79): 1 products
#   Meningitis (catid=95): 2 products
#   Mental_Illness_Care_With_Certified_Psychiatrists_Outpatient_Care_Only (catid=86): 1 products
#   Microbiology_And_Parasitology (catid=33): 13 products
#   Minor_Surgeries (catid=285): 58 products
#   Mmr (catid=93): 1 products
#   Mortuary_Services (catid=53): 2 products
#   MRI (catid=98): 1 products
# =============================================================================
