import numpy as np

# =============================================================================
# O.py
# Service category product assignments — letter O
# Generated by: product-service-mapper skill
# =============================================================================

Obstetrician = np.array([
    {"catid": 264, "prodcode": 16733, "descr": ""},
    {"catid": 264, "prodcode": 16734, "descr": ""},
    {"catid": 264, "prodcode": 16735, "descr": ""},
    {"catid": 264, "prodcode": 16736, "descr": ""},
    {"catid": 264, "prodcode": 16737, "descr": ""},
    {"catid": 264, "prodcode": 17745, "descr": ""},
    {"catid": 264, "prodcode": 20138, "descr": ""},
])

Obstetrics_And_Gynaecology_Care_In_Patient_Limit_Applies = np.array([
    {"catid": 38, "prodcode": 16733, "descr": ""},
    {"catid": 38, "prodcode": 16734, "descr": ""},
    {"catid": 38, "prodcode": 16735, "descr": ""},
    {"catid": 38, "prodcode": 16736, "descr": ""},
    {"catid": 38, "prodcode": 16737, "descr": ""},
    {"catid": 38, "prodcode": 16865, "descr": ""},
    {"catid": 38, "prodcode": 17535, "descr": ""},
    {"catid": 38, "prodcode": 17745, "descr": ""},
    {"catid": 38, "prodcode": 18011, "descr": ""},
    {"catid": 38, "prodcode": 18081, "descr": ""},
    {"catid": 38, "prodcode": 18088, "descr": ""},
    {"catid": 38, "prodcode": 19652, "descr": ""},
    {"catid": 38, "prodcode": 19653, "descr": ""},
    {"catid": 38, "prodcode": 19654, "descr": ""},
    {"catid": 38, "prodcode": 19672, "descr": ""},
    {"catid": 38, "prodcode": 19679, "descr": ""},
    {"catid": 38, "prodcode": 20138, "descr": ""},
    {"catid": 38, "prodcode": 20183, "descr": ""},
    {"catid": 38, "prodcode": 20222, "descr": ""},
])

Oncological_Investigations = np.array([
    {"catid": 139, "prodcode": 17976, "descr": ""},
    {"catid": 139, "prodcode": 17998, "descr": ""},
    {"catid": 139, "prodcode": 19359, "descr": ""},
    {"catid": 139, "prodcode": 19360, "descr": ""},
    {"catid": 139, "prodcode": 19362, "descr": ""},
    {"catid": 139, "prodcode": 19363, "descr": ""},
    {"catid": 139, "prodcode": 19376, "descr": ""},
    {"catid": 139, "prodcode": 19388, "descr": ""},
    {"catid": 139, "prodcode": 19390, "descr": ""},
    {"catid": 139, "prodcode": 19391, "descr": ""},
    {"catid": 139, "prodcode": 19392, "descr": ""},
    {"catid": 139, "prodcode": 20152, "descr": ""},
])

Oncologist = np.array([
    {"catid": 273, "prodcode": 19542, "descr": ""},
    {"catid": 273, "prodcode": 19543, "descr": ""},
])

Oncologist_Or_Cancer_Specialist_Visits = np.array([
    {"catid": 138, "prodcode": 16669, "descr": ""},
    {"catid": 138, "prodcode": 16670, "descr": ""},
    {"catid": 138, "prodcode": 17535, "descr": ""},
    {"catid": 138, "prodcode": 18088, "descr": ""},
    {"catid": 138, "prodcode": 18183, "descr": ""},
    {"catid": 138, "prodcode": 19593, "descr": ""},
    {"catid": 138, "prodcode": 20240, "descr": ""},
    {"catid": 138, "prodcode": 20737, "descr": ""},
])

Operculectomy = np.array([
    {"catid": 176, "prodcode": 18064, "descr": ""},
    {"catid": 176, "prodcode": 18123, "descr": ""},
    {"catid": 176, "prodcode": 19540, "descr": ""},
    {"catid": 176, "prodcode": 19638, "descr": ""},
    {"catid": 176, "prodcode": 19639, "descr": ""},
    {"catid": 176, "prodcode": 19640, "descr": ""},
    {"catid": 176, "prodcode": 20028, "descr": ""},
    {"catid": 176, "prodcode": 20200, "descr": ""},
    {"catid": 176, "prodcode": 20219, "descr": ""},
    {"catid": 176, "prodcode": 20228, "descr": ""},
    {"catid": 176, "prodcode": 20233, "descr": ""},
])

Opv_Or_Ipv = np.array([
    {"catid": 81, "prodcode": 19762, "descr": ""},
    {"catid": 81, "prodcode": 20737, "descr": ""},
])

Oral_and_Maxillofacial_Surgeon = np.array([
    {"catid": 283, "prodcode": 19599, "descr": ""},
    {"catid": 283, "prodcode": 19600, "descr": ""},
    {"catid": 283, "prodcode": 19601, "descr": ""},
    {"catid": 283, "prodcode": 19602, "descr": ""},
    {"catid": 283, "prodcode": 19603, "descr": ""},
])

Oral_Glucose_Tolerance_Test_OGTT = np.array([
    {"catid": 152, "prodcode": 19583, "descr": ""},
])

Orthopedic_Surgeon = np.array([
    {"catid": 263, "prodcode": 18086, "descr": ""},
    {"catid": 263, "prodcode": 18087, "descr": ""},
    {"catid": 263, "prodcode": 18127, "descr": ""},
    {"catid": 263, "prodcode": 18155, "descr": ""},
    {"catid": 263, "prodcode": 19518, "descr": ""},
    {"catid": 263, "prodcode": 19559, "descr": ""},
    {"catid": 263, "prodcode": 19608, "descr": ""},
    {"catid": 263, "prodcode": 19609, "descr": ""},
    {"catid": 263, "prodcode": 19622, "descr": ""},
    {"catid": 263, "prodcode": 19669, "descr": ""},
    {"catid": 263, "prodcode": 20167, "descr": ""},
    {"catid": 263, "prodcode": 20168, "descr": ""},
    {"catid": 263, "prodcode": 20170, "descr": ""},
    {"catid": 263, "prodcode": 20230, "descr": ""},
])

Osmotic_Fragility_Test = np.array([
    {"catid": 327, "prodcode": 19108, "descr": ""},
    {"catid": 327, "prodcode": 19220, "descr": ""},
    {"catid": 327, "prodcode": 20290, "descr": ""},
])

Out_Patient_care_Limit = np.array([
    {"catid": 57, "prodcode": 16669, "descr": ""},
    {"catid": 57, "prodcode": 16670, "descr": ""},
    {"catid": 57, "prodcode": 16804, "descr": ""},
    {"catid": 57, "prodcode": 17535, "descr": ""},
    {"catid": 57, "prodcode": 18088, "descr": ""},
    {"catid": 57, "prodcode": 18183, "descr": ""},
    {"catid": 57, "prodcode": 19474, "descr": ""},
    {"catid": 57, "prodcode": 19593, "descr": ""},
    {"catid": 57, "prodcode": 20240, "descr": ""},
    {"catid": 57, "prodcode": 20737, "descr": ""},
])

# =============================================================================
# SUMMARY — O.py
# =============================================================================
# Categories in this file : 12
# Total product entries    : 94
# Duplicate entries removed: 0
#
# Breakdown by category:
#   Obstetrician (catid=264): 7 products
#   Obstetrics_And_Gynaecology_Care_In_Patient_Limit_Applies (catid=38): 19 products
#   Oncological_Investigations (catid=139): 12 products
#   Oncologist (catid=273): 2 products
#   Oncologist_Or_Cancer_Specialist_Visits (catid=138): 8 products
#   Operculectomy (catid=176): 11 products
#   Opv_Or_Ipv (catid=81): 2 products
#   Oral_and_Maxillofacial_Surgeon (catid=283): 5 products
#   Oral_Glucose_Tolerance_Test_OGTT (catid=152): 1 products
#   Orthopedic_Surgeon (catid=263): 14 products
#   Osmotic_Fragility_Test (catid=327): 3 products
#   Out_Patient_care_Limit (catid=57): 10 products
# =============================================================================
