import numpy as np

# =============================================================================
# V.py
# Service category product assignments — letter V
# Generated by: product-service-mapper skill
# =============================================================================

VDRL_Veneral_Disease_Research_Laboratory_Test_unless_where_disallowed_by_diagnosis = np.array([
    {"catid": 245, "prodcode": 19354, "descr": ""},
    {"catid": 245, "prodcode": 19355, "descr": ""},
])

Vitamin_A = np.array([
    {"catid": 78, "prodcode": 16704, "descr": ""},
    {"catid": 78, "prodcode": 16705, "descr": ""},
    {"catid": 78, "prodcode": 16706, "descr": ""},
    {"catid": 78, "prodcode": 18540, "descr": ""},
    {"catid": 78, "prodcode": 19809, "descr": ""},
    {"catid": 78, "prodcode": 19810, "descr": ""},
    {"catid": 78, "prodcode": 20130, "descr": ""},
])

# =============================================================================
# SUMMARY — V.py
# =============================================================================
# Categories in this file : 2
# Total product entries    : 9
# Duplicate entries removed: 0
#
# Breakdown by category:
#   VDRL_Veneral_Disease_Research_Laboratory_Test_unless_where_disallowed_by_diagnosis (catid=245): 2 products
#   Vitamin_A (catid=78): 7 products
# =============================================================================
