import numpy as np

# =============================================================================
# B.py
# Service category product assignments — letter B
# Generated by: product-service-mapper skill
# =============================================================================
Basic_Diagnostic_Imaging = np.array([
    {"catid": 29, "prodcode": 20726, "descr": ""},
    {"catid": 29, "prodcode": 20765, "descr": ""},
    {"catid": 29, "prodcode": 20807, "descr": ""},
    {"catid": 29, "prodcode": 20813, "descr": ""},
    {"catid": 29, "prodcode": 20816, "descr": ""},
    {"catid": 29, "prodcode": 20817, "descr": ""},
    {"catid": 29, "prodcode": 20825, "descr": ""},
    {"catid": 29, "prodcode": 20827, "descr": ""},
    {"catid": 29, "prodcode": 21303, "descr": ""},
    {"catid": 29, "prodcode": 21306, "descr": ""},
    {"catid": 29, "prodcode": 21310, "descr": ""},
    {"catid": 29, "prodcode": 21312, "descr": ""},
    {"catid": 29, "prodcode": 21313, "descr": ""},
    {"catid": 29, "prodcode": 21317, "descr": ""},
    {"catid": 29, "prodcode": 21322, "descr": ""},
    {"catid": 29, "prodcode": 21323, "descr": ""},
    {"catid": 29, "prodcode": 21327, "descr": ""},
    {"catid": 29, "prodcode": 21330, "descr": ""},
    {"catid": 29, "prodcode": 21332, "descr": ""},
    {"catid": 29, "prodcode": 21334, "descr": ""},
    {"catid": 29, "prodcode": 21774, "descr": ""},
    {"catid": 29, "prodcode": 21778, "descr": ""},
    {"catid": 29, "prodcode": 21790, "descr": ""},
    {"catid": 29, "prodcode": 21798, "descr": ""},
    {"catid": 29, "prodcode": 21802, "descr": ""},
    {"catid": 29, "prodcode": 21804, "descr": ""},
    {"catid": 29, "prodcode": 22142, "descr": ""},
    {"catid": 29, "prodcode": 22145, "descr": ""},
    {"catid": 29, "prodcode": 22147, "descr": ""},
    {"catid": 29, "prodcode": 22620, "descr": ""},
    {"catid": 29, "prodcode": 22621, "descr": ""},
    {"catid": 29, "prodcode": 22623, "descr": ""},
    {"catid": 29, "prodcode": 22624, "descr": ""},
    {"catid": 29, "prodcode": 22625, "descr": ""},
    {"catid": 29, "prodcode": 22626, "descr": ""},
    {"catid": 29, "prodcode": 22628, "descr": ""},
    {"catid": 29, "prodcode": 22723, "descr": ""},
    {"catid": 29, "prodcode": 22727, "descr": ""},
    {"catid": 29, "prodcode": 22728, "descr": ""},
    {"catid": 29, "prodcode": 22729, "descr": ""},
    {"catid": 29, "prodcode": 22730, "descr": ""},
    {"catid": 29, "prodcode": 22731, "descr": ""},
    {"catid": 29, "prodcode": 22732, "descr": ""},
    {"catid": 29, "prodcode": 22733, "descr": ""},
    {"catid": 29, "prodcode": 22734, "descr": ""},
    {"catid": 29, "prodcode": 22735, "descr": ""},
    {"catid": 29, "prodcode": 22736, "descr": ""},
    {"catid": 29, "prodcode": 22737, "descr": ""},
    {"catid": 29, "prodcode": 22743, "descr": ""},
    {"catid": 29, "prodcode": 22744, "descr": ""},
    {"catid": 29, "prodcode": 22746, "descr": ""},
    {"catid": 29, "prodcode": 22748, "descr": ""},
    {"catid": 29, "prodcode": 22749, "descr": ""},
    {"catid": 29, "prodcode": 22754, "descr": ""},
    {"catid": 29, "prodcode": 22755, "descr": ""},
    {"catid": 29, "prodcode": 22756, "descr": ""},
    {"catid": 29, "prodcode": 23228, "descr": ""},
    {"catid": 29, "prodcode": 23235, "descr": ""},
    {"catid": 29, "prodcode": 23240, "descr": ""},
    {"catid": 29, "prodcode": 23243, "descr": ""},
    {"catid": 29, "prodcode": 23250, "descr": ""},
    {"catid": 29, "prodcode": 23902, "descr": ""},
    {"catid": 29, "prodcode": 23903, "descr": ""},
    {"catid": 29, "prodcode": 23904, "descr": ""},
    {"catid": 29, "prodcode": 24248, "descr": ""},
    {"catid": 29, "prodcode": 24252, "descr": ""},
    {"catid": 29, "prodcode": 24260, "descr": ""},
    {"catid": 29, "prodcode": 24448, "descr": ""},
    {"catid": 29, "prodcode": 24602, "descr": ""},
    {"catid": 29, "prodcode": 24609, "descr": ""},
    {"catid": 29, "prodcode": 24610, "descr": ""},
    {"catid": 29, "prodcode": 24611, "descr": ""},
    {"catid": 29, "prodcode": 24615, "descr": ""},
    {"catid": 29, "prodcode": 24616, "descr": ""},
])

Basic_Lab_Investigations_or_Xrays_and_Ultrasound = np.array([
    {"catid": 56, "prodcode": 20730, "descr": ""},
    {"catid": 56, "prodcode": 20732, "descr": ""},
    {"catid": 56, "prodcode": 20733, "descr": ""},
    {"catid": 56, "prodcode": 20807, "descr": ""},
    {"catid": 56, "prodcode": 20813, "descr": ""},
    {"catid": 56, "prodcode": 20816, "descr": ""},
    {"catid": 56, "prodcode": 20825, "descr": ""},
    {"catid": 56, "prodcode": 20827, "descr": ""},
    {"catid": 56, "prodcode": 21204, "descr": ""},
    {"catid": 56, "prodcode": 21205, "descr": ""},
    {"catid": 56, "prodcode": 21261, "descr": ""},
    {"catid": 56, "prodcode": 21291, "descr": ""},
    {"catid": 56, "prodcode": 21303, "descr": ""},
    {"catid": 56, "prodcode": 21306, "descr": ""},
    {"catid": 56, "prodcode": 21312, "descr": ""},
    {"catid": 56, "prodcode": 21313, "descr": ""},
    {"catid": 56, "prodcode": 21317, "descr": ""},
    {"catid": 56, "prodcode": 21322, "descr": ""},
    {"catid": 56, "prodcode": 21327, "descr": ""},
    {"catid": 56, "prodcode": 21332, "descr": ""},
    {"catid": 56, "prodcode": 21334, "descr": ""},
    {"catid": 56, "prodcode": 21632, "descr": ""},
    {"catid": 56, "prodcode": 21656, "descr": ""},
    {"catid": 56, "prodcode": 21657, "descr": ""},
    {"catid": 56, "prodcode": 21774, "descr": ""},
    {"catid": 56, "prodcode": 21778, "descr": ""},
    {"catid": 56, "prodcode": 21790, "descr": ""},
    {"catid": 56, "prodcode": 21802, "descr": ""},
    {"catid": 56, "prodcode": 21804, "descr": ""},
    {"catid": 56, "prodcode": 22078, "descr": ""},
    {"catid": 56, "prodcode": 22145, "descr": ""},
    {"catid": 56, "prodcode": 22147, "descr": ""},
    {"catid": 56, "prodcode": 22620, "descr": ""},
    {"catid": 56, "prodcode": 22623, "descr": ""},
    {"catid": 56, "prodcode": 22625, "descr": ""},
    {"catid": 56, "prodcode": 22628, "descr": ""},
    {"catid": 56, "prodcode": 22737, "descr": ""},
    {"catid": 56, "prodcode": 22743, "descr": ""},
    {"catid": 56, "prodcode": 22744, "descr": ""},
    {"catid": 56, "prodcode": 22746, "descr": ""},
    {"catid": 56, "prodcode": 22748, "descr": ""},
    {"catid": 56, "prodcode": 22749, "descr": ""},
    {"catid": 56, "prodcode": 22756, "descr": ""},
    {"catid": 56, "prodcode": 23157, "descr": ""},
    {"catid": 56, "prodcode": 23228, "descr": ""},
    {"catid": 56, "prodcode": 23240, "descr": ""},
    {"catid": 56, "prodcode": 23250, "descr": ""},
    {"catid": 56, "prodcode": 23902, "descr": ""},
    {"catid": 56, "prodcode": 23903, "descr": ""},
    {"catid": 56, "prodcode": 23912, "descr": ""},
    {"catid": 56, "prodcode": 24248, "descr": ""},
    {"catid": 56, "prodcode": 24252, "descr": ""},
    {"catid": 56, "prodcode": 24260, "descr": ""},
    {"catid": 56, "prodcode": 24602, "descr": ""},
    {"catid": 56, "prodcode": 24609, "descr": ""},
    {"catid": 56, "prodcode": 24610, "descr": ""},
])

Basic_ocular_tests = np.array([
    {"catid": 182, "prodcode": 20742, "descr": ""},
    {"catid": 182, "prodcode": 21204, "descr": ""},
    {"catid": 182, "prodcode": 21205, "descr": ""},
    {"catid": 182, "prodcode": 21240, "descr": ""},
    {"catid": 182, "prodcode": 21261, "descr": ""},
    {"catid": 182, "prodcode": 21283, "descr": ""},
    {"catid": 182, "prodcode": 21291, "descr": ""},
    {"catid": 182, "prodcode": 22132, "descr": ""},
    {"catid": 182, "prodcode": 22133, "descr": ""},
    {"catid": 182, "prodcode": 22134, "descr": ""},
    {"catid": 182, "prodcode": 22539, "descr": ""},
    {"catid": 182, "prodcode": 23912, "descr": ""},
    {"catid": 182, "prodcode": 24260, "descr": ""},
    {"catid": 182, "prodcode": 24342, "descr": ""},
    {"catid": 182, "prodcode": 24343, "descr": ""},
    {"catid": 182, "prodcode": 24344, "descr": ""},
])

Bcg = np.array([
    {"catid": 80, "prodcode": 20764, "descr": ""},
    {"catid": 80, "prodcode": 23000, "descr": ""},
    {"catid": 80, "prodcode": 23001, "descr": ""},
    {"catid": 80, "prodcode": 23373, "descr": ""},
    {"catid": 80, "prodcode": 23992, "descr": ""},
    {"catid": 80, "prodcode": 24419, "descr": ""},
])

Bleeding_Time = np.array([
    {"catid": 334, "prodcode": 21657, "descr": ""},
    {"catid": 334, "prodcode": 24618, "descr": ""},
])

Blood_Film = np.array([
    {"catid": 204, "prodcode": 21204, "descr": ""},
    {"catid": 204, "prodcode": 21205, "descr": ""},
    {"catid": 204, "prodcode": 21261, "descr": ""},
    {"catid": 204, "prodcode": 21291, "descr": ""},
    {"catid": 204, "prodcode": 23748, "descr": ""},
    {"catid": 204, "prodcode": 23749, "descr": ""},
    {"catid": 204, "prodcode": 23750, "descr": ""},
    {"catid": 204, "prodcode": 23751, "descr": ""},
    {"catid": 204, "prodcode": 23912, "descr": ""},
    {"catid": 204, "prodcode": 24260, "descr": ""},
])

Blood_Pregnancy_Beta_HCG_Test = np.array([
    {"catid": 205, "prodcode": 21950, "descr": ""},
    {"catid": 205, "prodcode": 21990, "descr": ""},
    {"catid": 205, "prodcode": 22000, "descr": ""},
    {"catid": 205, "prodcode": 23770, "descr": ""},
])

Blood_Pressure_Check_Hypertension_Screening = np.array([
    {"catid": 295, "prodcode": 22132, "descr": ""},
    {"catid": 295, "prodcode": 22133, "descr": ""},
    {"catid": 295, "prodcode": 22134, "descr": ""},
    {"catid": 295, "prodcode": 24342, "descr": ""},
    {"catid": 295, "prodcode": 24343, "descr": ""},
    {"catid": 295, "prodcode": 24344, "descr": ""},
])

Body_Massage = np.array([
    {"catid": 195, "prodcode": 21319, "descr": ""},
    {"catid": 195, "prodcode": 21320, "descr": ""},
    {"catid": 195, "prodcode": 21754, "descr": ""},
    {"catid": 195, "prodcode": 22077, "descr": ""},
    {"catid": 195, "prodcode": 23158, "descr": ""},
    {"catid": 195, "prodcode": 24459, "descr": ""},
    {"catid": 195, "prodcode": 24460, "descr": ""},
    {"catid": 195, "prodcode": 24461, "descr": ""},
    {"catid": 195, "prodcode": 24462, "descr": ""},
    {"catid": 195, "prodcode": 24463, "descr": ""},
])

Bronchoscopy = np.array([
    {"catid": 111, "prodcode": 21186, "descr": ""},
    {"catid": 111, "prodcode": 21697, "descr": ""},
    {"catid": 111, "prodcode": 21698, "descr": ""},
    {"catid": 111, "prodcode": 21699, "descr": ""},
    {"catid": 111, "prodcode": 21700, "descr": ""},
    {"catid": 111, "prodcode": 21701, "descr": ""},
    {"catid": 111, "prodcode": 21702, "descr": ""},
    {"catid": 111, "prodcode": 21703, "descr": ""},
    {"catid": 111, "prodcode": 21704, "descr": ""},
    {"catid": 111, "prodcode": 21705, "descr": ""},
    {"catid": 111, "prodcode": 21706, "descr": ""},
    {"catid": 111, "prodcode": 21707, "descr": ""},
    {"catid": 111, "prodcode": 21746, "descr": ""},
])

# =============================================================================
# SUMMARY — B.py
# =============================================================================
# Categories in this file : 16
# Total product entries    : 197
# Duplicate entries removed: 0
#
# Breakdown by category:
#   Basic_Diagnostic_Imaging (catid=29): 74 products
#   Basic_Lab_Investigations_or_Xrays_and_Ultrasound (catid=56): 56 products
#   Basic_ocular_tests (catid=182): 16 products
#   Bcg (catid=80): 6 products
#   Biennial_Lenses_and_Frames (catid=185): (no products — variable omitted)
#   Bleeding_Time (catid=334): 2 products
#   Blood_Culture (catid=248): (no products — variable omitted)
#   Blood_Film (catid=204): 10 products
#   Blood_group_on_request_by_clinician (catid=208): (no products — variable omitted)
#   Blood_Pregnancy_Beta_HCG_Test (catid=205): 4 products
#   Blood_Pressure_Check_Hypertension_Screening (catid=295): 6 products
#   Blood_Sugar_Check_Diabetes_Screening (catid=288): (no products — variable omitted)
#   Blood_urea_Nitrogen (catid=309): (no products — variable omitted)
#   Bmi_Check (catid=292): (no products — variable omitted)
#   Body_Massage (catid=195): 10 products
#   Bronchoscopy (catid=111): 13 products
# =============================================================================
