import numpy as np

# =============================================================================
# G.py
# Service category product assignments — letter G
# Generated by: product-service-mapper skill
# =============================================================================

G_6PD_Screening = np.array([
    {"catid": 313, "prodcode": 23112, "descr": ""},
    {"catid": 313, "prodcode": 23113, "descr": ""},
    {"catid": 313, "prodcode": 24404, "descr": ""},
    {"catid": 313, "prodcode": 24636, "descr": ""},
])

Gastroenterologist = np.array([
    {"catid": 269, "prodcode": 21184, "descr": ""},
])

Gastroscopy = np.array([
    {"catid": 117, "prodcode": 21204, "descr": ""},
    {"catid": 117, "prodcode": 21205, "descr": ""},
    {"catid": 117, "prodcode": 21261, "descr": ""},
    {"catid": 117, "prodcode": 21291, "descr": ""},
    {"catid": 117, "prodcode": 23912, "descr": ""},
    {"catid": 117, "prodcode": 24260, "descr": ""},
])

General_Consultation = np.array([
    {"catid": 54, "prodcode": 20794, "descr": ""},
    {"catid": 54, "prodcode": 20799, "descr": ""},
    {"catid": 54, "prodcode": 20800, "descr": ""},
    {"catid": 54, "prodcode": 20803, "descr": ""},
    {"catid": 54, "prodcode": 20804, "descr": ""},
    {"catid": 54, "prodcode": 21151, "descr": ""},
    {"catid": 54, "prodcode": 21295, "descr": ""},
    {"catid": 54, "prodcode": 21297, "descr": ""},
    {"catid": 54, "prodcode": 21300, "descr": ""},
    {"catid": 54, "prodcode": 21709, "descr": ""},
    {"catid": 54, "prodcode": 21764, "descr": ""},
    {"catid": 54, "prodcode": 21769, "descr": ""},
    {"catid": 54, "prodcode": 21773, "descr": ""},
    {"catid": 54, "prodcode": 22122, "descr": ""},
    {"catid": 54, "prodcode": 22123, "descr": ""},
    {"catid": 54, "prodcode": 22124, "descr": ""},
    {"catid": 54, "prodcode": 22129, "descr": ""},
    {"catid": 54, "prodcode": 22139, "descr": ""},
    {"catid": 54, "prodcode": 22721, "descr": ""},
    {"catid": 54, "prodcode": 22722, "descr": ""},
    {"catid": 54, "prodcode": 23220, "descr": ""},
    {"catid": 54, "prodcode": 23225, "descr": ""},
    {"catid": 54, "prodcode": 23890, "descr": ""},
    {"catid": 54, "prodcode": 24242, "descr": ""},
    {"catid": 54, "prodcode": 24562, "descr": ""},
    {"catid": 54, "prodcode": 24566, "descr": ""},
    {"catid": 54, "prodcode": 24567, "descr": ""},
    {"catid": 54, "prodcode": 24568, "descr": ""},
    {"catid": 54, "prodcode": 24569, "descr": ""},
    {"catid": 54, "prodcode": 24573, "descr": ""},
    {"catid": 54, "prodcode": 24574, "descr": ""},
    {"catid": 54, "prodcode": 24575, "descr": ""},
    {"catid": 54, "prodcode": 24579, "descr": ""},
    {"catid": 54, "prodcode": 24580, "descr": ""},
    {"catid": 54, "prodcode": 24582, "descr": ""},
])

General_Physical_Examination = np.array([
    {"catid": 294, "prodcode": 20749, "descr": ""},
    {"catid": 294, "prodcode": 21204, "descr": ""},
    {"catid": 294, "prodcode": 21205, "descr": ""},
    {"catid": 294, "prodcode": 21261, "descr": ""},
    {"catid": 294, "prodcode": 21291, "descr": ""},
    {"catid": 294, "prodcode": 23912, "descr": ""},
    {"catid": 294, "prodcode": 24260, "descr": ""},
    {"catid": 294, "prodcode": 24616, "descr": ""},
    {"catid": 294, "prodcode": 24617, "descr": ""},
])

Genotype_on_request_by_clinician = np.array([
    {"catid": 207, "prodcode": 21637, "descr": ""},
    {"catid": 207, "prodcode": 21949, "descr": ""},
    {"catid": 207, "prodcode": 21950, "descr": ""},
    {"catid": 207, "prodcode": 21960, "descr": ""},
    {"catid": 207, "prodcode": 21986, "descr": ""},
    {"catid": 207, "prodcode": 21998, "descr": ""},
    {"catid": 207, "prodcode": 23246, "descr": ""},
])

Gingival_Curettage = np.array([
    {"catid": 177, "prodcode": 24198, "descr": ""},
])

Grouping_and_Cross_Matching = np.array([
    {"catid": 199, "prodcode": 21206, "descr": ""},
    {"catid": 199, "prodcode": 21207, "descr": ""},
    {"catid": 199, "prodcode": 24192, "descr": ""},
])

Gym_Services_At_Network_Gym_Centres = np.array([
    {"catid": 192, "prodcode": 21319, "descr": ""},
    {"catid": 192, "prodcode": 21320, "descr": ""},
])

Gynaecologist = np.array([
    {"catid": 265, "prodcode": 20747, "descr": ""},
    {"catid": 265, "prodcode": 23763, "descr": ""},
])

# =============================================================================
# SUMMARY — G.py
# =============================================================================
# Categories in this file : 13
# Total product entries    : 70
# Duplicate entries removed: 0
#
# Breakdown by category:
#   G_6PD_Screening (catid=313): 4 products
#   Gastroenterologist (catid=269): 1 products
#   Gastroscopy (catid=117): 6 products
#   General_Consultation (catid=54): 35 products
#   General_Physical_Examination (catid=294): 9 products
#   General_Surgeon (catid=337): (no products — variable omitted)
#   Genotype_on_request_by_clinician (catid=207): 7 products
#   Gingival_Curettage (catid=177): 1 products
#   Glucose_Challenge_Test (catid=146): (no products — variable omitted)
#   Grouping_and_Cross_Matching (catid=199): 3 products
#   Gym_Services_At_Network_Gym_Centres (catid=192): 2 products
#   Gym_Discounted (catid=44): (no products — variable omitted)
#   Gynaecologist (catid=265): 2 products
# =============================================================================
