import numpy as np

# =============================================================================
# J.py
# Service category product assignments — letter J
# Generated by: product-service-mapper skill
# =============================================================================

Jadelle_Implant = np.array([
    {"catid": 187, "prodcode": 21037, "descr": ""},
    {"catid": 187, "prodcode": 21038, "descr": ""},
    {"catid": 187, "prodcode": 22557, "descr": ""},
    {"catid": 187, "prodcode": 22613, "descr": ""},
    {"catid": 187, "prodcode": 22614, "descr": ""},
    {"catid": 187, "prodcode": 22615, "descr": ""},
    {"catid": 187, "prodcode": 22616, "descr": ""},
    {"catid": 187, "prodcode": 22889, "descr": ""},
    {"catid": 187, "prodcode": 22890, "descr": ""},
    {"catid": 187, "prodcode": 22891, "descr": ""},
    {"catid": 187, "prodcode": 22892, "descr": ""},
    {"catid": 187, "prodcode": 24525, "descr": ""},
])

# =============================================================================
# SUMMARY — J.py
# =============================================================================
# Categories in this file : 1
# Total product entries    : 12
# Duplicate entries removed: 0
#
# Breakdown by category:
#   Jadelle_Implant (catid=187): 12 products
# =============================================================================
