import numpy as np

# =============================================================================
# T.py
# Service category product assignments — letter T
# Generated by: product-service-mapper skill
# =============================================================================

Therapeutic_Abortion_Manual_Vacuum_Aspiration = np.array([
    {"catid": 255, "prodcode": 20758, "descr": ""},
    {"catid": 255, "prodcode": 21204, "descr": ""},
    {"catid": 255, "prodcode": 21214, "descr": ""},
    {"catid": 255, "prodcode": 21215, "descr": ""},
    {"catid": 255, "prodcode": 21216, "descr": ""},
    {"catid": 255, "prodcode": 21224, "descr": ""},
    {"catid": 255, "prodcode": 21226, "descr": ""},
    {"catid": 255, "prodcode": 21229, "descr": ""},
    {"catid": 255, "prodcode": 21261, "descr": ""},
    {"catid": 255, "prodcode": 21716, "descr": ""},
    {"catid": 255, "prodcode": 22077, "descr": ""},
    {"catid": 255, "prodcode": 22078, "descr": ""},
    {"catid": 255, "prodcode": 22491, "descr": ""},
    {"catid": 255, "prodcode": 23213, "descr": ""},
    {"catid": 255, "prodcode": 23855, "descr": ""},
    {"catid": 255, "prodcode": 24532, "descr": ""},
])

Thoracic_Inlet_X_rays = np.array([
    {"catid": 125, "prodcode": 21679, "descr": ""},
    {"catid": 125, "prodcode": 21683, "descr": ""},
    {"catid": 125, "prodcode": 23288, "descr": ""},
    {"catid": 125, "prodcode": 24498, "descr": ""},
])

Thoraco_Lumbar_X_rays = np.array([
    {"catid": 126, "prodcode": 21679, "descr": ""},
    {"catid": 126, "prodcode": 21683, "descr": ""},
    {"catid": 126, "prodcode": 23288, "descr": ""},
])

Thoracoscopy = np.array([
    {"catid": 112, "prodcode": 20748, "descr": ""},
    {"catid": 112, "prodcode": 20749, "descr": ""},
    {"catid": 112, "prodcode": 20750, "descr": ""},
    {"catid": 112, "prodcode": 20751, "descr": ""},
    {"catid": 112, "prodcode": 20752, "descr": ""},
    {"catid": 112, "prodcode": 20783, "descr": ""},
    {"catid": 112, "prodcode": 20786, "descr": ""},
    {"catid": 112, "prodcode": 21204, "descr": ""},
    {"catid": 112, "prodcode": 21205, "descr": ""},
    {"catid": 112, "prodcode": 21214, "descr": ""},
    {"catid": 112, "prodcode": 21215, "descr": ""},
    {"catid": 112, "prodcode": 21216, "descr": ""},
    {"catid": 112, "prodcode": 21224, "descr": ""},
    {"catid": 112, "prodcode": 21226, "descr": ""},
    {"catid": 112, "prodcode": 21229, "descr": ""},
    {"catid": 112, "prodcode": 21247, "descr": ""},
    {"catid": 112, "prodcode": 21248, "descr": ""},
    {"catid": 112, "prodcode": 21249, "descr": ""},
    {"catid": 112, "prodcode": 21250, "descr": ""},
    {"catid": 112, "prodcode": 21251, "descr": ""},
    {"catid": 112, "prodcode": 21261, "descr": ""},
    {"catid": 112, "prodcode": 21291, "descr": ""},
    {"catid": 112, "prodcode": 21716, "descr": ""},
    {"catid": 112, "prodcode": 21760, "descr": ""},
    {"catid": 112, "prodcode": 22077, "descr": ""},
    {"catid": 112, "prodcode": 22078, "descr": ""},
    {"catid": 112, "prodcode": 22125, "descr": ""},
    {"catid": 112, "prodcode": 22491, "descr": ""},
    {"catid": 112, "prodcode": 22505, "descr": ""},
    {"catid": 112, "prodcode": 22506, "descr": ""},
    {"catid": 112, "prodcode": 22507, "descr": ""},
    {"catid": 112, "prodcode": 22564, "descr": ""},
    {"catid": 112, "prodcode": 23213, "descr": ""},
    {"catid": 112, "prodcode": 23875, "descr": ""},
    {"catid": 112, "prodcode": 23912, "descr": ""},
    {"catid": 112, "prodcode": 24260, "descr": ""},
    {"catid": 112, "prodcode": 24532, "descr": ""},
])

Thyroid_Function_Tests = np.array([
    {"catid": 314, "prodcode": 21649, "descr": ""},
    {"catid": 314, "prodcode": 21650, "descr": ""},
    {"catid": 314, "prodcode": 21653, "descr": ""},
    {"catid": 314, "prodcode": 23763, "descr": ""},
])

Toxoplasma_Screening = np.array([
    {"catid": 232, "prodcode": 21967, "descr": ""},
    {"catid": 232, "prodcode": 21968, "descr": ""},
    {"catid": 232, "prodcode": 22026, "descr": ""},
])

Treatment_of_basic_outpatient_and_in_patient_cases = np.array([
    {"catid": 58, "prodcode": 20745, "descr": ""},
    {"catid": 58, "prodcode": 20747, "descr": ""},
    {"catid": 58, "prodcode": 21234, "descr": ""},
    {"catid": 58, "prodcode": 21749, "descr": ""},
    {"catid": 58, "prodcode": 22057, "descr": ""},
    {"catid": 58, "prodcode": 22103, "descr": ""},
    {"catid": 58, "prodcode": 22497, "descr": ""},
    {"catid": 58, "prodcode": 22553, "descr": ""},
    {"catid": 58, "prodcode": 22554, "descr": ""},
    {"catid": 58, "prodcode": 23209, "descr": ""},
    {"catid": 58, "prodcode": 23836, "descr": ""},
    {"catid": 58, "prodcode": 23837, "descr": ""},
    {"catid": 58, "prodcode": 23849, "descr": ""},
    {"catid": 58, "prodcode": 24189, "descr": ""},
    {"catid": 58, "prodcode": 24190, "descr": ""},
    {"catid": 58, "prodcode": 24198, "descr": ""},
    {"catid": 58, "prodcode": 24453, "descr": ""},
    {"catid": 58, "prodcode": 24527, "descr": ""},
])

# =============================================================================
# SUMMARY — T.py
# =============================================================================
# Categories in this file : 9
# Total product entries    : 85
# Duplicate entries removed: 0
#
# Breakdown by category:
#   Therapeutic_Abortion_Manual_Vacuum_Aspiration (catid=255): 16 products
#   Thoracic_Inlet_X_rays (catid=125): 4 products
#   Thoraco_Lumbar_X_rays (catid=126): 3 products
#   Thoracoscopy (catid=112): 37 products
#   Throat_Swab_M_C_S (catid=238): (no products — variable omitted)
#   Thyroid_Function_Tests (catid=314): 4 products
#   Toxoplasma_Screening (catid=232): 3 products
#   Treatment_of_basic_outpatient_and_in_patient_cases (catid=58): 18 products
#   Trypanosomes_Screening (catid=231): (no products — variable omitted)
# =============================================================================
