import numpy as np

# =============================================================================
# U.py
# Service category product assignments — letter U
# Generated by: product-service-mapper skill
# =============================================================================
"""
Upper_GI_Endoscopy = np.array([
    {"catid": 102, "prodcode": 21204, "descr": ""},
    {"catid": 102, "prodcode": 21205, "descr": ""},
    {"catid": 102, "prodcode": 21247, "descr": ""},
    {"catid": 102, "prodcode": 21248, "descr": ""},
    {"catid": 102, "prodcode": 21249, "descr": ""},
    {"catid": 102, "prodcode": 21250, "descr": ""},
"""
Upper_GI_Endoscopy = np.array([    
    {"catid": 102, "prodcode": 21251, "descr": ""},
    {"catid": 102, "prodcode": 21261, "descr": ""},
    {"catid": 102, "prodcode": 21291, "descr": ""},
    {"catid": 102, "prodcode": 21760, "descr": ""},
    {"catid": 102, "prodcode": 23912, "descr": ""},
    {"catid": 102, "prodcode": 24260, "descr": ""},
    {"catid": 102, "prodcode": 24451, "descr": ""},
    {"catid": 102, "prodcode": 24543, "descr": ""},
])

Urethral_Swab_M_C_S = np.array([
    {"catid": 237, "prodcode": 21274, "descr": ""},
    {"catid": 237, "prodcode": 22468, "descr": ""},
    {"catid": 237, "prodcode": 24149, "descr": ""},
])

Urinalysis = np.array([
    {"catid": 300, "prodcode": 21204, "descr": ""},
    {"catid": 300, "prodcode": 21205, "descr": ""},
    {"catid": 300, "prodcode": 21261, "descr": ""},
    {"catid": 300, "prodcode": 21291, "descr": ""},
    {"catid": 300, "prodcode": 23912, "descr": ""},
    {"catid": 300, "prodcode": 24260, "descr": ""},
])

Urine_M_C_S = np.array([
    {"catid": 234, "prodcode": 21210, "descr": ""},
    {"catid": 234, "prodcode": 21211, "descr": ""},
    {"catid": 234, "prodcode": 23249, "descr": ""},
    {"catid": 234, "prodcode": 23775, "descr": ""},
    {"catid": 234, "prodcode": 23776, "descr": ""},
    {"catid": 234, "prodcode": 23777, "descr": ""},
    {"catid": 234, "prodcode": 23778, "descr": ""},
    {"catid": 234, "prodcode": 23779, "descr": ""},
    {"catid": 234, "prodcode": 23780, "descr": ""},
    {"catid": 234, "prodcode": 23781, "descr": ""},
    {"catid": 234, "prodcode": 23782, "descr": ""},
    {"catid": 234, "prodcode": 23783, "descr": ""},
    {"catid": 234, "prodcode": 23784, "descr": ""},
    {"catid": 234, "prodcode": 23785, "descr": ""},
    {"catid": 234, "prodcode": 23786, "descr": ""},
    {"catid": 234, "prodcode": 23787, "descr": ""},
    {"catid": 234, "prodcode": 23788, "descr": ""},
    {"catid": 234, "prodcode": 23789, "descr": ""},
    {"catid": 234, "prodcode": 23790, "descr": ""},
    {"catid": 234, "prodcode": 23791, "descr": ""},
    {"catid": 234, "prodcode": 23792, "descr": ""},
])

Urologist = np.array([
    {"catid": 262, "prodcode": 23168, "descr": ""},
    {"catid": 262, "prodcode": 24466, "descr": ""},
    {"catid": 262, "prodcode": 24616, "descr": ""},
    {"catid": 262, "prodcode": 24622, "descr": ""},
])

# =============================================================================
# SUMMARY — U.py
# =============================================================================
# Categories in this file : 6
# Total product entries    : 48
# Duplicate entries removed: 0
#
# Breakdown by category:
#   Upper_GI_Endoscopy (catid=102): 14 products
#   Urethral_Swab_M_C_S (catid=237): 3 products
#   Urinalysis (catid=300): 6 products
#   Urine_M_C_S (catid=234): 21 products
#   Urine_Pregnancy_Test (catid=166): (no products — variable omitted)
#   Urologist (catid=262): 4 products
# =============================================================================
