import numpy as np

# =============================================================================
# F.py
# Service category product assignments — letter F
# Generated by: product-service-mapper skill
# =============================================================================

Facials = np.array([
    {"catid": 194, "prodcode": 8161, "descr": ""},
    {"catid": 194, "prodcode": 8162, "descr": ""},
    {"catid": 194, "prodcode": 8242, "descr": ""},
    {"catid": 194, "prodcode": 8532, "descr": ""},
    {"catid": 194, "prodcode": 8537, "descr": ""},
    {"catid": 194, "prodcode": 8538, "descr": ""},
    {"catid": 194, "prodcode": 8539, "descr": ""},
    {"catid": 194, "prodcode": 8540, "descr": ""},
    {"catid": 194, "prodcode": 8541, "descr": ""},
    {"catid": 194, "prodcode": 9714, "descr": ""},
])

Family_Physician = np.array([
    {"catid": 282, "prodcode": 9148, "descr": ""},
])

Family_Planning_Out_Patient_Limit = np.array([
    {"catid": 43, "prodcode": 10748, "descr": ""},
])

Fertility_Investigations = np.array([
    {"catid": 227, "prodcode": 7913, "descr": ""},
    {"catid": 227, "prodcode": 7914, "descr": ""},
    {"catid": 227, "prodcode": 7915, "descr": ""},
    {"catid": 227, "prodcode": 8015, "descr": ""},
    {"catid": 227, "prodcode": 8016, "descr": ""},
    {"catid": 227, "prodcode": 8017, "descr": ""},
    {"catid": 227, "prodcode": 8018, "descr": ""},
    {"catid": 227, "prodcode": 8591, "descr": ""},
    {"catid": 227, "prodcode": 8592, "descr": ""},
    {"catid": 227, "prodcode": 8753, "descr": ""},
    {"catid": 227, "prodcode": 8754, "descr": ""},
    {"catid": 227, "prodcode": 8761, "descr": ""},
    {"catid": 227, "prodcode": 8820, "descr": ""},
    {"catid": 227, "prodcode": 8821, "descr": ""},
    {"catid": 227, "prodcode": 9004, "descr": ""},
    {"catid": 227, "prodcode": 9025, "descr": ""},
    {"catid": 227, "prodcode": 9036, "descr": ""},
    {"catid": 227, "prodcode": 9040, "descr": ""},
    {"catid": 227, "prodcode": 9363, "descr": ""},
    {"catid": 227, "prodcode": 9364, "descr": ""},
    {"catid": 227, "prodcode": 9365, "descr": ""},
    {"catid": 227, "prodcode": 9366, "descr": ""},
    {"catid": 227, "prodcode": 9367, "descr": ""},
    {"catid": 227, "prodcode": 9368, "descr": ""},
    {"catid": 227, "prodcode": 9369, "descr": ""},
    {"catid": 227, "prodcode": 9370, "descr": ""},
    {"catid": 227, "prodcode": 9371, "descr": ""},
    {"catid": 227, "prodcode": 9372, "descr": ""},
    {"catid": 227, "prodcode": 9373, "descr": ""},
    {"catid": 227, "prodcode": 9374, "descr": ""},
    {"catid": 227, "prodcode": 9375, "descr": ""},
    {"catid": 227, "prodcode": 9376, "descr": ""},
    {"catid": 227, "prodcode": 9377, "descr": ""},
    {"catid": 227, "prodcode": 9378, "descr": ""},
    {"catid": 227, "prodcode": 9426, "descr": ""},
    {"catid": 227, "prodcode": 9427, "descr": ""},
    {"catid": 227, "prodcode": 9443, "descr": ""},
    {"catid": 227, "prodcode": 9444, "descr": ""},
    {"catid": 227, "prodcode": 9445, "descr": ""},
    {"catid": 227, "prodcode": 9597, "descr": ""},
    {"catid": 227, "prodcode": 9738, "descr": ""},
    {"catid": 227, "prodcode": 9794, "descr": ""},
    {"catid": 227, "prodcode": 9796, "descr": ""},
])

Fertility_Specialist_Consultation_and_Counselling = np.array([
    {"catid": 226, "prodcode": 7965, "descr": ""},
    {"catid": 226, "prodcode": 7976, "descr": ""},
    {"catid": 226, "prodcode": 8016, "descr": ""},
    {"catid": 226, "prodcode": 8068, "descr": ""},
    {"catid": 226, "prodcode": 8580, "descr": ""},
    {"catid": 226, "prodcode": 8806, "descr": ""},
])

Full_Blood_Count_and_differentials_FBC = np.array([
    {"catid": 196, "prodcode": 7990, "descr": ""},
    {"catid": 196, "prodcode": 7991, "descr": ""},
    {"catid": 196, "prodcode": 7992, "descr": ""},
    {"catid": 196, "prodcode": 7993, "descr": ""},
    {"catid": 196, "prodcode": 7994, "descr": ""},
    {"catid": 196, "prodcode": 7995, "descr": ""},
    {"catid": 196, "prodcode": 8764, "descr": ""},
    {"catid": 196, "prodcode": 9662, "descr": ""},
    {"catid": 196, "prodcode": 9663, "descr": ""},
    {"catid": 196, "prodcode": 9666, "descr": ""},
    {"catid": 196, "prodcode": 10141, "descr": ""},
    {"catid": 196, "prodcode": 10166, "descr": ""},
])

# =============================================================================
# SUMMARY — F.py
# =============================================================================
# Categories in this file : 7
# Total product entries    : 73
#
# Breakdown by category:
#   Facials (catid=194): 10 products
#   Family_Physician (catid=282): 1 products
#   Family_Planning_Out_Patient_Limit (catid=43): 1 products
#   Fasting_Blood_Sugar (catid=149): (no products — variable omitted)
#   Fertility_Investigations (catid=227): 43 products
#   Fertility_Specialist_Consultation_and_Counselling (catid=226): 6 products
#   Full_Blood_Count_and_differentials_FBC (catid=196): 12 products
# =============================================================================
