import numpy as np

# =============================================================================
# K.py
# Service category product assignments — letter K
# Generated by: product-service-mapper skill
# =============================================================================

Kidney_Function_Tests = np.array([
    {"catid": 308, "prodcode": 7797, "descr": ""},
    {"catid": 308, "prodcode": 7839, "descr": ""},
    {"catid": 308, "prodcode": 7867, "descr": ""},
    {"catid": 308, "prodcode": 7868, "descr": ""},
    {"catid": 308, "prodcode": 7869, "descr": ""},
    {"catid": 308, "prodcode": 7870, "descr": ""},
    {"catid": 308, "prodcode": 7871, "descr": ""},
    {"catid": 308, "prodcode": 7872, "descr": ""},
    {"catid": 308, "prodcode": 7959, "descr": ""},
    {"catid": 308, "prodcode": 8003, "descr": ""},
    {"catid": 308, "prodcode": 8004, "descr": ""},
    {"catid": 308, "prodcode": 8005, "descr": ""},
    {"catid": 308, "prodcode": 8006, "descr": ""},
    {"catid": 308, "prodcode": 8032, "descr": ""},
    {"catid": 308, "prodcode": 8333, "descr": ""},
    {"catid": 308, "prodcode": 8682, "descr": ""},
    {"catid": 308, "prodcode": 8686, "descr": ""},
    {"catid": 308, "prodcode": 8687, "descr": ""},
    {"catid": 308, "prodcode": 8688, "descr": ""},
    {"catid": 308, "prodcode": 8739, "descr": ""},
    {"catid": 308, "prodcode": 8744, "descr": ""},
    {"catid": 308, "prodcode": 8745, "descr": ""},
    {"catid": 308, "prodcode": 9181, "descr": ""},
    {"catid": 308, "prodcode": 9425, "descr": ""},
    {"catid": 308, "prodcode": 9434, "descr": ""},
    {"catid": 308, "prodcode": 9764, "descr": ""},
    {"catid": 308, "prodcode": 9797, "descr": ""},
    {"catid": 308, "prodcode": 10111, "descr": ""},
    {"catid": 308, "prodcode": 10763, "descr": ""},
])

# =============================================================================
# SUMMARY — K.py
# =============================================================================
# Categories in this file : 1
# Total product entries    : 29
#
# Breakdown by category:
#   Kidney_Function_Tests (catid=308): 29 products
# =============================================================================
