import numpy as np

# =============================================================================
# L.py
# Service category product assignments — letter L
# Generated by: product-service-mapper skill
# =============================================================================

Laparoscopy = np.array([
    {"catid": 120, "prodcode": 8102, "descr": ""},
    {"catid": 120, "prodcode": 8114, "descr": ""},
    {"catid": 120, "prodcode": 8119, "descr": ""},
    {"catid": 120, "prodcode": 8120, "descr": ""},
    {"catid": 120, "prodcode": 8189, "descr": ""},
    {"catid": 120, "prodcode": 8937, "descr": ""},
    {"catid": 120, "prodcode": 8957, "descr": ""},
    {"catid": 120, "prodcode": 8972, "descr": ""},
    {"catid": 120, "prodcode": 9311, "descr": ""},
    {"catid": 120, "prodcode": 9363, "descr": ""},
    {"catid": 120, "prodcode": 9467, "descr": ""},
    {"catid": 120, "prodcode": 9687, "descr": ""},
    {"catid": 120, "prodcode": 9688, "descr": ""},
    {"catid": 120, "prodcode": 10184, "descr": ""},
    {"catid": 120, "prodcode": 10185, "descr": ""},
])

Laryngoscopy_Direct_and_Indirect = np.array([
    {"catid": 110, "prodcode": 10765, "descr": ""},
    {"catid": 110, "prodcode": 10768, "descr": ""},
])

Leishmania_Screening = np.array([
    {"catid": 233, "prodcode": 8444, "descr": ""},
    {"catid": 233, "prodcode": 8813, "descr": ""},
    {"catid": 233, "prodcode": 8825, "descr": ""},
    {"catid": 233, "prodcode": 8826, "descr": ""},
    {"catid": 233, "prodcode": 8834, "descr": ""},
    {"catid": 233, "prodcode": 9155, "descr": ""},
    {"catid": 233, "prodcode": 9418, "descr": ""},
    {"catid": 233, "prodcode": 9432, "descr": ""},
    {"catid": 233, "prodcode": 9433, "descr": ""},
])

Limbs_X_rays = np.array([
    {"catid": 136, "prodcode": 8398, "descr": ""},
    {"catid": 136, "prodcode": 8399, "descr": ""},
    {"catid": 136, "prodcode": 8400, "descr": ""},
    {"catid": 136, "prodcode": 8406, "descr": ""},
    {"catid": 136, "prodcode": 8890, "descr": ""},
    {"catid": 136, "prodcode": 9384, "descr": ""},
    {"catid": 136, "prodcode": 9385, "descr": ""},
])

Line_Of_Treatment_Confirmation_From_Secondary_And_Tertiary_Care_Centres = np.array([
    {"catid": 260, "prodcode": 8388, "descr": ""},
    {"catid": 260, "prodcode": 8522, "descr": ""},
    {"catid": 260, "prodcode": 8613, "descr": ""},
    {"catid": 260, "prodcode": 8617, "descr": ""},
    {"catid": 260, "prodcode": 8618, "descr": ""},
    {"catid": 260, "prodcode": 8879, "descr": ""},
    {"catid": 260, "prodcode": 8880, "descr": ""},
    {"catid": 260, "prodcode": 8881, "descr": ""},
    {"catid": 260, "prodcode": 8882, "descr": ""},
    {"catid": 260, "prodcode": 9804, "descr": ""},
    {"catid": 260, "prodcode": 9808, "descr": ""},
    {"catid": 260, "prodcode": 9809, "descr": ""},
])

Lipid_Profile_Fasting = np.array([
    {"catid": 143, "prodcode": 9204, "descr": ""},
    {"catid": 143, "prodcode": 9230, "descr": ""},
    {"catid": 143, "prodcode": 9231, "descr": ""},
    {"catid": 143, "prodcode": 9232, "descr": ""},
])

Liver_Function_Test = np.array([
    {"catid": 298, "prodcode": 9181, "descr": ""},
    {"catid": 298, "prodcode": 9404, "descr": ""},
    {"catid": 298, "prodcode": 10765, "descr": ""},
    {"catid": 298, "prodcode": 10766, "descr": ""},
    {"catid": 298, "prodcode": 10767, "descr": ""},
    {"catid": 298, "prodcode": 10768, "descr": ""},
])

Liver_Function_Test_LFT = np.array([
    {"catid": 144, "prodcode": 9181, "descr": ""},
    {"catid": 144, "prodcode": 9404, "descr": ""},
    {"catid": 144, "prodcode": 10765, "descr": ""},
    {"catid": 144, "prodcode": 10766, "descr": ""},
    {"catid": 144, "prodcode": 10767, "descr": ""},
    {"catid": 144, "prodcode": 10768, "descr": ""},
])

Lumbosacral_X_Rays = np.array([
    {"catid": 127, "prodcode": 8398, "descr": ""},
    {"catid": 127, "prodcode": 8399, "descr": ""},
])

# =============================================================================
# SUMMARY — L.py
# =============================================================================
# Categories in this file : 9
# Total product entries    : 63
#
# Breakdown by category:
#   Laparoscopy (catid=120): 15 products
#   Laryngoscopy_Direct_and_Indirect (catid=110): 2 products
#   Leishmania_Screening (catid=233): 9 products
#   Limbs_X_rays (catid=136): 7 products
#   Line_Of_Treatment_Confirmation_From_Secondary_And_Tertiary_Care_Centres (catid=260): 12 products
#   Lipid_Profile_Fasting (catid=143): 4 products
#   Liver_Function_Test (catid=298): 6 products
#   Liver_Function_Test_LFT (catid=144): 6 products
#   Lumbosacral_X_Rays (catid=127): 2 products
# =============================================================================
