import numpy as np

# =============================================================================
# S.py
# Service category product assignments — letter S
# Generated by: product-service-mapper skill
# =============================================================================

Scaling_and_Polishing = np.array([
    {"catid": 168, "prodcode": 8075, "descr": ""},
    {"catid": 168, "prodcode": 8525, "descr": ""},
    {"catid": 168, "prodcode": 8526, "descr": ""},
    {"catid": 168, "prodcode": 8527, "descr": ""},
    {"catid": 168, "prodcode": 8528, "descr": ""},
    {"catid": 168, "prodcode": 8529, "descr": ""},
    {"catid": 168, "prodcode": 8871, "descr": ""},
    {"catid": 168, "prodcode": 8875, "descr": ""},
])

Seeking_Second_Opinion = np.array([
    {"catid": 52, "prodcode": 8164, "descr": ""},
    {"catid": 52, "prodcode": 8230, "descr": ""},
    {"catid": 52, "prodcode": 8231, "descr": ""},
    {"catid": 52, "prodcode": 8233, "descr": ""},
    {"catid": 52, "prodcode": 8424, "descr": ""},
    {"catid": 52, "prodcode": 8438, "descr": ""},
    {"catid": 52, "prodcode": 8519, "descr": ""},
    {"catid": 52, "prodcode": 8520, "descr": ""},
    {"catid": 52, "prodcode": 8521, "descr": ""},
    {"catid": 52, "prodcode": 8523, "descr": ""},
    {"catid": 52, "prodcode": 8524, "descr": ""},
    {"catid": 52, "prodcode": 8537, "descr": ""},
    {"catid": 52, "prodcode": 8538, "descr": ""},
    {"catid": 52, "prodcode": 8539, "descr": ""},
    {"catid": 52, "prodcode": 8540, "descr": ""},
    {"catid": 52, "prodcode": 8541, "descr": ""},
    {"catid": 52, "prodcode": 8619, "descr": ""},
    {"catid": 52, "prodcode": 8850, "descr": ""},
    {"catid": 52, "prodcode": 8851, "descr": ""},
    {"catid": 52, "prodcode": 8852, "descr": ""},
    {"catid": 52, "prodcode": 8895, "descr": ""},
    {"catid": 52, "prodcode": 8968, "descr": ""},
    {"catid": 52, "prodcode": 8969, "descr": ""},
    {"catid": 52, "prodcode": 8970, "descr": ""},
    {"catid": 52, "prodcode": 8971, "descr": ""},
    {"catid": 52, "prodcode": 8972, "descr": ""},
    {"catid": 52, "prodcode": 8973, "descr": ""},
    {"catid": 52, "prodcode": 8974, "descr": ""},
    {"catid": 52, "prodcode": 8975, "descr": ""},
    {"catid": 52, "prodcode": 9361, "descr": ""},
])

Semen_M_C_S = np.array([
    {"catid": 322, "prodcode": 8755, "descr": ""},
    {"catid": 322, "prodcode": 8756, "descr": ""},
    {"catid": 322, "prodcode": 8759, "descr": ""},
])

Semi_Private_Room = np.array([
    {"catid": 341, "prodcode": 8857, "descr": ""},
    {"catid": 341, "prodcode": 8862, "descr": ""},
    {"catid": 341, "prodcode": 10191, "descr": ""},
])

Seminal_Fluid_Analysis_SFA = np.array([
    {"catid": 332, "prodcode": 8518, "descr": ""},
    {"catid": 332, "prodcode": 8756, "descr": ""},
    {"catid": 332, "prodcode": 10626, "descr": ""},
])

Serum_Acid_Phosphate = np.array([
    {"catid": 154, "prodcode": 8024, "descr": ""},
    {"catid": 154, "prodcode": 8025, "descr": ""},
    {"catid": 154, "prodcode": 8026, "descr": ""},
    {"catid": 154, "prodcode": 8027, "descr": ""},
    {"catid": 154, "prodcode": 8051, "descr": ""},
    {"catid": 154, "prodcode": 8052, "descr": ""},
    {"catid": 154, "prodcode": 8193, "descr": ""},
    {"catid": 154, "prodcode": 9327, "descr": ""},
    {"catid": 154, "prodcode": 9338, "descr": ""},
    {"catid": 154, "prodcode": 9340, "descr": ""},
    {"catid": 154, "prodcode": 9346, "descr": ""},
    {"catid": 154, "prodcode": 9369, "descr": ""},
    {"catid": 154, "prodcode": 9395, "descr": ""},
])

Serum_Albumin = np.array([
    {"catid": 157, "prodcode": 8000, "descr": ""},
    {"catid": 157, "prodcode": 8765, "descr": ""},
    {"catid": 157, "prodcode": 8766, "descr": ""},
])

Serum_Bilirubin_Total_and_Direct = np.array([
    {"catid": 156, "prodcode": 8490, "descr": ""},
    {"catid": 156, "prodcode": 8963, "descr": ""},
    {"catid": 156, "prodcode": 8966, "descr": ""},
    {"catid": 156, "prodcode": 9404, "descr": ""},
    {"catid": 156, "prodcode": 10765, "descr": ""},
    {"catid": 156, "prodcode": 10766, "descr": ""},
    {"catid": 156, "prodcode": 10767, "descr": ""},
    {"catid": 156, "prodcode": 10768, "descr": ""},
])

Serum_Calcium = np.array([
    {"catid": 148, "prodcode": 8057, "descr": ""},
])

Serum_Cholesterol = np.array([
    {"catid": 289, "prodcode": 9204, "descr": ""},
    {"catid": 289, "prodcode": 9230, "descr": ""},
    {"catid": 289, "prodcode": 9231, "descr": ""},
    {"catid": 289, "prodcode": 9232, "descr": ""},
])

Serum_Gamma_Glutamyl_Transferase = np.array([
    {"catid": 164, "prodcode": 9236, "descr": ""},
])

Serum_Inorganic_Phosphate = np.array([
    {"catid": 155, "prodcode": 7887, "descr": ""},
    {"catid": 155, "prodcode": 7980, "descr": ""},
    {"catid": 155, "prodcode": 7981, "descr": ""},
    {"catid": 155, "prodcode": 7982, "descr": ""},
    {"catid": 155, "prodcode": 7983, "descr": ""},
    {"catid": 155, "prodcode": 9560, "descr": ""},
    {"catid": 155, "prodcode": 9561, "descr": ""},
])

Serum_Lithium = np.array([
    {"catid": 160, "prodcode": 9281, "descr": ""},
    {"catid": 160, "prodcode": 9282, "descr": ""},
    {"catid": 160, "prodcode": 9283, "descr": ""},
    {"catid": 160, "prodcode": 9284, "descr": ""},
    {"catid": 160, "prodcode": 9285, "descr": ""},
])

Serum_Potasium = np.array([
    {"catid": 159, "prodcode": 9181, "descr": ""},
])

Sigmoidoscopy = np.array([
    {"catid": 101, "prodcode": 8894, "descr": ""},
    {"catid": 101, "prodcode": 8895, "descr": ""},
    {"catid": 101, "prodcode": 8896, "descr": ""},
    {"catid": 101, "prodcode": 8897, "descr": ""},
    {"catid": 101, "prodcode": 10772, "descr": ""},
])

Sinus_X_rays = np.array([
    {"catid": 130, "prodcode": 8399, "descr": ""},
    {"catid": 130, "prodcode": 9710, "descr": ""},
    {"catid": 130, "prodcode": 10666, "descr": ""},
])

Skin_Scraping_for_Fungi = np.array([
    {"catid": 229, "prodcode": 8813, "descr": ""},
    {"catid": 229, "prodcode": 8825, "descr": ""},
    {"catid": 229, "prodcode": 8826, "descr": ""},
    {"catid": 229, "prodcode": 8834, "descr": ""},
    {"catid": 229, "prodcode": 9418, "descr": ""},
    {"catid": 229, "prodcode": 9432, "descr": ""},
    {"catid": 229, "prodcode": 9433, "descr": ""},
])

Skin_Snip_for_Microfilaria = np.array([
    {"catid": 228, "prodcode": 8788, "descr": ""},
])

Skull_X_rays = np.array([
    {"catid": 133, "prodcode": 8398, "descr": ""},
    {"catid": 133, "prodcode": 8399, "descr": ""},
    {"catid": 133, "prodcode": 8579, "descr": ""},
])

Special_Care_baby_Unit = np.array([
    {"catid": 307, "prodcode": 8065, "descr": ""},
    {"catid": 307, "prodcode": 8066, "descr": ""},
    {"catid": 307, "prodcode": 8067, "descr": ""},
    {"catid": 307, "prodcode": 8147, "descr": ""},
    {"catid": 307, "prodcode": 8231, "descr": ""},
    {"catid": 307, "prodcode": 8232, "descr": ""},
    {"catid": 307, "prodcode": 9239, "descr": ""},
    {"catid": 307, "prodcode": 10163, "descr": ""},
    {"catid": 307, "prodcode": 10164, "descr": ""},
])

Specialist_Consultation = np.array([
    {"catid": 26, "prodcode": 8226, "descr": ""},
    {"catid": 26, "prodcode": 8227, "descr": ""},
    {"catid": 26, "prodcode": 8519, "descr": ""},
    {"catid": 26, "prodcode": 8520, "descr": ""},
])

Specialist_Opthalmologist_Consultation = np.array([
    {"catid": 181, "prodcode": 7965, "descr": ""},
    {"catid": 181, "prodcode": 7976, "descr": ""},
    {"catid": 181, "prodcode": 8068, "descr": ""},
    {"catid": 181, "prodcode": 8580, "descr": ""},
    {"catid": 181, "prodcode": 8806, "descr": ""},
])

Sputum_Acid_Fast_Bacilli_AFB_Test = np.array([
    {"catid": 336, "prodcode": 8199, "descr": ""},
    {"catid": 336, "prodcode": 8200, "descr": ""},
    {"catid": 336, "prodcode": 8201, "descr": ""},
    {"catid": 336, "prodcode": 8384, "descr": ""},
    {"catid": 336, "prodcode": 8773, "descr": ""},
    {"catid": 336, "prodcode": 8804, "descr": ""},
    {"catid": 336, "prodcode": 8805, "descr": ""},
    {"catid": 336, "prodcode": 8807, "descr": ""},
    {"catid": 336, "prodcode": 8808, "descr": ""},
    {"catid": 336, "prodcode": 9156, "descr": ""},
    {"catid": 336, "prodcode": 9242, "descr": ""},
    {"catid": 336, "prodcode": 9790, "descr": ""},
    {"catid": 336, "prodcode": 10108, "descr": ""},
])

Sputum_M_C_S = np.array([
    {"catid": 242, "prodcode": 8773, "descr": ""},
    {"catid": 242, "prodcode": 8809, "descr": ""},
    {"catid": 242, "prodcode": 8810, "descr": ""},
    {"catid": 242, "prodcode": 9156, "descr": ""},
    {"catid": 242, "prodcode": 9242, "descr": ""},
])

Standard_Room = np.array([
    {"catid": 340, "prodcode": 8364, "descr": ""},
    {"catid": 340, "prodcode": 10191, "descr": ""},
])

Stool_M_C_S = np.array([
    {"catid": 244, "prodcode": 8822, "descr": ""},
    {"catid": 244, "prodcode": 8823, "descr": ""},
])

Stool_Occult_Blood = np.array([
    {"catid": 249, "prodcode": 8827, "descr": ""},
    {"catid": 249, "prodcode": 8828, "descr": ""},
    {"catid": 249, "prodcode": 10772, "descr": ""},
])

Stress_Management = np.array([
    {"catid": 87, "prodcode": 8617, "descr": ""},
    {"catid": 87, "prodcode": 8618, "descr": ""},
])

Surgeries_All_Inclusive = np.array([
    {"catid": 46, "prodcode": 8084, "descr": ""},
    {"catid": 46, "prodcode": 8088, "descr": ""},
    {"catid": 46, "prodcode": 8094, "descr": ""},
    {"catid": 46, "prodcode": 8095, "descr": ""},
    {"catid": 46, "prodcode": 8096, "descr": ""},
    {"catid": 46, "prodcode": 8100, "descr": ""},
    {"catid": 46, "prodcode": 8101, "descr": ""},
    {"catid": 46, "prodcode": 8103, "descr": ""},
    {"catid": 46, "prodcode": 8105, "descr": ""},
    {"catid": 46, "prodcode": 8110, "descr": ""},
    {"catid": 46, "prodcode": 8111, "descr": ""},
    {"catid": 46, "prodcode": 8113, "descr": ""},
    {"catid": 46, "prodcode": 8114, "descr": ""},
    {"catid": 46, "prodcode": 8116, "descr": ""},
    {"catid": 46, "prodcode": 8117, "descr": ""},
    {"catid": 46, "prodcode": 8121, "descr": ""},
    {"catid": 46, "prodcode": 8122, "descr": ""},
    {"catid": 46, "prodcode": 8123, "descr": ""},
    {"catid": 46, "prodcode": 8124, "descr": ""},
    {"catid": 46, "prodcode": 8125, "descr": ""},
    {"catid": 46, "prodcode": 8126, "descr": ""},
    {"catid": 46, "prodcode": 8127, "descr": ""},
    {"catid": 46, "prodcode": 8128, "descr": ""},
    {"catid": 46, "prodcode": 8129, "descr": ""},
    {"catid": 46, "prodcode": 8130, "descr": ""},
    {"catid": 46, "prodcode": 8131, "descr": ""},
    {"catid": 46, "prodcode": 8132, "descr": ""},
    {"catid": 46, "prodcode": 8133, "descr": ""},
    {"catid": 46, "prodcode": 8134, "descr": ""},
    {"catid": 46, "prodcode": 8135, "descr": ""},
    {"catid": 46, "prodcode": 8141, "descr": ""},
    {"catid": 46, "prodcode": 8142, "descr": ""},
    {"catid": 46, "prodcode": 8144, "descr": ""},
    {"catid": 46, "prodcode": 8145, "descr": ""},
    {"catid": 46, "prodcode": 8146, "descr": ""},
    {"catid": 46, "prodcode": 8150, "descr": ""},
    {"catid": 46, "prodcode": 8151, "descr": ""},
    {"catid": 46, "prodcode": 8152, "descr": ""},
    {"catid": 46, "prodcode": 8153, "descr": ""},
    {"catid": 46, "prodcode": 8154, "descr": ""},
    {"catid": 46, "prodcode": 8155, "descr": ""},
    {"catid": 46, "prodcode": 8156, "descr": ""},
    {"catid": 46, "prodcode": 8159, "descr": ""},
    {"catid": 46, "prodcode": 8163, "descr": ""},
    {"catid": 46, "prodcode": 8164, "descr": ""},
    {"catid": 46, "prodcode": 8183, "descr": ""},
    {"catid": 46, "prodcode": 8184, "descr": ""},
    {"catid": 46, "prodcode": 8185, "descr": ""},
    {"catid": 46, "prodcode": 8186, "descr": ""},
    {"catid": 46, "prodcode": 8187, "descr": ""},
    {"catid": 46, "prodcode": 8191, "descr": ""},
    {"catid": 46, "prodcode": 8192, "descr": ""},
    {"catid": 46, "prodcode": 8194, "descr": ""},
    {"catid": 46, "prodcode": 8195, "descr": ""},
    {"catid": 46, "prodcode": 8196, "descr": ""},
    {"catid": 46, "prodcode": 8197, "descr": ""},
    {"catid": 46, "prodcode": 8202, "descr": ""},
    {"catid": 46, "prodcode": 8204, "descr": ""},
    {"catid": 46, "prodcode": 8205, "descr": ""},
    {"catid": 46, "prodcode": 8206, "descr": ""},
    {"catid": 46, "prodcode": 8207, "descr": ""},
    {"catid": 46, "prodcode": 8208, "descr": ""},
    {"catid": 46, "prodcode": 8209, "descr": ""},
    {"catid": 46, "prodcode": 8210, "descr": ""},
    {"catid": 46, "prodcode": 8211, "descr": ""},
    {"catid": 46, "prodcode": 8318, "descr": ""},
    {"catid": 46, "prodcode": 8373, "descr": ""},
    {"catid": 46, "prodcode": 8380, "descr": ""},
    {"catid": 46, "prodcode": 8381, "descr": ""},
    {"catid": 46, "prodcode": 8382, "descr": ""},
    {"catid": 46, "prodcode": 8383, "descr": ""},
    {"catid": 46, "prodcode": 8385, "descr": ""},
    {"catid": 46, "prodcode": 8386, "descr": ""},
    {"catid": 46, "prodcode": 8387, "descr": ""},
    {"catid": 46, "prodcode": 8390, "descr": ""},
    {"catid": 46, "prodcode": 8391, "descr": ""},
    {"catid": 46, "prodcode": 8392, "descr": ""},
    {"catid": 46, "prodcode": 8393, "descr": ""},
    {"catid": 46, "prodcode": 8395, "descr": ""},
    {"catid": 46, "prodcode": 8396, "descr": ""},
    {"catid": 46, "prodcode": 8397, "descr": ""},
    {"catid": 46, "prodcode": 8401, "descr": ""},
    {"catid": 46, "prodcode": 8402, "descr": ""},
    {"catid": 46, "prodcode": 8403, "descr": ""},
    {"catid": 46, "prodcode": 8404, "descr": ""},
    {"catid": 46, "prodcode": 8405, "descr": ""},
    {"catid": 46, "prodcode": 8407, "descr": ""},
    {"catid": 46, "prodcode": 8408, "descr": ""},
    {"catid": 46, "prodcode": 8409, "descr": ""},
    {"catid": 46, "prodcode": 8411, "descr": ""},
    {"catid": 46, "prodcode": 8412, "descr": ""},
    {"catid": 46, "prodcode": 8413, "descr": ""},
    {"catid": 46, "prodcode": 8414, "descr": ""},
    {"catid": 46, "prodcode": 8415, "descr": ""},
    {"catid": 46, "prodcode": 8416, "descr": ""},
    {"catid": 46, "prodcode": 8419, "descr": ""},
    {"catid": 46, "prodcode": 8420, "descr": ""},
    {"catid": 46, "prodcode": 8421, "descr": ""},
    {"catid": 46, "prodcode": 8423, "descr": ""},
    {"catid": 46, "prodcode": 8424, "descr": ""},
    {"catid": 46, "prodcode": 8425, "descr": ""},
    {"catid": 46, "prodcode": 8426, "descr": ""},
    {"catid": 46, "prodcode": 8427, "descr": ""},
    {"catid": 46, "prodcode": 8428, "descr": ""},
    {"catid": 46, "prodcode": 8429, "descr": ""},
    {"catid": 46, "prodcode": 8431, "descr": ""},
    {"catid": 46, "prodcode": 8432, "descr": ""},
    {"catid": 46, "prodcode": 8434, "descr": ""},
    {"catid": 46, "prodcode": 8438, "descr": ""},
    {"catid": 46, "prodcode": 8439, "descr": ""},
    {"catid": 46, "prodcode": 8440, "descr": ""},
    {"catid": 46, "prodcode": 8441, "descr": ""},
    {"catid": 46, "prodcode": 8442, "descr": ""},
    {"catid": 46, "prodcode": 8443, "descr": ""},
    {"catid": 46, "prodcode": 8444, "descr": ""},
    {"catid": 46, "prodcode": 8445, "descr": ""},
    {"catid": 46, "prodcode": 8446, "descr": ""},
    {"catid": 46, "prodcode": 8450, "descr": ""},
    {"catid": 46, "prodcode": 8451, "descr": ""},
    {"catid": 46, "prodcode": 8453, "descr": ""},
    {"catid": 46, "prodcode": 8454, "descr": ""},
    {"catid": 46, "prodcode": 8455, "descr": ""},
    {"catid": 46, "prodcode": 8456, "descr": ""},
    {"catid": 46, "prodcode": 8457, "descr": ""},
    {"catid": 46, "prodcode": 8458, "descr": ""},
    {"catid": 46, "prodcode": 8459, "descr": ""},
    {"catid": 46, "prodcode": 8461, "descr": ""},
    {"catid": 46, "prodcode": 8463, "descr": ""},
    {"catid": 46, "prodcode": 8464, "descr": ""},
    {"catid": 46, "prodcode": 8465, "descr": ""},
    {"catid": 46, "prodcode": 8466, "descr": ""},
    {"catid": 46, "prodcode": 8467, "descr": ""},
    {"catid": 46, "prodcode": 8468, "descr": ""},
    {"catid": 46, "prodcode": 8469, "descr": ""},
    {"catid": 46, "prodcode": 8470, "descr": ""},
    {"catid": 46, "prodcode": 8471, "descr": ""},
    {"catid": 46, "prodcode": 8472, "descr": ""},
    {"catid": 46, "prodcode": 8475, "descr": ""},
    {"catid": 46, "prodcode": 8476, "descr": ""},
    {"catid": 46, "prodcode": 8477, "descr": ""},
    {"catid": 46, "prodcode": 8478, "descr": ""},
    {"catid": 46, "prodcode": 8479, "descr": ""},
    {"catid": 46, "prodcode": 8480, "descr": ""},
    {"catid": 46, "prodcode": 8482, "descr": ""},
    {"catid": 46, "prodcode": 8492, "descr": ""},
    {"catid": 46, "prodcode": 8493, "descr": ""},
    {"catid": 46, "prodcode": 8498, "descr": ""},
    {"catid": 46, "prodcode": 8501, "descr": ""},
    {"catid": 46, "prodcode": 8504, "descr": ""},
    {"catid": 46, "prodcode": 8505, "descr": ""},
    {"catid": 46, "prodcode": 8506, "descr": ""},
    {"catid": 46, "prodcode": 8507, "descr": ""},
    {"catid": 46, "prodcode": 8508, "descr": ""},
    {"catid": 46, "prodcode": 8509, "descr": ""},
    {"catid": 46, "prodcode": 8537, "descr": ""},
    {"catid": 46, "prodcode": 8538, "descr": ""},
    {"catid": 46, "prodcode": 8539, "descr": ""},
    {"catid": 46, "prodcode": 8540, "descr": ""},
    {"catid": 46, "prodcode": 8541, "descr": ""},
    {"catid": 46, "prodcode": 8619, "descr": ""},
    {"catid": 46, "prodcode": 8843, "descr": ""},
    {"catid": 46, "prodcode": 8850, "descr": ""},
    {"catid": 46, "prodcode": 8851, "descr": ""},
    {"catid": 46, "prodcode": 8852, "descr": ""},
    {"catid": 46, "prodcode": 8869, "descr": ""},
    {"catid": 46, "prodcode": 8872, "descr": ""},
    {"catid": 46, "prodcode": 8874, "descr": ""},
    {"catid": 46, "prodcode": 8884, "descr": ""},
    {"catid": 46, "prodcode": 8885, "descr": ""},
    {"catid": 46, "prodcode": 8886, "descr": ""},
    {"catid": 46, "prodcode": 8887, "descr": ""},
    {"catid": 46, "prodcode": 8888, "descr": ""},
    {"catid": 46, "prodcode": 8892, "descr": ""},
    {"catid": 46, "prodcode": 8893, "descr": ""},
    {"catid": 46, "prodcode": 8900, "descr": ""},
    {"catid": 46, "prodcode": 8906, "descr": ""},
    {"catid": 46, "prodcode": 8907, "descr": ""},
    {"catid": 46, "prodcode": 8909, "descr": ""},
    {"catid": 46, "prodcode": 8910, "descr": ""},
    {"catid": 46, "prodcode": 8911, "descr": ""},
    {"catid": 46, "prodcode": 8912, "descr": ""},
    {"catid": 46, "prodcode": 8913, "descr": ""},
    {"catid": 46, "prodcode": 8919, "descr": ""},
    {"catid": 46, "prodcode": 8921, "descr": ""},
    {"catid": 46, "prodcode": 8922, "descr": ""},
    {"catid": 46, "prodcode": 8923, "descr": ""},
    {"catid": 46, "prodcode": 8924, "descr": ""},
    {"catid": 46, "prodcode": 8925, "descr": ""},
    {"catid": 46, "prodcode": 8926, "descr": ""},
    {"catid": 46, "prodcode": 8927, "descr": ""},
    {"catid": 46, "prodcode": 8928, "descr": ""},
    {"catid": 46, "prodcode": 8930, "descr": ""},
    {"catid": 46, "prodcode": 8931, "descr": ""},
    {"catid": 46, "prodcode": 8932, "descr": ""},
    {"catid": 46, "prodcode": 8933, "descr": ""},
    {"catid": 46, "prodcode": 8934, "descr": ""},
    {"catid": 46, "prodcode": 8935, "descr": ""},
    {"catid": 46, "prodcode": 8936, "descr": ""},
    {"catid": 46, "prodcode": 8938, "descr": ""},
    {"catid": 46, "prodcode": 8939, "descr": ""},
    {"catid": 46, "prodcode": 8943, "descr": ""},
    {"catid": 46, "prodcode": 8946, "descr": ""},
    {"catid": 46, "prodcode": 8947, "descr": ""},
    {"catid": 46, "prodcode": 8948, "descr": ""},
    {"catid": 46, "prodcode": 8949, "descr": ""},
    {"catid": 46, "prodcode": 8950, "descr": ""},
    {"catid": 46, "prodcode": 8951, "descr": ""},
    {"catid": 46, "prodcode": 8952, "descr": ""},
    {"catid": 46, "prodcode": 8953, "descr": ""},
    {"catid": 46, "prodcode": 8954, "descr": ""},
    {"catid": 46, "prodcode": 8955, "descr": ""},
    {"catid": 46, "prodcode": 8956, "descr": ""},
    {"catid": 46, "prodcode": 8957, "descr": ""},
    {"catid": 46, "prodcode": 8958, "descr": ""},
    {"catid": 46, "prodcode": 8959, "descr": ""},
    {"catid": 46, "prodcode": 8960, "descr": ""},
    {"catid": 46, "prodcode": 8961, "descr": ""},
    {"catid": 46, "prodcode": 8962, "descr": ""},
    {"catid": 46, "prodcode": 8963, "descr": ""},
    {"catid": 46, "prodcode": 8964, "descr": ""},
    {"catid": 46, "prodcode": 8965, "descr": ""},
    {"catid": 46, "prodcode": 8966, "descr": ""},
    {"catid": 46, "prodcode": 8967, "descr": ""},
    {"catid": 46, "prodcode": 8968, "descr": ""},
    {"catid": 46, "prodcode": 8969, "descr": ""},
    {"catid": 46, "prodcode": 8970, "descr": ""},
    {"catid": 46, "prodcode": 8971, "descr": ""},
    {"catid": 46, "prodcode": 8972, "descr": ""},
    {"catid": 46, "prodcode": 8973, "descr": ""},
    {"catid": 46, "prodcode": 8974, "descr": ""},
    {"catid": 46, "prodcode": 8975, "descr": ""},
    {"catid": 46, "prodcode": 8976, "descr": ""},
    {"catid": 46, "prodcode": 8977, "descr": ""},
    {"catid": 46, "prodcode": 8978, "descr": ""},
    {"catid": 46, "prodcode": 8979, "descr": ""},
    {"catid": 46, "prodcode": 8980, "descr": ""},
    {"catid": 46, "prodcode": 8981, "descr": ""},
    {"catid": 46, "prodcode": 8982, "descr": ""},
    {"catid": 46, "prodcode": 8983, "descr": ""},
    {"catid": 46, "prodcode": 8984, "descr": ""},
    {"catid": 46, "prodcode": 8985, "descr": ""},
    {"catid": 46, "prodcode": 8986, "descr": ""},
    {"catid": 46, "prodcode": 8987, "descr": ""},
    {"catid": 46, "prodcode": 8988, "descr": ""},
    {"catid": 46, "prodcode": 8989, "descr": ""},
    {"catid": 46, "prodcode": 8990, "descr": ""},
    {"catid": 46, "prodcode": 9148, "descr": ""},
    {"catid": 46, "prodcode": 9252, "descr": ""},
    {"catid": 46, "prodcode": 9253, "descr": ""},
    {"catid": 46, "prodcode": 9254, "descr": ""},
    {"catid": 46, "prodcode": 9255, "descr": ""},
    {"catid": 46, "prodcode": 9256, "descr": ""},
    {"catid": 46, "prodcode": 9257, "descr": ""},
    {"catid": 46, "prodcode": 9262, "descr": ""},
    {"catid": 46, "prodcode": 9263, "descr": ""},
    {"catid": 46, "prodcode": 9264, "descr": ""},
    {"catid": 46, "prodcode": 9265, "descr": ""},
    {"catid": 46, "prodcode": 9266, "descr": ""},
    {"catid": 46, "prodcode": 9267, "descr": ""},
    {"catid": 46, "prodcode": 9268, "descr": ""},
    {"catid": 46, "prodcode": 9271, "descr": ""},
    {"catid": 46, "prodcode": 9272, "descr": ""},
    {"catid": 46, "prodcode": 9273, "descr": ""},
    {"catid": 46, "prodcode": 9274, "descr": ""},
    {"catid": 46, "prodcode": 9275, "descr": ""},
    {"catid": 46, "prodcode": 9276, "descr": ""},
    {"catid": 46, "prodcode": 9277, "descr": ""},
    {"catid": 46, "prodcode": 9278, "descr": ""},
    {"catid": 46, "prodcode": 9279, "descr": ""},
    {"catid": 46, "prodcode": 9280, "descr": ""},
    {"catid": 46, "prodcode": 9286, "descr": ""},
    {"catid": 46, "prodcode": 9288, "descr": ""},
    {"catid": 46, "prodcode": 9289, "descr": ""},
    {"catid": 46, "prodcode": 9290, "descr": ""},
    {"catid": 46, "prodcode": 9291, "descr": ""},
    {"catid": 46, "prodcode": 9292, "descr": ""},
    {"catid": 46, "prodcode": 9293, "descr": ""},
    {"catid": 46, "prodcode": 9294, "descr": ""},
    {"catid": 46, "prodcode": 9296, "descr": ""},
    {"catid": 46, "prodcode": 9298, "descr": ""},
    {"catid": 46, "prodcode": 9299, "descr": ""},
    {"catid": 46, "prodcode": 9301, "descr": ""},
    {"catid": 46, "prodcode": 9302, "descr": ""},
    {"catid": 46, "prodcode": 9303, "descr": ""},
    {"catid": 46, "prodcode": 9304, "descr": ""},
    {"catid": 46, "prodcode": 9305, "descr": ""},
    {"catid": 46, "prodcode": 9309, "descr": ""},
    {"catid": 46, "prodcode": 9310, "descr": ""},
    {"catid": 46, "prodcode": 9315, "descr": ""},
    {"catid": 46, "prodcode": 9316, "descr": ""},
    {"catid": 46, "prodcode": 9317, "descr": ""},
    {"catid": 46, "prodcode": 9318, "descr": ""},
    {"catid": 46, "prodcode": 9321, "descr": ""},
    {"catid": 46, "prodcode": 9322, "descr": ""},
    {"catid": 46, "prodcode": 9324, "descr": ""},
    {"catid": 46, "prodcode": 9325, "descr": ""},
    {"catid": 46, "prodcode": 9326, "descr": ""},
    {"catid": 46, "prodcode": 9329, "descr": ""},
    {"catid": 46, "prodcode": 9331, "descr": ""},
    {"catid": 46, "prodcode": 9332, "descr": ""},
    {"catid": 46, "prodcode": 9333, "descr": ""},
    {"catid": 46, "prodcode": 9334, "descr": ""},
    {"catid": 46, "prodcode": 9336, "descr": ""},
    {"catid": 46, "prodcode": 9337, "descr": ""},
    {"catid": 46, "prodcode": 9339, "descr": ""},
    {"catid": 46, "prodcode": 9341, "descr": ""},
    {"catid": 46, "prodcode": 9342, "descr": ""},
    {"catid": 46, "prodcode": 9345, "descr": ""},
    {"catid": 46, "prodcode": 9349, "descr": ""},
    {"catid": 46, "prodcode": 9350, "descr": ""},
    {"catid": 46, "prodcode": 9351, "descr": ""},
    {"catid": 46, "prodcode": 9354, "descr": ""},
    {"catid": 46, "prodcode": 9355, "descr": ""},
    {"catid": 46, "prodcode": 9356, "descr": ""},
    {"catid": 46, "prodcode": 9357, "descr": ""},
    {"catid": 46, "prodcode": 9358, "descr": ""},
    {"catid": 46, "prodcode": 9442, "descr": ""},
    {"catid": 46, "prodcode": 9448, "descr": ""},
    {"catid": 46, "prodcode": 9449, "descr": ""},
    {"catid": 46, "prodcode": 9453, "descr": ""},
    {"catid": 46, "prodcode": 9454, "descr": ""},
    {"catid": 46, "prodcode": 9455, "descr": ""},
    {"catid": 46, "prodcode": 9457, "descr": ""},
    {"catid": 46, "prodcode": 9458, "descr": ""},
    {"catid": 46, "prodcode": 9459, "descr": ""},
    {"catid": 46, "prodcode": 9460, "descr": ""},
    {"catid": 46, "prodcode": 9461, "descr": ""},
    {"catid": 46, "prodcode": 9462, "descr": ""},
    {"catid": 46, "prodcode": 9463, "descr": ""},
    {"catid": 46, "prodcode": 9464, "descr": ""},
    {"catid": 46, "prodcode": 9466, "descr": ""},
    {"catid": 46, "prodcode": 9468, "descr": ""},
    {"catid": 46, "prodcode": 9469, "descr": ""},
    {"catid": 46, "prodcode": 9470, "descr": ""},
    {"catid": 46, "prodcode": 9471, "descr": ""},
    {"catid": 46, "prodcode": 9472, "descr": ""},
    {"catid": 46, "prodcode": 9473, "descr": ""},
    {"catid": 46, "prodcode": 9474, "descr": ""},
    {"catid": 46, "prodcode": 9476, "descr": ""},
    {"catid": 46, "prodcode": 9477, "descr": ""},
    {"catid": 46, "prodcode": 9478, "descr": ""},
    {"catid": 46, "prodcode": 9479, "descr": ""},
    {"catid": 46, "prodcode": 9481, "descr": ""},
    {"catid": 46, "prodcode": 9482, "descr": ""},
    {"catid": 46, "prodcode": 9609, "descr": ""},
    {"catid": 46, "prodcode": 9611, "descr": ""},
    {"catid": 46, "prodcode": 9612, "descr": ""},
    {"catid": 46, "prodcode": 9613, "descr": ""},
    {"catid": 46, "prodcode": 9614, "descr": ""},
    {"catid": 46, "prodcode": 9615, "descr": ""},
    {"catid": 46, "prodcode": 9616, "descr": ""},
    {"catid": 46, "prodcode": 9617, "descr": ""},
    {"catid": 46, "prodcode": 9618, "descr": ""},
    {"catid": 46, "prodcode": 9619, "descr": ""},
    {"catid": 46, "prodcode": 9620, "descr": ""},
    {"catid": 46, "prodcode": 9621, "descr": ""},
    {"catid": 46, "prodcode": 9622, "descr": ""},
    {"catid": 46, "prodcode": 9624, "descr": ""},
    {"catid": 46, "prodcode": 9626, "descr": ""},
    {"catid": 46, "prodcode": 9627, "descr": ""},
    {"catid": 46, "prodcode": 9628, "descr": ""},
    {"catid": 46, "prodcode": 9629, "descr": ""},
    {"catid": 46, "prodcode": 9630, "descr": ""},
    {"catid": 46, "prodcode": 9631, "descr": ""},
    {"catid": 46, "prodcode": 9632, "descr": ""},
    {"catid": 46, "prodcode": 9633, "descr": ""},
    {"catid": 46, "prodcode": 9635, "descr": ""},
    {"catid": 46, "prodcode": 9678, "descr": ""},
    {"catid": 46, "prodcode": 9679, "descr": ""},
    {"catid": 46, "prodcode": 9681, "descr": ""},
    {"catid": 46, "prodcode": 9682, "descr": ""},
    {"catid": 46, "prodcode": 9683, "descr": ""},
    {"catid": 46, "prodcode": 9744, "descr": ""},
    {"catid": 46, "prodcode": 9745, "descr": ""},
    {"catid": 46, "prodcode": 10120, "descr": ""},
    {"catid": 46, "prodcode": 10185, "descr": ""},
    {"catid": 46, "prodcode": 10188, "descr": ""},
    {"catid": 46, "prodcode": 10192, "descr": ""},
    {"catid": 46, "prodcode": 10193, "descr": ""},
    {"catid": 46, "prodcode": 10195, "descr": ""},
    {"catid": 46, "prodcode": 10198, "descr": ""},
    {"catid": 46, "prodcode": 10199, "descr": ""},
    {"catid": 46, "prodcode": 10200, "descr": ""},
    {"catid": 46, "prodcode": 10201, "descr": ""},
    {"catid": 46, "prodcode": 10202, "descr": ""},
    {"catid": 46, "prodcode": 10203, "descr": ""},
    {"catid": 46, "prodcode": 10204, "descr": ""},
    {"catid": 46, "prodcode": 10205, "descr": ""},
    {"catid": 46, "prodcode": 10206, "descr": ""},
    {"catid": 46, "prodcode": 10207, "descr": ""},
    {"catid": 46, "prodcode": 10209, "descr": ""},
    {"catid": 46, "prodcode": 10210, "descr": ""},
    {"catid": 46, "prodcode": 10620, "descr": ""},
    {"catid": 46, "prodcode": 10621, "descr": ""},
    {"catid": 46, "prodcode": 10622, "descr": ""},
    {"catid": 46, "prodcode": 10623, "descr": ""},
    {"catid": 46, "prodcode": 10624, "descr": ""},
    {"catid": 46, "prodcode": 10625, "descr": ""},
    {"catid": 46, "prodcode": 10628, "descr": ""},
    {"catid": 46, "prodcode": 10629, "descr": ""},
    {"catid": 46, "prodcode": 10630, "descr": ""},
    {"catid": 46, "prodcode": 10631, "descr": ""},
    {"catid": 46, "prodcode": 10632, "descr": ""},
    {"catid": 46, "prodcode": 10636, "descr": ""},
    {"catid": 46, "prodcode": 10642, "descr": ""},
    {"catid": 46, "prodcode": 10748, "descr": ""},
])

Surgical_Cancer_Care = np.array([
    {"catid": 141, "prodcode": 8106, "descr": ""},
    {"catid": 141, "prodcode": 8107, "descr": ""},
    {"catid": 141, "prodcode": 8108, "descr": ""},
    {"catid": 141, "prodcode": 8109, "descr": ""},
    {"catid": 141, "prodcode": 8200, "descr": ""},
    {"catid": 141, "prodcode": 8374, "descr": ""},
    {"catid": 141, "prodcode": 8375, "descr": ""},
    {"catid": 141, "prodcode": 8376, "descr": ""},
    {"catid": 141, "prodcode": 8377, "descr": ""},
    {"catid": 141, "prodcode": 8378, "descr": ""},
    {"catid": 141, "prodcode": 8379, "descr": ""},
    {"catid": 141, "prodcode": 8389, "descr": ""},
    {"catid": 141, "prodcode": 8445, "descr": ""},
    {"catid": 141, "prodcode": 8487, "descr": ""},
    {"catid": 141, "prodcode": 8488, "descr": ""},
    {"catid": 141, "prodcode": 8489, "descr": ""},
    {"catid": 141, "prodcode": 8490, "descr": ""},
    {"catid": 141, "prodcode": 8491, "descr": ""},
    {"catid": 141, "prodcode": 8883, "descr": ""},
    {"catid": 141, "prodcode": 8901, "descr": ""},
    {"catid": 141, "prodcode": 8902, "descr": ""},
    {"catid": 141, "prodcode": 8903, "descr": ""},
    {"catid": 141, "prodcode": 8904, "descr": ""},
    {"catid": 141, "prodcode": 8905, "descr": ""},
    {"catid": 141, "prodcode": 8918, "descr": ""},
    {"catid": 141, "prodcode": 8966, "descr": ""},
    {"catid": 141, "prodcode": 9297, "descr": ""},
    {"catid": 141, "prodcode": 9319, "descr": ""},
    {"catid": 141, "prodcode": 9323, "descr": ""},
    {"catid": 141, "prodcode": 9346, "descr": ""},
    {"catid": 141, "prodcode": 9347, "descr": ""},
    {"catid": 141, "prodcode": 10627, "descr": ""},
])

Surgical_extraction = np.array([
    {"catid": 172, "prodcode": 8537, "descr": ""},
    {"catid": 172, "prodcode": 8538, "descr": ""},
    {"catid": 172, "prodcode": 8539, "descr": ""},
    {"catid": 172, "prodcode": 8540, "descr": ""},
    {"catid": 172, "prodcode": 8541, "descr": ""},
])

Syphilis_Screening = np.array([
    {"catid": 320, "prodcode": 8518, "descr": ""},
    {"catid": 320, "prodcode": 10626, "descr": ""},
])

# =============================================================================
# SUMMARY — S.py
# =============================================================================
# Categories in this file : 41
# Total product entries    : 599
#
# Breakdown by category:
#   Scaling_and_Polishing (catid=168): 8 products
#   Seeking_Second_Opinion (catid=52): 30 products
#   Semen_M_C_S (catid=322): 3 products
#   Semi_Private_Room (catid=341): 3 products
#   Seminal_Fluid_Analysis_SFA (catid=332): 3 products
#   Serum_Acid_Phosphate (catid=154): 13 products
#   Serum_Albumin (catid=157): 3 products
#   Serum_Alkaline_Phosphate (catid=153): (no products — variable omitted)
#   Serum_Bicarbonate (catid=162): (no products — variable omitted)
#   Serum_Bilirubin_Total_and_Direct (catid=156): 8 products
#   Serum_Calcium (catid=148): 1 products
#   Serum_Chloride (catid=161): (no products — variable omitted)
#   Serum_Cholesterol (catid=289): 4 products
#   Serum_Gamma_Glutamyl_Transferase (catid=164): 1 products
#   Serum_Inorganic_Phosphate (catid=155): 7 products
#   Serum_Iron (catid=323): (no products — variable omitted)
#   Serum_Lactate_Dehydrogenase (catid=163): (no products — variable omitted)
#   Serum_Lithium (catid=160): 5 products
#   Serum_Magnesium (catid=158): (no products — variable omitted)
#   Serum_Potasium (catid=159): 1 products
#   Serum_Sodium (catid=145): (no products — variable omitted)
#   Serum_Uric_Acid (catid=315): (no products — variable omitted)
#   Sigmoidoscopy (catid=101): 5 products
#   Sinus_X_rays (catid=130): 3 products
#   Skin_Scraping_for_Fungi (catid=229): 7 products
#   Skin_Snip_for_Microfilaria (catid=228): 1 products
#   Skull_X_rays (catid=133): 3 products
#   Special_Care_baby_Unit (catid=307): 9 products
#   Specialist_Consultation (catid=26): 4 products
#   Specialist_Drug_Therapy (catid=211): (no products — variable omitted)
#   Specialist_Opthalmologist_Consultation (catid=181): 5 products
#   Sputum_Acid_Fast_Bacilli_AFB_Test (catid=336): 13 products
#   Sputum_M_C_S (catid=242): 5 products
#   Standard_Room (catid=340): 2 products
#   Stool_M_C_S (catid=244): 2 products
#   Stool_Occult_Blood (catid=249): 3 products
#   Stress_Management (catid=87): 2 products
#   Surgeries_All_Inclusive (catid=46): 406 products
#   Surgical_Cancer_Care (catid=141): 32 products
#   Surgical_extraction (catid=172): 5 products
#   Syphilis_Screening (catid=320): 2 products
# =============================================================================
