import numpy as np

# =============================================================================
# T.py
# Service category product assignments — letter T
# Generated by: product-service-mapper skill
# =============================================================================

Therapeutic_Abortion_Manual_Vacuum_Aspiration = np.array([
    {"catid": 255, "prodcode": 8007, "descr": ""},
    {"catid": 255, "prodcode": 8008, "descr": ""},
    {"catid": 255, "prodcode": 8009, "descr": ""},
    {"catid": 255, "prodcode": 8010, "descr": ""},
    {"catid": 255, "prodcode": 8011, "descr": ""},
    {"catid": 255, "prodcode": 8318, "descr": ""},
    {"catid": 255, "prodcode": 8873, "descr": ""},
    {"catid": 255, "prodcode": 9480, "descr": ""},
    {"catid": 255, "prodcode": 10642, "descr": ""},
    {"catid": 255, "prodcode": 10760, "descr": ""},
])

Thoracic_Inlet_X_rays = np.array([
    {"catid": 125, "prodcode": 8181, "descr": ""},
    {"catid": 125, "prodcode": 8182, "descr": ""},
    {"catid": 125, "prodcode": 8433, "descr": ""},
    {"catid": 125, "prodcode": 9009, "descr": ""},
    {"catid": 125, "prodcode": 9010, "descr": ""},
    {"catid": 125, "prodcode": 9011, "descr": ""},
    {"catid": 125, "prodcode": 9012, "descr": ""},
    {"catid": 125, "prodcode": 9013, "descr": ""},
    {"catid": 125, "prodcode": 9014, "descr": ""},
    {"catid": 125, "prodcode": 9287, "descr": ""},
    {"catid": 125, "prodcode": 9694, "descr": ""},
    {"catid": 125, "prodcode": 9716, "descr": ""},
    {"catid": 125, "prodcode": 9717, "descr": ""},
    {"catid": 125, "prodcode": 9718, "descr": ""},
])

Thoraco_Lumbar_X_rays = np.array([
    {"catid": 126, "prodcode": 8181, "descr": ""},
    {"catid": 126, "prodcode": 8182, "descr": ""},
    {"catid": 126, "prodcode": 8433, "descr": ""},
    {"catid": 126, "prodcode": 8548, "descr": ""},
    {"catid": 126, "prodcode": 8929, "descr": ""},
    {"catid": 126, "prodcode": 9009, "descr": ""},
    {"catid": 126, "prodcode": 9010, "descr": ""},
    {"catid": 126, "prodcode": 9011, "descr": ""},
    {"catid": 126, "prodcode": 9012, "descr": ""},
    {"catid": 126, "prodcode": 9013, "descr": ""},
    {"catid": 126, "prodcode": 9014, "descr": ""},
    {"catid": 126, "prodcode": 9015, "descr": ""},
    {"catid": 126, "prodcode": 9020, "descr": ""},
    {"catid": 126, "prodcode": 9287, "descr": ""},
    {"catid": 126, "prodcode": 9716, "descr": ""},
    {"catid": 126, "prodcode": 9717, "descr": ""},
    {"catid": 126, "prodcode": 9718, "descr": ""},
])

Thoracoscopy = np.array([
    {"catid": 112, "prodcode": 7965, "descr": ""},
    {"catid": 112, "prodcode": 7976, "descr": ""},
    {"catid": 112, "prodcode": 8068, "descr": ""},
    {"catid": 112, "prodcode": 8114, "descr": ""},
    {"catid": 112, "prodcode": 8115, "descr": ""},
    {"catid": 112, "prodcode": 8119, "descr": ""},
    {"catid": 112, "prodcode": 8120, "descr": ""},
    {"catid": 112, "prodcode": 8149, "descr": ""},
    {"catid": 112, "prodcode": 8318, "descr": ""},
    {"catid": 112, "prodcode": 8495, "descr": ""},
    {"catid": 112, "prodcode": 8496, "descr": ""},
    {"catid": 112, "prodcode": 8580, "descr": ""},
    {"catid": 112, "prodcode": 8806, "descr": ""},
    {"catid": 112, "prodcode": 8969, "descr": ""},
    {"catid": 112, "prodcode": 8970, "descr": ""},
    {"catid": 112, "prodcode": 8971, "descr": ""},
    {"catid": 112, "prodcode": 10642, "descr": ""},
])

Throat_Swab_M_C_S = np.array([
    {"catid": 238, "prodcode": 9167, "descr": ""},
])

Thyroid_Function_Tests = np.array([
    {"catid": 314, "prodcode": 7987, "descr": ""},
    {"catid": 314, "prodcode": 9176, "descr": ""},
    {"catid": 314, "prodcode": 9177, "descr": ""},
    {"catid": 314, "prodcode": 9178, "descr": ""},
    {"catid": 314, "prodcode": 9179, "descr": ""},
    {"catid": 314, "prodcode": 9180, "descr": ""},
    {"catid": 314, "prodcode": 9181, "descr": ""},
    {"catid": 314, "prodcode": 9182, "descr": ""},
    {"catid": 314, "prodcode": 9189, "descr": ""},
    {"catid": 314, "prodcode": 9239, "descr": ""},
    {"catid": 314, "prodcode": 9240, "descr": ""},
    {"catid": 314, "prodcode": 9241, "descr": ""},
])

Toxoplasma_Screening = np.array([
    {"catid": 232, "prodcode": 8007, "descr": ""},
    {"catid": 232, "prodcode": 8008, "descr": ""},
    {"catid": 232, "prodcode": 8009, "descr": ""},
    {"catid": 232, "prodcode": 8010, "descr": ""},
    {"catid": 232, "prodcode": 8011, "descr": ""},
    {"catid": 232, "prodcode": 8340, "descr": ""},
    {"catid": 232, "prodcode": 8748, "descr": ""},
    {"catid": 232, "prodcode": 8790, "descr": ""},
    {"catid": 232, "prodcode": 8814, "descr": ""},
    {"catid": 232, "prodcode": 8815, "descr": ""},
    {"catid": 232, "prodcode": 8873, "descr": ""},
    {"catid": 232, "prodcode": 9171, "descr": ""},
    {"catid": 232, "prodcode": 9174, "descr": ""},
    {"catid": 232, "prodcode": 9184, "descr": ""},
    {"catid": 232, "prodcode": 9187, "descr": ""},
    {"catid": 232, "prodcode": 9194, "descr": ""},
    {"catid": 232, "prodcode": 9220, "descr": ""},
    {"catid": 232, "prodcode": 9221, "descr": ""},
    {"catid": 232, "prodcode": 9222, "descr": ""},
    {"catid": 232, "prodcode": 9223, "descr": ""},
    {"catid": 232, "prodcode": 9229, "descr": ""},
    {"catid": 232, "prodcode": 9241, "descr": ""},
    {"catid": 232, "prodcode": 10126, "descr": ""},
    {"catid": 232, "prodcode": 10151, "descr": ""},
    {"catid": 232, "prodcode": 10152, "descr": ""},
    {"catid": 232, "prodcode": 10760, "descr": ""},
])

Treatment_of_basic_outpatient_and_in_patient_cases = np.array([
    {"catid": 58, "prodcode": 8164, "descr": ""},
    {"catid": 58, "prodcode": 8385, "descr": ""},
    {"catid": 58, "prodcode": 8424, "descr": ""},
    {"catid": 58, "prodcode": 8438, "descr": ""},
    {"catid": 58, "prodcode": 8537, "descr": ""},
    {"catid": 58, "prodcode": 8538, "descr": ""},
    {"catid": 58, "prodcode": 8539, "descr": ""},
    {"catid": 58, "prodcode": 8540, "descr": ""},
    {"catid": 58, "prodcode": 8541, "descr": ""},
    {"catid": 58, "prodcode": 8619, "descr": ""},
    {"catid": 58, "prodcode": 8850, "descr": ""},
    {"catid": 58, "prodcode": 8851, "descr": ""},
    {"catid": 58, "prodcode": 8852, "descr": ""},
    {"catid": 58, "prodcode": 8968, "descr": ""},
    {"catid": 58, "prodcode": 8969, "descr": ""},
    {"catid": 58, "prodcode": 8970, "descr": ""},
    {"catid": 58, "prodcode": 8971, "descr": ""},
    {"catid": 58, "prodcode": 8972, "descr": ""},
    {"catid": 58, "prodcode": 8973, "descr": ""},
    {"catid": 58, "prodcode": 8974, "descr": ""},
    {"catid": 58, "prodcode": 8975, "descr": ""},
])

Trypanosomes_Screening = np.array([
    {"catid": 231, "prodcode": 9155, "descr": ""},
])

# =============================================================================
# SUMMARY — T.py
# =============================================================================
# Categories in this file : 9
# Total product entries    : 119
#
# Breakdown by category:
#   Therapeutic_Abortion_Manual_Vacuum_Aspiration (catid=255): 10 products
#   Thoracic_Inlet_X_rays (catid=125): 14 products
#   Thoraco_Lumbar_X_rays (catid=126): 17 products
#   Thoracoscopy (catid=112): 17 products
#   Throat_Swab_M_C_S (catid=238): 1 products
#   Thyroid_Function_Tests (catid=314): 12 products
#   Toxoplasma_Screening (catid=232): 26 products
#   Treatment_of_basic_outpatient_and_in_patient_cases (catid=58): 21 products
#   Trypanosomes_Screening (catid=231): 1 products
# =============================================================================
