import numpy as np

# =============================================================================
# B.py
# Service category product assignments — letter B
# Generated by: product-service-mapper skill
# =============================================================================

Basic_Diagnostic_Imaging = np.array([
    {"catid": 29, "prodcode": 10820, "descr": ""},
    {"catid": 29, "prodcode": 10888, "descr": ""},
    {"catid": 29, "prodcode": 10889, "descr": ""},
    {"catid": 29, "prodcode": 10891, "descr": ""},
    {"catid": 29, "prodcode": 10898, "descr": ""},
    {"catid": 29, "prodcode": 10899, "descr": ""},
    {"catid": 29, "prodcode": 10901, "descr": ""},
    {"catid": 29, "prodcode": 10902, "descr": ""},
    {"catid": 29, "prodcode": 10903, "descr": ""},
    {"catid": 29, "prodcode": 10906, "descr": ""},
    {"catid": 29, "prodcode": 10907, "descr": ""},
    {"catid": 29, "prodcode": 10908, "descr": ""},
    {"catid": 29, "prodcode": 10915, "descr": ""},
    {"catid": 29, "prodcode": 10916, "descr": ""},
    {"catid": 29, "prodcode": 11373, "descr": ""},
    {"catid": 29, "prodcode": 11374, "descr": ""},
    {"catid": 29, "prodcode": 11375, "descr": ""},
    {"catid": 29, "prodcode": 11589, "descr": ""},
    {"catid": 29, "prodcode": 11755, "descr": ""},
    {"catid": 29, "prodcode": 11758, "descr": ""},
    {"catid": 29, "prodcode": 11908, "descr": ""},
    {"catid": 29, "prodcode": 12049, "descr": ""},
    {"catid": 29, "prodcode": 12050, "descr": ""},
    {"catid": 29, "prodcode": 12051, "descr": ""},
    {"catid": 29, "prodcode": 12052, "descr": ""},
    {"catid": 29, "prodcode": 12053, "descr": ""},
    {"catid": 29, "prodcode": 12054, "descr": ""},
    {"catid": 29, "prodcode": 12055, "descr": ""},
    {"catid": 29, "prodcode": 12056, "descr": ""},
    {"catid": 29, "prodcode": 12227, "descr": ""},
    {"catid": 29, "prodcode": 12229, "descr": ""},
    {"catid": 29, "prodcode": 12389, "descr": ""},
    {"catid": 29, "prodcode": 12425, "descr": ""},
    {"catid": 29, "prodcode": 12426, "descr": ""},
    {"catid": 29, "prodcode": 12427, "descr": ""},
    {"catid": 29, "prodcode": 12608, "descr": ""},
    {"catid": 29, "prodcode": 12841, "descr": ""},
    {"catid": 29, "prodcode": 12843, "descr": ""},
    {"catid": 29, "prodcode": 12987, "descr": ""},
    {"catid": 29, "prodcode": 12988, "descr": ""},
    {"catid": 29, "prodcode": 13019, "descr": ""},
    {"catid": 29, "prodcode": 13053, "descr": ""},
    {"catid": 29, "prodcode": 13061, "descr": ""},
    {"catid": 29, "prodcode": 13128, "descr": ""},
    {"catid": 29, "prodcode": 13129, "descr": ""},
    {"catid": 29, "prodcode": 13130, "descr": ""},
    {"catid": 29, "prodcode": 13132, "descr": ""},
    {"catid": 29, "prodcode": 13133, "descr": ""},
    {"catid": 29, "prodcode": 13134, "descr": ""},
    {"catid": 29, "prodcode": 13135, "descr": ""},
    {"catid": 29, "prodcode": 13136, "descr": ""},
    {"catid": 29, "prodcode": 13137, "descr": ""},
    {"catid": 29, "prodcode": 13138, "descr": ""},
    {"catid": 29, "prodcode": 13139, "descr": ""},
    {"catid": 29, "prodcode": 13140, "descr": ""},
    {"catid": 29, "prodcode": 13141, "descr": ""},
    {"catid": 29, "prodcode": 13142, "descr": ""},
    {"catid": 29, "prodcode": 13144, "descr": ""},
    {"catid": 29, "prodcode": 13145, "descr": ""},
    {"catid": 29, "prodcode": 13147, "descr": ""},
    {"catid": 29, "prodcode": 13149, "descr": ""},
    {"catid": 29, "prodcode": 13150, "descr": ""},
    {"catid": 29, "prodcode": 13151, "descr": ""},
    {"catid": 29, "prodcode": 13414, "descr": ""},
    {"catid": 29, "prodcode": 13494, "descr": ""},
    {"catid": 29, "prodcode": 13619, "descr": ""},
    {"catid": 29, "prodcode": 13620, "descr": ""},
    {"catid": 29, "prodcode": 13623, "descr": ""},
    {"catid": 29, "prodcode": 13625, "descr": ""},
    {"catid": 29, "prodcode": 13626, "descr": ""},
    {"catid": 29, "prodcode": 13627, "descr": ""},
    {"catid": 29, "prodcode": 13628, "descr": ""},
    {"catid": 29, "prodcode": 13630, "descr": ""},
    {"catid": 29, "prodcode": 13632, "descr": ""},
    {"catid": 29, "prodcode": 13675, "descr": ""},
    {"catid": 29, "prodcode": 13676, "descr": ""},
    {"catid": 29, "prodcode": 13677, "descr": ""},
    {"catid": 29, "prodcode": 13678, "descr": ""},
    {"catid": 29, "prodcode": 13679, "descr": ""},
])

Basic_Lab_Investigations_or_Xrays_and_Ultrasound = np.array([
    {"catid": 56, "prodcode": 10888, "descr": ""},
    {"catid": 56, "prodcode": 10889, "descr": ""},
    {"catid": 56, "prodcode": 10891, "descr": ""},
    {"catid": 56, "prodcode": 10898, "descr": ""},
    {"catid": 56, "prodcode": 10899, "descr": ""},
    {"catid": 56, "prodcode": 10901, "descr": ""},
    {"catid": 56, "prodcode": 10902, "descr": ""},
    {"catid": 56, "prodcode": 10903, "descr": ""},
    {"catid": 56, "prodcode": 10906, "descr": ""},
    {"catid": 56, "prodcode": 10907, "descr": ""},
    {"catid": 56, "prodcode": 10908, "descr": ""},
    {"catid": 56, "prodcode": 10915, "descr": ""},
    {"catid": 56, "prodcode": 10916, "descr": ""},
    {"catid": 56, "prodcode": 11373, "descr": ""},
    {"catid": 56, "prodcode": 11374, "descr": ""},
    {"catid": 56, "prodcode": 11375, "descr": ""},
    {"catid": 56, "prodcode": 11513, "descr": ""},
    {"catid": 56, "prodcode": 11514, "descr": ""},
    {"catid": 56, "prodcode": 11550, "descr": ""},
    {"catid": 56, "prodcode": 11551, "descr": ""},
    {"catid": 56, "prodcode": 11552, "descr": ""},
    {"catid": 56, "prodcode": 11553, "descr": ""},
    {"catid": 56, "prodcode": 11589, "descr": ""},
    {"catid": 56, "prodcode": 11735, "descr": ""},
    {"catid": 56, "prodcode": 11755, "descr": ""},
    {"catid": 56, "prodcode": 11758, "descr": ""},
    {"catid": 56, "prodcode": 11898, "descr": ""},
    {"catid": 56, "prodcode": 11899, "descr": ""},
    {"catid": 56, "prodcode": 11908, "descr": ""},
    {"catid": 56, "prodcode": 12049, "descr": ""},
    {"catid": 56, "prodcode": 12050, "descr": ""},
    {"catid": 56, "prodcode": 12051, "descr": ""},
    {"catid": 56, "prodcode": 12052, "descr": ""},
    {"catid": 56, "prodcode": 12053, "descr": ""},
    {"catid": 56, "prodcode": 12054, "descr": ""},
    {"catid": 56, "prodcode": 12055, "descr": ""},
    {"catid": 56, "prodcode": 12056, "descr": ""},
    {"catid": 56, "prodcode": 12227, "descr": ""},
    {"catid": 56, "prodcode": 12229, "descr": ""},
    {"catid": 56, "prodcode": 12389, "descr": ""},
    {"catid": 56, "prodcode": 12425, "descr": ""},
    {"catid": 56, "prodcode": 12426, "descr": ""},
    {"catid": 56, "prodcode": 12427, "descr": ""},
    {"catid": 56, "prodcode": 12608, "descr": ""},
    {"catid": 56, "prodcode": 12775, "descr": ""},
    {"catid": 56, "prodcode": 12776, "descr": ""},
    {"catid": 56, "prodcode": 12841, "descr": ""},
    {"catid": 56, "prodcode": 12843, "descr": ""},
    {"catid": 56, "prodcode": 12987, "descr": ""},
    {"catid": 56, "prodcode": 12988, "descr": ""},
    {"catid": 56, "prodcode": 12998, "descr": ""},
    {"catid": 56, "prodcode": 12999, "descr": ""},
    {"catid": 56, "prodcode": 13129, "descr": ""},
    {"catid": 56, "prodcode": 13130, "descr": ""},
    {"catid": 56, "prodcode": 13132, "descr": ""},
    {"catid": 56, "prodcode": 13133, "descr": ""},
    {"catid": 56, "prodcode": 13134, "descr": ""},
    {"catid": 56, "prodcode": 13135, "descr": ""},
    {"catid": 56, "prodcode": 13136, "descr": ""},
    {"catid": 56, "prodcode": 13137, "descr": ""},
    {"catid": 56, "prodcode": 13138, "descr": ""},
    {"catid": 56, "prodcode": 13139, "descr": ""},
    {"catid": 56, "prodcode": 13140, "descr": ""},
    {"catid": 56, "prodcode": 13141, "descr": ""},
    {"catid": 56, "prodcode": 13142, "descr": ""},
    {"catid": 56, "prodcode": 13144, "descr": ""},
    {"catid": 56, "prodcode": 13145, "descr": ""},
    {"catid": 56, "prodcode": 13147, "descr": ""},
    {"catid": 56, "prodcode": 13150, "descr": ""},
    {"catid": 56, "prodcode": 13151, "descr": ""},
    {"catid": 56, "prodcode": 13430, "descr": ""},
    {"catid": 56, "prodcode": 13494, "descr": ""},
    {"catid": 56, "prodcode": 13619, "descr": ""},
    {"catid": 56, "prodcode": 13620, "descr": ""},
    {"catid": 56, "prodcode": 13623, "descr": ""},
    {"catid": 56, "prodcode": 13625, "descr": ""},
    {"catid": 56, "prodcode": 13626, "descr": ""},
    {"catid": 56, "prodcode": 13627, "descr": ""},
    {"catid": 56, "prodcode": 13628, "descr": ""},
    {"catid": 56, "prodcode": 13630, "descr": ""},
    {"catid": 56, "prodcode": 13632, "descr": ""},
    {"catid": 56, "prodcode": 13675, "descr": ""},
    {"catid": 56, "prodcode": 13676, "descr": ""},
    {"catid": 56, "prodcode": 13677, "descr": ""},
    {"catid": 56, "prodcode": 13678, "descr": ""},
    {"catid": 56, "prodcode": 13679, "descr": ""},
])

Basic_ocular_tests = np.array([
    {"catid": 182, "prodcode": 11327, "descr": ""},
    {"catid": 182, "prodcode": 11735, "descr": ""},
    {"catid": 182, "prodcode": 11744, "descr": ""},
    {"catid": 182, "prodcode": 12381, "descr": ""},
    {"catid": 182, "prodcode": 12554, "descr": ""},
    {"catid": 182, "prodcode": 13397, "descr": ""},
    {"catid": 182, "prodcode": 13492, "descr": ""},
    {"catid": 182, "prodcode": 13570, "descr": ""},
    {"catid": 182, "prodcode": 13571, "descr": ""},
    {"catid": 182, "prodcode": 13595, "descr": ""},
    {"catid": 182, "prodcode": 13597, "descr": ""},
])

Bcg = np.array([
    {"catid": 80, "prodcode": 10836, "descr": ""},
    {"catid": 80, "prodcode": 10838, "descr": ""},
    {"catid": 80, "prodcode": 11472, "descr": ""},
    {"catid": 80, "prodcode": 11599, "descr": ""},
    {"catid": 80, "prodcode": 11722, "descr": ""},
    {"catid": 80, "prodcode": 12449, "descr": ""},
    {"catid": 80, "prodcode": 12583, "descr": ""},
    {"catid": 80, "prodcode": 12806, "descr": ""},
    {"catid": 80, "prodcode": 12807, "descr": ""},
    {"catid": 80, "prodcode": 12808, "descr": ""},
    {"catid": 80, "prodcode": 12809, "descr": ""},
    {"catid": 80, "prodcode": 12810, "descr": ""},
    {"catid": 80, "prodcode": 12811, "descr": ""},
    {"catid": 80, "prodcode": 12812, "descr": ""},
    {"catid": 80, "prodcode": 13486, "descr": ""},
    {"catid": 80, "prodcode": 13713, "descr": ""},
    {"catid": 80, "prodcode": 13715, "descr": ""},
])

Biennial_Lenses_and_Frames = np.array([
    {"catid": 185, "prodcode": 13420, "descr": ""},
    {"catid": 185, "prodcode": 13421, "descr": ""},
    {"catid": 185, "prodcode": 13422, "descr": ""},
    {"catid": 185, "prodcode": 13423, "descr": ""},
    {"catid": 185, "prodcode": 13424, "descr": ""},
    {"catid": 185, "prodcode": 13425, "descr": ""},
    {"catid": 185, "prodcode": 13426, "descr": ""},
    {"catid": 185, "prodcode": 13427, "descr": ""},
    {"catid": 185, "prodcode": 13428, "descr": ""},
])

Bleeding_Time = np.array([
    {"catid": 334, "prodcode": 11898, "descr": ""},
])

Blood_Culture = np.array([
    {"catid": 248, "prodcode": 10776, "descr": ""},
    {"catid": 248, "prodcode": 10777, "descr": ""},
    {"catid": 248, "prodcode": 10778, "descr": ""},
    {"catid": 248, "prodcode": 10779, "descr": ""},
    {"catid": 248, "prodcode": 10780, "descr": ""},
    {"catid": 248, "prodcode": 10794, "descr": ""},
    {"catid": 248, "prodcode": 11689, "descr": ""},
])

Blood_Film = np.array([
    {"catid": 204, "prodcode": 10783, "descr": ""},
    {"catid": 204, "prodcode": 11526, "descr": ""},
    {"catid": 204, "prodcode": 11735, "descr": ""},
    {"catid": 204, "prodcode": 12746, "descr": ""},
    {"catid": 204, "prodcode": 13824, "descr": ""},
])

Blood_group_on_request_by_clinician = np.array([
    {"catid": 208, "prodcode": 10786, "descr": ""},
    {"catid": 208, "prodcode": 10787, "descr": ""},
])

Blood_Pregnancy_Beta_HCG_Test = np.array([
    {"catid": 205, "prodcode": 10803, "descr": ""},
    {"catid": 205, "prodcode": 10804, "descr": ""},
    {"catid": 205, "prodcode": 11225, "descr": ""},
    {"catid": 205, "prodcode": 11228, "descr": ""},
    {"catid": 205, "prodcode": 11257, "descr": ""},
    {"catid": 205, "prodcode": 11268, "descr": ""},
    {"catid": 205, "prodcode": 11269, "descr": ""},
    {"catid": 205, "prodcode": 11271, "descr": ""},
    {"catid": 205, "prodcode": 11272, "descr": ""},
    {"catid": 205, "prodcode": 11517, "descr": ""},
    {"catid": 205, "prodcode": 11519, "descr": ""},
    {"catid": 205, "prodcode": 11521, "descr": ""},
    {"catid": 205, "prodcode": 11679, "descr": ""},
    {"catid": 205, "prodcode": 11884, "descr": ""},
    {"catid": 205, "prodcode": 11885, "descr": ""},
    {"catid": 205, "prodcode": 12126, "descr": ""},
    {"catid": 205, "prodcode": 12132, "descr": ""},
    {"catid": 205, "prodcode": 12145, "descr": ""},
    {"catid": 205, "prodcode": 12148, "descr": ""},
    {"catid": 205, "prodcode": 12161, "descr": ""},
    {"catid": 205, "prodcode": 12162, "descr": ""},
    {"catid": 205, "prodcode": 12552, "descr": ""},
    {"catid": 205, "prodcode": 12764, "descr": ""},
    {"catid": 205, "prodcode": 12765, "descr": ""},
    {"catid": 205, "prodcode": 13318, "descr": ""},
    {"catid": 205, "prodcode": 13319, "descr": ""},
    {"catid": 205, "prodcode": 13320, "descr": ""},
    {"catid": 205, "prodcode": 13321, "descr": ""},
    {"catid": 205, "prodcode": 13322, "descr": ""},
    {"catid": 205, "prodcode": 13323, "descr": ""},
    {"catid": 205, "prodcode": 13324, "descr": ""},
    {"catid": 205, "prodcode": 13325, "descr": ""},
    {"catid": 205, "prodcode": 13327, "descr": ""},
    {"catid": 205, "prodcode": 13329, "descr": ""},
    {"catid": 205, "prodcode": 13331, "descr": ""},
    {"catid": 205, "prodcode": 13332, "descr": ""},
    {"catid": 205, "prodcode": 13333, "descr": ""},
    {"catid": 205, "prodcode": 13334, "descr": ""},
    {"catid": 205, "prodcode": 13335, "descr": ""},
    {"catid": 205, "prodcode": 13336, "descr": ""},
    {"catid": 205, "prodcode": 13337, "descr": ""},
    {"catid": 205, "prodcode": 13338, "descr": ""},
    {"catid": 205, "prodcode": 13340, "descr": ""},
    {"catid": 205, "prodcode": 13341, "descr": ""},
    {"catid": 205, "prodcode": 13342, "descr": ""},
    {"catid": 205, "prodcode": 13345, "descr": ""},
    {"catid": 205, "prodcode": 13346, "descr": ""},
    {"catid": 205, "prodcode": 13348, "descr": ""},
    {"catid": 205, "prodcode": 13349, "descr": ""},
    {"catid": 205, "prodcode": 13350, "descr": ""},
    {"catid": 205, "prodcode": 13351, "descr": ""},
    {"catid": 205, "prodcode": 13352, "descr": ""},
    {"catid": 205, "prodcode": 13372, "descr": ""},
    {"catid": 205, "prodcode": 13373, "descr": ""},
    {"catid": 205, "prodcode": 13374, "descr": ""},
    {"catid": 205, "prodcode": 13375, "descr": ""},
    {"catid": 205, "prodcode": 13377, "descr": ""},
    {"catid": 205, "prodcode": 13563, "descr": ""},
    {"catid": 205, "prodcode": 13564, "descr": ""},
    {"catid": 205, "prodcode": 13565, "descr": ""},
    {"catid": 205, "prodcode": 13567, "descr": ""},
    {"catid": 205, "prodcode": 13568, "descr": ""},
    {"catid": 205, "prodcode": 13806, "descr": ""},
])

Blood_Pressure_Check_Hypertension_Screening = np.array([
    {"catid": 295, "prodcode": 13397, "descr": ""},
    {"catid": 295, "prodcode": 13570, "descr": ""},
    {"catid": 295, "prodcode": 13571, "descr": ""},
])

Blood_Sugar_Check_Diabetes_Screening = np.array([
    {"catid": 288, "prodcode": 13570, "descr": ""},
    {"catid": 288, "prodcode": 13571, "descr": ""},
])

Body_Massage = np.array([
    {"catid": 195, "prodcode": 11321, "descr": ""},
    {"catid": 195, "prodcode": 11322, "descr": ""},
    {"catid": 195, "prodcode": 12598, "descr": ""},
    {"catid": 195, "prodcode": 12784, "descr": ""},
    {"catid": 195, "prodcode": 12785, "descr": ""},
    {"catid": 195, "prodcode": 12786, "descr": ""},
    {"catid": 195, "prodcode": 12787, "descr": ""},
    {"catid": 195, "prodcode": 12985, "descr": ""},
    {"catid": 195, "prodcode": 13014, "descr": ""},
    {"catid": 195, "prodcode": 13058, "descr": ""},
    {"catid": 195, "prodcode": 13066, "descr": ""},
])

Bronchoscopy = np.array([
    {"catid": 111, "prodcode": 11719, "descr": ""},
    {"catid": 111, "prodcode": 11720, "descr": ""},
])

# =============================================================================
# SUMMARY — B.py
# =============================================================================
# Categories in this file : 16
# Total product entries    : 298
# Duplicate entries removed: 0
#
# Breakdown by category:
#   Basic_Diagnostic_Imaging (catid=29): 79 products
#   Basic_Lab_Investigations_or_Xrays_and_Ultrasound (catid=56): 86 products
#   Basic_ocular_tests (catid=182): 11 products
#   Bcg (catid=80): 17 products
#   Biennial_Lenses_and_Frames (catid=185): 9 products
#   Bleeding_Time (catid=334): 1 products
#   Blood_Culture (catid=248): 7 products
#   Blood_Film (catid=204): 5 products
#   Blood_group_on_request_by_clinician (catid=208): 2 products
#   Blood_Pregnancy_Beta_HCG_Test (catid=205): 63 products
#   Blood_Pressure_Check_Hypertension_Screening (catid=295): 3 products
#   Blood_Sugar_Check_Diabetes_Screening (catid=288): 2 products
#   Blood_urea_Nitrogen (catid=309): (no products — variable omitted)
#   Bmi_Check (catid=292): (no products — variable omitted)
#   Body_Massage (catid=195): 11 products
#   Bronchoscopy (catid=111): 2 products
# =============================================================================
