import numpy as np

# =============================================================================
# C.py
# Service category product assignments — letter C
# Generated by: product-service-mapper skill
# =============================================================================

Caesarian_Section_Emergency_covered_to_surgical_limit = np.array([
    {"catid": 256, "prodcode": 10825, "descr": ""},
    {"catid": 256, "prodcode": 10826, "descr": ""},
    {"catid": 256, "prodcode": 10827, "descr": ""},
    {"catid": 256, "prodcode": 10828, "descr": ""},
    {"catid": 256, "prodcode": 10829, "descr": ""},
    {"catid": 256, "prodcode": 11296, "descr": ""},
    {"catid": 256, "prodcode": 11297, "descr": ""},
    {"catid": 256, "prodcode": 11298, "descr": ""},
    {"catid": 256, "prodcode": 11299, "descr": ""},
    {"catid": 256, "prodcode": 11310, "descr": ""},
    {"catid": 256, "prodcode": 11334, "descr": ""},
    {"catid": 256, "prodcode": 11549, "descr": ""},
    {"catid": 256, "prodcode": 11561, "descr": ""},
    {"catid": 256, "prodcode": 12225, "descr": ""},
    {"catid": 256, "prodcode": 12353, "descr": ""},
    {"catid": 256, "prodcode": 12354, "descr": ""},
    {"catid": 256, "prodcode": 12355, "descr": ""},
    {"catid": 256, "prodcode": 12357, "descr": ""},
    {"catid": 256, "prodcode": 12376, "descr": ""},
    {"catid": 256, "prodcode": 12840, "descr": ""},
    {"catid": 256, "prodcode": 12969, "descr": ""},
    {"catid": 256, "prodcode": 13303, "descr": ""},
    {"catid": 256, "prodcode": 13433, "descr": ""},
    {"catid": 256, "prodcode": 13436, "descr": ""},
    {"catid": 256, "prodcode": 13437, "descr": ""},
    {"catid": 256, "prodcode": 13550, "descr": ""},
    {"catid": 256, "prodcode": 13586, "descr": ""},
    {"catid": 256, "prodcode": 13618, "descr": ""},
])

Cancer_Screening_Care = np.array([
    {"catid": 47, "prodcode": 10812, "descr": ""},
    {"catid": 47, "prodcode": 10839, "descr": ""},
    {"catid": 47, "prodcode": 10850, "descr": ""},
    {"catid": 47, "prodcode": 10855, "descr": ""},
    {"catid": 47, "prodcode": 11207, "descr": ""},
    {"catid": 47, "prodcode": 11208, "descr": ""},
    {"catid": 47, "prodcode": 11209, "descr": ""},
    {"catid": 47, "prodcode": 11219, "descr": ""},
    {"catid": 47, "prodcode": 11279, "descr": ""},
    {"catid": 47, "prodcode": 11344, "descr": ""},
    {"catid": 47, "prodcode": 11359, "descr": ""},
    {"catid": 47, "prodcode": 11581, "descr": ""},
    {"catid": 47, "prodcode": 12038, "descr": ""},
    {"catid": 47, "prodcode": 12346, "descr": ""},
    {"catid": 47, "prodcode": 12352, "descr": ""},
    {"catid": 47, "prodcode": 12361, "descr": ""},
    {"catid": 47, "prodcode": 12371, "descr": ""},
    {"catid": 47, "prodcode": 12589, "descr": ""},
    {"catid": 47, "prodcode": 12590, "descr": ""},
    {"catid": 47, "prodcode": 12825, "descr": ""},
    {"catid": 47, "prodcode": 12836, "descr": ""},
    {"catid": 47, "prodcode": 12837, "descr": ""},
    {"catid": 47, "prodcode": 12838, "descr": ""},
    {"catid": 47, "prodcode": 12839, "descr": ""},
    {"catid": 47, "prodcode": 12954, "descr": ""},
    {"catid": 47, "prodcode": 12971, "descr": ""},
    {"catid": 47, "prodcode": 13040, "descr": ""},
    {"catid": 47, "prodcode": 13085, "descr": ""},
    {"catid": 47, "prodcode": 13095, "descr": ""},
    {"catid": 47, "prodcode": 13116, "descr": ""},
    {"catid": 47, "prodcode": 13570, "descr": ""},
    {"catid": 47, "prodcode": 13571, "descr": ""},
    {"catid": 47, "prodcode": 13605, "descr": ""},
    {"catid": 47, "prodcode": 13611, "descr": ""},
])

Cancer_Related_Radiological_Investigations = np.array([
    {"catid": 140, "prodcode": 11908, "descr": ""},
    {"catid": 140, "prodcode": 12596, "descr": ""},
    {"catid": 140, "prodcode": 12775, "descr": ""},
    {"catid": 140, "prodcode": 12776, "descr": ""},
])

Cardiologist = np.array([
    {"catid": 276, "prodcode": 10841, "descr": ""},
    {"catid": 276, "prodcode": 11587, "descr": ""},
    {"catid": 276, "prodcode": 11588, "descr": ""},
    {"catid": 276, "prodcode": 13105, "descr": ""},
])

Cardiothoracic_Surgeon = np.array([
    {"catid": 267, "prodcode": 10844, "descr": ""},
    {"catid": 267, "prodcode": 10874, "descr": ""},
    {"catid": 267, "prodcode": 10894, "descr": ""},
    {"catid": 267, "prodcode": 11573, "descr": ""},
    {"catid": 267, "prodcode": 12554, "descr": ""},
    {"catid": 267, "prodcode": 12570, "descr": ""},
])

Cervical_Collar_and_Crutches = np.array([
    {"catid": 220, "prodcode": 10893, "descr": ""},
    {"catid": 220, "prodcode": 10894, "descr": ""},
    {"catid": 220, "prodcode": 10895, "descr": ""},
    {"catid": 220, "prodcode": 10896, "descr": ""},
    {"catid": 220, "prodcode": 10897, "descr": ""},
    {"catid": 220, "prodcode": 11197, "descr": ""},
    {"catid": 220, "prodcode": 11238, "descr": ""},
    {"catid": 220, "prodcode": 11295, "descr": ""},
    {"catid": 220, "prodcode": 11303, "descr": ""},
    {"catid": 220, "prodcode": 11305, "descr": ""},
    {"catid": 220, "prodcode": 11307, "descr": ""},
    {"catid": 220, "prodcode": 11308, "descr": ""},
    {"catid": 220, "prodcode": 11309, "descr": ""},
    {"catid": 220, "prodcode": 11543, "descr": ""},
    {"catid": 220, "prodcode": 11731, "descr": ""},
    {"catid": 220, "prodcode": 11743, "descr": ""},
    {"catid": 220, "prodcode": 12357, "descr": ""},
    {"catid": 220, "prodcode": 12421, "descr": ""},
    {"catid": 220, "prodcode": 12422, "descr": ""},
    {"catid": 220, "prodcode": 12768, "descr": ""},
])

Chemistry_Investigations = np.array([
    {"catid": 32, "prodcode": 10784, "descr": ""},
    {"catid": 32, "prodcode": 10792, "descr": ""},
    {"catid": 32, "prodcode": 11201, "descr": ""},
    {"catid": 32, "prodcode": 11202, "descr": ""},
    {"catid": 32, "prodcode": 11203, "descr": ""},
    {"catid": 32, "prodcode": 11204, "descr": ""},
    {"catid": 32, "prodcode": 11205, "descr": ""},
    {"catid": 32, "prodcode": 11212, "descr": ""},
    {"catid": 32, "prodcode": 11249, "descr": ""},
    {"catid": 32, "prodcode": 11250, "descr": ""},
    {"catid": 32, "prodcode": 11256, "descr": ""},
    {"catid": 32, "prodcode": 11258, "descr": ""},
    {"catid": 32, "prodcode": 11259, "descr": ""},
    {"catid": 32, "prodcode": 11523, "descr": ""},
    {"catid": 32, "prodcode": 11524, "descr": ""},
    {"catid": 32, "prodcode": 11683, "descr": ""},
    {"catid": 32, "prodcode": 11685, "descr": ""},
    {"catid": 32, "prodcode": 11693, "descr": ""},
    {"catid": 32, "prodcode": 11890, "descr": ""},
    {"catid": 32, "prodcode": 12167, "descr": ""},
    {"catid": 32, "prodcode": 12168, "descr": ""},
    {"catid": 32, "prodcode": 12171, "descr": ""},
    {"catid": 32, "prodcode": 12173, "descr": ""},
    {"catid": 32, "prodcode": 12175, "descr": ""},
    {"catid": 32, "prodcode": 12177, "descr": ""},
    {"catid": 32, "prodcode": 12326, "descr": ""},
    {"catid": 32, "prodcode": 12328, "descr": ""},
    {"catid": 32, "prodcode": 12329, "descr": ""},
    {"catid": 32, "prodcode": 12330, "descr": ""},
    {"catid": 32, "prodcode": 12332, "descr": ""},
    {"catid": 32, "prodcode": 12333, "descr": ""},
    {"catid": 32, "prodcode": 12525, "descr": ""},
    {"catid": 32, "prodcode": 12527, "descr": ""},
    {"catid": 32, "prodcode": 12529, "descr": ""},
    {"catid": 32, "prodcode": 12533, "descr": ""},
    {"catid": 32, "prodcode": 12748, "descr": ""},
    {"catid": 32, "prodcode": 13074, "descr": ""},
    {"catid": 32, "prodcode": 13312, "descr": ""},
    {"catid": 32, "prodcode": 13371, "descr": ""},
    {"catid": 32, "prodcode": 13566, "descr": ""},
    {"catid": 32, "prodcode": 13803, "descr": ""},
    {"catid": 32, "prodcode": 13808, "descr": ""},
    {"catid": 32, "prodcode": 13810, "descr": ""},
    {"catid": 32, "prodcode": 13811, "descr": ""},
])

Chemotherapy = np.array([
    {"catid": 142, "prodcode": 10840, "descr": ""},
    {"catid": 142, "prodcode": 11876, "descr": ""},
    {"catid": 142, "prodcode": 12308, "descr": ""},
])

Chest_X_Ray = np.array([
    {"catid": 301, "prodcode": 13315, "descr": ""},
    {"catid": 301, "prodcode": 13463, "descr": ""},
])

Chicken_Pox = np.array([
    {"catid": 92, "prodcode": 11348, "descr": ""},
    {"catid": 92, "prodcode": 11350, "descr": ""},
    {"catid": 92, "prodcode": 11351, "descr": ""},
    {"catid": 92, "prodcode": 11352, "descr": ""},
    {"catid": 92, "prodcode": 11353, "descr": ""},
    {"catid": 92, "prodcode": 13470, "descr": ""},
])

Chlamydia_Screening = np.array([
    {"catid": 331, "prodcode": 11227, "descr": ""},
    {"catid": 331, "prodcode": 11228, "descr": ""},
    {"catid": 331, "prodcode": 11229, "descr": ""},
    {"catid": 331, "prodcode": 13315, "descr": ""},
    {"catid": 331, "prodcode": 13316, "descr": ""},
])

Clotting_Time = np.array([
    {"catid": 333, "prodcode": 11198, "descr": ""},
])

Colonoscopy = np.array([
    {"catid": 118, "prodcode": 11573, "descr": ""},
    {"catid": 118, "prodcode": 11735, "descr": ""},
    {"catid": 118, "prodcode": 12958, "descr": ""},
    {"catid": 118, "prodcode": 13430, "descr": ""},
])

Composite_Filling = np.array([
    {"catid": 178, "prodcode": 10826, "descr": ""},
    {"catid": 178, "prodcode": 10827, "descr": ""},
    {"catid": 178, "prodcode": 10828, "descr": ""},
    {"catid": 178, "prodcode": 10829, "descr": ""},
    {"catid": 178, "prodcode": 11916, "descr": ""},
])

Contraceptive_Pills = np.array([
    {"catid": 186, "prodcode": 11168, "descr": ""},
    {"catid": 186, "prodcode": 11876, "descr": ""},
    {"catid": 186, "prodcode": 12169, "descr": ""},
    {"catid": 186, "prodcode": 12552, "descr": ""},
    {"catid": 186, "prodcode": 13372, "descr": ""},
    {"catid": 186, "prodcode": 13373, "descr": ""},
    {"catid": 186, "prodcode": 13374, "descr": ""},
    {"catid": 186, "prodcode": 13375, "descr": ""},
    {"catid": 186, "prodcode": 13806, "descr": ""},
])

Coomb_s_Test_Direct = np.array([
    {"catid": 326, "prodcode": 11228, "descr": ""},
    {"catid": 326, "prodcode": 13305, "descr": ""},
])

Coomb_s_Test_Indirect = np.array([
    {"catid": 325, "prodcode": 11228, "descr": ""},
    {"catid": 325, "prodcode": 11908, "descr": ""},
    {"catid": 325, "prodcode": 13305, "descr": ""},
])

Copper_T_Intrauterine_Device = np.array([
    {"catid": 189, "prodcode": 11171, "descr": ""},
    {"catid": 189, "prodcode": 11278, "descr": ""},
    {"catid": 189, "prodcode": 11876, "descr": ""},
    {"catid": 189, "prodcode": 12116, "descr": ""},
    {"catid": 189, "prodcode": 12117, "descr": ""},
    {"catid": 189, "prodcode": 12310, "descr": ""},
    {"catid": 189, "prodcode": 12311, "descr": ""},
    {"catid": 189, "prodcode": 12741, "descr": ""},
    {"catid": 189, "prodcode": 12742, "descr": ""},
])

CSF_M_C_S_CSF_Analysis = np.array([
    {"catid": 321, "prodcode": 11220, "descr": ""},
    {"catid": 321, "prodcode": 11221, "descr": ""},
    {"catid": 321, "prodcode": 11735, "descr": ""},
    {"catid": 321, "prodcode": 12806, "descr": ""},
    {"catid": 321, "prodcode": 12807, "descr": ""},
    {"catid": 321, "prodcode": 12808, "descr": ""},
    {"catid": 321, "prodcode": 12809, "descr": ""},
    {"catid": 321, "prodcode": 12810, "descr": ""},
    {"catid": 321, "prodcode": 12811, "descr": ""},
    {"catid": 321, "prodcode": 12812, "descr": ""},
])

CT_Scan = np.array([
    {"catid": 116, "prodcode": 12604, "descr": ""},
])

Cystoscopy = np.array([
    {"catid": 119, "prodcode": 11215, "descr": ""},
    {"catid": 119, "prodcode": 11216, "descr": ""},
    {"catid": 119, "prodcode": 11573, "descr": ""},
])

# =============================================================================
# SUMMARY — C.py
# =============================================================================
# Categories in this file : 25
# Total product entries    : 203
# Duplicate entries removed: 0
#
# Breakdown by category:
#   Caesarian_Section_Emergency_covered_to_surgical_limit (catid=256): 28 products
#   Cancer_Screening_Care (catid=47): 34 products
#   Cancer_Related_Radiological_Investigations (catid=140): 4 products
#   Cardiologist (catid=276): 4 products
#   Cardiothoracic_Surgeon (catid=267): 6 products
#   Cervical_Collar_and_Crutches (catid=220): 20 products
#   Cervical_Spine_X_rays (catid=132): (no products — variable omitted)
#   Chemistry_Investigations (catid=32): 44 products
#   Chemotherapy (catid=142): 3 products
#   Chest_X_Ray (catid=301): 2 products
#   Chest_X_Rays (catid=123): (no products — variable omitted)
#   Chicken_Pox (catid=92): 6 products
#   Chlamydia_Screening (catid=331): 5 products
#   Clotting_Time (catid=333): 1 products
#   Colonoscopy (catid=118): 4 products
#   Composite_Filling (catid=178): 5 products
#   Contraceptive_Pills (catid=186): 9 products
#   Coomb_s_Test_Direct (catid=326): 2 products
#   Coomb_s_Test_Indirect (catid=325): 3 products
#   Copper_T_Intrauterine_Device (catid=189): 9 products
#   Counselling_Sessions (catid=212): (no products — variable omitted)
#   Creatinine_phosphokinase (catid=319): (no products — variable omitted)
#   CSF_M_C_S_CSF_Analysis (catid=321): 10 products
#   CT_Scan (catid=116): 1 products
#   Cystoscopy (catid=119): 3 products
# =============================================================================
