import numpy as np

# =============================================================================
# I.py
# Service category product assignments — letter I
# Generated by: product-service-mapper skill
# =============================================================================

Implanon = np.array([
    {"catid": 188, "prodcode": 12307, "descr": ""},
    {"catid": 188, "prodcode": 12309, "descr": ""},
    {"catid": 188, "prodcode": 13076, "descr": ""},
])

In_Patient_Care_Limit = np.array([
    {"catid": 28, "prodcode": 12308, "descr": ""},
    {"catid": 28, "prodcode": 12312, "descr": ""},
    {"catid": 28, "prodcode": 12313, "descr": ""},
    {"catid": 28, "prodcode": 12971, "descr": ""},
    {"catid": 28, "prodcode": 13048, "descr": ""},
    {"catid": 28, "prodcode": 13049, "descr": ""},
    {"catid": 28, "prodcode": 13050, "descr": ""},
    {"catid": 28, "prodcode": 13052, "descr": ""},
])

Incision_and_Drainage = np.array([
    {"catid": 180, "prodcode": 11549, "descr": ""},
    {"catid": 180, "prodcode": 12225, "descr": ""},
    {"catid": 180, "prodcode": 12353, "descr": ""},
    {"catid": 180, "prodcode": 12354, "descr": ""},
    {"catid": 180, "prodcode": 12355, "descr": ""},
    {"catid": 180, "prodcode": 12357, "descr": ""},
    {"catid": 180, "prodcode": 12840, "descr": ""},
    {"catid": 180, "prodcode": 13123, "descr": ""},
    {"catid": 180, "prodcode": 13397, "descr": ""},
    {"catid": 180, "prodcode": 13414, "descr": ""},
    {"catid": 180, "prodcode": 13618, "descr": ""},
])

Incubator_Care = np.array([
    {"catid": 217, "prodcode": 10805, "descr": ""},
    {"catid": 217, "prodcode": 11282, "descr": ""},
    {"catid": 217, "prodcode": 12346, "descr": ""},
    {"catid": 217, "prodcode": 12361, "descr": ""},
    {"catid": 217, "prodcode": 12838, "descr": ""},
    {"catid": 217, "prodcode": 13569, "descr": ""},
])

Infertility_Care = np.array([
    {"catid": 39, "prodcode": 10868, "descr": ""},
    {"catid": 39, "prodcode": 10872, "descr": ""},
    {"catid": 39, "prodcode": 12297, "descr": ""},
    {"catid": 39, "prodcode": 12298, "descr": ""},
    {"catid": 39, "prodcode": 12999, "descr": ""},
    {"catid": 39, "prodcode": 13060, "descr": ""},
    {"catid": 39, "prodcode": 13409, "descr": ""},
])

Injectibles = np.array([
    {"catid": 216, "prodcode": 11168, "descr": ""},
    {"catid": 216, "prodcode": 11399, "descr": ""},
    {"catid": 216, "prodcode": 11843, "descr": ""},
    {"catid": 216, "prodcode": 12907, "descr": ""},
    {"catid": 216, "prodcode": 12908, "descr": ""},
])

Intensive_Care_Unit = np.array([
    {"catid": 91, "prodcode": 10909, "descr": ""},
    {"catid": 91, "prodcode": 10910, "descr": ""},
    {"catid": 91, "prodcode": 11273, "descr": ""},
    {"catid": 91, "prodcode": 11274, "descr": ""},
    {"catid": 91, "prodcode": 11275, "descr": ""},
    {"catid": 91, "prodcode": 11276, "descr": ""},
    {"catid": 91, "prodcode": 11277, "descr": ""},
    {"catid": 91, "prodcode": 12371, "descr": ""},
    {"catid": 91, "prodcode": 12372, "descr": ""},
])

Intermediate_Surgeries = np.array([
    {"catid": 286, "prodcode": 10811, "descr": ""},
    {"catid": 286, "prodcode": 10815, "descr": ""},
    {"catid": 286, "prodcode": 10816, "descr": ""},
    {"catid": 286, "prodcode": 10817, "descr": ""},
    {"catid": 286, "prodcode": 10818, "descr": ""},
    {"catid": 286, "prodcode": 10821, "descr": ""},
    {"catid": 286, "prodcode": 10823, "descr": ""},
    {"catid": 286, "prodcode": 10824, "descr": ""},
    {"catid": 286, "prodcode": 10831, "descr": ""},
    {"catid": 286, "prodcode": 10835, "descr": ""},
    {"catid": 286, "prodcode": 11301, "descr": ""},
    {"catid": 286, "prodcode": 11313, "descr": ""},
    {"catid": 286, "prodcode": 11325, "descr": ""},
    {"catid": 286, "prodcode": 11326, "descr": ""},
    {"catid": 286, "prodcode": 11328, "descr": ""},
    {"catid": 286, "prodcode": 11332, "descr": ""},
    {"catid": 286, "prodcode": 11336, "descr": ""},
    {"catid": 286, "prodcode": 11342, "descr": ""},
    {"catid": 286, "prodcode": 11346, "descr": ""},
    {"catid": 286, "prodcode": 11542, "descr": ""},
    {"catid": 286, "prodcode": 11544, "descr": ""},
    {"catid": 286, "prodcode": 11545, "descr": ""},
    {"catid": 286, "prodcode": 11546, "descr": ""},
    {"catid": 286, "prodcode": 11556, "descr": ""},
    {"catid": 286, "prodcode": 11557, "descr": ""},
    {"catid": 286, "prodcode": 11563, "descr": ""},
    {"catid": 286, "prodcode": 11564, "descr": ""},
    {"catid": 286, "prodcode": 11715, "descr": ""},
    {"catid": 286, "prodcode": 11716, "descr": ""},
    {"catid": 286, "prodcode": 11718, "descr": ""},
    {"catid": 286, "prodcode": 11721, "descr": ""},
    {"catid": 286, "prodcode": 11723, "descr": ""},
    {"catid": 286, "prodcode": 11726, "descr": ""},
    {"catid": 286, "prodcode": 11727, "descr": ""},
    {"catid": 286, "prodcode": 11728, "descr": ""},
    {"catid": 286, "prodcode": 11732, "descr": ""},
    {"catid": 286, "prodcode": 11733, "descr": ""},
    {"catid": 286, "prodcode": 11740, "descr": ""},
    {"catid": 286, "prodcode": 11741, "descr": ""},
    {"catid": 286, "prodcode": 11910, "descr": ""},
    {"catid": 286, "prodcode": 11911, "descr": ""},
    {"catid": 286, "prodcode": 11913, "descr": ""},
    {"catid": 286, "prodcode": 11914, "descr": ""},
    {"catid": 286, "prodcode": 11921, "descr": ""},
    {"catid": 286, "prodcode": 11923, "descr": ""},
    {"catid": 286, "prodcode": 12190, "descr": ""},
    {"catid": 286, "prodcode": 12191, "descr": ""},
    {"catid": 286, "prodcode": 12192, "descr": ""},
    {"catid": 286, "prodcode": 12193, "descr": ""},
    {"catid": 286, "prodcode": 12194, "descr": ""},
    {"catid": 286, "prodcode": 12197, "descr": ""},
    {"catid": 286, "prodcode": 12198, "descr": ""},
    {"catid": 286, "prodcode": 12199, "descr": ""},
    {"catid": 286, "prodcode": 12200, "descr": ""},
    {"catid": 286, "prodcode": 12201, "descr": ""},
    {"catid": 286, "prodcode": 12359, "descr": ""},
    {"catid": 286, "prodcode": 12360, "descr": ""},
    {"catid": 286, "prodcode": 12365, "descr": ""},
    {"catid": 286, "prodcode": 12366, "descr": ""},
    {"catid": 286, "prodcode": 12367, "descr": ""},
    {"catid": 286, "prodcode": 12368, "descr": ""},
    {"catid": 286, "prodcode": 12373, "descr": ""},
    {"catid": 286, "prodcode": 12414, "descr": ""},
    {"catid": 286, "prodcode": 12415, "descr": ""},
    {"catid": 286, "prodcode": 12523, "descr": ""},
    {"catid": 286, "prodcode": 12551, "descr": ""},
    {"catid": 286, "prodcode": 12553, "descr": ""},
    {"catid": 286, "prodcode": 12554, "descr": ""},
    {"catid": 286, "prodcode": 12555, "descr": ""},
    {"catid": 286, "prodcode": 12557, "descr": ""},
    {"catid": 286, "prodcode": 12558, "descr": ""},
    {"catid": 286, "prodcode": 12559, "descr": ""},
    {"catid": 286, "prodcode": 12560, "descr": ""},
    {"catid": 286, "prodcode": 12561, "descr": ""},
    {"catid": 286, "prodcode": 12562, "descr": ""},
    {"catid": 286, "prodcode": 12563, "descr": ""},
    {"catid": 286, "prodcode": 12564, "descr": ""},
    {"catid": 286, "prodcode": 12565, "descr": ""},
    {"catid": 286, "prodcode": 12572, "descr": ""},
    {"catid": 286, "prodcode": 12574, "descr": ""},
    {"catid": 286, "prodcode": 12578, "descr": ""},
    {"catid": 286, "prodcode": 12581, "descr": ""},
    {"catid": 286, "prodcode": 12582, "descr": ""},
    {"catid": 286, "prodcode": 12786, "descr": ""},
    {"catid": 286, "prodcode": 12787, "descr": ""},
    {"catid": 286, "prodcode": 12792, "descr": ""},
    {"catid": 286, "prodcode": 12793, "descr": ""},
    {"catid": 286, "prodcode": 12794, "descr": ""},
    {"catid": 286, "prodcode": 12796, "descr": ""},
    {"catid": 286, "prodcode": 12800, "descr": ""},
    {"catid": 286, "prodcode": 12801, "descr": ""},
    {"catid": 286, "prodcode": 12802, "descr": ""},
    {"catid": 286, "prodcode": 12965, "descr": ""},
    {"catid": 286, "prodcode": 13065, "descr": ""},
    {"catid": 286, "prodcode": 13075, "descr": ""},
    {"catid": 286, "prodcode": 13077, "descr": ""},
    {"catid": 286, "prodcode": 13078, "descr": ""},
    {"catid": 286, "prodcode": 13080, "descr": ""},
    {"catid": 286, "prodcode": 13082, "descr": ""},
    {"catid": 286, "prodcode": 13083, "descr": ""},
    {"catid": 286, "prodcode": 13403, "descr": ""},
    {"catid": 286, "prodcode": 13404, "descr": ""},
    {"catid": 286, "prodcode": 13405, "descr": ""},
    {"catid": 286, "prodcode": 13407, "descr": ""},
    {"catid": 286, "prodcode": 13408, "descr": ""},
    {"catid": 286, "prodcode": 13410, "descr": ""},
    {"catid": 286, "prodcode": 13411, "descr": ""},
    {"catid": 286, "prodcode": 13412, "descr": ""},
    {"catid": 286, "prodcode": 13413, "descr": ""},
    {"catid": 286, "prodcode": 13419, "descr": ""},
    {"catid": 286, "prodcode": 13429, "descr": ""},
    {"catid": 286, "prodcode": 13435, "descr": ""},
    {"catid": 286, "prodcode": 13440, "descr": ""},
    {"catid": 286, "prodcode": 13441, "descr": ""},
    {"catid": 286, "prodcode": 13442, "descr": ""},
    {"catid": 286, "prodcode": 13444, "descr": ""},
    {"catid": 286, "prodcode": 13445, "descr": ""},
    {"catid": 286, "prodcode": 13451, "descr": ""},
    {"catid": 286, "prodcode": 13453, "descr": ""},
    {"catid": 286, "prodcode": 13559, "descr": ""},
    {"catid": 286, "prodcode": 13578, "descr": ""},
    {"catid": 286, "prodcode": 13581, "descr": ""},
    {"catid": 286, "prodcode": 13582, "descr": ""},
    {"catid": 286, "prodcode": 13583, "descr": ""},
    {"catid": 286, "prodcode": 13584, "descr": ""},
    {"catid": 286, "prodcode": 13585, "descr": ""},
    {"catid": 286, "prodcode": 13587, "descr": ""},
    {"catid": 286, "prodcode": 13599, "descr": ""},
])

# =============================================================================
# SUMMARY — I.py
# =============================================================================
# Categories in this file : 8
# Total product entries    : 177
# Duplicate entries removed: 0
#
# Breakdown by category:
#   Implanon (catid=188): 3 products
#   In_Patient_Care_Limit (catid=28): 8 products
#   Incision_and_Drainage (catid=180): 11 products
#   Incubator_Care (catid=217): 6 products
#   Infertility_Care (catid=39): 7 products
#   Injectibles (catid=216): 5 products
#   Intensive_Care_Unit (catid=91): 9 products
#   Intermediate_Surgeries (catid=286): 128 products
# =============================================================================
