import numpy as np

# =============================================================================
# J.py
# Service category product assignments — letter J
# Generated by: product-service-mapper skill
# =============================================================================

Jadelle_Implant = np.array([
    {"catid": 187, "prodcode": 13076, "descr": ""},
])

# =============================================================================
# SUMMARY — J.py
# =============================================================================
# Categories in this file : 1
# Total product entries    : 1
# Duplicate entries removed: 0
#
# Breakdown by category:
#   Jadelle_Implant (catid=187): 1 products
# =============================================================================
