import numpy as np

# =============================================================================
# M.py
# Service category product assignments — letter M
# Generated by: product-service-mapper skill
# =============================================================================
"""
Major_Surgeries = np.array([
    {"catid": 287, "prodcode": 10911, "descr": ""},
    {"catid": 287, "prodcode": 10912, "descr": ""},
    {"catid": 287, "prodcode": 11285, "descr": ""},
    {"catid": 287, "prodcode": 11314, "descr": ""},
    {"catid": 287, "prodcode": 11337, "descr": ""},
    {"catid": 287, "prodcode": 11338, "descr": ""},
    {"catid": 287, "prodcode": 11573, "descr": ""},
    {"catid": 287, "prodcode": 11742, "descr": ""},
    {"catid": 287, "prodcode": 11909, "descr": ""},
    {"catid": 287, "prodcode": 12345, "descr": ""},
    {"catid": 287, "prodcode": 12554, "descr": ""},
    {"catid": 287, "prodcode": 12570, "descr": ""},
    {"catid": 287, "prodcode": 12576, "descr": ""},
    {"catid": 287, "prodcode": 12789, "descr": ""},
    {"catid": 287, "prodcode": 12790, "descr": ""},
    {"catid": 287, "prodcode": 12963, "descr": ""},
    {"catid": 287, "prodcode": 12964, "descr": ""},
    {"catid": 287, "prodcode": 13402, "descr": ""},
    {"catid": 287, "prodcode": 13439, "descr": ""},
    {"catid": 287, "prodcode": 13447, "descr": ""},
    {"catid": 287, "prodcode": 13574, "descr": ""},
    {"catid": 287, "prodcode": 13575, "descr": ""},
    {"catid": 287, "prodcode": 13588, "descr": ""},
    {"catid": 287, "prodcode": 13592, "descr": ""},
    {"catid": 287, "prodcode": 13594, "descr": ""},
])

Malaria_Parasite = np.array([
    {"catid": 230, "prodcode": 11513, "descr": ""},
    {"catid": 230, "prodcode": 11514, "descr": ""},
    {"catid": 230, "prodcode": 11550, "descr": ""},
    {"catid": 230, "prodcode": 11551, "descr": ""},
    {"catid": 230, "prodcode": 11552, "descr": ""},
    {"catid": 230, "prodcode": 11553, "descr": ""},
    {"catid": 230, "prodcode": 12746, "descr": ""},
    {"catid": 230, "prodcode": 12998, "descr": ""},
    {"catid": 230, "prodcode": 12999, "descr": ""},
    {"catid": 230, "prodcode": 13430, "descr": ""},
])

Male_Circumcision_and_Ear_piercing_within_first_6_wks = np.array([
    {"catid": 225, "prodcode": 11288, "descr": ""},
    {"catid": 225, "prodcode": 11289, "descr": ""},
    {"catid": 225, "prodcode": 11316, "descr": ""},
    {"catid": 225, "prodcode": 11317, "descr": ""},
    {"catid": 225, "prodcode": 11318, "descr": ""},
    {"catid": 225, "prodcode": 11319, "descr": ""},
    {"catid": 225, "prodcode": 11320, "descr": ""},
])

Mammography_For_Women_40_Years_Of_Age = np.array([
    {"catid": 291, "prodcode": 12596, "descr": ""},
    {"catid": 291, "prodcode": 12783, "descr": ""},
])

Mandibles_or_Temporomandibular_Joint_X_Rays = np.array([
    {"catid": 128, "prodcode": 11321, "descr": ""},
    {"catid": 128, "prodcode": 11322, "descr": ""},
    {"catid": 128, "prodcode": 11929, "descr": ""},
    {"catid": 128, "prodcode": 11930, "descr": ""},
    {"catid": 128, "prodcode": 11931, "descr": ""},
    {"catid": 128, "prodcode": 12597, "descr": ""},
    {"catid": 128, "prodcode": 12598, "descr": ""},
    {"catid": 128, "prodcode": 12599, "descr": ""},
    {"catid": 128, "prodcode": 12985, "descr": ""},
    {"catid": 128, "prodcode": 13014, "descr": ""},
    {"catid": 128, "prodcode": 13058, "descr": ""},
    {"catid": 128, "prodcode": 13148, "descr": ""},
])

Mantoux_Heaf_s_Test = np.array([
    {"catid": 247, "prodcode": 11513, "descr": ""},
    {"catid": 247, "prodcode": 11514, "descr": ""},
    {"catid": 247, "prodcode": 11550, "descr": ""},
    {"catid": 247, "prodcode": 11551, "descr": ""},
    {"catid": 247, "prodcode": 11552, "descr": ""},
    {"catid": 247, "prodcode": 11553, "descr": ""},
    {"catid": 247, "prodcode": 12998, "descr": ""},
    {"catid": 247, "prodcode": 12999, "descr": ""},
    {"catid": 247, "prodcode": 13430, "descr": ""},
])

Mastoid_X_rays = np.array([
    {"catid": 131, "prodcode": 12600, "descr": ""},
    {"catid": 131, "prodcode": 13463, "descr": ""},
])

MCH = np.array([
    {"catid": 202, "prodcode": 11393, "descr": ""},
    {"catid": 202, "prodcode": 12030, "descr": ""},
])

MCHC = np.array([
    {"catid": 210, "prodcode": 11393, "descr": ""},
    {"catid": 210, "prodcode": 12030, "descr": ""},
    {"catid": 210, "prodcode": 12754, "descr": ""},
])

MCV = np.array([
    {"catid": 203, "prodcode": 12754, "descr": ""},
])

Measles = np.array([
    {"catid": 79, "prodcode": 12756, "descr": ""},
    {"catid": 79, "prodcode": 12803, "descr": ""},
    {"catid": 79, "prodcode": 12804, "descr": ""},
    {"catid": 79, "prodcode": 12817, "descr": ""},
    {"catid": 79, "prodcode": 12818, "descr": ""},
    {"catid": 79, "prodcode": 12820, "descr": ""},
    {"catid": 79, "prodcode": 12821, "descr": ""},
])

Meningitis = np.array([
    {"catid": 95, "prodcode": 12806, "descr": ""},
    {"catid": 95, "prodcode": 12807, "descr": ""},
    {"catid": 95, "prodcode": 12808, "descr": ""},
    {"catid": 95, "prodcode": 12809, "descr": ""},
    {"catid": 95, "prodcode": 12810, "descr": ""},
    {"catid": 95, "prodcode": 12811, "descr": ""},
    {"catid": 95, "prodcode": 12812, "descr": ""},
    {"catid": 95, "prodcode": 12814, "descr": ""},
    {"catid": 95, "prodcode": 12815, "descr": ""},
    {"catid": 95, "prodcode": 13354, "descr": ""},
    {"catid": 95, "prodcode": 13355, "descr": ""},
    {"catid": 95, "prodcode": 13460, "descr": ""},
    {"catid": 95, "prodcode": 13461, "descr": ""},
    {"catid": 95, "prodcode": 13462, "descr": ""},
    {"catid": 95, "prodcode": 13463, "descr": ""},
    {"catid": 95, "prodcode": 13464, "descr": ""},
    {"catid": 95, "prodcode": 13465, "descr": ""},
    {"catid": 95, "prodcode": 13466, "descr": ""},
    {"catid": 95, "prodcode": 13467, "descr": ""},
    {"catid": 95, "prodcode": 13556, "descr": ""},
])

Mental_Illness_Care_With_Certified_Psychiatrists_Outpatient_Care_Only = np.array([
    {"catid": 86, "prodcode": 12308, "descr": ""},
    {"catid": 86, "prodcode": 12948, "descr": ""},
    {"catid": 86, "prodcode": 12949, "descr": ""},
])

Microbiology_And_Parasitology = np.array([
    {"catid": 33, "prodcode": 10776, "descr": ""},
    {"catid": 33, "prodcode": 10777, "descr": ""},
    {"catid": 33, "prodcode": 10778, "descr": ""},
    {"catid": 33, "prodcode": 10779, "descr": ""},
    {"catid": 33, "prodcode": 10780, "descr": ""},
    {"catid": 33, "prodcode": 11214, "descr": ""},
    {"catid": 33, "prodcode": 11221, "descr": ""},
    {"catid": 33, "prodcode": 11263, "descr": ""},
    {"catid": 33, "prodcode": 11291, "descr": ""},
    {"catid": 33, "prodcode": 11292, "descr": ""},
    {"catid": 33, "prodcode": 11518, "descr": ""},
    {"catid": 33, "prodcode": 11520, "descr": ""},
    {"catid": 33, "prodcode": 11677, "descr": ""},
    {"catid": 33, "prodcode": 11678, "descr": ""},
    {"catid": 33, "prodcode": 11680, "descr": ""},
    {"catid": 33, "prodcode": 11686, "descr": ""},
    {"catid": 33, "prodcode": 11687, "descr": ""},
    {"catid": 33, "prodcode": 11689, "descr": ""},
    {"catid": 33, "prodcode": 11700, "descr": ""},
    {"catid": 33, "prodcode": 11701, "descr": ""},
    {"catid": 33, "prodcode": 11881, "descr": ""},
    {"catid": 33, "prodcode": 11901, "descr": ""},
    {"catid": 33, "prodcode": 11902, "descr": ""},
    {"catid": 33, "prodcode": 12152, "descr": ""},
    {"catid": 33, "prodcode": 12153, "descr": ""},
    {"catid": 33, "prodcode": 12154, "descr": ""},
    {"catid": 33, "prodcode": 12155, "descr": ""},
    {"catid": 33, "prodcode": 12176, "descr": ""},
    {"catid": 33, "prodcode": 12179, "descr": ""},
    {"catid": 33, "prodcode": 12181, "descr": ""},
    {"catid": 33, "prodcode": 12182, "descr": ""},
    {"catid": 33, "prodcode": 12534, "descr": ""},
    {"catid": 33, "prodcode": 12535, "descr": ""},
    {"catid": 33, "prodcode": 12536, "descr": ""},
    {"catid": 33, "prodcode": 12537, "descr": ""},
    {"catid": 33, "prodcode": 12744, "descr": ""},
    {"catid": 33, "prodcode": 12747, "descr": ""},
    {"catid": 33, "prodcode": 12758, "descr": ""},
    {"catid": 33, "prodcode": 12760, "descr": ""},
    {"catid": 33, "prodcode": 12761, "descr": ""},
    {"catid": 33, "prodcode": 12936, "descr": ""},
    {"catid": 33, "prodcode": 12937, "descr": ""},
    {"catid": 33, "prodcode": 12938, "descr": ""},
    {"catid": 33, "prodcode": 12977, "descr": ""},
    {"catid": 33, "prodcode": 12984, "descr": ""},
    {"catid": 33, "prodcode": 13306, "descr": ""},
    {"catid": 33, "prodcode": 13307, "descr": ""},
    {"catid": 33, "prodcode": 13314, "descr": ""},
    {"catid": 33, "prodcode": 13317, "descr": ""},
    {"catid": 33, "prodcode": 13328, "descr": ""},
    {"catid": 33, "prodcode": 13330, "descr": ""},
    {"catid": 33, "prodcode": 13339, "descr": ""},
    {"catid": 33, "prodcode": 13343, "descr": ""},
    {"catid": 33, "prodcode": 13344, "descr": ""},
    {"catid": 33, "prodcode": 13347, "descr": ""},
    {"catid": 33, "prodcode": 13350, "descr": ""},
    {"catid": 33, "prodcode": 13356, "descr": ""},
    {"catid": 33, "prodcode": 13357, "descr": ""},
    {"catid": 33, "prodcode": 13358, "descr": ""},
    {"catid": 33, "prodcode": 13361, "descr": ""},
    {"catid": 33, "prodcode": 13362, "descr": ""},
    {"catid": 33, "prodcode": 13363, "descr": ""},
    {"catid": 33, "prodcode": 13364, "descr": ""},
    {"catid": 33, "prodcode": 13392, "descr": ""},
    {"catid": 33, "prodcode": 13481, "descr": ""},
    {"catid": 33, "prodcode": 13553, "descr": ""},
    {"catid": 33, "prodcode": 13556, "descr": ""},
    {"catid": 33, "prodcode": 13796, "descr": ""},
    {"catid": 33, "prodcode": 13797, "descr": ""},
    {"catid": 33, "prodcode": 13799, "descr": ""},
    {"catid": 33, "prodcode": 13829, "descr": ""},
    {"catid": 33, "prodcode": 13834, "descr": ""},
    {"catid": 33, "prodcode": 13835, "descr": ""},
])
"""

Minor_Surgeries = np.array([
    {"catid": 285, "prodcode": 10819, "descr": ""},
    {"catid": 285, "prodcode": 10830, "descr": ""},
    {"catid": 285, "prodcode": 10832, "descr": ""},
    {"catid": 285, "prodcode": 10833, "descr": ""},
    {"catid": 285, "prodcode": 10834, "descr": ""},
    {"catid": 285, "prodcode": 11316, "descr": ""},
    {"catid": 285, "prodcode": 11317, "descr": ""},
    {"catid": 285, "prodcode": 11318, "descr": ""},
    {"catid": 285, "prodcode": 11319, "descr": ""},
    {"catid": 285, "prodcode": 11320, "descr": ""},
    {"catid": 285, "prodcode": 11330, "descr": ""},
    {"catid": 285, "prodcode": 11515, "descr": ""},
    {"catid": 285, "prodcode": 11558, "descr": ""},
    {"catid": 285, "prodcode": 11559, "descr": ""},
    {"catid": 285, "prodcode": 11561, "descr": ""},
    {"catid": 285, "prodcode": 11562, "descr": ""},
    {"catid": 285, "prodcode": 11574, "descr": ""},
    {"catid": 285, "prodcode": 11713, "descr": ""},
    {"catid": 285, "prodcode": 11737, "descr": ""},
    {"catid": 285, "prodcode": 11738, "descr": ""},
    {"catid": 285, "prodcode": 11746, "descr": ""},
    {"catid": 285, "prodcode": 11925, "descr": ""},
    {"catid": 285, "prodcode": 11926, "descr": ""},
    {"catid": 285, "prodcode": 11928, "descr": ""},
    {"catid": 285, "prodcode": 11933, "descr": ""},
    {"catid": 285, "prodcode": 11934, "descr": ""},
    {"catid": 285, "prodcode": 12041, "descr": ""},
    {"catid": 285, "prodcode": 12043, "descr": ""},
    {"catid": 285, "prodcode": 12189, "descr": ""},
    {"catid": 285, "prodcode": 12225, "descr": ""},
    {"catid": 285, "prodcode": 12344, "descr": ""},
    {"catid": 285, "prodcode": 12353, "descr": ""},
    {"catid": 285, "prodcode": 12354, "descr": ""},
    {"catid": 285, "prodcode": 12355, "descr": ""},
    {"catid": 285, "prodcode": 12357, "descr": ""},
    {"catid": 285, "prodcode": 12376, "descr": ""},
    {"catid": 285, "prodcode": 12388, "descr": ""},
    {"catid": 285, "prodcode": 12416, "descr": ""},
    {"catid": 285, "prodcode": 12417, "descr": ""},
    {"catid": 285, "prodcode": 12524, "descr": ""},
    {"catid": 285, "prodcode": 12569, "descr": ""},
    {"catid": 285, "prodcode": 12579, "descr": ""},
    {"catid": 285, "prodcode": 12786, "descr": ""},
    {"catid": 285, "prodcode": 12787, "descr": ""},
    {"catid": 285, "prodcode": 12960, "descr": ""},
    {"catid": 285, "prodcode": 12961, "descr": ""},
    {"catid": 285, "prodcode": 12963, "descr": ""},
    {"catid": 285, "prodcode": 12967, "descr": ""},
    {"catid": 285, "prodcode": 12968, "descr": ""},
    {"catid": 285, "prodcode": 13398, "descr": ""},
    {"catid": 285, "prodcode": 13438, "descr": ""},
    {"catid": 285, "prodcode": 13448, "descr": ""},
    {"catid": 285, "prodcode": 13858, "descr": ""},
])

Mmr = np.array([
    {"catid": 93, "prodcode": 12816, "descr": ""},
    {"catid": 93, "prodcode": 12817, "descr": ""},
    {"catid": 93, "prodcode": 12818, "descr": ""},
    {"catid": 93, "prodcode": 12820, "descr": ""},
    {"catid": 93, "prodcode": 12821, "descr": ""},
    {"catid": 93, "prodcode": 13470, "descr": ""},
])

MRI = np.array([
    {"catid": 98, "prodcode": 10890, "descr": ""},
    {"catid": 98, "prodcode": 12602, "descr": ""},
    {"catid": 98, "prodcode": 12603, "descr": ""},
    {"catid": 98, "prodcode": 12604, "descr": ""},
    {"catid": 98, "prodcode": 12605, "descr": ""},
    {"catid": 98, "prodcode": 12606, "descr": ""},
    {"catid": 98, "prodcode": 12607, "descr": ""},
    {"catid": 98, "prodcode": 12985, "descr": ""},
    {"catid": 98, "prodcode": 13058, "descr": ""},
    {"catid": 98, "prodcode": 13066, "descr": ""},
])

# =============================================================================
# SUMMARY — M.py
# =============================================================================
# Categories in this file : 18
# Total product entries    : 245
# Duplicate entries removed: 0
#
# Breakdown by category:
#   Major_Surgeries (catid=287): 25 products
#   Malaria_Parasite (catid=230): 10 products
#   Male_Circumcision_and_Ear_piercing_within_first_6_wks (catid=225): 7 products
#   Mammography_For_Women_40_Years_Of_Age (catid=291): 2 products
#   Mandibles_or_Temporomandibular_Joint_X_Rays (catid=128): 12 products
#   Mantoux_Heaf_s_Test (catid=247): 9 products
#   Mastoid_X_rays (catid=131): 2 products
#   MCH (catid=202): 2 products
#   MCHC (catid=210): 3 products
#   MCV (catid=203): 1 products
#   Measles (catid=79): 7 products
#   Meningitis (catid=95): 20 products
#   Mental_Illness_Care_With_Certified_Psychiatrists_Outpatient_Care_Only (catid=86): 3 products
#   Microbiology_And_Parasitology (catid=33): 73 products
#   Minor_Surgeries (catid=285): 53 products
#   Mmr (catid=93): 6 products
#   Mortuary_Services (catid=53): (no products — variable omitted)
#   MRI (catid=98): 10 products
# =============================================================================
