import numpy as np

# =============================================================================
# N.py
# Service category product assignments — letter N
# Generated by: product-service-mapper skill
# =============================================================================

Neck_X_rays = np.array([
    {"catid": 122, "prodcode": 10893, "descr": ""},
    {"catid": 122, "prodcode": 10894, "descr": ""},
    {"catid": 122, "prodcode": 10895, "descr": ""},
    {"catid": 122, "prodcode": 10896, "descr": ""},
    {"catid": 122, "prodcode": 10897, "descr": ""},
    {"catid": 122, "prodcode": 11197, "descr": ""},
    {"catid": 122, "prodcode": 11238, "descr": ""},
    {"catid": 122, "prodcode": 11295, "descr": ""},
    {"catid": 122, "prodcode": 11303, "descr": ""},
    {"catid": 122, "prodcode": 11305, "descr": ""},
    {"catid": 122, "prodcode": 11307, "descr": ""},
    {"catid": 122, "prodcode": 11308, "descr": ""},
    {"catid": 122, "prodcode": 11309, "descr": ""},
    {"catid": 122, "prodcode": 11321, "descr": ""},
    {"catid": 122, "prodcode": 11322, "descr": ""},
    {"catid": 122, "prodcode": 11731, "descr": ""},
    {"catid": 122, "prodcode": 11929, "descr": ""},
    {"catid": 122, "prodcode": 11930, "descr": ""},
    {"catid": 122, "prodcode": 11931, "descr": ""},
    {"catid": 122, "prodcode": 12598, "descr": ""},
    {"catid": 122, "prodcode": 12768, "descr": ""},
    {"catid": 122, "prodcode": 12985, "descr": ""},
    {"catid": 122, "prodcode": 13014, "descr": ""},
    {"catid": 122, "prodcode": 13058, "descr": ""},
    {"catid": 122, "prodcode": 13148, "descr": ""},
])

Neonatologist = np.array([
    {"catid": 280, "prodcode": 10857, "descr": ""},
    {"catid": 280, "prodcode": 10858, "descr": ""},
    {"catid": 280, "prodcode": 11302, "descr": ""},
    {"catid": 280, "prodcode": 11586, "descr": ""},
    {"catid": 280, "prodcode": 11602, "descr": ""},
    {"catid": 280, "prodcode": 12371, "descr": ""},
    {"catid": 280, "prodcode": 12372, "descr": ""},
    {"catid": 280, "prodcode": 12822, "descr": ""},
    {"catid": 280, "prodcode": 12825, "descr": ""},
    {"catid": 280, "prodcode": 12962, "descr": ""},
    {"catid": 280, "prodcode": 13159, "descr": ""},
    {"catid": 280, "prodcode": 13160, "descr": ""},
])

Nephrologist = np.array([
    {"catid": 278, "prodcode": 11376, "descr": ""},
    {"catid": 278, "prodcode": 11683, "descr": ""},
    {"catid": 278, "prodcode": 11685, "descr": ""},
    {"catid": 278, "prodcode": 12826, "descr": ""},
    {"catid": 278, "prodcode": 12827, "descr": ""},
])

Neurologist = np.array([
    {"catid": 277, "prodcode": 12830, "descr": ""},
])

Neurosurgeon = np.array([
    {"catid": 268, "prodcode": 11549, "descr": ""},
    {"catid": 268, "prodcode": 12840, "descr": ""},
    {"catid": 268, "prodcode": 13417, "descr": ""},
    {"catid": 268, "prodcode": 13618, "descr": ""},
])

Non_surgical_extraction = np.array([
    {"catid": 173, "prodcode": 11548, "descr": ""},
    {"catid": 173, "prodcode": 11549, "descr": ""},
    {"catid": 173, "prodcode": 11747, "descr": ""},
    {"catid": 173, "prodcode": 12786, "descr": ""},
    {"catid": 173, "prodcode": 12787, "descr": ""},
    {"catid": 173, "prodcode": 12840, "descr": ""},
    {"catid": 173, "prodcode": 13618, "descr": ""},
])

Norplant = np.array([
    {"catid": 191, "prodcode": 11020, "descr": ""},
    {"catid": 191, "prodcode": 11820, "descr": ""},
    {"catid": 191, "prodcode": 13076, "descr": ""},
])

Npi_Immunization_0_5_Years = np.array([
    {"catid": 40, "prodcode": 11472, "descr": ""},
    {"catid": 40, "prodcode": 11599, "descr": ""},
    {"catid": 40, "prodcode": 11722, "descr": ""},
    {"catid": 40, "prodcode": 12383, "descr": ""},
    {"catid": 40, "prodcode": 12449, "descr": ""},
    {"catid": 40, "prodcode": 12583, "descr": ""},
    {"catid": 40, "prodcode": 13044, "descr": ""},
    {"catid": 40, "prodcode": 13045, "descr": ""},
    {"catid": 40, "prodcode": 13486, "descr": ""},
    {"catid": 40, "prodcode": 13713, "descr": ""},
    {"catid": 40, "prodcode": 13715, "descr": ""},
])

Number_of_Sessions_Covered = np.array([
    {"catid": 223, "prodcode": 10859, "descr": ""},
    {"catid": 223, "prodcode": 11528, "descr": ""},
    {"catid": 223, "prodcode": 12370, "descr": ""},
    {"catid": 223, "prodcode": 12777, "descr": ""},
    {"catid": 223, "prodcode": 13401, "descr": ""},
])

Nursing_Care_and_Consumables = np.array([
    {"catid": 214, "prodcode": 10806, "descr": ""},
    {"catid": 214, "prodcode": 10807, "descr": ""},
    {"catid": 214, "prodcode": 11273, "descr": ""},
    {"catid": 214, "prodcode": 11274, "descr": ""},
    {"catid": 214, "prodcode": 11275, "descr": ""},
    {"catid": 214, "prodcode": 11276, "descr": ""},
    {"catid": 214, "prodcode": 11277, "descr": ""},
    {"catid": 214, "prodcode": 11281, "descr": ""},
    {"catid": 214, "prodcode": 11283, "descr": ""},
    {"catid": 214, "prodcode": 11286, "descr": ""},
    {"catid": 214, "prodcode": 11287, "descr": ""},
    {"catid": 214, "prodcode": 11290, "descr": ""},
    {"catid": 214, "prodcode": 11293, "descr": ""},
    {"catid": 214, "prodcode": 11294, "descr": ""},
    {"catid": 214, "prodcode": 11702, "descr": ""},
    {"catid": 214, "prodcode": 11904, "descr": ""},
    {"catid": 214, "prodcode": 11905, "descr": ""},
    {"catid": 214, "prodcode": 11906, "descr": ""},
    {"catid": 214, "prodcode": 12035, "descr": ""},
    {"catid": 214, "prodcode": 12183, "descr": ""},
    {"catid": 214, "prodcode": 12266, "descr": ""},
    {"catid": 214, "prodcode": 12267, "descr": ""},
    {"catid": 214, "prodcode": 12308, "descr": ""},
    {"catid": 214, "prodcode": 12312, "descr": ""},
    {"catid": 214, "prodcode": 12313, "descr": ""},
    {"catid": 214, "prodcode": 12342, "descr": ""},
    {"catid": 214, "prodcode": 12343, "descr": ""},
    {"catid": 214, "prodcode": 12348, "descr": ""},
    {"catid": 214, "prodcode": 12349, "descr": ""},
    {"catid": 214, "prodcode": 12584, "descr": ""},
    {"catid": 214, "prodcode": 12585, "descr": ""},
    {"catid": 214, "prodcode": 12771, "descr": ""},
    {"catid": 214, "prodcode": 12772, "descr": ""},
    {"catid": 214, "prodcode": 12773, "descr": ""},
    {"catid": 214, "prodcode": 12774, "descr": ""},
    {"catid": 214, "prodcode": 12782, "descr": ""},
    {"catid": 214, "prodcode": 12795, "descr": ""},
    {"catid": 214, "prodcode": 12797, "descr": ""},
    {"catid": 214, "prodcode": 12940, "descr": ""},
    {"catid": 214, "prodcode": 12941, "descr": ""},
    {"catid": 214, "prodcode": 12942, "descr": ""},
    {"catid": 214, "prodcode": 12943, "descr": ""},
    {"catid": 214, "prodcode": 12944, "descr": ""},
    {"catid": 214, "prodcode": 12945, "descr": ""},
    {"catid": 214, "prodcode": 12946, "descr": ""},
    {"catid": 214, "prodcode": 12947, "descr": ""},
    {"catid": 214, "prodcode": 12950, "descr": ""},
    {"catid": 214, "prodcode": 12951, "descr": ""},
    {"catid": 214, "prodcode": 12952, "descr": ""},
    {"catid": 214, "prodcode": 12953, "descr": ""},
    {"catid": 214, "prodcode": 12971, "descr": ""},
    {"catid": 214, "prodcode": 13048, "descr": ""},
    {"catid": 214, "prodcode": 13049, "descr": ""},
    {"catid": 214, "prodcode": 13050, "descr": ""},
    {"catid": 214, "prodcode": 13056, "descr": ""},
    {"catid": 214, "prodcode": 13782, "descr": ""},
    {"catid": 214, "prodcode": 13858, "descr": ""},
])

# =============================================================================
# SUMMARY — N.py
# =============================================================================
# Categories in this file : 10
# Total product entries    : 130
# Duplicate entries removed: 0
#
# Breakdown by category:
#   Neck_X_rays (catid=122): 25 products
#   Neonatologist (catid=280): 12 products
#   Nephrologist (catid=278): 5 products
#   Neurologist (catid=277): 1 products
#   Neurosurgeon (catid=268): 4 products
#   Non_surgical_extraction (catid=173): 7 products
#   Norplant (catid=191): 3 products
#   Npi_Immunization_0_5_Years (catid=40): 11 products
#   Number_of_Sessions_Covered (catid=223): 5 products
#   Nursing_Care_and_Consumables (catid=214): 57 products
# =============================================================================
