import numpy as np

# =============================================================================
# O.py
# Service category product assignments — letter O
# Generated by: product-service-mapper skill
# =============================================================================

Obstetrician = np.array([
    {"catid": 264, "prodcode": 10825, "descr": ""},
    {"catid": 264, "prodcode": 10826, "descr": ""},
    {"catid": 264, "prodcode": 10827, "descr": ""},
    {"catid": 264, "prodcode": 10828, "descr": ""},
    {"catid": 264, "prodcode": 10829, "descr": ""},
    {"catid": 264, "prodcode": 11296, "descr": ""},
    {"catid": 264, "prodcode": 11297, "descr": ""},
    {"catid": 264, "prodcode": 11298, "descr": ""},
    {"catid": 264, "prodcode": 11334, "descr": ""},
    {"catid": 264, "prodcode": 12552, "descr": ""},
    {"catid": 264, "prodcode": 12969, "descr": ""},
    {"catid": 264, "prodcode": 13372, "descr": ""},
    {"catid": 264, "prodcode": 13373, "descr": ""},
    {"catid": 264, "prodcode": 13374, "descr": ""},
    {"catid": 264, "prodcode": 13375, "descr": ""},
    {"catid": 264, "prodcode": 13434, "descr": ""},
    {"catid": 264, "prodcode": 13806, "descr": ""},
])

Obstetrics_And_Gynaecology_Care_In_Patient_Limit_Applies = np.array([
    {"catid": 38, "prodcode": 10825, "descr": ""},
    {"catid": 38, "prodcode": 10826, "descr": ""},
    {"catid": 38, "prodcode": 10827, "descr": ""},
    {"catid": 38, "prodcode": 10828, "descr": ""},
    {"catid": 38, "prodcode": 10829, "descr": ""},
    {"catid": 38, "prodcode": 10854, "descr": ""},
    {"catid": 38, "prodcode": 11296, "descr": ""},
    {"catid": 38, "prodcode": 11297, "descr": ""},
    {"catid": 38, "prodcode": 11298, "descr": ""},
    {"catid": 38, "prodcode": 11310, "descr": ""},
    {"catid": 38, "prodcode": 11334, "descr": ""},
    {"catid": 38, "prodcode": 11549, "descr": ""},
    {"catid": 38, "prodcode": 11710, "descr": ""},
    {"catid": 38, "prodcode": 11756, "descr": ""},
    {"catid": 38, "prodcode": 11908, "descr": ""},
    {"catid": 38, "prodcode": 12552, "descr": ""},
    {"catid": 38, "prodcode": 12778, "descr": ""},
    {"catid": 38, "prodcode": 12779, "descr": ""},
    {"catid": 38, "prodcode": 12840, "descr": ""},
    {"catid": 38, "prodcode": 12969, "descr": ""},
    {"catid": 38, "prodcode": 12989, "descr": ""},
    {"catid": 38, "prodcode": 13372, "descr": ""},
    {"catid": 38, "prodcode": 13373, "descr": ""},
    {"catid": 38, "prodcode": 13374, "descr": ""},
    {"catid": 38, "prodcode": 13375, "descr": ""},
    {"catid": 38, "prodcode": 13572, "descr": ""},
    {"catid": 38, "prodcode": 13573, "descr": ""},
    {"catid": 38, "prodcode": 13608, "descr": ""},
    {"catid": 38, "prodcode": 13618, "descr": ""},
    {"catid": 38, "prodcode": 13664, "descr": ""},
    {"catid": 38, "prodcode": 13806, "descr": ""},
])

Oncological_Investigations = np.array([
    {"catid": 139, "prodcode": 10839, "descr": ""},
    {"catid": 139, "prodcode": 11207, "descr": ""},
    {"catid": 139, "prodcode": 11208, "descr": ""},
    {"catid": 139, "prodcode": 11209, "descr": ""},
    {"catid": 139, "prodcode": 11219, "descr": ""},
    {"catid": 139, "prodcode": 12158, "descr": ""},
    {"catid": 139, "prodcode": 12159, "descr": ""},
    {"catid": 139, "prodcode": 12320, "descr": ""},
    {"catid": 139, "prodcode": 12321, "descr": ""},
    {"catid": 139, "prodcode": 13085, "descr": ""},
    {"catid": 139, "prodcode": 13095, "descr": ""},
    {"catid": 139, "prodcode": 13605, "descr": ""},
])

Oncologist = np.array([
    {"catid": 273, "prodcode": 10840, "descr": ""},
])

Oncologist_Or_Cancer_Specialist_Visits = np.array([
    {"catid": 138, "prodcode": 10853, "descr": ""},
    {"catid": 138, "prodcode": 10854, "descr": ""},
    {"catid": 138, "prodcode": 10855, "descr": ""},
    {"catid": 138, "prodcode": 10856, "descr": ""},
    {"catid": 138, "prodcode": 10857, "descr": ""},
    {"catid": 138, "prodcode": 10858, "descr": ""},
    {"catid": 138, "prodcode": 10859, "descr": ""},
    {"catid": 138, "prodcode": 10860, "descr": ""},
    {"catid": 138, "prodcode": 10861, "descr": ""},
    {"catid": 138, "prodcode": 10862, "descr": ""},
    {"catid": 138, "prodcode": 10863, "descr": ""},
    {"catid": 138, "prodcode": 10864, "descr": ""},
    {"catid": 138, "prodcode": 10865, "descr": ""},
    {"catid": 138, "prodcode": 10866, "descr": ""},
    {"catid": 138, "prodcode": 10867, "descr": ""},
    {"catid": 138, "prodcode": 10868, "descr": ""},
    {"catid": 138, "prodcode": 10869, "descr": ""},
    {"catid": 138, "prodcode": 10870, "descr": ""},
    {"catid": 138, "prodcode": 10871, "descr": ""},
    {"catid": 138, "prodcode": 10872, "descr": ""},
    {"catid": 138, "prodcode": 10873, "descr": ""},
    {"catid": 138, "prodcode": 10874, "descr": ""},
    {"catid": 138, "prodcode": 10875, "descr": ""},
    {"catid": 138, "prodcode": 10876, "descr": ""},
    {"catid": 138, "prodcode": 10877, "descr": ""},
    {"catid": 138, "prodcode": 10878, "descr": ""},
    {"catid": 138, "prodcode": 10879, "descr": ""},
    {"catid": 138, "prodcode": 10880, "descr": ""},
    {"catid": 138, "prodcode": 10881, "descr": ""},
    {"catid": 138, "prodcode": 10882, "descr": ""},
    {"catid": 138, "prodcode": 10883, "descr": ""},
    {"catid": 138, "prodcode": 10884, "descr": ""},
    {"catid": 138, "prodcode": 10885, "descr": ""},
    {"catid": 138, "prodcode": 11359, "descr": ""},
    {"catid": 138, "prodcode": 11361, "descr": ""},
    {"catid": 138, "prodcode": 11372, "descr": ""},
    {"catid": 138, "prodcode": 11549, "descr": ""},
    {"catid": 138, "prodcode": 11751, "descr": ""},
    {"catid": 138, "prodcode": 11939, "descr": ""},
    {"catid": 138, "prodcode": 12592, "descr": ""},
    {"catid": 138, "prodcode": 12840, "descr": ""},
    {"catid": 138, "prodcode": 12990, "descr": ""},
    {"catid": 138, "prodcode": 12991, "descr": ""},
    {"catid": 138, "prodcode": 13020, "descr": ""},
    {"catid": 138, "prodcode": 13026, "descr": ""},
    {"catid": 138, "prodcode": 13618, "descr": ""},
])

Operculectomy = np.array([
    {"catid": 176, "prodcode": 10819, "descr": ""},
    {"catid": 176, "prodcode": 10832, "descr": ""},
    {"catid": 176, "prodcode": 10833, "descr": ""},
    {"catid": 176, "prodcode": 10834, "descr": ""},
    {"catid": 176, "prodcode": 11515, "descr": ""},
    {"catid": 176, "prodcode": 11574, "descr": ""},
    {"catid": 176, "prodcode": 11737, "descr": ""},
    {"catid": 176, "prodcode": 11738, "descr": ""},
    {"catid": 176, "prodcode": 12041, "descr": ""},
    {"catid": 176, "prodcode": 12043, "descr": ""},
    {"catid": 176, "prodcode": 12416, "descr": ""},
    {"catid": 176, "prodcode": 12417, "descr": ""},
    {"catid": 176, "prodcode": 12524, "descr": ""},
    {"catid": 176, "prodcode": 13448, "descr": ""},
])

Opv_Or_Ipv = np.array([
    {"catid": 81, "prodcode": 12214, "descr": ""},
    {"catid": 81, "prodcode": 12991, "descr": ""},
    {"catid": 81, "prodcode": 13029, "descr": ""},
    {"catid": 81, "prodcode": 13044, "descr": ""},
    {"catid": 81, "prodcode": 13045, "descr": ""},
    {"catid": 81, "prodcode": 13122, "descr": ""},
])

Oral_and_Maxillofacial_Surgeon = np.array([
    {"catid": 283, "prodcode": 13076, "descr": ""},
])

Orthopedic_Surgeon = np.array([
    {"catid": 263, "prodcode": 11321, "descr": ""},
    {"catid": 263, "prodcode": 11745, "descr": ""},
    {"catid": 263, "prodcode": 11909, "descr": ""},
    {"catid": 263, "prodcode": 11929, "descr": ""},
    {"catid": 263, "prodcode": 11930, "descr": ""},
    {"catid": 263, "prodcode": 11931, "descr": ""},
    {"catid": 263, "prodcode": 12226, "descr": ""},
    {"catid": 263, "prodcode": 12228, "descr": ""},
    {"catid": 263, "prodcode": 12580, "descr": ""},
    {"catid": 263, "prodcode": 12598, "descr": ""},
    {"catid": 263, "prodcode": 12775, "descr": ""},
    {"catid": 263, "prodcode": 12776, "descr": ""},
    {"catid": 263, "prodcode": 12985, "descr": ""},
    {"catid": 263, "prodcode": 13058, "descr": ""},
    {"catid": 263, "prodcode": 13066, "descr": ""},
    {"catid": 263, "prodcode": 13072, "descr": ""},
    {"catid": 263, "prodcode": 13148, "descr": ""},
    {"catid": 263, "prodcode": 13588, "descr": ""},
])

Osmotic_Fragility_Test = np.array([
    {"catid": 327, "prodcode": 11155, "descr": ""},
    {"catid": 327, "prodcode": 11384, "descr": ""},
    {"catid": 327, "prodcode": 11389, "descr": ""},
    {"catid": 327, "prodcode": 11390, "descr": ""},
    {"catid": 327, "prodcode": 11392, "descr": ""},
    {"catid": 327, "prodcode": 11419, "descr": ""},
    {"catid": 327, "prodcode": 12331, "descr": ""},
    {"catid": 327, "prodcode": 12437, "descr": ""},
    {"catid": 327, "prodcode": 12521, "descr": ""},
    {"catid": 327, "prodcode": 12733, "descr": ""},
    {"catid": 327, "prodcode": 12734, "descr": ""},
    {"catid": 327, "prodcode": 13172, "descr": ""},
])

Out_Patient_care_Limit = np.array([
    {"catid": 57, "prodcode": 10853, "descr": ""},
    {"catid": 57, "prodcode": 10854, "descr": ""},
    {"catid": 57, "prodcode": 10855, "descr": ""},
    {"catid": 57, "prodcode": 10856, "descr": ""},
    {"catid": 57, "prodcode": 10857, "descr": ""},
    {"catid": 57, "prodcode": 10858, "descr": ""},
    {"catid": 57, "prodcode": 10859, "descr": ""},
    {"catid": 57, "prodcode": 10860, "descr": ""},
    {"catid": 57, "prodcode": 10861, "descr": ""},
    {"catid": 57, "prodcode": 10862, "descr": ""},
    {"catid": 57, "prodcode": 10863, "descr": ""},
    {"catid": 57, "prodcode": 10864, "descr": ""},
    {"catid": 57, "prodcode": 10865, "descr": ""},
    {"catid": 57, "prodcode": 10866, "descr": ""},
    {"catid": 57, "prodcode": 10867, "descr": ""},
    {"catid": 57, "prodcode": 10868, "descr": ""},
    {"catid": 57, "prodcode": 10869, "descr": ""},
    {"catid": 57, "prodcode": 10870, "descr": ""},
    {"catid": 57, "prodcode": 10871, "descr": ""},
    {"catid": 57, "prodcode": 10872, "descr": ""},
    {"catid": 57, "prodcode": 10873, "descr": ""},
    {"catid": 57, "prodcode": 10874, "descr": ""},
    {"catid": 57, "prodcode": 10875, "descr": ""},
    {"catid": 57, "prodcode": 10876, "descr": ""},
    {"catid": 57, "prodcode": 10877, "descr": ""},
    {"catid": 57, "prodcode": 10878, "descr": ""},
    {"catid": 57, "prodcode": 10879, "descr": ""},
    {"catid": 57, "prodcode": 10880, "descr": ""},
    {"catid": 57, "prodcode": 10881, "descr": ""},
    {"catid": 57, "prodcode": 10882, "descr": ""},
    {"catid": 57, "prodcode": 10883, "descr": ""},
    {"catid": 57, "prodcode": 10884, "descr": ""},
    {"catid": 57, "prodcode": 10885, "descr": ""},
    {"catid": 57, "prodcode": 11359, "descr": ""},
    {"catid": 57, "prodcode": 11361, "descr": ""},
    {"catid": 57, "prodcode": 11372, "descr": ""},
    {"catid": 57, "prodcode": 11513, "descr": ""},
    {"catid": 57, "prodcode": 11514, "descr": ""},
    {"catid": 57, "prodcode": 11550, "descr": ""},
    {"catid": 57, "prodcode": 11551, "descr": ""},
    {"catid": 57, "prodcode": 11552, "descr": ""},
    {"catid": 57, "prodcode": 11553, "descr": ""},
    {"catid": 57, "prodcode": 11751, "descr": ""},
    {"catid": 57, "prodcode": 11939, "descr": ""},
    {"catid": 57, "prodcode": 12592, "descr": ""},
    {"catid": 57, "prodcode": 12990, "descr": ""},
    {"catid": 57, "prodcode": 12991, "descr": ""},
    {"catid": 57, "prodcode": 12998, "descr": ""},
    {"catid": 57, "prodcode": 12999, "descr": ""},
    {"catid": 57, "prodcode": 13020, "descr": ""},
    {"catid": 57, "prodcode": 13026, "descr": ""},
    {"catid": 57, "prodcode": 13430, "descr": ""},
])

# =============================================================================
# SUMMARY — O.py
# =============================================================================
# Categories in this file : 12
# Total product entries    : 210
# Duplicate entries removed: 0
#
# Breakdown by category:
#   Obstetrician (catid=264): 17 products
#   Obstetrics_And_Gynaecology_Care_In_Patient_Limit_Applies (catid=38): 31 products
#   Oncological_Investigations (catid=139): 12 products
#   Oncologist (catid=273): 1 products
#   Oncologist_Or_Cancer_Specialist_Visits (catid=138): 46 products
#   Operculectomy (catid=176): 14 products
#   Opv_Or_Ipv (catid=81): 6 products
#   Oral_and_Maxillofacial_Surgeon (catid=283): 1 products
#   Oral_Glucose_Tolerance_Test_OGTT (catid=152): (no products — variable omitted)
#   Orthopedic_Surgeon (catid=263): 18 products
#   Osmotic_Fragility_Test (catid=327): 12 products
#   Out_Patient_care_Limit (catid=57): 52 products
# =============================================================================
