import numpy as np

# =============================================================================
# X.py
# Service category product assignments — letter X
# Generated by: product-service-mapper skill
# =============================================================================

X_rays_of_All_Body_Joints = np.array([
    {"catid": 129, "prodcode": 12418, "descr": ""},
    {"catid": 129, "prodcode": 13624, "descr": ""},
])

# =============================================================================
# SUMMARY — X.py
# =============================================================================
# Categories in this file : 1
# Total product entries    : 2
# Duplicate entries removed: 0
#
# Breakdown by category:
#   X_rays_of_All_Body_Joints (catid=129): 2 products
# =============================================================================
