import numpy as np

# =============================================================================
# C.py
# Service category product assignments — letter C
# Generated by: product-service-mapper skill
# =============================================================================

Caesarian_Section_Emergency_covered_to_surgical_limit = np.array([
    {"catid": 256, "prodcode": 29118, "descr": ""},
    {"catid": 256, "prodcode": 29119, "descr": ""},
    {"catid": 256, "prodcode": 29120, "descr": ""},
    {"catid": 256, "prodcode": 29130, "descr": ""},
    {"catid": 256, "prodcode": 29248, "descr": ""},
    {"catid": 256, "prodcode": 29273, "descr": ""},
    {"catid": 256, "prodcode": 29275, "descr": ""},
    {"catid": 256, "prodcode": 29276, "descr": ""},
    {"catid": 256, "prodcode": 29290, "descr": ""},
    {"catid": 256, "prodcode": 29517, "descr": ""},
    {"catid": 256, "prodcode": 29667, "descr": ""},
    {"catid": 256, "prodcode": 29817, "descr": ""},
    {"catid": 256, "prodcode": 29818, "descr": ""},
    {"catid": 256, "prodcode": 29862, "descr": ""},
    {"catid": 256, "prodcode": 29910, "descr": ""},
    {"catid": 256, "prodcode": 31369, "descr": ""},
    {"catid": 256, "prodcode": 31490, "descr": ""},
    {"catid": 256, "prodcode": 31570, "descr": ""},
    {"catid": 256, "prodcode": 31586, "descr": ""},
    {"catid": 256, "prodcode": 31587, "descr": ""},
    {"catid": 256, "prodcode": 31595, "descr": ""},
    {"catid": 256, "prodcode": 31597, "descr": ""},
    {"catid": 256, "prodcode": 31598, "descr": ""},
    {"catid": 256, "prodcode": 31599, "descr": ""},
    {"catid": 256, "prodcode": 31600, "descr": ""},
    {"catid": 256, "prodcode": 31601, "descr": ""},
    {"catid": 256, "prodcode": 31602, "descr": ""},
    {"catid": 256, "prodcode": 31603, "descr": ""},
    {"catid": 256, "prodcode": 31604, "descr": ""},
    {"catid": 256, "prodcode": 31605, "descr": ""},
    {"catid": 256, "prodcode": 31606, "descr": ""},
    {"catid": 256, "prodcode": 31607, "descr": ""},
    {"catid": 256, "prodcode": 31608, "descr": ""},
    {"catid": 256, "prodcode": 31609, "descr": ""},
    {"catid": 256, "prodcode": 31610, "descr": ""},
    {"catid": 256, "prodcode": 31611, "descr": ""},
    {"catid": 256, "prodcode": 31612, "descr": ""},
    {"catid": 256, "prodcode": 31613, "descr": ""},
    {"catid": 256, "prodcode": 31614, "descr": ""},
    {"catid": 256, "prodcode": 31615, "descr": ""},
    {"catid": 256, "prodcode": 31616, "descr": ""},
])

Cancer_Screening_Care = np.array([
    {"catid": 47, "prodcode": 28999, "descr": ""},
    {"catid": 47, "prodcode": 29097, "descr": ""},
    {"catid": 47, "prodcode": 29098, "descr": ""},
    {"catid": 47, "prodcode": 29099, "descr": ""},
    {"catid": 47, "prodcode": 29108, "descr": ""},
    {"catid": 47, "prodcode": 29109, "descr": ""},
    {"catid": 47, "prodcode": 29206, "descr": ""},
    {"catid": 47, "prodcode": 29217, "descr": ""},
    {"catid": 47, "prodcode": 29219, "descr": ""},
    {"catid": 47, "prodcode": 29568, "descr": ""},
    {"catid": 47, "prodcode": 29926, "descr": ""},
    {"catid": 47, "prodcode": 31397, "descr": ""},
    {"catid": 47, "prodcode": 31398, "descr": ""},
    {"catid": 47, "prodcode": 31399, "descr": ""},
    {"catid": 47, "prodcode": 31401, "descr": ""},
    {"catid": 47, "prodcode": 31405, "descr": ""},
    {"catid": 47, "prodcode": 31406, "descr": ""},
    {"catid": 47, "prodcode": 31407, "descr": ""},
    {"catid": 47, "prodcode": 31408, "descr": ""},
    {"catid": 47, "prodcode": 31410, "descr": ""},
])

Cancer_Related_Radiological_Investigations = np.array([
    {"catid": 140, "prodcode": 29220, "descr": ""},
    {"catid": 140, "prodcode": 29525, "descr": ""},
    {"catid": 140, "prodcode": 29526, "descr": ""},
    {"catid": 140, "prodcode": 30015, "descr": ""},
    {"catid": 140, "prodcode": 31849, "descr": ""},
    {"catid": 140, "prodcode": 31850, "descr": ""},
])

Cardiologist = np.array([
    {"catid": 276, "prodcode": 29962, "descr": ""},
])

Cardiothoracic_Surgeon = np.array([
    {"catid": 267, "prodcode": 29125, "descr": ""},
    {"catid": 267, "prodcode": 29965, "descr": ""},
    {"catid": 267, "prodcode": 30054, "descr": ""},
    {"catid": 267, "prodcode": 30055, "descr": ""},
    {"catid": 267, "prodcode": 30138, "descr": ""},
    {"catid": 267, "prodcode": 30139, "descr": ""},
    {"catid": 267, "prodcode": 30141, "descr": ""},
    {"catid": 267, "prodcode": 30142, "descr": ""},
    {"catid": 267, "prodcode": 31618, "descr": ""},
    {"catid": 267, "prodcode": 31760, "descr": ""},
    {"catid": 267, "prodcode": 32282, "descr": ""},
])

Cervical_Collar_and_Crutches = np.array([
    {"catid": 220, "prodcode": 29079, "descr": ""},
    {"catid": 220, "prodcode": 29080, "descr": ""},
    {"catid": 220, "prodcode": 29863, "descr": ""},
    {"catid": 220, "prodcode": 29991, "descr": ""},
    {"catid": 220, "prodcode": 29995, "descr": ""},
    {"catid": 220, "prodcode": 29996, "descr": ""},
    {"catid": 220, "prodcode": 29999, "descr": ""},
    {"catid": 220, "prodcode": 30000, "descr": ""},
    {"catid": 220, "prodcode": 30001, "descr": ""},
    {"catid": 220, "prodcode": 30054, "descr": ""},
    {"catid": 220, "prodcode": 30055, "descr": ""},
    {"catid": 220, "prodcode": 30057, "descr": ""},
    {"catid": 220, "prodcode": 30688, "descr": ""},
    {"catid": 220, "prodcode": 31303, "descr": ""},
    {"catid": 220, "prodcode": 31304, "descr": ""},
    {"catid": 220, "prodcode": 31424, "descr": ""},
    {"catid": 220, "prodcode": 31577, "descr": ""},
    {"catid": 220, "prodcode": 31622, "descr": ""},
    {"catid": 220, "prodcode": 31623, "descr": ""},
    {"catid": 220, "prodcode": 31638, "descr": ""},
    {"catid": 220, "prodcode": 31640, "descr": ""},
    {"catid": 220, "prodcode": 31644, "descr": ""},
    {"catid": 220, "prodcode": 31645, "descr": ""},
    {"catid": 220, "prodcode": 31646, "descr": ""},
    {"catid": 220, "prodcode": 31647, "descr": ""},
    {"catid": 220, "prodcode": 31648, "descr": ""},
    {"catid": 220, "prodcode": 31649, "descr": ""},
    {"catid": 220, "prodcode": 31650, "descr": ""},
    {"catid": 220, "prodcode": 31651, "descr": ""},
    {"catid": 220, "prodcode": 31652, "descr": ""},
    {"catid": 220, "prodcode": 31653, "descr": ""},
    {"catid": 220, "prodcode": 31658, "descr": ""},
    {"catid": 220, "prodcode": 31659, "descr": ""},
    {"catid": 220, "prodcode": 31660, "descr": ""},
    {"catid": 220, "prodcode": 31663, "descr": ""},
    {"catid": 220, "prodcode": 31664, "descr": ""},
    {"catid": 220, "prodcode": 31665, "descr": ""},
    {"catid": 220, "prodcode": 31667, "descr": ""},
    {"catid": 220, "prodcode": 31668, "descr": ""},
    {"catid": 220, "prodcode": 31808, "descr": ""},
    {"catid": 220, "prodcode": 31809, "descr": ""},
    {"catid": 220, "prodcode": 31849, "descr": ""},
])

Cervical_Spine_X_rays = np.array([
    {"catid": 132, "prodcode": 29999, "descr": ""},
])

Chemistry_Investigations = np.array([
    {"catid": 32, "prodcode": 28971, "descr": ""},
    {"catid": 32, "prodcode": 28983, "descr": ""},
    {"catid": 32, "prodcode": 28988, "descr": ""},
    {"catid": 32, "prodcode": 28991, "descr": ""},
    {"catid": 32, "prodcode": 28992, "descr": ""},
    {"catid": 32, "prodcode": 28995, "descr": ""},
    {"catid": 32, "prodcode": 29050, "descr": ""},
    {"catid": 32, "prodcode": 29057, "descr": ""},
    {"catid": 32, "prodcode": 29114, "descr": ""},
    {"catid": 32, "prodcode": 29804, "descr": ""},
    {"catid": 32, "prodcode": 31404, "descr": ""},
])

Chemotherapy = np.array([
    {"catid": 142, "prodcode": 31212, "descr": ""},
])

Chest_X_Ray = np.array([
    {"catid": 301, "prodcode": 29589, "descr": ""},
    {"catid": 301, "prodcode": 30016, "descr": ""},
    {"catid": 301, "prodcode": 30018, "descr": ""},
])

Chest_X_Rays = np.array([
    {"catid": 123, "prodcode": 30016, "descr": ""},
    {"catid": 123, "prodcode": 30018, "descr": ""},
])

Chicken_Pox = np.array([
    {"catid": 92, "prodcode": 30710, "descr": ""},
])

Chlamydia_Screening = np.array([
    {"catid": 331, "prodcode": 31426, "descr": ""},
])

Clotting_Time = np.array([
    {"catid": 333, "prodcode": 31438, "descr": ""},
])

Colonoscopy = np.array([
    {"catid": 118, "prodcode": 30064, "descr": ""},
    {"catid": 118, "prodcode": 31663, "descr": ""},
    {"catid": 118, "prodcode": 31664, "descr": ""},
    {"catid": 118, "prodcode": 31740, "descr": ""},
    {"catid": 118, "prodcode": 31741, "descr": ""},
    {"catid": 118, "prodcode": 31742, "descr": ""},
])

Contraceptive_Pills = np.array([
    {"catid": 186, "prodcode": 29566, "descr": ""},
    {"catid": 186, "prodcode": 31212, "descr": ""},
    {"catid": 186, "prodcode": 31213, "descr": ""},
    {"catid": 186, "prodcode": 31233, "descr": ""},
])

Coomb_s_Test_Direct = np.array([
    {"catid": 326, "prodcode": 28964, "descr": ""},
    {"catid": 326, "prodcode": 29047, "descr": ""},
    {"catid": 326, "prodcode": 31442, "descr": ""},
    {"catid": 326, "prodcode": 31446, "descr": ""},
    {"catid": 326, "prodcode": 31448, "descr": ""},
])

Coomb_s_Test_Indirect = np.array([
    {"catid": 325, "prodcode": 28964, "descr": ""},
    {"catid": 325, "prodcode": 29047, "descr": ""},
    {"catid": 325, "prodcode": 29108, "descr": ""},
    {"catid": 325, "prodcode": 29109, "descr": ""},
    {"catid": 325, "prodcode": 29219, "descr": ""},
    {"catid": 325, "prodcode": 29220, "descr": ""},
    {"catid": 325, "prodcode": 31446, "descr": ""},
    {"catid": 325, "prodcode": 31448, "descr": ""},
])

Copper_T_Intrauterine_Device = np.array([
    {"catid": 189, "prodcode": 31212, "descr": ""},
    {"catid": 189, "prodcode": 31514, "descr": ""},
])

Creatinine_phosphokinase = np.array([
    {"catid": 319, "prodcode": 31435, "descr": ""},
    {"catid": 319, "prodcode": 31436, "descr": ""},
    {"catid": 319, "prodcode": 31457, "descr": ""},
    {"catid": 319, "prodcode": 31459, "descr": ""},
    {"catid": 319, "prodcode": 31460, "descr": ""},
])

CSF_M_C_S_CSF_Analysis = np.array([
    {"catid": 321, "prodcode": 31310, "descr": ""},
    {"catid": 321, "prodcode": 31394, "descr": ""},
    {"catid": 321, "prodcode": 31423, "descr": ""},
    {"catid": 321, "prodcode": 31469, "descr": ""},
])

CT_Scan = np.array([
    {"catid": 116, "prodcode": 29621, "descr": ""},
    {"catid": 116, "prodcode": 29627, "descr": ""},
    {"catid": 116, "prodcode": 29633, "descr": ""},
    {"catid": 116, "prodcode": 29635, "descr": ""},
    {"catid": 116, "prodcode": 29638, "descr": ""},
    {"catid": 116, "prodcode": 29639, "descr": ""},
    {"catid": 116, "prodcode": 29648, "descr": ""},
    {"catid": 116, "prodcode": 29834, "descr": ""},
    {"catid": 116, "prodcode": 29977, "descr": ""},
    {"catid": 116, "prodcode": 29978, "descr": ""},
    {"catid": 116, "prodcode": 29980, "descr": ""},
    {"catid": 116, "prodcode": 29982, "descr": ""},
    {"catid": 116, "prodcode": 30010, "descr": ""},
    {"catid": 116, "prodcode": 30011, "descr": ""},
    {"catid": 116, "prodcode": 30012, "descr": ""},
    {"catid": 116, "prodcode": 30030, "descr": ""},
    {"catid": 116, "prodcode": 30031, "descr": ""},
    {"catid": 116, "prodcode": 30032, "descr": ""},
    {"catid": 116, "prodcode": 30034, "descr": ""},
    {"catid": 116, "prodcode": 30036, "descr": ""},
    {"catid": 116, "prodcode": 30037, "descr": ""},
    {"catid": 116, "prodcode": 30038, "descr": ""},
    {"catid": 116, "prodcode": 30039, "descr": ""},
    {"catid": 116, "prodcode": 30040, "descr": ""},
    {"catid": 116, "prodcode": 30041, "descr": ""},
    {"catid": 116, "prodcode": 30042, "descr": ""},
    {"catid": 116, "prodcode": 30043, "descr": ""},
    {"catid": 116, "prodcode": 30044, "descr": ""},
    {"catid": 116, "prodcode": 30047, "descr": ""},
    {"catid": 116, "prodcode": 30048, "descr": ""},
    {"catid": 116, "prodcode": 30049, "descr": ""},
    {"catid": 116, "prodcode": 30051, "descr": ""},
    {"catid": 116, "prodcode": 30052, "descr": ""},
    {"catid": 116, "prodcode": 30053, "descr": ""},
    {"catid": 116, "prodcode": 30054, "descr": ""},
    {"catid": 116, "prodcode": 30055, "descr": ""},
    {"catid": 116, "prodcode": 30057, "descr": ""},
    {"catid": 116, "prodcode": 30058, "descr": ""},
    {"catid": 116, "prodcode": 30059, "descr": ""},
    {"catid": 116, "prodcode": 30060, "descr": ""},
    {"catid": 116, "prodcode": 30061, "descr": ""},
    {"catid": 116, "prodcode": 30062, "descr": ""},
    {"catid": 116, "prodcode": 30063, "descr": ""},
    {"catid": 116, "prodcode": 30064, "descr": ""},
    {"catid": 116, "prodcode": 30065, "descr": ""},
    {"catid": 116, "prodcode": 30066, "descr": ""},
    {"catid": 116, "prodcode": 30067, "descr": ""},
    {"catid": 116, "prodcode": 30068, "descr": ""},
    {"catid": 116, "prodcode": 30070, "descr": ""},
    {"catid": 116, "prodcode": 30071, "descr": ""},
    {"catid": 116, "prodcode": 30072, "descr": ""},
    {"catid": 116, "prodcode": 30073, "descr": ""},
    {"catid": 116, "prodcode": 30074, "descr": ""},
    {"catid": 116, "prodcode": 30075, "descr": ""},
    {"catid": 116, "prodcode": 30077, "descr": ""},
    {"catid": 116, "prodcode": 30078, "descr": ""},
    {"catid": 116, "prodcode": 30080, "descr": ""},
    {"catid": 116, "prodcode": 30081, "descr": ""},
    {"catid": 116, "prodcode": 30082, "descr": ""},
    {"catid": 116, "prodcode": 30083, "descr": ""},
    {"catid": 116, "prodcode": 30086, "descr": ""},
    {"catid": 116, "prodcode": 30088, "descr": ""},
    {"catid": 116, "prodcode": 30089, "descr": ""},
    {"catid": 116, "prodcode": 30090, "descr": ""},
    {"catid": 116, "prodcode": 30092, "descr": ""},
    {"catid": 116, "prodcode": 30093, "descr": ""},
    {"catid": 116, "prodcode": 30094, "descr": ""},
    {"catid": 116, "prodcode": 30096, "descr": ""},
    {"catid": 116, "prodcode": 30097, "descr": ""},
    {"catid": 116, "prodcode": 30098, "descr": ""},
    {"catid": 116, "prodcode": 30100, "descr": ""},
    {"catid": 116, "prodcode": 30101, "descr": ""},
    {"catid": 116, "prodcode": 30102, "descr": ""},
    {"catid": 116, "prodcode": 30103, "descr": ""},
    {"catid": 116, "prodcode": 30105, "descr": ""},
    {"catid": 116, "prodcode": 30107, "descr": ""},
    {"catid": 116, "prodcode": 30108, "descr": ""},
    {"catid": 116, "prodcode": 30109, "descr": ""},
    {"catid": 116, "prodcode": 30110, "descr": ""},
    {"catid": 116, "prodcode": 30111, "descr": ""},
    {"catid": 116, "prodcode": 30113, "descr": ""},
    {"catid": 116, "prodcode": 30115, "descr": ""},
    {"catid": 116, "prodcode": 30116, "descr": ""},
    {"catid": 116, "prodcode": 30118, "descr": ""},
    {"catid": 116, "prodcode": 30120, "descr": ""},
    {"catid": 116, "prodcode": 30121, "descr": ""},
    {"catid": 116, "prodcode": 30122, "descr": ""},
    {"catid": 116, "prodcode": 30123, "descr": ""},
    {"catid": 116, "prodcode": 30124, "descr": ""},
    {"catid": 116, "prodcode": 30125, "descr": ""},
    {"catid": 116, "prodcode": 30126, "descr": ""},
    {"catid": 116, "prodcode": 30127, "descr": ""},
    {"catid": 116, "prodcode": 30128, "descr": ""},
    {"catid": 116, "prodcode": 30129, "descr": ""},
    {"catid": 116, "prodcode": 30130, "descr": ""},
    {"catid": 116, "prodcode": 30131, "descr": ""},
    {"catid": 116, "prodcode": 30132, "descr": ""},
    {"catid": 116, "prodcode": 30133, "descr": ""},
    {"catid": 116, "prodcode": 30134, "descr": ""},
    {"catid": 116, "prodcode": 30135, "descr": ""},
    {"catid": 116, "prodcode": 30136, "descr": ""},
    {"catid": 116, "prodcode": 30137, "descr": ""},
    {"catid": 116, "prodcode": 30138, "descr": ""},
    {"catid": 116, "prodcode": 30139, "descr": ""},
    {"catid": 116, "prodcode": 30141, "descr": ""},
    {"catid": 116, "prodcode": 30142, "descr": ""},
    {"catid": 116, "prodcode": 30143, "descr": ""},
    {"catid": 116, "prodcode": 30144, "descr": ""},
    {"catid": 116, "prodcode": 30145, "descr": ""},
    {"catid": 116, "prodcode": 30146, "descr": ""},
    {"catid": 116, "prodcode": 30147, "descr": ""},
    {"catid": 116, "prodcode": 30150, "descr": ""},
    {"catid": 116, "prodcode": 30151, "descr": ""},
    {"catid": 116, "prodcode": 30152, "descr": ""},
    {"catid": 116, "prodcode": 30153, "descr": ""},
    {"catid": 116, "prodcode": 30154, "descr": ""},
    {"catid": 116, "prodcode": 30155, "descr": ""},
])

Cystoscopy = np.array([
    {"catid": 119, "prodcode": 28965, "descr": ""},
    {"catid": 119, "prodcode": 28966, "descr": ""},
    {"catid": 119, "prodcode": 28967, "descr": ""},
    {"catid": 119, "prodcode": 28970, "descr": ""},
    {"catid": 119, "prodcode": 31628, "descr": ""},
    {"catid": 119, "prodcode": 31824, "descr": ""},
])

# =============================================================================
# SUMMARY — C.py
# =============================================================================
# Categories in this file : 25
# Total product entries    : 299
# Duplicate entries removed: 0
#
# Breakdown by category:
#   Caesarian_Section_Emergency_covered_to_surgical_limit (catid=256): 41 products
#   Cancer_Screening_Care (catid=47): 20 products
#   Cancer_Related_Radiological_Investigations (catid=140): 6 products
#   Cardiologist (catid=276): 1 products
#   Cardiothoracic_Surgeon (catid=267): 11 products
#   Cervical_Collar_and_Crutches (catid=220): 42 products
#   Cervical_Spine_X_rays (catid=132): 1 products
#   Chemistry_Investigations (catid=32): 11 products
#   Chemotherapy (catid=142): 1 products
#   Chest_X_Ray (catid=301): 3 products
#   Chest_X_Rays (catid=123): 2 products
#   Chicken_Pox (catid=92): 1 products
#   Chlamydia_Screening (catid=331): 1 products
#   Clotting_Time (catid=333): 1 products
#   Colonoscopy (catid=118): 6 products
#   Composite_Filling (catid=178): (no products — variable omitted)
#   Contraceptive_Pills (catid=186): 4 products
#   Coomb_s_Test_Direct (catid=326): 5 products
#   Coomb_s_Test_Indirect (catid=325): 8 products
#   Copper_T_Intrauterine_Device (catid=189): 2 products
#   Counselling_Sessions (catid=212): (no products — variable omitted)
#   Creatinine_phosphokinase (catid=319): 5 products
#   CSF_M_C_S_CSF_Analysis (catid=321): 4 products
#   CT_Scan (catid=116): 117 products
#   Cystoscopy (catid=119): 6 products
# =============================================================================
