import numpy as np

# =============================================================================
# D.py
# Service category product assignments — letter D
# Generated by: product-service-mapper skill
# =============================================================================

D_Dimer = np.array([
    {"catid": 335, "prodcode": 30124, "descr": ""},
])

Delivery_Multiple = np.array([
    {"catid": 253, "prodcode": 29092, "descr": ""},
    {"catid": 253, "prodcode": 29111, "descr": ""},
    {"catid": 253, "prodcode": 29134, "descr": ""},
    {"catid": 253, "prodcode": 29273, "descr": ""},
    {"catid": 253, "prodcode": 29275, "descr": ""},
    {"catid": 253, "prodcode": 29276, "descr": ""},
    {"catid": 253, "prodcode": 29667, "descr": ""},
    {"catid": 253, "prodcode": 31369, "descr": ""},
    {"catid": 253, "prodcode": 31445, "descr": ""},
    {"catid": 253, "prodcode": 31589, "descr": ""},
    {"catid": 253, "prodcode": 31590, "descr": ""},
    {"catid": 253, "prodcode": 31592, "descr": ""},
    {"catid": 253, "prodcode": 31593, "descr": ""},
    {"catid": 253, "prodcode": 31595, "descr": ""},
    {"catid": 253, "prodcode": 31597, "descr": ""},
    {"catid": 253, "prodcode": 31598, "descr": ""},
    {"catid": 253, "prodcode": 31599, "descr": ""},
    {"catid": 253, "prodcode": 31600, "descr": ""},
    {"catid": 253, "prodcode": 31601, "descr": ""},
    {"catid": 253, "prodcode": 31602, "descr": ""},
    {"catid": 253, "prodcode": 31603, "descr": ""},
    {"catid": 253, "prodcode": 31604, "descr": ""},
    {"catid": 253, "prodcode": 31605, "descr": ""},
    {"catid": 253, "prodcode": 31606, "descr": ""},
    {"catid": 253, "prodcode": 31607, "descr": ""},
    {"catid": 253, "prodcode": 31608, "descr": ""},
    {"catid": 253, "prodcode": 31609, "descr": ""},
    {"catid": 253, "prodcode": 31610, "descr": ""},
    {"catid": 253, "prodcode": 31611, "descr": ""},
    {"catid": 253, "prodcode": 31612, "descr": ""},
    {"catid": 253, "prodcode": 31613, "descr": ""},
    {"catid": 253, "prodcode": 31614, "descr": ""},
])

Delivery_SVD_or_Normal_and_Complicated = np.array([
    {"catid": 252, "prodcode": 29125, "descr": ""},
    {"catid": 252, "prodcode": 29130, "descr": ""},
    {"catid": 252, "prodcode": 29273, "descr": ""},
    {"catid": 252, "prodcode": 29275, "descr": ""},
    {"catid": 252, "prodcode": 29276, "descr": ""},
    {"catid": 252, "prodcode": 29280, "descr": ""},
    {"catid": 252, "prodcode": 29633, "descr": ""},
    {"catid": 252, "prodcode": 29667, "descr": ""},
    {"catid": 252, "prodcode": 29922, "descr": ""},
    {"catid": 252, "prodcode": 29923, "descr": ""},
    {"catid": 252, "prodcode": 29924, "descr": ""},
    {"catid": 252, "prodcode": 30132, "descr": ""},
    {"catid": 252, "prodcode": 30133, "descr": ""},
    {"catid": 252, "prodcode": 31570, "descr": ""},
    {"catid": 252, "prodcode": 31702, "descr": ""},
    {"catid": 252, "prodcode": 31802, "descr": ""},
])

Dental_Care = np.array([
    {"catid": 36, "prodcode": 28530, "descr": ""},
    {"catid": 36, "prodcode": 28531, "descr": ""},
    {"catid": 36, "prodcode": 28532, "descr": ""},
    {"catid": 36, "prodcode": 28676, "descr": ""},
    {"catid": 36, "prodcode": 29135, "descr": ""},
    {"catid": 36, "prodcode": 29136, "descr": ""},
    {"catid": 36, "prodcode": 29235, "descr": ""},
    {"catid": 36, "prodcode": 29238, "descr": ""},
    {"catid": 36, "prodcode": 29527, "descr": ""},
    {"catid": 36, "prodcode": 29944, "descr": ""},
    {"catid": 36, "prodcode": 29988, "descr": ""},
    {"catid": 36, "prodcode": 30066, "descr": ""},
    {"catid": 36, "prodcode": 30246, "descr": ""},
    {"catid": 36, "prodcode": 31609, "descr": ""},
    {"catid": 36, "prodcode": 31845, "descr": ""},
])

Dental_pain_therapy = np.array([
    {"catid": 171, "prodcode": 29177, "descr": ""},
    {"catid": 171, "prodcode": 29178, "descr": ""},
    {"catid": 171, "prodcode": 29179, "descr": ""},
    {"catid": 171, "prodcode": 29180, "descr": ""},
    {"catid": 171, "prodcode": 29181, "descr": ""},
    {"catid": 171, "prodcode": 29182, "descr": ""},
    {"catid": 171, "prodcode": 29183, "descr": ""},
    {"catid": 171, "prodcode": 29184, "descr": ""},
    {"catid": 171, "prodcode": 29185, "descr": ""},
    {"catid": 171, "prodcode": 29186, "descr": ""},
    {"catid": 171, "prodcode": 29904, "descr": ""},
])

Dermatologist = np.array([
    {"catid": 281, "prodcode": 31838, "descr": ""},
    {"catid": 281, "prodcode": 31839, "descr": ""},
])

Diagnosis_Confirmation_From_Secondary_And_Tertiary_Care_Centres = np.array([
    {"catid": 259, "prodcode": 29219, "descr": ""},
    {"catid": 259, "prodcode": 29255, "descr": ""},
])

Dialysis_And_All_Related_Care = np.array([
    {"catid": 257, "prodcode": 29096, "descr": ""},
    {"catid": 257, "prodcode": 29148, "descr": ""},
    {"catid": 257, "prodcode": 29149, "descr": ""},
    {"catid": 257, "prodcode": 29666, "descr": ""},
    {"catid": 257, "prodcode": 31417, "descr": ""},
    {"catid": 257, "prodcode": 31510, "descr": ""},
    {"catid": 257, "prodcode": 31571, "descr": ""},
])

Dpt = np.array([
    {"catid": 84, "prodcode": 32308, "descr": ""},
])

# =============================================================================
# SUMMARY — D.py
# =============================================================================
# Categories in this file : 11
# Total product entries    : 87
# Duplicate entries removed: 0
#
# Breakdown by category:
#   D_Dimer (catid=335): 1 products
#   Delivery_Multiple (catid=253): 32 products
#   Delivery_SVD_or_Normal_and_Complicated (catid=252): 16 products
#   Dental_Care (catid=36): 15 products
#   Dental_consultation (catid=338): (no products — variable omitted)
#   Dental_pain_therapy (catid=171): 11 products
#   Dermatologist (catid=281): 2 products
#   Diagnosis_Confirmation_From_Secondary_And_Tertiary_Care_Centres (catid=259): 2 products
#   Dialysis_And_All_Related_Care (catid=257): 7 products
#   Dietician_or_Nutritionist (catid=270): (no products — variable omitted)
#   Dpt (catid=84): 1 products
# =============================================================================
