import numpy as np

# =============================================================================
# F.py
# Service category product assignments — letter F
# Generated by: product-service-mapper skill
# =============================================================================

Facials = np.array([
    {"catid": 194, "prodcode": 29112, "descr": ""},
    {"catid": 194, "prodcode": 29155, "descr": ""},
    {"catid": 194, "prodcode": 29255, "descr": ""},
    {"catid": 194, "prodcode": 30155, "descr": ""},
])

Family_Physician = np.array([
    {"catid": 282, "prodcode": 31775, "descr": ""},
])

Family_Planning_Out_Patient_Limit = np.array([
    {"catid": 43, "prodcode": 31213, "descr": ""},
    {"catid": 43, "prodcode": 31233, "descr": ""},
    {"catid": 43, "prodcode": 31514, "descr": ""},
])

Fasting_Blood_Sugar = np.array([
    {"catid": 149, "prodcode": 29555, "descr": ""},
    {"catid": 149, "prodcode": 29556, "descr": ""},
    {"catid": 149, "prodcode": 29557, "descr": ""},
])

Fertility_Investigations = np.array([
    {"catid": 227, "prodcode": 29043, "descr": ""},
    {"catid": 227, "prodcode": 29220, "descr": ""},
    {"catid": 227, "prodcode": 29525, "descr": ""},
    {"catid": 227, "prodcode": 29526, "descr": ""},
    {"catid": 227, "prodcode": 30015, "descr": ""},
    {"catid": 227, "prodcode": 31212, "descr": ""},
    {"catid": 227, "prodcode": 31454, "descr": ""},
    {"catid": 227, "prodcode": 31469, "descr": ""},
    {"catid": 227, "prodcode": 31849, "descr": ""},
    {"catid": 227, "prodcode": 31850, "descr": ""},
])

Fertility_Specialist_Consultation_and_Counselling = np.array([
    {"catid": 226, "prodcode": 31514, "descr": ""},
])

Full_Blood_Count_and_differentials_FBC = np.array([
    {"catid": 196, "prodcode": 29031, "descr": ""},
])

# =============================================================================
# SUMMARY — F.py
# =============================================================================
# Categories in this file : 7
# Total product entries    : 23
# Duplicate entries removed: 0
#
# Breakdown by category:
#   Facials (catid=194): 4 products
#   Family_Physician (catid=282): 1 products
#   Family_Planning_Out_Patient_Limit (catid=43): 3 products
#   Fasting_Blood_Sugar (catid=149): 3 products
#   Fertility_Investigations (catid=227): 10 products
#   Fertility_Specialist_Consultation_and_Counselling (catid=226): 1 products
#   Full_Blood_Count_and_differentials_FBC (catid=196): 1 products
# =============================================================================
