import numpy as np

# =============================================================================
# K.py
# Service category product assignments — letter K
# Generated by: product-service-mapper skill
# =============================================================================

Kidney_Function_Tests = np.array([
    {"catid": 308, "prodcode": 29808, "descr": ""},
    {"catid": 308, "prodcode": 31429, "descr": ""},
    {"catid": 308, "prodcode": 31470, "descr": ""},
    {"catid": 308, "prodcode": 32018, "descr": ""},
    {"catid": 308, "prodcode": 32116, "descr": ""},
    {"catid": 308, "prodcode": 32117, "descr": ""},
    {"catid": 308, "prodcode": 32118, "descr": ""},
    {"catid": 308, "prodcode": 32119, "descr": ""},
])

# =============================================================================
# SUMMARY — K.py
# =============================================================================
# Categories in this file : 1
# Total product entries    : 8
# Duplicate entries removed: 0
#
# Breakdown by category:
#   Kidney_Function_Tests (catid=308): 8 products
# =============================================================================
