import numpy as np

# =============================================================================
# M.py
# Service category product assignments — letter M
# Generated by: product-service-mapper skill
# =============================================================================

Major_Surgeries = np.array([
    {"catid": 287, "prodcode": 29125, "descr": ""},
    {"catid": 287, "prodcode": 29130, "descr": ""},
    {"catid": 287, "prodcode": 29160, "descr": ""},
    {"catid": 287, "prodcode": 29164, "descr": ""},
    {"catid": 287, "prodcode": 29165, "descr": ""},
    {"catid": 287, "prodcode": 29169, "descr": ""},
    {"catid": 287, "prodcode": 29172, "descr": ""},
    {"catid": 287, "prodcode": 29176, "descr": ""},
    {"catid": 287, "prodcode": 29187, "descr": ""},
    {"catid": 287, "prodcode": 29197, "descr": ""},
    {"catid": 287, "prodcode": 29209, "descr": ""},
    {"catid": 287, "prodcode": 29242, "descr": ""},
    {"catid": 287, "prodcode": 29243, "descr": ""},
    {"catid": 287, "prodcode": 29284, "descr": ""},
    {"catid": 287, "prodcode": 29758, "descr": ""},
    {"catid": 287, "prodcode": 29934, "descr": ""},
    {"catid": 287, "prodcode": 29939, "descr": ""},
    {"catid": 287, "prodcode": 31586, "descr": ""},
    {"catid": 287, "prodcode": 31681, "descr": ""},
    {"catid": 287, "prodcode": 31684, "descr": ""},
    {"catid": 287, "prodcode": 31699, "descr": ""},
    {"catid": 287, "prodcode": 31733, "descr": ""},
    {"catid": 287, "prodcode": 31735, "descr": ""},
    {"catid": 287, "prodcode": 31751, "descr": ""},
    {"catid": 287, "prodcode": 31760, "descr": ""},
    {"catid": 287, "prodcode": 31794, "descr": ""},
    {"catid": 287, "prodcode": 31795, "descr": ""},
    {"catid": 287, "prodcode": 31796, "descr": ""},
    {"catid": 287, "prodcode": 31797, "descr": ""},
    {"catid": 287, "prodcode": 31798, "descr": ""},
    {"catid": 287, "prodcode": 31799, "descr": ""},
    {"catid": 287, "prodcode": 31805, "descr": ""},
    {"catid": 287, "prodcode": 31815, "descr": ""},
    {"catid": 287, "prodcode": 31816, "descr": ""},
])

Male_Circumcision_and_Ear_piercing_within_first_6_wks = np.array([
    {"catid": 225, "prodcode": 31575, "descr": ""},
    {"catid": 225, "prodcode": 31689, "descr": ""},
    {"catid": 225, "prodcode": 31690, "descr": ""},
    {"catid": 225, "prodcode": 31693, "descr": ""},
    {"catid": 225, "prodcode": 31694, "descr": ""},
])

Mammography_For_Women_40_Years_Of_Age = np.array([
    {"catid": 291, "prodcode": 29568, "descr": ""},
])

Mandibles_or_Temporomandibular_Joint_X_Rays = np.array([
    {"catid": 128, "prodcode": 30107, "descr": ""},
    {"catid": 128, "prodcode": 31701, "descr": ""},
    {"catid": 128, "prodcode": 31702, "descr": ""},
    {"catid": 128, "prodcode": 31709, "descr": ""},
    {"catid": 128, "prodcode": 31713, "descr": ""},
    {"catid": 128, "prodcode": 31714, "descr": ""},
    {"catid": 128, "prodcode": 31721, "descr": ""},
    {"catid": 128, "prodcode": 31722, "descr": ""},
    {"catid": 128, "prodcode": 31725, "descr": ""},
    {"catid": 128, "prodcode": 31726, "descr": ""},
    {"catid": 128, "prodcode": 31727, "descr": ""},
    {"catid": 128, "prodcode": 31802, "descr": ""},
    {"catid": 128, "prodcode": 31803, "descr": ""},
])

Mantoux_Heaf_s_Test = np.array([
    {"catid": 247, "prodcode": 29589, "descr": ""},
])

Microbiology_And_Parasitology = np.array([
    {"catid": 33, "prodcode": 28993, "descr": ""},
    {"catid": 33, "prodcode": 29002, "descr": ""},
    {"catid": 33, "prodcode": 29051, "descr": ""},
    {"catid": 33, "prodcode": 29052, "descr": ""},
    {"catid": 33, "prodcode": 29059, "descr": ""},
    {"catid": 33, "prodcode": 29060, "descr": ""},
    {"catid": 33, "prodcode": 29061, "descr": ""},
    {"catid": 33, "prodcode": 29062, "descr": ""},
    {"catid": 33, "prodcode": 29344, "descr": ""},
    {"catid": 33, "prodcode": 29345, "descr": ""},
    {"catid": 33, "prodcode": 31394, "descr": ""},
    {"catid": 33, "prodcode": 31417, "descr": ""},
    {"catid": 33, "prodcode": 31423, "descr": ""},
])

Minor_Surgeries = np.array([
    {"catid": 285, "prodcode": 29130, "descr": ""},
    {"catid": 285, "prodcode": 29139, "descr": ""},
    {"catid": 285, "prodcode": 29140, "descr": ""},
    {"catid": 285, "prodcode": 29146, "descr": ""},
    {"catid": 285, "prodcode": 29177, "descr": ""},
    {"catid": 285, "prodcode": 29178, "descr": ""},
    {"catid": 285, "prodcode": 29179, "descr": ""},
    {"catid": 285, "prodcode": 29180, "descr": ""},
    {"catid": 285, "prodcode": 29181, "descr": ""},
    {"catid": 285, "prodcode": 29182, "descr": ""},
    {"catid": 285, "prodcode": 29183, "descr": ""},
    {"catid": 285, "prodcode": 29184, "descr": ""},
    {"catid": 285, "prodcode": 29185, "descr": ""},
    {"catid": 285, "prodcode": 29186, "descr": ""},
    {"catid": 285, "prodcode": 29189, "descr": ""},
    {"catid": 285, "prodcode": 29191, "descr": ""},
    {"catid": 285, "prodcode": 29213, "descr": ""},
    {"catid": 285, "prodcode": 29214, "descr": ""},
    {"catid": 285, "prodcode": 29227, "descr": ""},
    {"catid": 285, "prodcode": 29248, "descr": ""},
    {"catid": 285, "prodcode": 29257, "descr": ""},
    {"catid": 285, "prodcode": 29267, "descr": ""},
    {"catid": 285, "prodcode": 29270, "descr": ""},
    {"catid": 285, "prodcode": 29368, "descr": ""},
    {"catid": 285, "prodcode": 29662, "descr": ""},
    {"catid": 285, "prodcode": 29758, "descr": ""},
    {"catid": 285, "prodcode": 29864, "descr": ""},
    {"catid": 285, "prodcode": 29904, "descr": ""},
    {"catid": 285, "prodcode": 29911, "descr": ""},
    {"catid": 285, "prodcode": 29912, "descr": ""},
    {"catid": 285, "prodcode": 29940, "descr": ""},
    {"catid": 285, "prodcode": 30157, "descr": ""},
    {"catid": 285, "prodcode": 31490, "descr": ""},
    {"catid": 285, "prodcode": 31496, "descr": ""},
    {"catid": 285, "prodcode": 31572, "descr": ""},
    {"catid": 285, "prodcode": 31574, "descr": ""},
    {"catid": 285, "prodcode": 31575, "descr": ""},
    {"catid": 285, "prodcode": 31689, "descr": ""},
    {"catid": 285, "prodcode": 31690, "descr": ""},
    {"catid": 285, "prodcode": 31693, "descr": ""},
    {"catid": 285, "prodcode": 31694, "descr": ""},
])

Mortuary_Services = np.array([
    {"catid": 53, "prodcode": 31578, "descr": ""},
])

MRI = np.array([
    {"catid": 98, "prodcode": 29645, "descr": ""},
    {"catid": 98, "prodcode": 29664, "descr": ""},
    {"catid": 98, "prodcode": 29853, "descr": ""},
    {"catid": 98, "prodcode": 29979, "descr": ""},
    {"catid": 98, "prodcode": 29981, "descr": ""},
    {"catid": 98, "prodcode": 29983, "descr": ""},
    {"catid": 98, "prodcode": 29986, "descr": ""},
    {"catid": 98, "prodcode": 29989, "descr": ""},
    {"catid": 98, "prodcode": 30019, "descr": ""},
    {"catid": 98, "prodcode": 32615, "descr": ""},
])

# =============================================================================
# SUMMARY — M.py
# =============================================================================
# Categories in this file : 18
# Total product entries    : 119
# Duplicate entries removed: 0
#
# Breakdown by category:
#   Major_Surgeries (catid=287): 34 products
#   Malaria_Parasite (catid=230): (no products — variable omitted)
#   Male_Circumcision_and_Ear_piercing_within_first_6_wks (catid=225): 5 products
#   Mammography_For_Women_40_Years_Of_Age (catid=291): 1 products
#   Mandibles_or_Temporomandibular_Joint_X_Rays (catid=128): 13 products
#   Mantoux_Heaf_s_Test (catid=247): 1 products
#   Mastoid_X_rays (catid=131): (no products — variable omitted)
#   MCH (catid=202): (no products — variable omitted)
#   MCHC (catid=210): (no products — variable omitted)
#   MCV (catid=203): (no products — variable omitted)
#   Measles (catid=79): (no products — variable omitted)
#   Meningitis (catid=95): (no products — variable omitted)
#   Mental_Illness_Care_With_Certified_Psychiatrists_Outpatient_Care_Only (catid=86): (no products — variable omitted)
#   Microbiology_And_Parasitology (catid=33): 13 products
#   Minor_Surgeries (catid=285): 41 products
#   Mmr (catid=93): (no products — variable omitted)
#   Mortuary_Services (catid=53): 1 products
#   MRI (catid=98): 10 products
# =============================================================================
