import numpy as np

# =============================================================================
# O.py
# Service category product assignments — letter O
# Generated by: product-service-mapper skill
# =============================================================================

Obstetrician = np.array([
    {"catid": 264, "prodcode": 29273, "descr": ""},
    {"catid": 264, "prodcode": 29275, "descr": ""},
    {"catid": 264, "prodcode": 29276, "descr": ""},
    {"catid": 264, "prodcode": 29566, "descr": ""},
    {"catid": 264, "prodcode": 29667, "descr": ""},
    {"catid": 264, "prodcode": 31369, "descr": ""},
    {"catid": 264, "prodcode": 31589, "descr": ""},
    {"catid": 264, "prodcode": 31590, "descr": ""},
    {"catid": 264, "prodcode": 31592, "descr": ""},
    {"catid": 264, "prodcode": 31593, "descr": ""},
    {"catid": 264, "prodcode": 31595, "descr": ""},
    {"catid": 264, "prodcode": 31597, "descr": ""},
    {"catid": 264, "prodcode": 31598, "descr": ""},
    {"catid": 264, "prodcode": 31599, "descr": ""},
    {"catid": 264, "prodcode": 31600, "descr": ""},
    {"catid": 264, "prodcode": 31601, "descr": ""},
    {"catid": 264, "prodcode": 31602, "descr": ""},
    {"catid": 264, "prodcode": 31603, "descr": ""},
    {"catid": 264, "prodcode": 31604, "descr": ""},
    {"catid": 264, "prodcode": 31605, "descr": ""},
    {"catid": 264, "prodcode": 31606, "descr": ""},
    {"catid": 264, "prodcode": 31607, "descr": ""},
    {"catid": 264, "prodcode": 31608, "descr": ""},
    {"catid": 264, "prodcode": 31609, "descr": ""},
    {"catid": 264, "prodcode": 31610, "descr": ""},
    {"catid": 264, "prodcode": 31611, "descr": ""},
    {"catid": 264, "prodcode": 31612, "descr": ""},
    {"catid": 264, "prodcode": 31613, "descr": ""},
    {"catid": 264, "prodcode": 31614, "descr": ""},
])

Obstetrics_And_Gynaecology_Care_In_Patient_Limit_Applies = np.array([
    {"catid": 38, "prodcode": 29007, "descr": ""},
    {"catid": 38, "prodcode": 29008, "descr": ""},
    {"catid": 38, "prodcode": 29108, "descr": ""},
    {"catid": 38, "prodcode": 29109, "descr": ""},
    {"catid": 38, "prodcode": 29204, "descr": ""},
    {"catid": 38, "prodcode": 29207, "descr": ""},
    {"catid": 38, "prodcode": 29216, "descr": ""},
    {"catid": 38, "prodcode": 29219, "descr": ""},
    {"catid": 38, "prodcode": 29220, "descr": ""},
    {"catid": 38, "prodcode": 29273, "descr": ""},
    {"catid": 38, "prodcode": 29275, "descr": ""},
    {"catid": 38, "prodcode": 29276, "descr": ""},
    {"catid": 38, "prodcode": 29280, "descr": ""},
    {"catid": 38, "prodcode": 29290, "descr": ""},
    {"catid": 38, "prodcode": 29566, "descr": ""},
    {"catid": 38, "prodcode": 29667, "descr": ""},
    {"catid": 38, "prodcode": 29922, "descr": ""},
    {"catid": 38, "prodcode": 29923, "descr": ""},
    {"catid": 38, "prodcode": 29924, "descr": ""},
    {"catid": 38, "prodcode": 31369, "descr": ""},
    {"catid": 38, "prodcode": 31570, "descr": ""},
    {"catid": 38, "prodcode": 31586, "descr": ""},
    {"catid": 38, "prodcode": 31587, "descr": ""},
    {"catid": 38, "prodcode": 31589, "descr": ""},
    {"catid": 38, "prodcode": 31590, "descr": ""},
    {"catid": 38, "prodcode": 31592, "descr": ""},
    {"catid": 38, "prodcode": 31593, "descr": ""},
    {"catid": 38, "prodcode": 31595, "descr": ""},
    {"catid": 38, "prodcode": 31597, "descr": ""},
    {"catid": 38, "prodcode": 31598, "descr": ""},
    {"catid": 38, "prodcode": 31599, "descr": ""},
    {"catid": 38, "prodcode": 31600, "descr": ""},
    {"catid": 38, "prodcode": 31601, "descr": ""},
    {"catid": 38, "prodcode": 31602, "descr": ""},
    {"catid": 38, "prodcode": 31603, "descr": ""},
    {"catid": 38, "prodcode": 31604, "descr": ""},
    {"catid": 38, "prodcode": 31605, "descr": ""},
    {"catid": 38, "prodcode": 31606, "descr": ""},
    {"catid": 38, "prodcode": 31607, "descr": ""},
    {"catid": 38, "prodcode": 31608, "descr": ""},
    {"catid": 38, "prodcode": 31609, "descr": ""},
    {"catid": 38, "prodcode": 31610, "descr": ""},
    {"catid": 38, "prodcode": 31611, "descr": ""},
    {"catid": 38, "prodcode": 31612, "descr": ""},
    {"catid": 38, "prodcode": 31613, "descr": ""},
    {"catid": 38, "prodcode": 31614, "descr": ""},
])

Oncological_Investigations = np.array([
    {"catid": 139, "prodcode": 28999, "descr": ""},
    {"catid": 139, "prodcode": 29864, "descr": ""},
    {"catid": 139, "prodcode": 31397, "descr": ""},
    {"catid": 139, "prodcode": 31398, "descr": ""},
    {"catid": 139, "prodcode": 31399, "descr": ""},
    {"catid": 139, "prodcode": 31401, "descr": ""},
    {"catid": 139, "prodcode": 31410, "descr": ""},
])

Oncologist_Or_Cancer_Specialist_Visits = np.array([
    {"catid": 138, "prodcode": 29205, "descr": ""},
    {"catid": 138, "prodcode": 29220, "descr": ""},
    {"catid": 138, "prodcode": 29965, "descr": ""},
    {"catid": 138, "prodcode": 29971, "descr": ""},
    {"catid": 138, "prodcode": 29972, "descr": ""},
    {"catid": 138, "prodcode": 29973, "descr": ""},
    {"catid": 138, "prodcode": 29975, "descr": ""},
    {"catid": 138, "prodcode": 29976, "descr": ""},
    {"catid": 138, "prodcode": 31570, "descr": ""},
])

Operculectomy = np.array([
    {"catid": 176, "prodcode": 29662, "descr": ""},
])

Opv_Or_Ipv = np.array([
    {"catid": 81, "prodcode": 29929, "descr": ""},
])

Oral_and_Maxillofacial_Surgeon = np.array([
    {"catid": 283, "prodcode": 31785, "descr": ""},
    {"catid": 283, "prodcode": 31787, "descr": ""},
    {"catid": 283, "prodcode": 31788, "descr": ""},
    {"catid": 283, "prodcode": 31789, "descr": ""},
    {"catid": 283, "prodcode": 31790, "descr": ""},
    {"catid": 283, "prodcode": 31791, "descr": ""},
    {"catid": 283, "prodcode": 31792, "descr": ""},
])

Orthopedic_Surgeon = np.array([
    {"catid": 263, "prodcode": 29221, "descr": ""},
    {"catid": 263, "prodcode": 29263, "descr": ""},
    {"catid": 263, "prodcode": 31709, "descr": ""},
    {"catid": 263, "prodcode": 31710, "descr": ""},
    {"catid": 263, "prodcode": 31713, "descr": ""},
    {"catid": 263, "prodcode": 31714, "descr": ""},
    {"catid": 263, "prodcode": 31715, "descr": ""},
    {"catid": 263, "prodcode": 31716, "descr": ""},
    {"catid": 263, "prodcode": 31721, "descr": ""},
    {"catid": 263, "prodcode": 31722, "descr": ""},
    {"catid": 263, "prodcode": 31726, "descr": ""},
    {"catid": 263, "prodcode": 31727, "descr": ""},
    {"catid": 263, "prodcode": 31803, "descr": ""},
])

Osmotic_Fragility_Test = np.array([
    {"catid": 327, "prodcode": 29543, "descr": ""},
    {"catid": 327, "prodcode": 29928, "descr": ""},
    {"catid": 327, "prodcode": 30965, "descr": ""},
    {"catid": 327, "prodcode": 31029, "descr": ""},
    {"catid": 327, "prodcode": 31190, "descr": ""},
    {"catid": 327, "prodcode": 31192, "descr": ""},
    {"catid": 327, "prodcode": 31193, "descr": ""},
    {"catid": 327, "prodcode": 31883, "descr": ""},
    {"catid": 327, "prodcode": 31887, "descr": ""},
    {"catid": 327, "prodcode": 31901, "descr": ""},
    {"catid": 327, "prodcode": 31902, "descr": ""},
    {"catid": 327, "prodcode": 31903, "descr": ""},
    {"catid": 327, "prodcode": 31904, "descr": ""},
    {"catid": 327, "prodcode": 31905, "descr": ""},
    {"catid": 327, "prodcode": 32312, "descr": ""},
    {"catid": 327, "prodcode": 32317, "descr": ""},
])

Out_Patient_care_Limit = np.array([
    {"catid": 57, "prodcode": 29205, "descr": ""},
    {"catid": 57, "prodcode": 29220, "descr": ""},
    {"catid": 57, "prodcode": 29965, "descr": ""},
    {"catid": 57, "prodcode": 29971, "descr": ""},
    {"catid": 57, "prodcode": 29972, "descr": ""},
    {"catid": 57, "prodcode": 29973, "descr": ""},
    {"catid": 57, "prodcode": 29975, "descr": ""},
    {"catid": 57, "prodcode": 29976, "descr": ""},
])

# =============================================================================
# SUMMARY — O.py
# =============================================================================
# Categories in this file : 12
# Total product entries    : 137
# Duplicate entries removed: 0
#
# Breakdown by category:
#   Obstetrician (catid=264): 29 products
#   Obstetrics_And_Gynaecology_Care_In_Patient_Limit_Applies (catid=38): 46 products
#   Oncological_Investigations (catid=139): 7 products
#   Oncologist (catid=273): (no products — variable omitted)
#   Oncologist_Or_Cancer_Specialist_Visits (catid=138): 9 products
#   Operculectomy (catid=176): 1 products
#   Opv_Or_Ipv (catid=81): 1 products
#   Oral_and_Maxillofacial_Surgeon (catid=283): 7 products
#   Oral_Glucose_Tolerance_Test_OGTT (catid=152): (no products — variable omitted)
#   Orthopedic_Surgeon (catid=263): 13 products
#   Osmotic_Fragility_Test (catid=327): 16 products
#   Out_Patient_care_Limit (catid=57): 8 products
# =============================================================================
