import numpy as np

# =============================================================================
# A.py
# Service category product assignments — letter A
# Generated by: product-service-mapper skill
# =============================================================================

Abdominal_X_Rays = np.array([
    {"catid": 121, "prodcode": 3396, "descr": ""},
    {"catid": 121, "prodcode": 4689, "descr": ""},
])

Accident_And_Emergency_Care_Out_Patient = np.array([
    {"catid": 27, "prodcode": 3134, "descr": ""},
    {"catid": 27, "prodcode": 3135, "descr": ""},
    {"catid": 27, "prodcode": 3285, "descr": ""},
    {"catid": 27, "prodcode": 3313, "descr": ""},
    {"catid": 27, "prodcode": 3314, "descr": ""},
    {"catid": 27, "prodcode": 4621, "descr": ""},
    {"catid": 27, "prodcode": 5028, "descr": ""},
])

Additional_Immunization_0_5_Years = np.array([
    {"catid": 41, "prodcode": 3507, "descr": ""},
])

Additional_Immunization_6_Years_And_Above = np.array([
    {"catid": 42, "prodcode": 3293, "descr": ""},
    {"catid": 42, "prodcode": 3294, "descr": ""},
    {"catid": 42, "prodcode": 3295, "descr": ""},
    {"catid": 42, "prodcode": 3296, "descr": ""},
    {"catid": 42, "prodcode": 3297, "descr": ""},
    {"catid": 42, "prodcode": 3298, "descr": ""},
    {"catid": 42, "prodcode": 3299, "descr": ""},
    {"catid": 42, "prodcode": 4604, "descr": ""},
    {"catid": 42, "prodcode": 4608, "descr": ""},
    {"catid": 42, "prodcode": 4609, "descr": ""},
])

Admission = np.array([
    {"catid": 215, "prodcode": 3134, "descr": ""},
    {"catid": 215, "prodcode": 3135, "descr": ""},
    {"catid": 215, "prodcode": 3285, "descr": ""},
    {"catid": 215, "prodcode": 5028, "descr": ""},
])

Advanced_Diagnostic_Imaging = np.array([
    {"catid": 30, "prodcode": 2624, "descr": ""},
    {"catid": 30, "prodcode": 2631, "descr": ""},
    {"catid": 30, "prodcode": 3470, "descr": ""},
    {"catid": 30, "prodcode": 3788, "descr": ""},
    {"catid": 30, "prodcode": 3808, "descr": ""},
    {"catid": 30, "prodcode": 3812, "descr": ""},
    {"catid": 30, "prodcode": 3827, "descr": ""},
    {"catid": 30, "prodcode": 3829, "descr": ""},
    {"catid": 30, "prodcode": 3868, "descr": ""},
    {"catid": 30, "prodcode": 3915, "descr": ""},
    {"catid": 30, "prodcode": 3930, "descr": ""},
    {"catid": 30, "prodcode": 4597, "descr": ""},
    {"catid": 30, "prodcode": 4696, "descr": ""},
    {"catid": 30, "prodcode": 5103, "descr": ""},
])

Advanced_Laboratory_Investigations_Pathology = np.array([
    {"catid": 34, "prodcode": 3140, "descr": ""},
    {"catid": 34, "prodcode": 3154, "descr": ""},
    {"catid": 34, "prodcode": 3155, "descr": ""},
    {"catid": 34, "prodcode": 3171, "descr": ""},
    {"catid": 34, "prodcode": 3177, "descr": ""},
    {"catid": 34, "prodcode": 3178, "descr": ""},
    {"catid": 34, "prodcode": 3184, "descr": ""},
    {"catid": 34, "prodcode": 3185, "descr": ""},
    {"catid": 34, "prodcode": 3186, "descr": ""},
    {"catid": 34, "prodcode": 3187, "descr": ""},
    {"catid": 34, "prodcode": 3188, "descr": ""},
    {"catid": 34, "prodcode": 3189, "descr": ""},
    {"catid": 34, "prodcode": 3192, "descr": ""},
    {"catid": 34, "prodcode": 3193, "descr": ""},
    {"catid": 34, "prodcode": 3195, "descr": ""},
    {"catid": 34, "prodcode": 3196, "descr": ""},
    {"catid": 34, "prodcode": 3197, "descr": ""},
    {"catid": 34, "prodcode": 3198, "descr": ""},
    {"catid": 34, "prodcode": 3200, "descr": ""},
    {"catid": 34, "prodcode": 3202, "descr": ""},
    {"catid": 34, "prodcode": 3205, "descr": ""},
    {"catid": 34, "prodcode": 3211, "descr": ""},
    {"catid": 34, "prodcode": 3212, "descr": ""},
    {"catid": 34, "prodcode": 3215, "descr": ""},
    {"catid": 34, "prodcode": 3217, "descr": ""},
    {"catid": 34, "prodcode": 3218, "descr": ""},
    {"catid": 34, "prodcode": 3220, "descr": ""},
    {"catid": 34, "prodcode": 3224, "descr": ""},
    {"catid": 34, "prodcode": 3228, "descr": ""},
    {"catid": 34, "prodcode": 3231, "descr": ""},
    {"catid": 34, "prodcode": 3237, "descr": ""},
    {"catid": 34, "prodcode": 3238, "descr": ""},
    {"catid": 34, "prodcode": 3240, "descr": ""},
    {"catid": 34, "prodcode": 3244, "descr": ""},
    {"catid": 34, "prodcode": 3246, "descr": ""},
    {"catid": 34, "prodcode": 3247, "descr": ""},
    {"catid": 34, "prodcode": 3248, "descr": ""},
    {"catid": 34, "prodcode": 3254, "descr": ""},
    {"catid": 34, "prodcode": 3256, "descr": ""},
    {"catid": 34, "prodcode": 3257, "descr": ""},
    {"catid": 34, "prodcode": 3258, "descr": ""},
    {"catid": 34, "prodcode": 3259, "descr": ""},
    {"catid": 34, "prodcode": 3260, "descr": ""},
    {"catid": 34, "prodcode": 3261, "descr": ""},
    {"catid": 34, "prodcode": 3262, "descr": ""},
    {"catid": 34, "prodcode": 3265, "descr": ""},
    {"catid": 34, "prodcode": 3292, "descr": ""},
    {"catid": 34, "prodcode": 3416, "descr": ""},
    {"catid": 34, "prodcode": 3417, "descr": ""},
    {"catid": 34, "prodcode": 3660, "descr": ""},
    {"catid": 34, "prodcode": 3676, "descr": ""},
    {"catid": 34, "prodcode": 3677, "descr": ""},
    {"catid": 34, "prodcode": 3678, "descr": ""},
    {"catid": 34, "prodcode": 3682, "descr": ""},
    {"catid": 34, "prodcode": 3691, "descr": ""},
    {"catid": 34, "prodcode": 3692, "descr": ""},
    {"catid": 34, "prodcode": 3702, "descr": ""},
    {"catid": 34, "prodcode": 3703, "descr": ""},
    {"catid": 34, "prodcode": 3705, "descr": ""},
    {"catid": 34, "prodcode": 3706, "descr": ""},
    {"catid": 34, "prodcode": 3725, "descr": ""},
    {"catid": 34, "prodcode": 3731, "descr": ""},
    {"catid": 34, "prodcode": 3732, "descr": ""},
    {"catid": 34, "prodcode": 3739, "descr": ""},
    {"catid": 34, "prodcode": 3740, "descr": ""},
    {"catid": 34, "prodcode": 3742, "descr": ""},
    {"catid": 34, "prodcode": 3745, "descr": ""},
    {"catid": 34, "prodcode": 3750, "descr": ""},
    {"catid": 34, "prodcode": 4387, "descr": ""},
    {"catid": 34, "prodcode": 4393, "descr": ""},
    {"catid": 34, "prodcode": 4401, "descr": ""},
    {"catid": 34, "prodcode": 4411, "descr": ""},
    {"catid": 34, "prodcode": 4414, "descr": ""},
    {"catid": 34, "prodcode": 4416, "descr": ""},
    {"catid": 34, "prodcode": 4420, "descr": ""},
    {"catid": 34, "prodcode": 4422, "descr": ""},
    {"catid": 34, "prodcode": 4426, "descr": ""},
    {"catid": 34, "prodcode": 4429, "descr": ""},
    {"catid": 34, "prodcode": 4440, "descr": ""},
    {"catid": 34, "prodcode": 4441, "descr": ""},
    {"catid": 34, "prodcode": 4442, "descr": ""},
    {"catid": 34, "prodcode": 4443, "descr": ""},
    {"catid": 34, "prodcode": 4445, "descr": ""},
    {"catid": 34, "prodcode": 4446, "descr": ""},
    {"catid": 34, "prodcode": 4447, "descr": ""},
    {"catid": 34, "prodcode": 4448, "descr": ""},
    {"catid": 34, "prodcode": 4449, "descr": ""},
    {"catid": 34, "prodcode": 4452, "descr": ""},
    {"catid": 34, "prodcode": 4453, "descr": ""},
    {"catid": 34, "prodcode": 4454, "descr": ""},
    {"catid": 34, "prodcode": 4455, "descr": ""},
    {"catid": 34, "prodcode": 4456, "descr": ""},
    {"catid": 34, "prodcode": 4457, "descr": ""},
    {"catid": 34, "prodcode": 4471, "descr": ""},
    {"catid": 34, "prodcode": 4484, "descr": ""},
    {"catid": 34, "prodcode": 4487, "descr": ""},
    {"catid": 34, "prodcode": 4488, "descr": ""},
    {"catid": 34, "prodcode": 4489, "descr": ""},
    {"catid": 34, "prodcode": 4490, "descr": ""},
    {"catid": 34, "prodcode": 4497, "descr": ""},
    {"catid": 34, "prodcode": 4499, "descr": ""},
    {"catid": 34, "prodcode": 4500, "descr": ""},
    {"catid": 34, "prodcode": 4502, "descr": ""},
    {"catid": 34, "prodcode": 4513, "descr": ""},
    {"catid": 34, "prodcode": 4521, "descr": ""},
    {"catid": 34, "prodcode": 4524, "descr": ""},
    {"catid": 34, "prodcode": 4525, "descr": ""},
    {"catid": 34, "prodcode": 4533, "descr": ""},
    {"catid": 34, "prodcode": 4534, "descr": ""},
    {"catid": 34, "prodcode": 4535, "descr": ""},
    {"catid": 34, "prodcode": 4541, "descr": ""},
    {"catid": 34, "prodcode": 4542, "descr": ""},
    {"catid": 34, "prodcode": 4544, "descr": ""},
    {"catid": 34, "prodcode": 4549, "descr": ""},
    {"catid": 34, "prodcode": 4556, "descr": ""},
    {"catid": 34, "prodcode": 4557, "descr": ""},
    {"catid": 34, "prodcode": 4558, "descr": ""},
    {"catid": 34, "prodcode": 4560, "descr": ""},
    {"catid": 34, "prodcode": 4561, "descr": ""},
    {"catid": 34, "prodcode": 4562, "descr": ""},
    {"catid": 34, "prodcode": 4569, "descr": ""},
    {"catid": 34, "prodcode": 4982, "descr": ""},
    {"catid": 34, "prodcode": 4996, "descr": ""},
    {"catid": 34, "prodcode": 4999, "descr": ""},
    {"catid": 34, "prodcode": 5001, "descr": ""},
    {"catid": 34, "prodcode": 5004, "descr": ""},
    {"catid": 34, "prodcode": 5005, "descr": ""},
    {"catid": 34, "prodcode": 5006, "descr": ""},
    {"catid": 34, "prodcode": 5007, "descr": ""},
    {"catid": 34, "prodcode": 5008, "descr": ""},
    {"catid": 34, "prodcode": 5034, "descr": ""},
])

Advanced_Ocular_tests = np.array([
    {"catid": 184, "prodcode": 2621, "descr": ""},
    {"catid": 184, "prodcode": 2624, "descr": ""},
    {"catid": 184, "prodcode": 2635, "descr": ""},
    {"catid": 184, "prodcode": 3330, "descr": ""},
    {"catid": 184, "prodcode": 3384, "descr": ""},
    {"catid": 184, "prodcode": 3385, "descr": ""},
    {"catid": 184, "prodcode": 3416, "descr": ""},
    {"catid": 184, "prodcode": 3417, "descr": ""},
    {"catid": 184, "prodcode": 3473, "descr": ""},
    {"catid": 184, "prodcode": 3785, "descr": ""},
    {"catid": 184, "prodcode": 3808, "descr": ""},
    {"catid": 184, "prodcode": 3829, "descr": ""},
    {"catid": 184, "prodcode": 4724, "descr": ""},
    {"catid": 184, "prodcode": 4737, "descr": ""},
    {"catid": 184, "prodcode": 4787, "descr": ""},
    {"catid": 184, "prodcode": 5034, "descr": ""},
])

Amalgam_Filling = np.array([
    {"catid": 179, "prodcode": 2606, "descr": ""},
    {"catid": 179, "prodcode": 3329, "descr": ""},
    {"catid": 179, "prodcode": 3330, "descr": ""},
    {"catid": 179, "prodcode": 3331, "descr": ""},
    {"catid": 179, "prodcode": 3384, "descr": ""},
    {"catid": 179, "prodcode": 3385, "descr": ""},
    {"catid": 179, "prodcode": 4498, "descr": ""},
    {"catid": 179, "prodcode": 4737, "descr": ""},
    {"catid": 179, "prodcode": 4805, "descr": ""},
    {"catid": 179, "prodcode": 4978, "descr": ""},
    {"catid": 179, "prodcode": 4979, "descr": ""},
])

Antenatal_Care_Including_all_specialist_care_and_anc_drugs = np.array([
    {"catid": 251, "prodcode": 2601, "descr": ""},
    {"catid": 251, "prodcode": 2616, "descr": ""},
    {"catid": 251, "prodcode": 2621, "descr": ""},
    {"catid": 251, "prodcode": 2635, "descr": ""},
    {"catid": 251, "prodcode": 3191, "descr": ""},
    {"catid": 251, "prodcode": 3210, "descr": ""},
    {"catid": 251, "prodcode": 3253, "descr": ""},
    {"catid": 251, "prodcode": 3290, "descr": ""},
    {"catid": 251, "prodcode": 3291, "descr": ""},
    {"catid": 251, "prodcode": 3473, "descr": ""},
    {"catid": 251, "prodcode": 4509, "descr": ""},
    {"catid": 251, "prodcode": 4510, "descr": ""},
    {"catid": 251, "prodcode": 4511, "descr": ""},
    {"catid": 251, "prodcode": 4724, "descr": ""},
    {"catid": 251, "prodcode": 4787, "descr": ""},
    {"catid": 251, "prodcode": 4995, "descr": ""},
])

Aspirates_M_C_S = np.array([
    {"catid": 243, "prodcode": 3263, "descr": ""},
])

Assisted_Delivery = np.array([
    {"catid": 254, "prodcode": 3425, "descr": ""},
    {"catid": 254, "prodcode": 3426, "descr": ""},
    {"catid": 254, "prodcode": 3427, "descr": ""},
    {"catid": 254, "prodcode": 3428, "descr": ""},
    {"catid": 254, "prodcode": 5028, "descr": ""},
    {"catid": 254, "prodcode": 5032, "descr": ""},
])

# =============================================================================
# SUMMARY — A.py
# =============================================================================
# Categories in this file : 15
# Total product entries    : 219
# Duplicate entries removed: 0
#
# Breakdown by category:
#   Abdominal_X_Rays (catid=121): 2 products
#   Access_to_prescribed_drugs (catid=222): (no products — variable omitted)
#   Accident_And_Emergency_Care_Out_Patient (catid=27): 7 products
#   Additional_Immunization_0_5_Years (catid=41): 1 products
#   Additional_Immunization_6_Years_And_Above (catid=42): 10 products
#   Admission (catid=215): 4 products
#   Advanced_Diagnostic_Imaging (catid=30): 14 products
#   Advanced_Laboratory_Investigations_Pathology (catid=34): 131 products
#   Advanced_Ocular_tests (catid=184): 16 products
#   After_Demise_Compensation (catid=250): (no products — variable omitted)
#   Amalgam_Filling (catid=179): 11 products
#   Annual_Visual_Acuity_Check_Using_Snellen_Chart (catid=290): (no products — variable omitted)
#   Antenatal_Care_Including_all_specialist_care_and_anc_drugs (catid=251): 16 products
#   Aspirates_M_C_S (catid=243): 1 products
#   Assisted_Delivery (catid=254): 6 products
# =============================================================================
