import numpy as np

# =============================================================================
# H.py
# Service category product assignments — letter H
# Generated by: product-service-mapper skill
# =============================================================================

HBA1C = np.array([
    {"catid": 316, "prodcode": 3143, "descr": ""},
    {"catid": 316, "prodcode": 3718, "descr": ""},
    {"catid": 316, "prodcode": 4995, "descr": ""},
])

Hematological_Test = np.array([
    {"catid": 31, "prodcode": 3157, "descr": ""},
    {"catid": 31, "prodcode": 3158, "descr": ""},
    {"catid": 31, "prodcode": 3723, "descr": ""},
    {"catid": 31, "prodcode": 3724, "descr": ""},
    {"catid": 31, "prodcode": 3730, "descr": ""},
    {"catid": 31, "prodcode": 4496, "descr": ""},
])

Hepatitis_B = np.array([
    {"catid": 83, "prodcode": 3144, "descr": ""},
    {"catid": 83, "prodcode": 3145, "descr": ""},
    {"catid": 83, "prodcode": 3170, "descr": ""},
    {"catid": 83, "prodcode": 4391, "descr": ""},
    {"catid": 83, "prodcode": 4486, "descr": ""},
    {"catid": 83, "prodcode": 4986, "descr": ""},
])

Hepatitis_B_Surface_Antigen_HBSAg = np.array([
    {"catid": 310, "prodcode": 3144, "descr": ""},
    {"catid": 310, "prodcode": 3145, "descr": ""},
    {"catid": 310, "prodcode": 3170, "descr": ""},
    {"catid": 310, "prodcode": 4391, "descr": ""},
    {"catid": 310, "prodcode": 4486, "descr": ""},
    {"catid": 310, "prodcode": 4986, "descr": ""},
])

Hepatitis_C_Screening = np.array([
    {"catid": 317, "prodcode": 3144, "descr": ""},
    {"catid": 317, "prodcode": 3159, "descr": ""},
    {"catid": 317, "prodcode": 3222, "descr": ""},
    {"catid": 317, "prodcode": 3223, "descr": ""},
    {"catid": 317, "prodcode": 3225, "descr": ""},
    {"catid": 317, "prodcode": 3227, "descr": ""},
    {"catid": 317, "prodcode": 3229, "descr": ""},
    {"catid": 317, "prodcode": 3230, "descr": ""},
    {"catid": 317, "prodcode": 3232, "descr": ""},
    {"catid": 317, "prodcode": 3233, "descr": ""},
    {"catid": 317, "prodcode": 3236, "descr": ""},
    {"catid": 317, "prodcode": 3239, "descr": ""},
    {"catid": 317, "prodcode": 3243, "descr": ""},
    {"catid": 317, "prodcode": 3245, "descr": ""},
    {"catid": 317, "prodcode": 3748, "descr": ""},
    {"catid": 317, "prodcode": 4391, "descr": ""},
])

Hiv_Care_And_Treatment_At_Designated_Sites = np.array([
    {"catid": 51, "prodcode": 3140, "descr": ""},
    {"catid": 51, "prodcode": 3191, "descr": ""},
    {"catid": 51, "prodcode": 3210, "descr": ""},
    {"catid": 51, "prodcode": 3253, "descr": ""},
    {"catid": 51, "prodcode": 4455, "descr": ""},
    {"catid": 51, "prodcode": 4509, "descr": ""},
    {"catid": 51, "prodcode": 4510, "descr": ""},
    {"catid": 51, "prodcode": 4511, "descr": ""},
])

HIV_Screening = np.array([
    {"catid": 311, "prodcode": 3140, "descr": ""},
    {"catid": 311, "prodcode": 3219, "descr": ""},
    {"catid": 311, "prodcode": 3226, "descr": ""},
    {"catid": 311, "prodcode": 3241, "descr": ""},
    {"catid": 311, "prodcode": 3250, "descr": ""},
    {"catid": 311, "prodcode": 3747, "descr": ""},
    {"catid": 311, "prodcode": 4455, "descr": ""},
    {"catid": 311, "prodcode": 4465, "descr": ""},
    {"catid": 311, "prodcode": 4466, "descr": ""},
    {"catid": 311, "prodcode": 4568, "descr": ""},
])

Hysteroscopy = np.array([
    {"catid": 113, "prodcode": 3307, "descr": ""},
    {"catid": 113, "prodcode": 3309, "descr": ""},
    {"catid": 113, "prodcode": 3310, "descr": ""},
    {"catid": 113, "prodcode": 3371, "descr": ""},
    {"catid": 113, "prodcode": 3374, "descr": ""},
    {"catid": 113, "prodcode": 4720, "descr": ""},
])

# =============================================================================
# SUMMARY — H.py
# =============================================================================
# Categories in this file : 14
# Total product entries    : 61
# Duplicate entries removed: 0
#
# Breakdown by category:
#   H_Pylori (catid=246): (no products — variable omitted)
#   HBA1C (catid=316): 3 products
#   Hematological_Test (catid=31): 6 products
#   Hematologist (catid=272): (no products — variable omitted)
#   Hemoglobin_HB (catid=200): (no products — variable omitted)
#   Hepatitis_B (catid=83): 6 products
#   Hepatitis_B_Screening (catid=318): (no products — variable omitted)
#   Hepatitis_B_Surface_Antigen_HBSAg (catid=310): 6 products
#   Hepatitis_C_Screening (catid=317): 16 products
#   High_Vaginal_Swab_HVS_M_or_C_or_S (catid=236): (no products — variable omitted)
#   Hiv_Care_And_Treatment_At_Designated_Sites (catid=51): 8 products
#   HIV_Confirmatory_Test (catid=312): (no products — variable omitted)
#   HIV_Screening (catid=311): 10 products
#   Hysteroscopy (catid=113): 6 products
# =============================================================================
