import numpy as np

# =============================================================================
# I.py
# Service category product assignments — letter I
# Generated by: product-service-mapper skill
# =============================================================================

In_Patient_Care_Limit = np.array([
    {"catid": 28, "prodcode": 2591, "descr": ""},
    {"catid": 28, "prodcode": 2592, "descr": ""},
    {"catid": 28, "prodcode": 2593, "descr": ""},
    {"catid": 28, "prodcode": 2594, "descr": ""},
    {"catid": 28, "prodcode": 2595, "descr": ""},
    {"catid": 28, "prodcode": 3134, "descr": ""},
    {"catid": 28, "prodcode": 3135, "descr": ""},
    {"catid": 28, "prodcode": 3285, "descr": ""},
    {"catid": 28, "prodcode": 5028, "descr": ""},
    {"catid": 28, "prodcode": 5063, "descr": ""},
    {"catid": 28, "prodcode": 5064, "descr": ""},
    {"catid": 28, "prodcode": 5065, "descr": ""},
])

Incision_and_Drainage = np.array([
    {"catid": 180, "prodcode": 3291, "descr": ""},
    {"catid": 180, "prodcode": 3314, "descr": ""},
    {"catid": 180, "prodcode": 4776, "descr": ""},
])

Incubator_Care = np.array([
    {"catid": 217, "prodcode": 3284, "descr": ""},
])

Infertility_Care = np.array([
    {"catid": 39, "prodcode": 4805, "descr": ""},
    {"catid": 39, "prodcode": 4979, "descr": ""},
    {"catid": 39, "prodcode": 4980, "descr": ""},
])

Injectibles = np.array([
    {"catid": 216, "prodcode": 4814, "descr": ""},
    {"catid": 216, "prodcode": 4815, "descr": ""},
    {"catid": 216, "prodcode": 4816, "descr": ""},
])

Intermediate_Surgeries = np.array([
    {"catid": 286, "prodcode": 3308, "descr": ""},
    {"catid": 286, "prodcode": 3315, "descr": ""},
    {"catid": 286, "prodcode": 3317, "descr": ""},
    {"catid": 286, "prodcode": 3318, "descr": ""},
    {"catid": 286, "prodcode": 3321, "descr": ""},
    {"catid": 286, "prodcode": 3323, "descr": ""},
    {"catid": 286, "prodcode": 3324, "descr": ""},
    {"catid": 286, "prodcode": 3325, "descr": ""},
    {"catid": 286, "prodcode": 3326, "descr": ""},
    {"catid": 286, "prodcode": 3342, "descr": ""},
    {"catid": 286, "prodcode": 3343, "descr": ""},
    {"catid": 286, "prodcode": 3344, "descr": ""},
    {"catid": 286, "prodcode": 3345, "descr": ""},
    {"catid": 286, "prodcode": 3346, "descr": ""},
    {"catid": 286, "prodcode": 3347, "descr": ""},
    {"catid": 286, "prodcode": 3348, "descr": ""},
    {"catid": 286, "prodcode": 3350, "descr": ""},
    {"catid": 286, "prodcode": 3352, "descr": ""},
    {"catid": 286, "prodcode": 3353, "descr": ""},
    {"catid": 286, "prodcode": 3354, "descr": ""},
    {"catid": 286, "prodcode": 3355, "descr": ""},
    {"catid": 286, "prodcode": 3356, "descr": ""},
    {"catid": 286, "prodcode": 3358, "descr": ""},
    {"catid": 286, "prodcode": 3360, "descr": ""},
    {"catid": 286, "prodcode": 3362, "descr": ""},
    {"catid": 286, "prodcode": 3363, "descr": ""},
    {"catid": 286, "prodcode": 3376, "descr": ""},
    {"catid": 286, "prodcode": 3377, "descr": ""},
    {"catid": 286, "prodcode": 3381, "descr": ""},
    {"catid": 286, "prodcode": 3386, "descr": ""},
    {"catid": 286, "prodcode": 3387, "descr": ""},
    {"catid": 286, "prodcode": 3388, "descr": ""},
    {"catid": 286, "prodcode": 3389, "descr": ""},
    {"catid": 286, "prodcode": 3390, "descr": ""},
    {"catid": 286, "prodcode": 3392, "descr": ""},
    {"catid": 286, "prodcode": 3393, "descr": ""},
    {"catid": 286, "prodcode": 3394, "descr": ""},
    {"catid": 286, "prodcode": 3404, "descr": ""},
    {"catid": 286, "prodcode": 3405, "descr": ""},
    {"catid": 286, "prodcode": 3407, "descr": ""},
    {"catid": 286, "prodcode": 3408, "descr": ""},
    {"catid": 286, "prodcode": 3409, "descr": ""},
    {"catid": 286, "prodcode": 3410, "descr": ""},
    {"catid": 286, "prodcode": 3411, "descr": ""},
    {"catid": 286, "prodcode": 3412, "descr": ""},
    {"catid": 286, "prodcode": 3413, "descr": ""},
    {"catid": 286, "prodcode": 3414, "descr": ""},
    {"catid": 286, "prodcode": 3415, "descr": ""},
    {"catid": 286, "prodcode": 3416, "descr": ""},
    {"catid": 286, "prodcode": 3417, "descr": ""},
    {"catid": 286, "prodcode": 3418, "descr": ""},
    {"catid": 286, "prodcode": 3419, "descr": ""},
    {"catid": 286, "prodcode": 3421, "descr": ""},
    {"catid": 286, "prodcode": 3422, "descr": ""},
    {"catid": 286, "prodcode": 3429, "descr": ""},
    {"catid": 286, "prodcode": 3658, "descr": ""},
    {"catid": 286, "prodcode": 4610, "descr": ""},
    {"catid": 286, "prodcode": 4622, "descr": ""},
    {"catid": 286, "prodcode": 4624, "descr": ""},
    {"catid": 286, "prodcode": 4626, "descr": ""},
    {"catid": 286, "prodcode": 4628, "descr": ""},
    {"catid": 286, "prodcode": 4629, "descr": ""},
    {"catid": 286, "prodcode": 4640, "descr": ""},
    {"catid": 286, "prodcode": 4659, "descr": ""},
    {"catid": 286, "prodcode": 4665, "descr": ""},
    {"catid": 286, "prodcode": 4668, "descr": ""},
    {"catid": 286, "prodcode": 4670, "descr": ""},
    {"catid": 286, "prodcode": 4675, "descr": ""},
    {"catid": 286, "prodcode": 4676, "descr": ""},
    {"catid": 286, "prodcode": 4678, "descr": ""},
    {"catid": 286, "prodcode": 4679, "descr": ""},
    {"catid": 286, "prodcode": 4688, "descr": ""},
    {"catid": 286, "prodcode": 4690, "descr": ""},
    {"catid": 286, "prodcode": 4697, "descr": ""},
    {"catid": 286, "prodcode": 4698, "descr": ""},
    {"catid": 286, "prodcode": 4699, "descr": ""},
    {"catid": 286, "prodcode": 4702, "descr": ""},
    {"catid": 286, "prodcode": 4711, "descr": ""},
    {"catid": 286, "prodcode": 4712, "descr": ""},
    {"catid": 286, "prodcode": 4713, "descr": ""},
    {"catid": 286, "prodcode": 4715, "descr": ""},
    {"catid": 286, "prodcode": 4716, "descr": ""},
    {"catid": 286, "prodcode": 4717, "descr": ""},
    {"catid": 286, "prodcode": 4718, "descr": ""},
    {"catid": 286, "prodcode": 4719, "descr": ""},
    {"catid": 286, "prodcode": 4722, "descr": ""},
    {"catid": 286, "prodcode": 4726, "descr": ""},
    {"catid": 286, "prodcode": 4730, "descr": ""},
    {"catid": 286, "prodcode": 4731, "descr": ""},
    {"catid": 286, "prodcode": 4732, "descr": ""},
    {"catid": 286, "prodcode": 4733, "descr": ""},
    {"catid": 286, "prodcode": 4734, "descr": ""},
    {"catid": 286, "prodcode": 4735, "descr": ""},
    {"catid": 286, "prodcode": 4745, "descr": ""},
    {"catid": 286, "prodcode": 4751, "descr": ""},
    {"catid": 286, "prodcode": 4756, "descr": ""},
    {"catid": 286, "prodcode": 4757, "descr": ""},
    {"catid": 286, "prodcode": 4759, "descr": ""},
    {"catid": 286, "prodcode": 5016, "descr": ""},
    {"catid": 286, "prodcode": 5017, "descr": ""},
    {"catid": 286, "prodcode": 5019, "descr": ""},
    {"catid": 286, "prodcode": 5020, "descr": ""},
    {"catid": 286, "prodcode": 5021, "descr": ""},
    {"catid": 286, "prodcode": 5024, "descr": ""},
    {"catid": 286, "prodcode": 5033, "descr": ""},
    {"catid": 286, "prodcode": 5035, "descr": ""},
    {"catid": 286, "prodcode": 5043, "descr": ""},
    {"catid": 286, "prodcode": 5059, "descr": ""},
    {"catid": 286, "prodcode": 5060, "descr": ""},
    {"catid": 286, "prodcode": 5062, "descr": ""},
])

# =============================================================================
# SUMMARY — I.py
# =============================================================================
# Categories in this file : 8
# Total product entries    : 132
# Duplicate entries removed: 0
#
# Breakdown by category:
#   Implanon (catid=188): (no products — variable omitted)
#   In_Patient_Care_Limit (catid=28): 12 products
#   Incision_and_Drainage (catid=180): 3 products
#   Incubator_Care (catid=217): 1 products
#   Infertility_Care (catid=39): 3 products
#   Injectibles (catid=216): 3 products
#   Intensive_Care_Unit (catid=91): (no products — variable omitted)
#   Intermediate_Surgeries (catid=286): 110 products
# =============================================================================
