import numpy as np

# =============================================================================
# L.py
# Service category product assignments — letter L
# Generated by: product-service-mapper skill
# =============================================================================

Laparoscopy = np.array([
    {"catid": 120, "prodcode": 2624, "descr": ""},
    {"catid": 120, "prodcode": 2625, "descr": ""},
    {"catid": 120, "prodcode": 3300, "descr": ""},
    {"catid": 120, "prodcode": 3301, "descr": ""},
    {"catid": 120, "prodcode": 3302, "descr": ""},
    {"catid": 120, "prodcode": 3303, "descr": ""},
    {"catid": 120, "prodcode": 3304, "descr": ""},
    {"catid": 120, "prodcode": 3305, "descr": ""},
    {"catid": 120, "prodcode": 3306, "descr": ""},
    {"catid": 120, "prodcode": 3393, "descr": ""},
    {"catid": 120, "prodcode": 3416, "descr": ""},
    {"catid": 120, "prodcode": 3417, "descr": ""},
    {"catid": 120, "prodcode": 3424, "descr": ""},
    {"catid": 120, "prodcode": 4672, "descr": ""},
    {"catid": 120, "prodcode": 4673, "descr": ""},
    {"catid": 120, "prodcode": 4674, "descr": ""},
    {"catid": 120, "prodcode": 5034, "descr": ""},
    {"catid": 120, "prodcode": 5035, "descr": ""},
])

Laryngoscopy_Direct_and_Indirect = np.array([
    {"catid": 110, "prodcode": 3695, "descr": ""},
    {"catid": 110, "prodcode": 4512, "descr": ""},
    {"catid": 110, "prodcode": 4514, "descr": ""},
    {"catid": 110, "prodcode": 5037, "descr": ""},
    {"catid": 110, "prodcode": 5038, "descr": ""},
])

Leishmania_Screening = np.array([
    {"catid": 233, "prodcode": 3139, "descr": ""},
    {"catid": 233, "prodcode": 3151, "descr": ""},
    {"catid": 233, "prodcode": 3152, "descr": ""},
    {"catid": 233, "prodcode": 3156, "descr": ""},
    {"catid": 233, "prodcode": 3665, "descr": ""},
    {"catid": 233, "prodcode": 3666, "descr": ""},
    {"catid": 233, "prodcode": 3727, "descr": ""},
    {"catid": 233, "prodcode": 3728, "descr": ""},
    {"catid": 233, "prodcode": 3729, "descr": ""},
    {"catid": 233, "prodcode": 4543, "descr": ""},
])

Limbs_X_rays = np.array([
    {"catid": 136, "prodcode": 3251, "descr": ""},
    {"catid": 136, "prodcode": 3399, "descr": ""},
    {"catid": 136, "prodcode": 4685, "descr": ""},
    {"catid": 136, "prodcode": 4686, "descr": ""},
    {"catid": 136, "prodcode": 4721, "descr": ""},
    {"catid": 136, "prodcode": 5039, "descr": ""},
])

Line_Of_Treatment_Confirmation_From_Secondary_And_Tertiary_Care_Centres = np.array([
    {"catid": 260, "prodcode": 3398, "descr": ""},
    {"catid": 260, "prodcode": 4748, "descr": ""},
    {"catid": 260, "prodcode": 5087, "descr": ""},
    {"catid": 260, "prodcode": 5100, "descr": ""},
])

Lipid_Profile_Fasting = np.array([
    {"catid": 143, "prodcode": 3141, "descr": ""},
    {"catid": 143, "prodcode": 3663, "descr": ""},
    {"catid": 143, "prodcode": 4390, "descr": ""},
    {"catid": 143, "prodcode": 4476, "descr": ""},
    {"catid": 143, "prodcode": 4477, "descr": ""},
    {"catid": 143, "prodcode": 4478, "descr": ""},
    {"catid": 143, "prodcode": 4479, "descr": ""},
    {"catid": 143, "prodcode": 4480, "descr": ""},
    {"catid": 143, "prodcode": 4481, "descr": ""},
    {"catid": 143, "prodcode": 4482, "descr": ""},
    {"catid": 143, "prodcode": 4483, "descr": ""},
    {"catid": 143, "prodcode": 4988, "descr": ""},
])

Liver_Function_Test = np.array([
    {"catid": 298, "prodcode": 3153, "descr": ""},
    {"catid": 298, "prodcode": 3662, "descr": ""},
    {"catid": 298, "prodcode": 3693, "descr": ""},
    {"catid": 298, "prodcode": 3694, "descr": ""},
    {"catid": 298, "prodcode": 3695, "descr": ""},
    {"catid": 298, "prodcode": 3696, "descr": ""},
    {"catid": 298, "prodcode": 3697, "descr": ""},
    {"catid": 298, "prodcode": 3698, "descr": ""},
    {"catid": 298, "prodcode": 3699, "descr": ""},
    {"catid": 298, "prodcode": 3700, "descr": ""},
    {"catid": 298, "prodcode": 3701, "descr": ""},
])

Liver_Function_Test_LFT = np.array([
    {"catid": 144, "prodcode": 3153, "descr": ""},
    {"catid": 144, "prodcode": 3178, "descr": ""},
    {"catid": 144, "prodcode": 3200, "descr": ""},
    {"catid": 144, "prodcode": 3261, "descr": ""},
    {"catid": 144, "prodcode": 3265, "descr": ""},
    {"catid": 144, "prodcode": 3662, "descr": ""},
    {"catid": 144, "prodcode": 3693, "descr": ""},
    {"catid": 144, "prodcode": 3694, "descr": ""},
    {"catid": 144, "prodcode": 3695, "descr": ""},
    {"catid": 144, "prodcode": 3696, "descr": ""},
    {"catid": 144, "prodcode": 3697, "descr": ""},
    {"catid": 144, "prodcode": 3698, "descr": ""},
    {"catid": 144, "prodcode": 3699, "descr": ""},
    {"catid": 144, "prodcode": 3700, "descr": ""},
    {"catid": 144, "prodcode": 3701, "descr": ""},
    {"catid": 144, "prodcode": 4982, "descr": ""},
])

Lumbosacral_X_Rays = np.array([
    {"catid": 127, "prodcode": 4685, "descr": ""},
    {"catid": 127, "prodcode": 4686, "descr": ""},
])

# =============================================================================
# SUMMARY — L.py
# =============================================================================
# Categories in this file : 9
# Total product entries    : 84
# Duplicate entries removed: 0
#
# Breakdown by category:
#   Laparoscopy (catid=120): 18 products
#   Laryngoscopy_Direct_and_Indirect (catid=110): 5 products
#   Leishmania_Screening (catid=233): 10 products
#   Limbs_X_rays (catid=136): 6 products
#   Line_Of_Treatment_Confirmation_From_Secondary_And_Tertiary_Care_Centres (catid=260): 4 products
#   Lipid_Profile_Fasting (catid=143): 12 products
#   Liver_Function_Test (catid=298): 11 products
#   Liver_Function_Test_LFT (catid=144): 16 products
#   Lumbosacral_X_Rays (catid=127): 2 products
# =============================================================================
