import numpy as np

# =============================================================================
# V.py
# Service category product assignments — letter V
# Generated by: product-service-mapper skill
# =============================================================================

VDRL_Veneral_Disease_Research_Laboratory_Test_unless_where_disallowed_by_diagnosis = np.array([
    {"catid": 245, "prodcode": 4402, "descr": ""},
    {"catid": 245, "prodcode": 4403, "descr": ""},
    {"catid": 245, "prodcode": 4404, "descr": ""},
    {"catid": 245, "prodcode": 4405, "descr": ""},
])

Vitamin_A = np.array([
    {"catid": 78, "prodcode": 3507, "descr": ""},
])

# =============================================================================
# SUMMARY — V.py
# =============================================================================
# Categories in this file : 2
# Total product entries    : 5
# Duplicate entries removed: 0
#
# Breakdown by category:
#   VDRL_Veneral_Disease_Research_Laboratory_Test_unless_where_disallowed_by_diagnosis (catid=245): 4 products
#   Vitamin_A (catid=78): 1 products
# =============================================================================
