import numpy as np

# =============================================================================
# K.py
# Service category product assignments — letter K
# Generated by: product-service-mapper skill
# =============================================================================

Kidney_Function_Tests = np.array([
    {"catid": 308, "prodcode": 32921, "descr": ""},
    {"catid": 308, "prodcode": 32957, "descr": ""},
    {"catid": 308, "prodcode": 32970, "descr": ""},
    {"catid": 308, "prodcode": 32971, "descr": ""},
    {"catid": 308, "prodcode": 32972, "descr": ""},
    {"catid": 308, "prodcode": 32974, "descr": ""},
    {"catid": 308, "prodcode": 32975, "descr": ""},
    {"catid": 308, "prodcode": 32976, "descr": ""},
    {"catid": 308, "prodcode": 32977, "descr": ""},
    {"catid": 308, "prodcode": 34071, "descr": ""},
    {"catid": 308, "prodcode": 34409, "descr": ""},
    {"catid": 308, "prodcode": 34795, "descr": ""},
    {"catid": 308, "prodcode": 35124, "descr": ""},
    {"catid": 308, "prodcode": 35758, "descr": ""},
    {"catid": 308, "prodcode": 36042, "descr": ""},
])

# =============================================================================
# SUMMARY — K.py
# =============================================================================
# Categories in this file : 1
# Total product entries    : 15
# Duplicate entries removed: 0
#
# Breakdown by category:
#   Kidney_Function_Tests (catid=308): 15 products
# =============================================================================
