import numpy as np

# =============================================================================
# L.py
# Service category product assignments — letter L
# Generated by: product-service-mapper skill
# =============================================================================

Laparoscopy = np.array([
    {"catid": 120, "prodcode": 32522, "descr": ""},
    {"catid": 120, "prodcode": 32524, "descr": ""},
    {"catid": 120, "prodcode": 33110, "descr": ""},
    {"catid": 120, "prodcode": 33111, "descr": ""},
    {"catid": 120, "prodcode": 34154, "descr": ""},
    {"catid": 120, "prodcode": 34155, "descr": ""},
    {"catid": 120, "prodcode": 34163, "descr": ""},
    {"catid": 120, "prodcode": 34633, "descr": ""},
    {"catid": 120, "prodcode": 34636, "descr": ""},
    {"catid": 120, "prodcode": 34641, "descr": ""},
    {"catid": 120, "prodcode": 34642, "descr": ""},
    {"catid": 120, "prodcode": 34643, "descr": ""},
    {"catid": 120, "prodcode": 35806, "descr": ""},
    {"catid": 120, "prodcode": 35836, "descr": ""},
    {"catid": 120, "prodcode": 35850, "descr": ""},
    {"catid": 120, "prodcode": 35851, "descr": ""},
    {"catid": 120, "prodcode": 35862, "descr": ""},
    {"catid": 120, "prodcode": 35863, "descr": ""},
    {"catid": 120, "prodcode": 35949, "descr": ""},
])

Laryngoscopy_Direct_and_Indirect = np.array([
    {"catid": 110, "prodcode": 32440, "descr": ""},
    {"catid": 110, "prodcode": 32529, "descr": ""},
    {"catid": 110, "prodcode": 33081, "descr": ""},
    {"catid": 110, "prodcode": 33722, "descr": ""},
    {"catid": 110, "prodcode": 33723, "descr": ""},
    {"catid": 110, "prodcode": 34738, "descr": ""},
    {"catid": 110, "prodcode": 35047, "descr": ""},
    {"catid": 110, "prodcode": 35048, "descr": ""},
    {"catid": 110, "prodcode": 35159, "descr": ""},
])

Leishmania_Screening = np.array([
    {"catid": 233, "prodcode": 34549, "descr": ""},
])

Limbs_X_rays = np.array([
    {"catid": 136, "prodcode": 32562, "descr": ""},
    {"catid": 136, "prodcode": 32563, "descr": ""},
    {"catid": 136, "prodcode": 33071, "descr": ""},
    {"catid": 136, "prodcode": 33221, "descr": ""},
    {"catid": 136, "prodcode": 33222, "descr": ""},
    {"catid": 136, "prodcode": 33223, "descr": ""},
    {"catid": 136, "prodcode": 33224, "descr": ""},
    {"catid": 136, "prodcode": 33225, "descr": ""},
    {"catid": 136, "prodcode": 33226, "descr": ""},
    {"catid": 136, "prodcode": 33740, "descr": ""},
    {"catid": 136, "prodcode": 34577, "descr": ""},
])

Line_Of_Treatment_Confirmation_From_Secondary_And_Tertiary_Care_Centres = np.array([
    {"catid": 260, "prodcode": 33121, "descr": ""},
    {"catid": 260, "prodcode": 33237, "descr": ""},
    {"catid": 260, "prodcode": 33238, "descr": ""},
    {"catid": 260, "prodcode": 33753, "descr": ""},
    {"catid": 260, "prodcode": 33754, "descr": ""},
    {"catid": 260, "prodcode": 34968, "descr": ""},
    {"catid": 260, "prodcode": 35083, "descr": ""},
    {"catid": 260, "prodcode": 35135, "descr": ""},
    {"catid": 260, "prodcode": 35136, "descr": ""},
])

Lipid_Profile_Fasting = np.array([
    {"catid": 143, "prodcode": 33604, "descr": ""},
    {"catid": 143, "prodcode": 33605, "descr": ""},
    {"catid": 143, "prodcode": 35808, "descr": ""},
    {"catid": 143, "prodcode": 35812, "descr": ""},
    {"catid": 143, "prodcode": 35823, "descr": ""},
])

Liver_Function_Test = np.array([
    {"catid": 298, "prodcode": 35816, "descr": ""},
    {"catid": 298, "prodcode": 35817, "descr": ""},
    {"catid": 298, "prodcode": 35828, "descr": ""},
])

Liver_Function_Test_LFT = np.array([
    {"catid": 144, "prodcode": 35816, "descr": ""},
    {"catid": 144, "prodcode": 35817, "descr": ""},
    {"catid": 144, "prodcode": 35828, "descr": ""},
])

Lumbosacral_X_Rays = np.array([
    {"catid": 127, "prodcode": 33071, "descr": ""},
    {"catid": 127, "prodcode": 33221, "descr": ""},
    {"catid": 127, "prodcode": 33222, "descr": ""},
    {"catid": 127, "prodcode": 33223, "descr": ""},
    {"catid": 127, "prodcode": 33224, "descr": ""},
    {"catid": 127, "prodcode": 33225, "descr": ""},
    {"catid": 127, "prodcode": 33226, "descr": ""},
    {"catid": 127, "prodcode": 33740, "descr": ""},
    {"catid": 127, "prodcode": 34577, "descr": ""},
])

# =============================================================================
# SUMMARY — L.py
# =============================================================================
# Categories in this file : 9
# Total product entries    : 69
# Duplicate entries removed: 0
#
# Breakdown by category:
#   Laparoscopy (catid=120): 19 products
#   Laryngoscopy_Direct_and_Indirect (catid=110): 9 products
#   Leishmania_Screening (catid=233): 1 products
#   Limbs_X_rays (catid=136): 11 products
#   Line_Of_Treatment_Confirmation_From_Secondary_And_Tertiary_Care_Centres (catid=260): 9 products
#   Lipid_Profile_Fasting (catid=143): 5 products
#   Liver_Function_Test (catid=298): 3 products
#   Liver_Function_Test_LFT (catid=144): 3 products
#   Lumbosacral_X_Rays (catid=127): 9 products
# =============================================================================
