import numpy as np

# =============================================================================
# B.py
# Service category product assignments — letter B
# Generated by: product-service-mapper skill
# =============================================================================

Basic_Diagnostic_Imaging = np.array([
    {"catid": 29, "prodcode": 32590, "descr": ""},
    {"catid": 29, "prodcode": 32605, "descr": ""},
    {"catid": 29, "prodcode": 32606, "descr": ""},
    {"catid": 29, "prodcode": 32613, "descr": ""},
    {"catid": 29, "prodcode": 32614, "descr": ""},
    {"catid": 29, "prodcode": 32617, "descr": ""},
    {"catid": 29, "prodcode": 32622, "descr": ""},
    {"catid": 29, "prodcode": 33243, "descr": ""},
    {"catid": 29, "prodcode": 33244, "descr": ""},
    {"catid": 29, "prodcode": 33248, "descr": ""},
    {"catid": 29, "prodcode": 33252, "descr": ""},
    {"catid": 29, "prodcode": 33254, "descr": ""},
    {"catid": 29, "prodcode": 33255, "descr": ""},
    {"catid": 29, "prodcode": 33256, "descr": ""},
    {"catid": 29, "prodcode": 33257, "descr": ""},
    {"catid": 29, "prodcode": 33262, "descr": ""},
    {"catid": 29, "prodcode": 33265, "descr": ""},
    {"catid": 29, "prodcode": 33266, "descr": ""},
    {"catid": 29, "prodcode": 34178, "descr": ""},
    {"catid": 29, "prodcode": 34179, "descr": ""},
    {"catid": 29, "prodcode": 34180, "descr": ""},
    {"catid": 29, "prodcode": 34183, "descr": ""},
    {"catid": 29, "prodcode": 34184, "descr": ""},
    {"catid": 29, "prodcode": 34185, "descr": ""},
    {"catid": 29, "prodcode": 34189, "descr": ""},
    {"catid": 29, "prodcode": 34195, "descr": ""},
    {"catid": 29, "prodcode": 34197, "descr": ""},
    {"catid": 29, "prodcode": 34198, "descr": ""},
    {"catid": 29, "prodcode": 34200, "descr": ""},
    {"catid": 29, "prodcode": 34662, "descr": ""},
    {"catid": 29, "prodcode": 34665, "descr": ""},
    {"catid": 29, "prodcode": 34667, "descr": ""},
    {"catid": 29, "prodcode": 34997, "descr": ""},
    {"catid": 29, "prodcode": 35000, "descr": ""},
    {"catid": 29, "prodcode": 35239, "descr": ""},
    {"catid": 29, "prodcode": 35241, "descr": ""},
    {"catid": 29, "prodcode": 35243, "descr": ""},
    {"catid": 29, "prodcode": 35244, "descr": ""},
    {"catid": 29, "prodcode": 35371, "descr": ""},
    {"catid": 29, "prodcode": 35372, "descr": ""},
    {"catid": 29, "prodcode": 35373, "descr": ""},
    {"catid": 29, "prodcode": 35375, "descr": ""},
    {"catid": 29, "prodcode": 35379, "descr": ""},
    {"catid": 29, "prodcode": 35380, "descr": ""},
    {"catid": 29, "prodcode": 35385, "descr": ""},
    {"catid": 29, "prodcode": 35925, "descr": ""},
    {"catid": 29, "prodcode": 35926, "descr": ""},
    {"catid": 29, "prodcode": 35937, "descr": ""},
    {"catid": 29, "prodcode": 35939, "descr": ""},
    {"catid": 29, "prodcode": 35940, "descr": ""},
    {"catid": 29, "prodcode": 36006, "descr": ""},
])

Basic_Lab_Investigations_or_Xrays_and_Ultrasound = np.array([
    {"catid": 56, "prodcode": 32522, "descr": ""},
    {"catid": 56, "prodcode": 32524, "descr": ""},
    {"catid": 56, "prodcode": 32590, "descr": ""},
    {"catid": 56, "prodcode": 32605, "descr": ""},
    {"catid": 56, "prodcode": 32606, "descr": ""},
    {"catid": 56, "prodcode": 32613, "descr": ""},
    {"catid": 56, "prodcode": 32614, "descr": ""},
    {"catid": 56, "prodcode": 32622, "descr": ""},
    {"catid": 56, "prodcode": 32997, "descr": ""},
    {"catid": 56, "prodcode": 33039, "descr": ""},
    {"catid": 56, "prodcode": 33142, "descr": ""},
    {"catid": 56, "prodcode": 33143, "descr": ""},
    {"catid": 56, "prodcode": 33144, "descr": ""},
    {"catid": 56, "prodcode": 33145, "descr": ""},
    {"catid": 56, "prodcode": 33243, "descr": ""},
    {"catid": 56, "prodcode": 33244, "descr": ""},
    {"catid": 56, "prodcode": 33248, "descr": ""},
    {"catid": 56, "prodcode": 33252, "descr": ""},
    {"catid": 56, "prodcode": 33254, "descr": ""},
    {"catid": 56, "prodcode": 33255, "descr": ""},
    {"catid": 56, "prodcode": 33256, "descr": ""},
    {"catid": 56, "prodcode": 33257, "descr": ""},
    {"catid": 56, "prodcode": 33262, "descr": ""},
    {"catid": 56, "prodcode": 33265, "descr": ""},
    {"catid": 56, "prodcode": 33266, "descr": ""},
    {"catid": 56, "prodcode": 33642, "descr": ""},
    {"catid": 56, "prodcode": 33643, "descr": ""},
    {"catid": 56, "prodcode": 34163, "descr": ""},
    {"catid": 56, "prodcode": 34178, "descr": ""},
    {"catid": 56, "prodcode": 34179, "descr": ""},
    {"catid": 56, "prodcode": 34180, "descr": ""},
    {"catid": 56, "prodcode": 34183, "descr": ""},
    {"catid": 56, "prodcode": 34184, "descr": ""},
    {"catid": 56, "prodcode": 34185, "descr": ""},
    {"catid": 56, "prodcode": 34195, "descr": ""},
    {"catid": 56, "prodcode": 34197, "descr": ""},
    {"catid": 56, "prodcode": 34198, "descr": ""},
    {"catid": 56, "prodcode": 34200, "descr": ""},
    {"catid": 56, "prodcode": 34636, "descr": ""},
    {"catid": 56, "prodcode": 34662, "descr": ""},
    {"catid": 56, "prodcode": 34665, "descr": ""},
    {"catid": 56, "prodcode": 34667, "descr": ""},
    {"catid": 56, "prodcode": 35239, "descr": ""},
    {"catid": 56, "prodcode": 35241, "descr": ""},
    {"catid": 56, "prodcode": 35243, "descr": ""},
    {"catid": 56, "prodcode": 35245, "descr": ""},
    {"catid": 56, "prodcode": 35371, "descr": ""},
    {"catid": 56, "prodcode": 35372, "descr": ""},
    {"catid": 56, "prodcode": 35373, "descr": ""},
    {"catid": 56, "prodcode": 35375, "descr": ""},
    {"catid": 56, "prodcode": 35379, "descr": ""},
    {"catid": 56, "prodcode": 35380, "descr": ""},
    {"catid": 56, "prodcode": 35385, "descr": ""},
    {"catid": 56, "prodcode": 35925, "descr": ""},
    {"catid": 56, "prodcode": 35926, "descr": ""},
    {"catid": 56, "prodcode": 35937, "descr": ""},
    {"catid": 56, "prodcode": 35939, "descr": ""},
    {"catid": 56, "prodcode": 35940, "descr": ""},
    {"catid": 56, "prodcode": 36006, "descr": ""},
])

Basic_ocular_tests = np.array([
    {"catid": 182, "prodcode": 32997, "descr": ""},
    {"catid": 182, "prodcode": 33039, "descr": ""},
    {"catid": 182, "prodcode": 33142, "descr": ""},
    {"catid": 182, "prodcode": 33143, "descr": ""},
    {"catid": 182, "prodcode": 33144, "descr": ""},
    {"catid": 182, "prodcode": 33145, "descr": ""},
])

Bcg = np.array([
    {"catid": 80, "prodcode": 32499, "descr": ""},
    {"catid": 80, "prodcode": 32709, "descr": ""},
    {"catid": 80, "prodcode": 32710, "descr": ""},
    {"catid": 80, "prodcode": 35465, "descr": ""},
    {"catid": 80, "prodcode": 35466, "descr": ""},
    {"catid": 80, "prodcode": 35467, "descr": ""},
])

Biennial_Lenses_and_Frames = np.array([
    {"catid": 185, "prodcode": 34128, "descr": ""},
])

Bleeding_Time = np.array([
    {"catid": 334, "prodcode": 33608, "descr": ""},
])

Blood_Film = np.array([
    {"catid": 204, "prodcode": 32997, "descr": ""},
    {"catid": 204, "prodcode": 33039, "descr": ""},
    {"catid": 204, "prodcode": 33142, "descr": ""},
    {"catid": 204, "prodcode": 33143, "descr": ""},
    {"catid": 204, "prodcode": 33144, "descr": ""},
    {"catid": 204, "prodcode": 33145, "descr": ""},
])

Blood_Pregnancy_Beta_HCG_Test = np.array([
    {"catid": 205, "prodcode": 32965, "descr": ""},
    {"catid": 205, "prodcode": 34096, "descr": ""},
    {"catid": 205, "prodcode": 34280, "descr": ""},
    {"catid": 205, "prodcode": 34281, "descr": ""},
    {"catid": 205, "prodcode": 34282, "descr": ""},
    {"catid": 205, "prodcode": 34283, "descr": ""},
    {"catid": 205, "prodcode": 34436, "descr": ""},
    {"catid": 205, "prodcode": 34437, "descr": ""},
    {"catid": 205, "prodcode": 34541, "descr": ""},
])

Blood_Sugar_Check_Diabetes_Screening = np.array([
    {"catid": 288, "prodcode": 32435, "descr": ""},
])

Body_Massage = np.array([
    {"catid": 195, "prodcode": 32471, "descr": ""},
    {"catid": 195, "prodcode": 32472, "descr": ""},
    {"catid": 195, "prodcode": 33088, "descr": ""},
    {"catid": 195, "prodcode": 33093, "descr": ""},
    {"catid": 195, "prodcode": 33740, "descr": ""},
    {"catid": 195, "prodcode": 34154, "descr": ""},
    {"catid": 195, "prodcode": 34155, "descr": ""},
])

Bronchoscopy = np.array([
    {"catid": 111, "prodcode": 32620, "descr": ""},
    {"catid": 111, "prodcode": 32621, "descr": ""},
    {"catid": 111, "prodcode": 33084, "descr": ""},
    {"catid": 111, "prodcode": 33085, "descr": ""},
    {"catid": 111, "prodcode": 33086, "descr": ""},
    {"catid": 111, "prodcode": 33088, "descr": ""},
    {"catid": 111, "prodcode": 33089, "descr": ""},
    {"catid": 111, "prodcode": 33090, "descr": ""},
    {"catid": 111, "prodcode": 33091, "descr": ""},
    {"catid": 111, "prodcode": 33092, "descr": ""},
    {"catid": 111, "prodcode": 33093, "descr": ""},
    {"catid": 111, "prodcode": 33094, "descr": ""},
    {"catid": 111, "prodcode": 33095, "descr": ""},
    {"catid": 111, "prodcode": 33096, "descr": ""},
    {"catid": 111, "prodcode": 33097, "descr": ""},
    {"catid": 111, "prodcode": 33098, "descr": ""},
    {"catid": 111, "prodcode": 33722, "descr": ""},
    {"catid": 111, "prodcode": 33723, "descr": ""},
    {"catid": 111, "prodcode": 34142, "descr": ""},
    {"catid": 111, "prodcode": 35200, "descr": ""},
    {"catid": 111, "prodcode": 35201, "descr": ""},
    {"catid": 111, "prodcode": 35203, "descr": ""},
])

# =============================================================================
# SUMMARY — B.py
# =============================================================================
# Categories in this file : 16
# Total product entries    : 169
# Duplicate entries removed: 0
#
# Breakdown by category:
#   Basic_Diagnostic_Imaging (catid=29): 51 products
#   Basic_Lab_Investigations_or_Xrays_and_Ultrasound (catid=56): 59 products
#   Basic_ocular_tests (catid=182): 6 products
#   Bcg (catid=80): 6 products
#   Biennial_Lenses_and_Frames (catid=185): 1 products
#   Bleeding_Time (catid=334): 1 products
#   Blood_Culture (catid=248): (no products — variable omitted)
#   Blood_Film (catid=204): 6 products
#   Blood_group_on_request_by_clinician (catid=208): (no products — variable omitted)
#   Blood_Pregnancy_Beta_HCG_Test (catid=205): 9 products
#   Blood_Pressure_Check_Hypertension_Screening (catid=295): (no products — variable omitted)
#   Blood_Sugar_Check_Diabetes_Screening (catid=288): 1 products
#   Blood_urea_Nitrogen (catid=309): (no products — variable omitted)
#   Bmi_Check (catid=292): (no products — variable omitted)
#   Body_Massage (catid=195): 7 products
#   Bronchoscopy (catid=111): 22 products
# =============================================================================
