import numpy as np

# =============================================================================
# H.py
# Service category product assignments — letter H
# Generated by: product-service-mapper skill
# =============================================================================

H_Pylori = np.array([
    {"catid": 246, "prodcode": 33611, "descr": ""},
    {"catid": 246, "prodcode": 34412, "descr": ""},
    {"catid": 246, "prodcode": 34414, "descr": ""},
    {"catid": 246, "prodcode": 34415, "descr": ""},
    {"catid": 246, "prodcode": 34416, "descr": ""},
    {"catid": 246, "prodcode": 34446, "descr": ""},
    {"catid": 246, "prodcode": 34447, "descr": ""},
    {"catid": 246, "prodcode": 34448, "descr": ""},
])

HBA1C = np.array([
    {"catid": 316, "prodcode": 32428, "descr": ""},
    {"catid": 316, "prodcode": 32429, "descr": ""},
    {"catid": 316, "prodcode": 32435, "descr": ""},
    {"catid": 316, "prodcode": 34090, "descr": ""},
    {"catid": 316, "prodcode": 34091, "descr": ""},
    {"catid": 316, "prodcode": 34092, "descr": ""},
    {"catid": 316, "prodcode": 34093, "descr": ""},
    {"catid": 316, "prodcode": 34095, "descr": ""},
    {"catid": 316, "prodcode": 34420, "descr": ""},
    {"catid": 316, "prodcode": 34432, "descr": ""},
    {"catid": 316, "prodcode": 34433, "descr": ""},
])

Hematological_Test = np.array([
    {"catid": 31, "prodcode": 34100, "descr": ""},
    {"catid": 31, "prodcode": 34101, "descr": ""},
    {"catid": 31, "prodcode": 34102, "descr": ""},
    {"catid": 31, "prodcode": 34105, "descr": ""},
])

Hemoglobin_HB = np.array([
    {"catid": 200, "prodcode": 34092, "descr": ""},
    {"catid": 200, "prodcode": 34093, "descr": ""},
    {"catid": 200, "prodcode": 34421, "descr": ""},
    {"catid": 200, "prodcode": 34449, "descr": ""},
    {"catid": 200, "prodcode": 34450, "descr": ""},
])

Hepatitis_B = np.array([
    {"catid": 83, "prodcode": 34169, "descr": ""},
    {"catid": 83, "prodcode": 34255, "descr": ""},
    {"catid": 83, "prodcode": 34257, "descr": ""},
    {"catid": 83, "prodcode": 34258, "descr": ""},
    {"catid": 83, "prodcode": 34259, "descr": ""},
    {"catid": 83, "prodcode": 34458, "descr": ""},
    {"catid": 83, "prodcode": 34459, "descr": ""},
    {"catid": 83, "prodcode": 34460, "descr": ""},
    {"catid": 83, "prodcode": 34462, "descr": ""},
    {"catid": 83, "prodcode": 34463, "descr": ""},
    {"catid": 83, "prodcode": 34464, "descr": ""},
    {"catid": 83, "prodcode": 34466, "descr": ""},
    {"catid": 83, "prodcode": 34467, "descr": ""},
    {"catid": 83, "prodcode": 34468, "descr": ""},
    {"catid": 83, "prodcode": 34469, "descr": ""},
    {"catid": 83, "prodcode": 34470, "descr": ""},
    {"catid": 83, "prodcode": 34471, "descr": ""},
    {"catid": 83, "prodcode": 34472, "descr": ""},
    {"catid": 83, "prodcode": 34473, "descr": ""},
    {"catid": 83, "prodcode": 34474, "descr": ""},
    {"catid": 83, "prodcode": 34475, "descr": ""},
    {"catid": 83, "prodcode": 34477, "descr": ""},
    {"catid": 83, "prodcode": 34478, "descr": ""},
    {"catid": 83, "prodcode": 34479, "descr": ""},
    {"catid": 83, "prodcode": 34482, "descr": ""},
    {"catid": 83, "prodcode": 34483, "descr": ""},
    {"catid": 83, "prodcode": 34486, "descr": ""},
    {"catid": 83, "prodcode": 34487, "descr": ""},
    {"catid": 83, "prodcode": 34489, "descr": ""},
    {"catid": 83, "prodcode": 34490, "descr": ""},
    {"catid": 83, "prodcode": 34492, "descr": ""},
    {"catid": 83, "prodcode": 34493, "descr": ""},
    {"catid": 83, "prodcode": 34498, "descr": ""},
    {"catid": 83, "prodcode": 34499, "descr": ""},
    {"catid": 83, "prodcode": 34500, "descr": ""},
    {"catid": 83, "prodcode": 34501, "descr": ""},
    {"catid": 83, "prodcode": 34654, "descr": ""},
])

Hepatitis_B_Screening = np.array([
    {"catid": 318, "prodcode": 34429, "descr": ""},
    {"catid": 318, "prodcode": 34452, "descr": ""},
    {"catid": 318, "prodcode": 34453, "descr": ""},
    {"catid": 318, "prodcode": 34454, "descr": ""},
    {"catid": 318, "prodcode": 34505, "descr": ""},
])

Hepatitis_B_Surface_Antigen_HBSAg = np.array([
    {"catid": 310, "prodcode": 34169, "descr": ""},
    {"catid": 310, "prodcode": 34255, "descr": ""},
    {"catid": 310, "prodcode": 34257, "descr": ""},
    {"catid": 310, "prodcode": 34258, "descr": ""},
    {"catid": 310, "prodcode": 34259, "descr": ""},
    {"catid": 310, "prodcode": 34436, "descr": ""},
    {"catid": 310, "prodcode": 34451, "descr": ""},
    {"catid": 310, "prodcode": 34458, "descr": ""},
    {"catid": 310, "prodcode": 34459, "descr": ""},
    {"catid": 310, "prodcode": 34460, "descr": ""},
    {"catid": 310, "prodcode": 34462, "descr": ""},
    {"catid": 310, "prodcode": 34463, "descr": ""},
    {"catid": 310, "prodcode": 34464, "descr": ""},
    {"catid": 310, "prodcode": 34466, "descr": ""},
    {"catid": 310, "prodcode": 34467, "descr": ""},
    {"catid": 310, "prodcode": 34468, "descr": ""},
    {"catid": 310, "prodcode": 34469, "descr": ""},
    {"catid": 310, "prodcode": 34470, "descr": ""},
    {"catid": 310, "prodcode": 34471, "descr": ""},
    {"catid": 310, "prodcode": 34472, "descr": ""},
    {"catid": 310, "prodcode": 34473, "descr": ""},
    {"catid": 310, "prodcode": 34474, "descr": ""},
    {"catid": 310, "prodcode": 34475, "descr": ""},
    {"catid": 310, "prodcode": 34477, "descr": ""},
    {"catid": 310, "prodcode": 34478, "descr": ""},
    {"catid": 310, "prodcode": 34479, "descr": ""},
    {"catid": 310, "prodcode": 34482, "descr": ""},
    {"catid": 310, "prodcode": 34483, "descr": ""},
    {"catid": 310, "prodcode": 34486, "descr": ""},
    {"catid": 310, "prodcode": 34487, "descr": ""},
    {"catid": 310, "prodcode": 34489, "descr": ""},
    {"catid": 310, "prodcode": 34490, "descr": ""},
    {"catid": 310, "prodcode": 34492, "descr": ""},
    {"catid": 310, "prodcode": 34493, "descr": ""},
    {"catid": 310, "prodcode": 34498, "descr": ""},
    {"catid": 310, "prodcode": 34499, "descr": ""},
    {"catid": 310, "prodcode": 34500, "descr": ""},
    {"catid": 310, "prodcode": 34501, "descr": ""},
    {"catid": 310, "prodcode": 34654, "descr": ""},
])

Hepatitis_C_Screening = np.array([
    {"catid": 317, "prodcode": 34439, "descr": ""},
    {"catid": 317, "prodcode": 34455, "descr": ""},
    {"catid": 317, "prodcode": 34456, "descr": ""},
    {"catid": 317, "prodcode": 34467, "descr": ""},
    {"catid": 317, "prodcode": 34468, "descr": ""},
    {"catid": 317, "prodcode": 34469, "descr": ""},
    {"catid": 317, "prodcode": 34472, "descr": ""},
    {"catid": 317, "prodcode": 34473, "descr": ""},
    {"catid": 317, "prodcode": 34482, "descr": ""},
    {"catid": 317, "prodcode": 34483, "descr": ""},
    {"catid": 317, "prodcode": 34505, "descr": ""},
    {"catid": 317, "prodcode": 34510, "descr": ""},
    {"catid": 317, "prodcode": 34523, "descr": ""},
])

High_Vaginal_Swab_HVS_M_or_C_or_S = np.array([
    {"catid": 236, "prodcode": 34514, "descr": ""},
    {"catid": 236, "prodcode": 34546, "descr": ""},
    {"catid": 236, "prodcode": 34548, "descr": ""},
    {"catid": 236, "prodcode": 34549, "descr": ""},
    {"catid": 236, "prodcode": 34550, "descr": ""},
    {"catid": 236, "prodcode": 34551, "descr": ""},
])

Hiv_Care_And_Treatment_At_Designated_Sites = np.array([
    {"catid": 51, "prodcode": 34522, "descr": ""},
    {"catid": 51, "prodcode": 34523, "descr": ""},
    {"catid": 51, "prodcode": 34524, "descr": ""},
    {"catid": 51, "prodcode": 34526, "descr": ""},
    {"catid": 51, "prodcode": 34527, "descr": ""},
    {"catid": 51, "prodcode": 34529, "descr": ""},
    {"catid": 51, "prodcode": 34530, "descr": ""},
    {"catid": 51, "prodcode": 34532, "descr": ""},
])

HIV_Screening = np.array([
    {"catid": 311, "prodcode": 34532, "descr": ""},
])

Hysteroscopy = np.array([
    {"catid": 113, "prodcode": 32458, "descr": ""},
    {"catid": 113, "prodcode": 33080, "descr": ""},
    {"catid": 113, "prodcode": 33081, "descr": ""},
    {"catid": 113, "prodcode": 33082, "descr": ""},
    {"catid": 113, "prodcode": 33083, "descr": ""},
    {"catid": 113, "prodcode": 33213, "descr": ""},
    {"catid": 113, "prodcode": 33744, "descr": ""},
    {"catid": 113, "prodcode": 35170, "descr": ""},
    {"catid": 113, "prodcode": 35171, "descr": ""},
    {"catid": 113, "prodcode": 35200, "descr": ""},
    {"catid": 113, "prodcode": 35201, "descr": ""},
    {"catid": 113, "prodcode": 35203, "descr": ""},
])

# =============================================================================
# SUMMARY — H.py
# =============================================================================
# Categories in this file : 14
# Total product entries    : 149
# Duplicate entries removed: 0
#
# Breakdown by category:
#   H_Pylori (catid=246): 8 products
#   HBA1C (catid=316): 11 products
#   Hematological_Test (catid=31): 4 products
#   Hematologist (catid=272): (no products — variable omitted)
#   Hemoglobin_HB (catid=200): 5 products
#   Hepatitis_B (catid=83): 37 products
#   Hepatitis_B_Screening (catid=318): 5 products
#   Hepatitis_B_Surface_Antigen_HBSAg (catid=310): 39 products
#   Hepatitis_C_Screening (catid=317): 13 products
#   High_Vaginal_Swab_HVS_M_or_C_or_S (catid=236): 6 products
#   Hiv_Care_And_Treatment_At_Designated_Sites (catid=51): 8 products
#   HIV_Confirmatory_Test (catid=312): (no products — variable omitted)
#   HIV_Screening (catid=311): 1 products
#   Hysteroscopy (catid=113): 12 products
# =============================================================================
