import numpy as np

# =============================================================================
# J.py
# Service category product assignments — letter J
# Generated by: product-service-mapper skill
# =============================================================================

Jadelle_Implant = np.array([
    {"catid": 187, "prodcode": 35215, "descr": ""},
    {"catid": 187, "prodcode": 35232, "descr": ""},
    {"catid": 187, "prodcode": 35233, "descr": ""},
    {"catid": 187, "prodcode": 35538, "descr": ""},
    {"catid": 187, "prodcode": 35539, "descr": ""},
    {"catid": 187, "prodcode": 35540, "descr": ""},
    {"catid": 187, "prodcode": 35541, "descr": ""},
])

# =============================================================================
# SUMMARY — J.py
# =============================================================================
# Categories in this file : 1
# Total product entries    : 7
# Duplicate entries removed: 0
#
# Breakdown by category:
#   Jadelle_Implant (catid=187): 7 products
# =============================================================================
