import numpy as np

# =============================================================================
# J.py
# Service category product assignments — letter J
# Generated by: product-service-mapper skill
# =============================================================================

Jadelle_Implant = np.array([
    {"catid": 187, "prodcode": 15290, "descr": ""},
    {"catid": 187, "prodcode": 15718, "descr": ""},
    {"catid": 187, "prodcode": 15830, "descr": ""},
    {"catid": 187, "prodcode": 15831, "descr": ""},
    {"catid": 187, "prodcode": 15871, "descr": ""},
    {"catid": 187, "prodcode": 15872, "descr": ""},
    {"catid": 187, "prodcode": 15873, "descr": ""},
    {"catid": 187, "prodcode": 15874, "descr": ""},
])

# =============================================================================
# SUMMARY — J.py
# =============================================================================
# Categories in this file : 1
# Total product entries    : 8
# Duplicate entries removed: 0
#
# Breakdown by category:
#   Jadelle_Implant (catid=187): 8 products
# =============================================================================
