import numpy as np

# =============================================================================
# K.py
# Service category product assignments — letter K
# Generated by: product-service-mapper skill
# =============================================================================

Kidney_Function_Tests = np.array([
    {"catid": 308, "prodcode": 14161, "descr": ""},
    {"catid": 308, "prodcode": 14163, "descr": ""},
    {"catid": 308, "prodcode": 14173, "descr": ""},
    {"catid": 308, "prodcode": 14178, "descr": ""},
    {"catid": 308, "prodcode": 14182, "descr": ""},
    {"catid": 308, "prodcode": 14185, "descr": ""},
    {"catid": 308, "prodcode": 14187, "descr": ""},
    {"catid": 308, "prodcode": 14188, "descr": ""},
    {"catid": 308, "prodcode": 14189, "descr": ""},
    {"catid": 308, "prodcode": 14204, "descr": ""},
    {"catid": 308, "prodcode": 14206, "descr": ""},
    {"catid": 308, "prodcode": 14694, "descr": ""},
    {"catid": 308, "prodcode": 14695, "descr": ""},
    {"catid": 308, "prodcode": 14918, "descr": ""},
    {"catid": 308, "prodcode": 15185, "descr": ""},
    {"catid": 308, "prodcode": 15186, "descr": ""},
    {"catid": 308, "prodcode": 15187, "descr": ""},
    {"catid": 308, "prodcode": 15188, "descr": ""},
    {"catid": 308, "prodcode": 15213, "descr": ""},
    {"catid": 308, "prodcode": 15214, "descr": ""},
    {"catid": 308, "prodcode": 15372, "descr": ""},
    {"catid": 308, "prodcode": 15375, "descr": ""},
    {"catid": 308, "prodcode": 15423, "descr": ""},
    {"catid": 308, "prodcode": 15424, "descr": ""},
    {"catid": 308, "prodcode": 15425, "descr": ""},
    {"catid": 308, "prodcode": 15426, "descr": ""},
    {"catid": 308, "prodcode": 15814, "descr": ""},
    {"catid": 308, "prodcode": 16287, "descr": ""},
    {"catid": 308, "prodcode": 16288, "descr": ""},
    {"catid": 308, "prodcode": 16289, "descr": ""},
    {"catid": 308, "prodcode": 16290, "descr": ""},
    {"catid": 308, "prodcode": 16291, "descr": ""},
    {"catid": 308, "prodcode": 16292, "descr": ""},
    {"catid": 308, "prodcode": 16346, "descr": ""},
    {"catid": 308, "prodcode": 16395, "descr": ""},
    {"catid": 308, "prodcode": 16417, "descr": ""},
    {"catid": 308, "prodcode": 16461, "descr": ""},
    {"catid": 308, "prodcode": 16462, "descr": ""},
    {"catid": 308, "prodcode": 16463, "descr": ""},
    {"catid": 308, "prodcode": 16464, "descr": ""},
    {"catid": 308, "prodcode": 16465, "descr": ""},
    {"catid": 308, "prodcode": 16466, "descr": ""},
    {"catid": 308, "prodcode": 16467, "descr": ""},
    {"catid": 308, "prodcode": 16571, "descr": ""},
])

# =============================================================================
# SUMMARY — K.py
# =============================================================================
# Categories in this file : 1
# Total product entries    : 44
# Duplicate entries removed: 0
#
# Breakdown by category:
#   Kidney_Function_Tests (catid=308): 44 products
# =============================================================================
