import numpy as np

# =============================================================================
# S.py
# Service category product assignments — letter S
# Generated by: product-service-mapper skill
# =============================================================================

Scaling_and_Polishing = np.array([
    {"catid": 168, "prodcode": 13874, "descr": ""},
    {"catid": 168, "prodcode": 13875, "descr": ""},
])

Seeking_Second_Opinion = np.array([
    {"catid": 52, "prodcode": 13844, "descr": ""},
    {"catid": 52, "prodcode": 13865, "descr": ""},
    {"catid": 52, "prodcode": 13907, "descr": ""},
    {"catid": 52, "prodcode": 13908, "descr": ""},
    {"catid": 52, "prodcode": 14886, "descr": ""},
    {"catid": 52, "prodcode": 14887, "descr": ""},
    {"catid": 52, "prodcode": 15028, "descr": ""},
    {"catid": 52, "prodcode": 15029, "descr": ""},
    {"catid": 52, "prodcode": 15510, "descr": ""},
    {"catid": 52, "prodcode": 15594, "descr": ""},
    {"catid": 52, "prodcode": 15595, "descr": ""},
    {"catid": 52, "prodcode": 16412, "descr": ""},
    {"catid": 52, "prodcode": 16497, "descr": ""},
])

Semi_Private_Room = np.array([
    {"catid": 341, "prodcode": 16499, "descr": ""},
])

Seminal_Fluid_Analysis_SFA = np.array([
    {"catid": 332, "prodcode": 16393, "descr": ""},
])

Serum_Acid_Phosphate = np.array([
    {"catid": 154, "prodcode": 13926, "descr": ""},
    {"catid": 154, "prodcode": 14146, "descr": ""},
    {"catid": 154, "prodcode": 14799, "descr": ""},
    {"catid": 154, "prodcode": 15528, "descr": ""},
    {"catid": 154, "prodcode": 15932, "descr": ""},
    {"catid": 154, "prodcode": 16201, "descr": ""},
])

Serum_Bilirubin_Total_and_Direct = np.array([
    {"catid": 156, "prodcode": 13905, "descr": ""},
    {"catid": 156, "prodcode": 14061, "descr": ""},
    {"catid": 156, "prodcode": 14179, "descr": ""},
    {"catid": 156, "prodcode": 14919, "descr": ""},
    {"catid": 156, "prodcode": 14920, "descr": ""},
])

Serum_Calcium = np.array([
    {"catid": 148, "prodcode": 16529, "descr": ""},
])

Serum_Chloride = np.array([
    {"catid": 161, "prodcode": 14161, "descr": ""},
    {"catid": 161, "prodcode": 15372, "descr": ""},
    {"catid": 161, "prodcode": 16417, "descr": ""},
])

Serum_Cholesterol = np.array([
    {"catid": 289, "prodcode": 14074, "descr": ""},
    {"catid": 289, "prodcode": 14996, "descr": ""},
    {"catid": 289, "prodcode": 14997, "descr": ""},
    {"catid": 289, "prodcode": 15661, "descr": ""},
    {"catid": 289, "prodcode": 15838, "descr": ""},
])

Serum_Gamma_Glutamyl_Transferase = np.array([
    {"catid": 164, "prodcode": 14159, "descr": ""},
    {"catid": 164, "prodcode": 15627, "descr": ""},
])

Serum_Inorganic_Phosphate = np.array([
    {"catid": 155, "prodcode": 14750, "descr": ""},
    {"catid": 155, "prodcode": 15412, "descr": ""},
    {"catid": 155, "prodcode": 15413, "descr": ""},
    {"catid": 155, "prodcode": 15414, "descr": ""},
    {"catid": 155, "prodcode": 15415, "descr": ""},
    {"catid": 155, "prodcode": 15630, "descr": ""},
    {"catid": 155, "prodcode": 16247, "descr": ""},
    {"catid": 155, "prodcode": 16248, "descr": ""},
    {"catid": 155, "prodcode": 16302, "descr": ""},
])

Serum_Iron = np.array([
    {"catid": 323, "prodcode": 15737, "descr": ""},
    {"catid": 323, "prodcode": 16533, "descr": ""},
])

Serum_Lithium = np.array([
    {"catid": 160, "prodcode": 14101, "descr": ""},
    {"catid": 160, "prodcode": 15814, "descr": ""},
    {"catid": 160, "prodcode": 16461, "descr": ""},
    {"catid": 160, "prodcode": 16462, "descr": ""},
])

Serum_Magnesium = np.array([
    {"catid": 158, "prodcode": 15975, "descr": ""},
    {"catid": 158, "prodcode": 15976, "descr": ""},
    {"catid": 158, "prodcode": 15977, "descr": ""},
    {"catid": 158, "prodcode": 15978, "descr": ""},
])

Serum_Potasium = np.array([
    {"catid": 159, "prodcode": 14161, "descr": ""},
    {"catid": 159, "prodcode": 15372, "descr": ""},
    {"catid": 159, "prodcode": 16417, "descr": ""},
])

Serum_Sodium = np.array([
    {"catid": 145, "prodcode": 15104, "descr": ""},
    {"catid": 145, "prodcode": 15934, "descr": ""},
    {"catid": 145, "prodcode": 15935, "descr": ""},
])

Sigmoidoscopy = np.array([
    {"catid": 101, "prodcode": 13881, "descr": ""},
    {"catid": 101, "prodcode": 14921, "descr": ""},
    {"catid": 101, "prodcode": 15102, "descr": ""},
    {"catid": 101, "prodcode": 15103, "descr": ""},
    {"catid": 101, "prodcode": 16387, "descr": ""},
])

Skin_Scraping_for_Fungi = np.array([
    {"catid": 229, "prodcode": 13841, "descr": ""},
    {"catid": 229, "prodcode": 13842, "descr": ""},
    {"catid": 229, "prodcode": 14050, "descr": ""},
    {"catid": 229, "prodcode": 14057, "descr": ""},
    {"catid": 229, "prodcode": 14164, "descr": ""},
    {"catid": 229, "prodcode": 14174, "descr": ""},
    {"catid": 229, "prodcode": 14184, "descr": ""},
    {"catid": 229, "prodcode": 14190, "descr": ""},
    {"catid": 229, "prodcode": 14201, "descr": ""},
    {"catid": 229, "prodcode": 14217, "descr": ""},
    {"catid": 229, "prodcode": 14361, "descr": ""},
    {"catid": 229, "prodcode": 14362, "descr": ""},
    {"catid": 229, "prodcode": 14370, "descr": ""},
    {"catid": 229, "prodcode": 15581, "descr": ""},
    {"catid": 229, "prodcode": 15955, "descr": ""},
    {"catid": 229, "prodcode": 15956, "descr": ""},
    {"catid": 229, "prodcode": 15957, "descr": ""},
    {"catid": 229, "prodcode": 15958, "descr": ""},
    {"catid": 229, "prodcode": 15959, "descr": ""},
    {"catid": 229, "prodcode": 15960, "descr": ""},
    {"catid": 229, "prodcode": 15961, "descr": ""},
    {"catid": 229, "prodcode": 15962, "descr": ""},
    {"catid": 229, "prodcode": 15963, "descr": ""},
    {"catid": 229, "prodcode": 15964, "descr": ""},
    {"catid": 229, "prodcode": 15965, "descr": ""},
    {"catid": 229, "prodcode": 15966, "descr": ""},
    {"catid": 229, "prodcode": 15967, "descr": ""},
])

Skin_Snip_for_Microfilaria = np.array([
    {"catid": 228, "prodcode": 15954, "descr": ""},
])

Skull_X_rays = np.array([
    {"catid": 133, "prodcode": 16176, "descr": ""},
])

Special_Care_baby_Unit = np.array([
    {"catid": 307, "prodcode": 13859, "descr": ""},
    {"catid": 307, "prodcode": 14331, "descr": ""},
    {"catid": 307, "prodcode": 14332, "descr": ""},
    {"catid": 307, "prodcode": 15390, "descr": ""},
    {"catid": 307, "prodcode": 15434, "descr": ""},
    {"catid": 307, "prodcode": 15455, "descr": ""},
    {"catid": 307, "prodcode": 15798, "descr": ""},
    {"catid": 307, "prodcode": 16115, "descr": ""},
    {"catid": 307, "prodcode": 16137, "descr": ""},
    {"catid": 307, "prodcode": 16272, "descr": ""},
    {"catid": 307, "prodcode": 16325, "descr": ""},
    {"catid": 307, "prodcode": 16365, "descr": ""},
    {"catid": 307, "prodcode": 16366, "descr": ""},
    {"catid": 307, "prodcode": 16367, "descr": ""},
    {"catid": 307, "prodcode": 16368, "descr": ""},
])

Specialist_Drug_Therapy = np.array([
    {"catid": 211, "prodcode": 13850, "descr": ""},
])

Specialist_Opthalmologist_Consultation = np.array([
    {"catid": 181, "prodcode": 13840, "descr": ""},
    {"catid": 181, "prodcode": 14343, "descr": ""},
])

Sputum_Acid_Fast_Bacilli_AFB_Test = np.array([
    {"catid": 336, "prodcode": 14082, "descr": ""},
    {"catid": 336, "prodcode": 14218, "descr": ""},
    {"catid": 336, "prodcode": 14798, "descr": ""},
    {"catid": 336, "prodcode": 14800, "descr": ""},
    {"catid": 336, "prodcode": 14807, "descr": ""},
    {"catid": 336, "prodcode": 16072, "descr": ""},
    {"catid": 336, "prodcode": 16394, "descr": ""},
])

Sputum_M_C_S = np.array([
    {"catid": 242, "prodcode": 14082, "descr": ""},
])

Stool_M_C_S = np.array([
    {"catid": 244, "prodcode": 15918, "descr": ""},
    {"catid": 244, "prodcode": 16695, "descr": ""},
])

Stool_Occult_Blood = np.array([
    {"catid": 249, "prodcode": 14921, "descr": ""},
])

Stress_Management = np.array([
    {"catid": 87, "prodcode": 16389, "descr": ""},
])

Surgeries_All_Inclusive = np.array([
    {"catid": 46, "prodcode": 13865, "descr": ""},
    {"catid": 46, "prodcode": 13871, "descr": ""},
    {"catid": 46, "prodcode": 13893, "descr": ""},
    {"catid": 46, "prodcode": 13902, "descr": ""},
    {"catid": 46, "prodcode": 13903, "descr": ""},
    {"catid": 46, "prodcode": 13904, "descr": ""},
    {"catid": 46, "prodcode": 13905, "descr": ""},
    {"catid": 46, "prodcode": 13906, "descr": ""},
    {"catid": 46, "prodcode": 13907, "descr": ""},
    {"catid": 46, "prodcode": 13908, "descr": ""},
    {"catid": 46, "prodcode": 13913, "descr": ""},
    {"catid": 46, "prodcode": 14087, "descr": ""},
    {"catid": 46, "prodcode": 14088, "descr": ""},
    {"catid": 46, "prodcode": 14089, "descr": ""},
    {"catid": 46, "prodcode": 14108, "descr": ""},
    {"catid": 46, "prodcode": 14109, "descr": ""},
    {"catid": 46, "prodcode": 14110, "descr": ""},
    {"catid": 46, "prodcode": 14111, "descr": ""},
    {"catid": 46, "prodcode": 14886, "descr": ""},
    {"catid": 46, "prodcode": 14887, "descr": ""},
    {"catid": 46, "prodcode": 15028, "descr": ""},
    {"catid": 46, "prodcode": 15029, "descr": ""},
    {"catid": 46, "prodcode": 15277, "descr": ""},
    {"catid": 46, "prodcode": 15352, "descr": ""},
    {"catid": 46, "prodcode": 15363, "descr": ""},
    {"catid": 46, "prodcode": 15364, "descr": ""},
    {"catid": 46, "prodcode": 15510, "descr": ""},
    {"catid": 46, "prodcode": 15592, "descr": ""},
    {"catid": 46, "prodcode": 15594, "descr": ""},
    {"catid": 46, "prodcode": 15595, "descr": ""},
    {"catid": 46, "prodcode": 16326, "descr": ""},
    {"catid": 46, "prodcode": 16384, "descr": ""},
    {"catid": 46, "prodcode": 16412, "descr": ""},
    {"catid": 46, "prodcode": 16497, "descr": ""},
    {"catid": 46, "prodcode": 16517, "descr": ""},
])

Surgical_Cancer_Care = np.array([
    {"catid": 141, "prodcode": 13880, "descr": ""},
    {"catid": 141, "prodcode": 13884, "descr": ""},
    {"catid": 141, "prodcode": 14096, "descr": ""},
    {"catid": 141, "prodcode": 15041, "descr": ""},
])

Surgical_extraction = np.array([
    {"catid": 172, "prodcode": 13907, "descr": ""},
    {"catid": 172, "prodcode": 13908, "descr": ""},
    {"catid": 172, "prodcode": 15799, "descr": ""},
    {"catid": 172, "prodcode": 15800, "descr": ""},
    {"catid": 172, "prodcode": 15801, "descr": ""},
    {"catid": 172, "prodcode": 15802, "descr": ""},
])

Syphilis_Screening = np.array([
    {"catid": 320, "prodcode": 14043, "descr": ""},
    {"catid": 320, "prodcode": 14069, "descr": ""},
    {"catid": 320, "prodcode": 14070, "descr": ""},
    {"catid": 320, "prodcode": 14632, "descr": ""},
    {"catid": 320, "prodcode": 14637, "descr": ""},
    {"catid": 320, "prodcode": 16538, "descr": ""},
])

# =============================================================================
# SUMMARY — S.py
# =============================================================================
# Categories in this file : 41
# Total product entries    : 179
# Duplicate entries removed: 0
#
# Breakdown by category:
#   Scaling_and_Polishing (catid=168): 2 products
#   Seeking_Second_Opinion (catid=52): 13 products
#   Semen_M_C_S (catid=322): (no products — variable omitted)
#   Semi_Private_Room (catid=341): 1 products
#   Seminal_Fluid_Analysis_SFA (catid=332): 1 products
#   Serum_Acid_Phosphate (catid=154): 6 products
#   Serum_Albumin (catid=157): (no products — variable omitted)
#   Serum_Alkaline_Phosphate (catid=153): (no products — variable omitted)
#   Serum_Bicarbonate (catid=162): (no products — variable omitted)
#   Serum_Bilirubin_Total_and_Direct (catid=156): 5 products
#   Serum_Calcium (catid=148): 1 products
#   Serum_Chloride (catid=161): 3 products
#   Serum_Cholesterol (catid=289): 5 products
#   Serum_Gamma_Glutamyl_Transferase (catid=164): 2 products
#   Serum_Inorganic_Phosphate (catid=155): 9 products
#   Serum_Iron (catid=323): 2 products
#   Serum_Lactate_Dehydrogenase (catid=163): (no products — variable omitted)
#   Serum_Lithium (catid=160): 4 products
#   Serum_Magnesium (catid=158): 4 products
#   Serum_Potasium (catid=159): 3 products
#   Serum_Sodium (catid=145): 3 products
#   Serum_Uric_Acid (catid=315): (no products — variable omitted)
#   Sigmoidoscopy (catid=101): 5 products
#   Sinus_X_rays (catid=130): (no products — variable omitted)
#   Skin_Scraping_for_Fungi (catid=229): 27 products
#   Skin_Snip_for_Microfilaria (catid=228): 1 products
#   Skull_X_rays (catid=133): 1 products
#   Special_Care_baby_Unit (catid=307): 15 products
#   Specialist_Consultation (catid=26): (no products — variable omitted)
#   Specialist_Drug_Therapy (catid=211): 1 products
#   Specialist_Opthalmologist_Consultation (catid=181): 2 products
#   Sputum_Acid_Fast_Bacilli_AFB_Test (catid=336): 7 products
#   Sputum_M_C_S (catid=242): 1 products
#   Standard_Room (catid=340): (no products — variable omitted)
#   Stool_M_C_S (catid=244): 2 products
#   Stool_Occult_Blood (catid=249): 1 products
#   Stress_Management (catid=87): 1 products
#   Surgeries_All_Inclusive (catid=46): 35 products
#   Surgical_Cancer_Care (catid=141): 4 products
#   Surgical_extraction (catid=172): 6 products
#   Syphilis_Screening (catid=320): 6 products
# =============================================================================
