import numpy as np

# =============================================================================
# U.py
# Service category product assignments — letter U
# Generated by: product-service-mapper skill
# =============================================================================

Upper_GI_Endoscopy = np.array([
    {"catid": 102, "prodcode": 13840, "descr": ""},
    {"catid": 102, "prodcode": 14343, "descr": ""},
    {"catid": 102, "prodcode": 14389, "descr": ""},
    {"catid": 102, "prodcode": 14921, "descr": ""},
    {"catid": 102, "prodcode": 15461, "descr": ""},
    {"catid": 102, "prodcode": 15522, "descr": ""},
])

Urethral_Swab_M_C_S = np.array([
    {"catid": 237, "prodcode": 14165, "descr": ""},
    {"catid": 237, "prodcode": 14222, "descr": ""},
    {"catid": 237, "prodcode": 14236, "descr": ""},
    {"catid": 237, "prodcode": 14237, "descr": ""},
    {"catid": 237, "prodcode": 14238, "descr": ""},
    {"catid": 237, "prodcode": 15305, "descr": ""},
    {"catid": 237, "prodcode": 15306, "descr": ""},
    {"catid": 237, "prodcode": 15307, "descr": ""},
    {"catid": 237, "prodcode": 15308, "descr": ""},
    {"catid": 237, "prodcode": 15309, "descr": ""},
])

Urinalysis = np.array([
    {"catid": 300, "prodcode": 13840, "descr": ""},
    {"catid": 300, "prodcode": 14215, "descr": ""},
    {"catid": 300, "prodcode": 14343, "descr": ""},
])

Urine_M_C_S = np.array([
    {"catid": 234, "prodcode": 13841, "descr": ""},
    {"catid": 234, "prodcode": 13842, "descr": ""},
    {"catid": 234, "prodcode": 14050, "descr": ""},
    {"catid": 234, "prodcode": 14057, "descr": ""},
    {"catid": 234, "prodcode": 14164, "descr": ""},
    {"catid": 234, "prodcode": 14174, "descr": ""},
    {"catid": 234, "prodcode": 14184, "descr": ""},
    {"catid": 234, "prodcode": 14190, "descr": ""},
    {"catid": 234, "prodcode": 14201, "descr": ""},
    {"catid": 234, "prodcode": 14217, "descr": ""},
    {"catid": 234, "prodcode": 14361, "descr": ""},
    {"catid": 234, "prodcode": 14362, "descr": ""},
    {"catid": 234, "prodcode": 14370, "descr": ""},
    {"catid": 234, "prodcode": 15324, "descr": ""},
    {"catid": 234, "prodcode": 15955, "descr": ""},
    {"catid": 234, "prodcode": 15956, "descr": ""},
    {"catid": 234, "prodcode": 15957, "descr": ""},
    {"catid": 234, "prodcode": 15958, "descr": ""},
    {"catid": 234, "prodcode": 15959, "descr": ""},
    {"catid": 234, "prodcode": 15960, "descr": ""},
    {"catid": 234, "prodcode": 15961, "descr": ""},
    {"catid": 234, "prodcode": 15962, "descr": ""},
    {"catid": 234, "prodcode": 15963, "descr": ""},
    {"catid": 234, "prodcode": 15964, "descr": ""},
    {"catid": 234, "prodcode": 15965, "descr": ""},
    {"catid": 234, "prodcode": 15966, "descr": ""},
    {"catid": 234, "prodcode": 15967, "descr": ""},
])

Urine_Pregnancy_Test = np.array([
    {"catid": 166, "prodcode": 13870, "descr": ""},
    {"catid": 166, "prodcode": 14128, "descr": ""},
    {"catid": 166, "prodcode": 14129, "descr": ""},
    {"catid": 166, "prodcode": 14171, "descr": ""},
    {"catid": 166, "prodcode": 14205, "descr": ""},
])

Urologist = np.array([
    {"catid": 262, "prodcode": 13926, "descr": ""},
    {"catid": 262, "prodcode": 14137, "descr": ""},
    {"catid": 262, "prodcode": 14146, "descr": ""},
    {"catid": 262, "prodcode": 15007, "descr": ""},
    {"catid": 262, "prodcode": 15008, "descr": ""},
    {"catid": 262, "prodcode": 15026, "descr": ""},
    {"catid": 262, "prodcode": 15027, "descr": ""},
    {"catid": 262, "prodcode": 15528, "descr": ""},
    {"catid": 262, "prodcode": 15932, "descr": ""},
    {"catid": 262, "prodcode": 16201, "descr": ""},
])

# =============================================================================
# SUMMARY — U.py
# =============================================================================
# Categories in this file : 6
# Total product entries    : 61
# Duplicate entries removed: 0
#
# Breakdown by category:
#   Upper_GI_Endoscopy (catid=102): 6 products
#   Urethral_Swab_M_C_S (catid=237): 10 products
#   Urinalysis (catid=300): 3 products
#   Urine_M_C_S (catid=234): 27 products
#   Urine_Pregnancy_Test (catid=166): 5 products
#   Urologist (catid=262): 10 products
# =============================================================================
